### ISSUE TITLE
Fails to start on macOS Monterey (12.0 beta 1)

### ISSUE THREAD

**Issue by call** [actions/runner#1171]
**Describe the bug**

GitHub Actions runner fails to configure or run on macOS Monterey beta 1.

**To Reproduce**

1. Follow the standard installation instructions in the `Actions / Add self-hosted runner` pane.
1. Run `./config.sh --url <myurl> --token <mytoken>`
1. App immediately crashes.

**Expected behavior**

Should be able to configure and run GitHub Actions runner on macOS 10.13+, according to [docs](https://github.com/actions/runner/blob/main/docs/start/envosx.md).

## Runner Version and Platform

**macOS version:**
```
sw_vers
ProductName:	macOS
ProductVersion:	12.0
BuildVersion:	21A5248p
```

**Runner version:** `v2.278.0`

## What's not working?
The app fails to configure or start.

## Job Log Output
```dotnet
./config.sh --url <myurl> --token <mytoken>
Process terminated. Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Arg_ExternalException
   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.Runtime.InteropServices.SEHException..ctor()
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(System.Reflection.MetadataToken, System.Reflection.MetadataImport ByRef, System.Reflection.RuntimeModule, System.Reflection.MetadataToken, System.RuntimeType, Boolean, ListBuilder`1<System.Object> ByRef, System.RuntimeType ByRef, System.IRuntimeMethodInfo ByRef, Boolean ByRef, Boolean ByRef)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1<System.Object> ByRef, System.Reflection.RuntimeModule, Int32, System.RuntimeType, Boolean, ListBuilder`1<System.Object>)
   at System.Reflection.CustomAttribute.GetCustomAttributes(System.Reflection.RuntimeModule, Int32, Int32, System.RuntimeType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(System.Reflection.RuntimeAssembly, System.RuntimeType)
   at System.Reflection.RuntimeAssembly.GetCustomAttributes(System.Type, Boolean)
   at System.Attribute.GetCustomAttributes(System.Reflection.Assembly, System.Type, Boolean)
   at System.Attribute.GetCustomAttribute(System.Reflection.Assembly, System.Type, Boolean)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Reflection.Assembly)
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(System.Reflection.Assembly, System.Resources.UltimateResourceFallbackLocation ByRef)
   at System.Resources.ResourceManager.CommonAssemblyInit()
   at System.Resources.ResourceManager..ctor(System.Type)
   at System.SR.get_ResourceManager()
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.Runtime.InteropServices.SEHException..ctor()
   at System.Globalization.CultureData.GetDefaultLocaleName(System.String ByRef)
   at System.Globalization.CultureInfo.GetUserDefaultCulture()
   at System.Globalization.CultureInfo.InitializeUserDefaultCulture()
   at System.Globalization.CultureInfo.get_CurrentCulture()
   at System.Text.RegularExpressions.Regex..ctor(System.String, System.Text.RegularExpressions.RegexOptions, System.TimeSpan, Boolean)
   at System.Text.RegularExpressions.Regex..ctor(System.String, System.Text.RegularExpressions.RegexOptions)
   at GitHub.Runner.Sdk.RunnerWebProxy..ctor()
   at GitHub.Runner.Common.HostContext..ctor(System.String, System.String)
   at GitHub.Runner.Listener.Program.Main(System.String[])
./config.sh: line 81:  7988 Abort trap: 6           ./bin/Runner.Listener configure "$@"
```

## Troubleshooting steps

I saw some similar posts that suggested setting the following may help:

```bash
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
```

I tried this but it didn't resolve the issue.

**Comment by TingluoHuang** [comment]
@call the runner won't work on M1 or BigSur+ for now, dotnet core doesn't support it yet.

**Comment by call** [comment]
@TingluoHuang Do you know of somewhere where I can track Monterey support (not apple silicon) for dotnet core? Thank you.

**Comment by TingluoHuang** [comment]
maybe https://github.com/dotnet/runtime

**Comment by ruvceskistefan** [comment]
Hi @call,
Since @TingluoHuang explained everything to you, I'm going to close this issue. Feel free to reopen this one or report new one if needed.
