### ISSUE TITLE
Can not use secrets in composite jobs 

### ISSUE THREAD

**Issue by minaf1** [actions/runner#1284]
**Describe the bug**
I have tried using the following documentation to pass a secret from a workflow to the composite job: [documentation](https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action#creating-an-action-metadata-file)

**To Reproduce**
See my gist here: [link to gist](https://gist.github.com/minaf1/3c46dca83c62b976d98d17ebe5c860e8)

**Expected behavior**
That it would not fail with an error and display the value of the passed secret. ( I understand that it could be masked in output log)  

## Runner Version and Platform
Version of your runner?
I am using the github-hosted runner, so I assume it is the most current version.

OS of the machine running the runner? OSX/Windows/Linux/...
Linux

## What's not working?
Please include error messages and screenshots.
This ends up giving me the following error:
`Error: /home/runner/work/my-repo/my-repo/./.github/actions/my-action/action.yml:
Error: /home/runner/work/my-repo/my-repo/./.github/actions/my-action/action.yml: (Line: 12, Col: 54, Idx: 253) - (Line: 12, Col: 54, Idx: 253): Mapping values are not allowed in this context.
Error: System.ArgumentException: Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load /home/runner/work/my-repo/my-repo/./.github/actions/my-action/action.yml`

**Comment by fearphage** [comment]
Without seeing the contents of `minaf1/GitHubActions`, it's hard to say what's wrong here. However you can see an example of an action referencing itself after checkout:

https://github.com/docker/build-push-action/blob/a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229/.github/workflows/ci.yml#L15-L28

**Comment by minaf1** [comment]
the GithubActions repo contains the action.yaml that I referred to in the gist.

**Comment by thboop** [comment]
Hey @minaf1 I set up a repro [here](https://github.com/thboop/comp-secrets) using your code trying to reproduce and I was unable to. Is the indentation off in your action.yaml? Or can you setup a simple test case in public repos?

**Comment by minaf1** [comment]
@thboop Perhaps the issue is because the 2 files are in different repositories. Hence why the workflow file needs the repo specified in the checkout action. I will edit the description above with all the details I know about this issue.
