### ISSUE TITLE
Regression in `JobServer.ConnectAsync`

### ISSUE THREAD

**Issue by juliobbv** [actions/runner#1342]
Introduced by: https://github.com/actions/runner/pull/1316

When the connection in `JobServer.ConnectAsync` gets re-created after a retry, *sometimes* this exception is thrown:

```
System.ArgumentException: The 'DelegatingHandler' list is invalid because the property 'InnerHandler' of 'ThrottlingReportHandler' is not null. (Parameter 'handlers')
   at System.Net.Http.HttpClientFactory.CreatePipeline(HttpMessageHandler innerHandler, IEnumerable`1 handlers)
   at GitHub.Services.WebApi.VssConnection..ctor(Uri baseUrl, VssHttpMessageHandler innerHandler, IEnumerable`1 delegatingHandlers, Boolean allowUnattributedClients)
   at GitHub.Services.WebApi.VssConnection..ctor(Uri baseUrl, VssHttpMessageHandler innerHandler, IEnumerable`1 delegatingHandlers)
   at GitHub.Runner.Sdk.VssUtil.CreateConnection(Uri serverUri, VssCredentials credentials, IEnumerable`1 additionalDelegatingHandler, Nullable`1 timeout)
   at GitHub.Runner.Common.JobServer.RefreshConnectionAsync(Uri jobServerUrl, VssCredentials jobServerCredential, DelegatingHandler[] delegatingHandler)
   at GitHub.Runner.Common.JobServer.ConnectAsync(Uri jobServerUrl, VssCredentials jobServerCredential, DelegatingHandler[] delegatingHandler)
   at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
```

Investigate why is this happening and fix.

**Comment by juliobbv** [comment]
This has been rolled out and fixed.
