### ISSUE TITLE
Issue running steps on ephemeral kubernetes agent - No such file or directory

### ISSUE THREAD

**Issue by MichaelJJ** [actions/runner#1464]
**Describe the bug**
We are using the new self-hosted runner scaling API to create a new kubernetes agent with every new job.  When trying to run steps like checkout v2, we receive the error No such file or directory.  We can manually run git commands.

## Runner Version and Platform
Version of your runner?

2.284.0 using docker image based on ubuntu:20.04.  The image has the runner pre-installed  We have a handful of utilities pre-installed and also run the `installdependencies.sh` during image creation.

## What's not working?
Actions steps, like actions/checkout@v2

Action workflow:

```
jobs:
  test-build:
    runs-on: self-hosted
    steps:
    - name: pull
      uses: actions/checkout@v2
```

## Job Log Output

```
##[group]Run actions/checkout@v2
2021-11-04T15:18:27.5101918Z with:
2021-11-04T15:18:27.5102825Z   repository: ****
2021-11-04T15:18:27.5104008Z   token: ***
2021-11-04T15:18:27.5104359Z   ssh-strict: true
2021-11-04T15:18:27.5104777Z   persist-credentials: true
2021-11-04T15:18:27.5105183Z   clean: true
2021-11-04T15:18:27.5105527Z   fetch-depth: 1
2021-11-04T15:18:27.5105854Z   lfs: false
2021-11-04T15:18:27.5106199Z   submodules: false
2021-11-04T15:18:27.5106549Z ##[endgroup]
2021-11-04T15:18:27.5182071Z ##[error]No such file or directory
2021-11-04T15:18:27.5190763Z ##[debug]System.ComponentModel.Win32Exception (2): No such file or directory
2021-11-04T15:18:27.5192403Z ##[debug]   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
2021-11-04T15:18:27.5194067Z ##[debug]   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
2021-11-04T15:18:27.5195191Z ##[debug]   at System.Diagnostics.Process.Start()
2021-11-04T15:18:27.5197055Z ##[debug]   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
2021-11-04T15:18:27.5200247Z ##[debug]   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
2021-11-04T15:18:27.5203334Z ##[debug]   at GitHub.Runner.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
2021-11-04T15:18:27.5205631Z ##[debug]   at GitHub.Runner.Worker.Handlers.NodeScriptActionHandler.RunAsync(ActionRunStage stage)
2021-11-04T15:18:27.5206859Z ##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
2021-11-04T15:18:27.5207933Z ##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
```

**Comment by TingluoHuang** [comment]
@MichaelJJ the runner didn't call `git` directly, the `actions/checkout@v2` will call it.
the error seems related to the runner can't start the `actions/checkout@v2` actions.

Can your runner run step? only `actions/checkout@v2` fail or all kinds of steps in the job are failing?

Also, make sure you don't have a really big environment set on the environment or in your job since a huge environment variable block might block creating a new process on the OS.

**Comment by MichaelJJ** [comment]
It doesn't appear to be able to run any step, I've also tried actions/setup-python@v2.

I don't have any env variables set.  This is the entire workflow:

```
name: Run

on:
  workflow_dispatch: {}
  
jobs:
  Test-Job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
``

I've also attached the dockerfile used to create the agent  The entrypoint script simply starts the runner on container start.
[Dockerfile-runner.txt](https://github.com/actions/runner/files/7476254/Dockerfile-runner.txt)

**Comment by MichaelJJ** [comment]
I was able to resolve the issue by fixing the dockerfile.

**Comment by TingluoHuang** [comment]
```
&& mv ./externals ./externalstmp \
```

☝️  I assume that's the problem?

**Comment by MichaelJJ** [comment]
Yes, I copied the dockerfile from another project and missed that portion.
