### ISSUE TITLE
Self-hosted runner Status switch to offline after logout

### ISSUE THREAD

**Issue by zivbaz** [actions/runner#1476]
Hello,

We're running a self-hosted runner on macOS M1 with the Monterey OS version.
  
We installed the service using `svc.sh install` and start it with `svc.sh start`.
Staring the service working without any issues, and the runner status is Idle.

The problem starts after we close the login session (SSH or Screen share). 
After a few minutes, the status changed to offline.
When we enter again to the runner, the status change to Idle.

Checking the runner logs shows this:

> [2021-11-11 13:50:06Z INFO HostContext] Well known directory 'Bin': '/Users/runner/runner-four-mac/bin'
[2021-11-11 13:50:06Z INFO HostContext] Well known directory 'Root': '/Users/runner/runner-four-mac'
[2021-11-11 13:50:06Z INFO HostContext] Well known directory 'Bin': '/Users/runner/runner-four-mac/bin'
[2021-11-11 13:50:06Z INFO HostContext] Well known directory 'Bin': '/Users/runner/runner-four-mac/bin'
[2021-11-11 13:50:06Z INFO HostContext] Well known directory 'Root': '/Users/runner/runner-four-mac'
[2021-11-11 13:50:06Z INFO UnixUtil] Which: 'chmod'
[2021-11-11 13:50:06Z INFO UnixUtil] Location: '/bin/chmod'
[2021-11-11 13:50:06Z INFO UnixUtil] Running /bin/chmod 755 "/Users/runner/runner-four-mac/svc.sh"
[2021-11-11 13:50:06Z INFO ProcessInvokerWrapper] Starting process:
[2021-11-11 13:50:06Z INFO ProcessInvokerWrapper]   File name: '/bin/chmod'
[2021-11-11 13:50:06Z INFO ProcessInvokerWrapper]   Arguments: '755 "/Users/runner/runner-four-mac/svc.sh"'
[2021-11-11 13:50:06Z INFO ProcessInvokerWrapper]   Working directory: '/Users/runner/runner-four-mac'
[2021-11-11 13:50:06Z INFO ProcessInvokerWrapper]   Require exit code zero: 'True'
[2021-11-11 13:50:06Z INFO ProcessInvokerWrapper]   Encoding web name:  ; code page: ''
[2021-11-11 13:50:06Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'False'
[2021-11-11 13:50:06Z INFO ProcessInvokerWrapper]   Redirected STDIN: 'False'
[2021-11-11 13:50:06Z INFO ProcessInvokerWrapper]   Persist current code page: 'False'
[2021-11-11 13:50:06Z INFO ProcessInvokerWrapper]   Keep redirected STDIN open: 'False'
[2021-11-11 13:50:06Z INFO ProcessInvokerWrapper]   High priority process: 'False'
[2021-11-11 13:50:06Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2021-11-11 13:50:06Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2021-11-11 13:50:06Z INFO ProcessInvokerWrapper] Process started with process id 3012, waiting for process exit.
[2021-11-11 13:50:06Z INFO ProcessInvokerWrapper] Finished process 3012 with exit code 0, and elapsed time 00:00:00.0347568.
[2021-11-11 13:50:06Z INFO Listener] Runner execution has finished with return code 0

Looks like the process stopped working after logging out.

More logs:

> [2021-11-11 14:07:46Z ERR  MessageListener] Catch exception during get next message.
[2021-11-11 14:07:47Z ERR  MessageListener] System.TimeoutException: The HTTP request timed out after 00:01:00.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (89): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Listener.MessageListener.GetNextMessageAsync(CancellationToken token)
[2021-11-11 14:07:47Z ERR  MessageListener] #####################################################
[2021-11-11 14:07:47Z ERR  MessageListener] System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (89): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[2021-11-11 14:07:47Z ERR  MessageListener] #####################################################
[2021-11-11 14:07:47Z ERR  MessageListener] System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (89): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
[2021-11-11 14:07:47Z ERR  MessageListener] #####################################################
[2021-11-11 14:07:47Z ERR  MessageListener] System.Net.Sockets.SocketException (89): Operation canceled
[2021-11-11 14:07:47Z INFO MessageListener] Retriable exception: The HTTP request timed out after 00:01:00.
[2021-11-11 14:07:47Z ERR  Terminal] WRITE ERROR: 2021-11-11 14:07:47Z: Runner connect error: The HTTP request timed out after 00:01:00.. Retrying until reconnected.
[2021-11-11 14:07:47Z INFO RunnerServer] Refresh MessageQueue VssConnection to get on a different AFD node.
[2021-11-11 14:07:47Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2021-11-11 14:07:47Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2021-11-11 14:07:47Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2021-11-11 14:07:48Z INFO MessageListener] Sleeping for 25.893 seconds before retrying.
[2021-11-11 14:09:04Z INFO Terminal] WRITE LINE: 2021-11-11 14:09:04Z: Runner reconnected.
[2021-11-11 14:25:49Z INFO MessageListener] No message retrieved from session 'bb49b50e-4338-46a4-821e-cd80c5997162' within last 30 minutes.
[2021-11-11 14:27:53Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/XmnnSsvjBXnSuyMv6O9s0RlhrxuSWrvC22eYgickmCea1v50Uj/_apis/distributedtask/pools/1/messages?sessionId=bb49b50e-4338-46a4-821e-cd80c5997162 timed out after 60 seconds.
[2021-11-11 14:27:53Z ERR  MessageListener] Catch exception during get next message.
[2021-11-11 14:27:53Z ERR  MessageListener] System.TimeoutException: The HTTP request timed out after 00:01:00.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (89): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Listener.MessageListener.GetNextMessageAsync(CancellationToken token)
[2021-11-11 14:27:53Z ERR  MessageListener] #####################################################
[2021-11-11 14:27:53Z ERR  MessageListener] System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (89): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[2021-11-11 14:27:53Z ERR  MessageListener] #####################################################
[2021-11-11 14:27:53Z ERR  MessageListener] System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (89): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
[2021-11-11 14:27:53Z ERR  MessageListener] #####################################################
[2021-11-11 14:27:53Z ERR  MessageListener] System.Net.Sockets.SocketException (89): Operation canceled
[2021-11-11 14:27:53Z INFO MessageListener] Retriable exception: The HTTP request timed out after 00:01:00.
[2021-11-11 14:27:53Z ERR  Terminal] WRITE ERROR: 2021-11-11 14:27:53Z: Runner connect error: The HTTP request timed out after 00:01:00.. Retrying until reconnected.

> Stop retry on SessionConflictException after retried for 240 seconds.
Failed to create session. The actions runner runner-four-mac already has an active session for owner runnertwo.
Runner listener exited with error code 1
Runner listener exit with terminated error, stop the service, no retry needed.
2021-11-11 08:26:31Z: Runner connect error: The HTTP request timed out after 00:01:00.. Retrying until reconnected.
2021-11-11 08:27:49Z: Runner reconnected.
2021-11-11 08:48:55Z: Runner connect error: The HTTP request timed out after 00:01:00.. Retrying until reconnected.
2021-11-11 13:01:16Z: Runner reconnected.
Shutting down runner listener
Sending SIGINT to runner listener to stop
Sending SIGKILL to runner listener
Exiting...
An error occurred: nodename nor servname provided, or not known
Runner listener exited with error code 2
Runner listener exit with retryable error, re-launch runner in 5 seconds.
Shutting down runner listener
Sending SIGINT to runner listener to stop
Sending SIGKILL to runner listener
Shutting down runner listener
Sending SIGINT to runner listener to stop
Sending SIGKILL to runner listener
.path=/opt/homebrew/opt/ruby@2.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
.path=/opt/homebrew/opt/ruby@2.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
Starting Runner listener with startup type: service
Started listener process, pid: 1783
Started running service

**Expected behavior**
Runner status stays ideal after logging out or restarting.

## Runner Version and Platform
Runner is built for OSX (X64) - osx-x64.
RuntimeInformation: Darwin 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT root:xnu-8019.41.5~1/RELEASE_ARM64_T8101.
Version: 2.284.0
Commit: 9027c154d05776c16f6df6c0345bc9ec20440ebe

**Comment by TingluoHuang** [comment]
@zivbaz the runner service by default installed as `LaunchAgents` (bind to logon user) service in macOS.
You will need to change it to `LaunchDaemons` if you want the service to keep working after logout.

**Comment by zivbaz** [comment]
Thank you @TingluoHuang, any idea how can I do it?

**Comment by francescov1** [comment]
+1 would love an explanation on how to do this

**Comment by TingluoHuang** [comment]
I think these steps should do the trick:
- `./svc.sh stop`
- move the plist file from `LaunchAgents` to `LaunchDaemons `
- make sure edit the `./svc.sh` and make the `LAUNCH_PATH` to the right location since it was pointed to `
"${HOME}/Library/LaunchAgents"`
- `./svc.sh start`

**Comment by nikola-jokic** [comment]
Hey everyone,

I will now close this issue since the answer is provided and there is no activity on it for a long time.

**Comment by F-WRunTime** [comment]
> I think these steps should do the trick:
> 
> * `./svc.sh stop`
> * move the plist file from `LaunchAgents` to `LaunchDaemons `
> * make sure edit the `./svc.sh` and make the `LAUNCH_PATH` to the right location since it was pointed to ` "${HOME}/Library/LaunchAgents"`
> * `./svc.sh start`

This did not work for me on my M1. LaunchDaemons folder is not for users per this error: 
```
Warning: Expecting a LaunchAgents path since the command was ran as user. Got LaunchDaemons instead.
```

**Comment by TheMates** [comment]
Try launching it manually. First I had to do some adjustments to change the ownership/permissions of the .plist, see https://stackoverflow.com/questions/28063598/error-while-executing-plist-file-path-had-bad-ownership-permissions
Then launch it from command line. First you need to switch to root by `sudo su`, then launch the .plist
`launchctl load -w ${your_plist_path}`

A little non automated, but did the trick for me. 

You can stop the service with `launchctl unload ${your_plist_path}`, after all, this is exactly what svc.sh start and stop do, you can check the script.

**Comment by tarbaiev-smg** [comment]
Maybe it will be useful to someone. I spent some time trying to figure out why one of my runners went offline after closing remote session. Both machines were M1 Mac mini. I noticed that one of the Macs went to sleep while the other didn't. You can verify this by checking for `DEAD_PROCESS` messages in `system.log`.
To prevent the sleeping I had to enable the following option (which was enabled on the other Mac):
`System Preferences > Displays > Advanced > Prevent automatic sleeping when display is off`

It's a pity that this option is so hidden and is not under the `Energy Saver` menu.
After this my runner no longer goes offline.

**Comment by harryWonder** [comment]
> Similar thing is happening with the Linux system as well. The self hosted runner is on AWS EC2 amazon linux instance and it went offline after closing the linux connection. Has anyone done in Linux systems as well?

I am currently experiencing this issue as well. The self-hosted runner doesn't pick up a new Job after being Idle for a while.

**Comment by harryWonder** [comment]
Despite configuring the runner to run in the background (Ubuntu 22.04 EC2 VM), the runner doesn't pick up any new job after being Idle for a while.

**Comment by barnabasbusa** [comment]
> System Preferences > Displays > Advanced > Prevent automatic sleeping when display is off

For those of you who have no GUI, you can do this with `sudo systemsetup -setcomputersleep never` also.
