### ISSUE TITLE
Runner listener exited and session duplicated

### ISSUE THREAD

**Issue by rr-binh-nguyen** [actions/runner#1506]
**Describe the bug**
Runner listener exited with error code null and when it started, a duplicated session preventing the process to connect to the runner. Eventually our GHA job failed after 20 minutes plus

**To Reproduce**
1. I'm not sure how to reproduce the issue. Probably we need to kill runner listener's process
2. See error

**Expected behavior**
Runner listener re-launch should resume the existing session or create a new session. If the runner is not functional it should not receive new job from GHA.

**Workaround**
We delete the faulty runner pod, and has no issue with the new runner pod.

## Runner Version and Platform
2.284.0

OS: Ubuntu 20.04/ Docker container in Kubernetes (AWS EKS 1.19)

### Runner pod's logs
```
2021-11-23 17:57:50Z: Running job: terraform-cd
Runner listener exited with error code null
Runner listener exit with undefined return code, re-launch runner in 5 seconds.
Starting Runner listener with startup type: service
Started listener process, pid: 6021

√ Connected to GitHub

A session for this runner already exists.
2021-11-23 17:58:25Z: Runner connect error: The actions runner rr-devops-7c676ff546-dxzvx already has an active session for owner rr-devops-7c676ff546-dxzvx.. Retrying until reconnected.
```

**Comment by TiagoGouvea** [comment]
The same here, after a clean install on an ARM 64 machine on AWS.

```
[ec2-user@ip]$ sudo ./svc.sh status

/etc/systemd/system/actions.runner.meetbreakout-breakout-backend.aws-runner.service
● actions.runner.meetbreakout-breakout-backend.aws-runner.service - GitHub Actions Runner (meetbreakout-breakout-backend.aws-runner)
   Loaded: loaded (/etc/systemd/system/actions.runner.meetbreakout-breakout-backend.aws-runner.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2021-12-01 17:40:44 UTC; 1min 35s ago
 Main PID: 1656 (runsvc.sh)
   CGroup: /system.slice/actions.runner.meetbreakout-breakout-backend.aws-runner.service
           ├─1656 /bin/bash /home/ec2-user/backend-runner/runsvc.sh
           └─1659 ./externals/node12/bin/node ./bin/RunnerService.js

Dec 01 17:42:16 ip.ec2.internal runsvc.sh[1656]: at System.Globalization.GlobalizationMode..cctor()
Dec 01 17:42:16 ip.ec2.internal runsvc.sh[1656]: at System.Globalization.CultureData.CreateCultureWithInvariantData()
Dec 01 17:42:16 ip.ec2.internal runsvc.sh[1656]: at System.Globalization.CultureData.get_Invariant()
Dec 01 17:42:16 ip.ec2.internal runsvc.sh[1656]: at System.Globalization.CultureInfo..cctor()
Dec 01 17:42:16 ip.ec2.internal runsvc.sh[1656]: at System.StringComparer..cctor()
Dec 01 17:42:16 ip.ec2.internal runsvc.sh[1656]: at GitHub.Runner.Sdk.RunnerWebProxy..ctor()
Dec 01 17:42:16 ip.ec2.internal runsvc.sh[1656]: at GitHub.Runner.Common.HostContext..ctor(System.String, System.String)
Dec 01 17:42:16 ip.ec2.internal runsvc.sh[1656]: at GitHub.Runner.Listener.Program.Main(System.String[])
Dec 01 17:42:16 ip.ec2.internal runsvc.sh[1656]: Runner listener exited with error code null
Dec 01 17:42:16 ip.ec2.internal runsvc.sh[1656]: Runner listener exit with undefined return code, re-launch runner in 5 seconds. 
```

**Comment by TiagoGouvea** [comment]
Related to #743

**Comment by nikola-jokic** [comment]
Hi @rr-binh-nguyen,

Are you still seeing this issue on a newer runner version? Usually, after some time, runner picks up and starts listening on jobs when the session expires, which should not take a long time. When a connection error occurs, the runner will attempt after a few seconds and it should succeed after a few moments.

Could you please tell me if the successful connection occurs after a while?

**Comment by nikola-jokic** [comment]
Since there is no activity on this issue, I will close it now. If you are seeing this issue now, feel free to re-open it. Please, keep in mind the previous comment about troubleshooting issues like this 😊

**Comment by gitcos** [comment]
We're having the same problem on a self-hosted runner for a GitHub Enterprise, and I found this issue with a Google search.

Here's what we get in the runner's logs, mildly edited to anonymize:

```
[2022-11-16 16:50:12Z ERR  GitHubActionsService] POST request to https://github.OURDOMAIN.com/_services/pipelines/[long hash deleted from public post]/_apis/distributedtask/pools/7/sessions failed. HTTP Status: Conflict
[2022-11-16 16:50:12Z ERR  MessageListener] Catch exception during create session.
[2022-11-16 16:50:12Z ERR  MessageListener] GitHub.DistributedTask.WebApi.TaskAgentSessionConflictException: The actions runner HOSTNAME-ARM64 already has an active session for owner HOSTNAME.
```

I can't figure out which of the troubleshooting docs @nikola-jokic linked to above are relevant to this issue.  None of them seem to be.

We've had this happen in the past, and the problem goes away after an hour - I assume this is because the existing session expires so GHE allows a new session to be created.  But it seems like there should be a better process for this than leaving the runner offline for an hour.

**Comment by gitcos** [comment]
Just commenting to say we've run into this again a couple of times recently, and still haven't found any better answer.

**Comment by Martiix** [comment]
We ran into this issue as recently as yesterday:
```
Nov 27 18:43:15 se-ci-agent-15 runsvc.sh[2127]: √ Connected to GitHub
Nov 27 18:43:15 se-ci-agent-15 runsvc.sh[2127]: A session for this runner already exists.
Nov 27 18:43:15 se-ci-agent-15 runsvc.sh[2127]: Stop retry on SessionConflictException after retried for 240 seconds.
Nov 27 18:43:15 se-ci-agent-15 runsvc.sh[2127]: Failed to create session. The actions runner se-ci-agent-15-zivid-zivid-sdk-runner-7 already has an active session.
Nov 27 18:43:15 se-ci-agent-15 runsvc.sh[2127]: Runner listener exited with error code 5
Nov 27 18:43:15 se-ci-agent-15 runsvc.sh[2127]: Runner listener exit with Session Conflict error, stop the service, no retry needed.
```

This issue has caused several of our runners to be removed from the runner pool for at least the last week. It is very unfortunate as it is only randomly detected by counting all our runners every day. And every time we have to manually delete the runners on the host to recreate them. We have 116 self-hosted runners, and this morning it was 113, and on Tuesday it was only 109. Not great having to start every day with re-adding runners that have been removed, especially when our CI is already crowded at full capacity.
