### ISSUE TITLE
[Self-hosted] job abandoned

### ISSUE THREAD

**Issue by weimingzha0** [actions/runner#1546]
**Describe the bug**

Since yesterday,  CI jobs keep failing. I tried to re-run the previously passed changes and still failed.
Also tried the latest runner (actions-runner-linux-x64-2.285.1.tar.gz) but still the same.

The CI job runs a script (customized action script). It takes about 15 mins to finish.

The job actually finished correctly as I can see from my host log  but CI reports error like:

The self-hosted runner: xxx lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.

journalctl shows:
Job build_ubuntu completed with result: Abandoned

The "raw log" in web UI shows:

2021-12-10T04:55:30.4780954Z ##[error]The operation was canceled.
2021-12-10T04:55:30.4933658Z Post job cleanup.

Please advise how should I diagnose the issue?

OS: Ubuntu 18.04
Runner: actions-runner-linux-x64-2.285.1.tar.gz

**Comment by mccarron** [comment]
We're seeing this too, and another user posted about the same issue: 
https://github.com/actions/runner/issues/1545

Super curious.

**Comment by combinatorial** [comment]
We're seeing this across self-hosted runners on macOS, linux and Windows.

**Comment by weimingzha0** [comment]
If we reduce the total time to  ~11 minutes by disabling part of tests, it's OK.

**Comment by combinatorial** [comment]
Also being discussed here: https://github.community/t/jobs-getting-killed-for-no-reason/216720

**Comment by Bercon** [comment]
I have the same issue. Github Actions runner logs say it receives a shutdown command from server at almost exactly 15 minutes after starting the run:

`[2021-12-09 20:16:00Z INFO Worker] Cancellation/Shutdown message received.`

And also get the same message you do in Github Actions website:

`The self-hosted runner: XXXXXX lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.`

**Comment by muojp** [comment]
Same here. GitHub Actions self-hosted runner Linux-x86_64 2.285.1 abandons task at 14min 56 sec (maybe somebody wrote such song???) which leads long running CI tasks to 100% failure.

**Comment by luochongjun** [comment]
> Same here. GitHub Actions self-hosted runner Linux-x86_64 2.285.1 abandons task at 14min 56 sec (maybe somebody wrote such song???) which leads long running CI tasks to 100% failure.

I have the same problem and hope to fix it as soon as possible.

**Comment by JohnLBergqvist** [comment]
Here are logs from the `_diag` directory which may shed some more light on the situation:
```
 ```
[2021-12-10 08:13:47Z INFO JobDispatcher] Successfully renew job request 783714, job is valid till 12/10/2021 08:23:47
[2021-12-10 08:14:47Z INFO JobDispatcher] Successfully renew job request 783714, job is valid till 12/10/2021 08:24:47
[2021-12-10 08:15:47Z INFO JobDispatcher] Successfully renew job request 783714, job is valid till 12/10/2021 08:25:47
[2021-12-10 08:16:47Z INFO JobDispatcher] Successfully renew job request 783714, job is valid till 12/10/2021 08:26:47
[2021-12-10 08:17:47Z INFO JobDispatcher] Successfully renew job request 783714, job is valid till 12/10/2021 08:27:47
[2021-12-10 08:18:47Z INFO JobDispatcher] Successfully renew job request 783714, job is valid till 12/10/2021 08:28:47
[2021-12-10 08:19:47Z INFO JobDispatcher] Successfully renew job request 783714, job is valid till 12/10/2021 08:29:47
[2021-12-10 08:20:47Z INFO JobDispatcher] Successfully renew job request 783714, job is valid till 12/10/2021 08:30:47
[2021-12-10 08:21:47Z INFO JobDispatcher] Successfully renew job request 783714, job is valid till 12/10/2021 08:31:47
[2021-12-10 08:22:47Z INFO JobDispatcher] Successfully renew job request 783714, job is valid till 12/10/2021 08:32:47
[2021-12-10 08:23:47Z INFO JobDispatcher] Successfully renew job request 783714, job is valid till 12/10/2021 08:33:47
[2021-12-10 08:24:47Z INFO JobDispatcher] Successfully renew job request 783714, job is valid till 12/10/2021 08:34:47
[2021-12-10 08:25:47Z INFO JobDispatcher] Successfully renew job request 783714, job is valid till 12/10/2021 08:35:47
[2021-12-10 08:26:47Z INFO JobDispatcher] Successfully renew job request 783714, job is valid till 12/10/2021 08:36:47
[2021-12-10 08:27:47Z ERR  GitHubActionsService] PATCH request to https://pipelines.actions.githubusercontent.com/[token]/_apis/distributedtask/pools/1/jobrequests/[job-id]?lockToken=00000000-0000-0000-0000-000000000000 failed. HTTP Status: BadRequest, AFD Ref: Ref A: [ref-value] Ref B: [ref-value] Ref C: 2021-12-10T08:27:47Z
[2021-12-10 08:27:47Z INFO JobDispatcher] TaskAgentJobTokenExpiredException received renew job request 783714, job is no longer valid, stop renew job request.
[2021-12-10 08:27:47Z INFO JobDispatcher] Send job cancellation message to worker for job [other token].
```

**Comment by poemonsense** [comment]
we are facing the same issue. Jobs are killed within 15 minutes. See https://github.com/OpenXiangShan/XiangShan/actions

**Comment by DaHuoKolmostar** [comment]
We are also facing the same issues.

**Comment by CoolZeroNL** [comment]
getting the same here.

![image](https://user-images.githubusercontent.com/26223744/145552377-9c5d97fa-371e-4efc-892b-54c6dadf33a0.png)

`[2021-12-10 09:26:27Z ERR  GitHubActionsService] POST request to https://pipelines.actions.githubusercontent.com/xvHIYcbkzGYxgj2jV2vuKlI8e7bhG14Sxs4beAU/00000000-0000-0000-0000-000000000000/_apis/distributedtask/hubs/Actions/plans/8cbfd4eb-e222-494c-95e4-d68e490b4b51/events failed. HTTP Status: BadRequest, AFD Ref: Ref A: F4A6CDF03A314B098D7CD25BD4091FF1 Ref B: AM3EDGE0916 Ref C: 2021-12-10T09:26:27Z
[2021-12-10 09:26:27Z ERR  JobRunner] TaskOrchestrationPlanTerminatedException received, while attempting to raise JobCompletedEvent for job ca395085-040a-526b-2ce8-bdc85f692774.
[2021-12-10 09:26:27Z ERR  JobRunner] GitHub.DistributedTask.WebApi.TaskOrchestrationPlanTerminatedException: Orchestration plan 8cbfd4eb-e222-494c-95e4-d68e490b4b51 is not in a runnable state.
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpMethod method, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable 1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.DistributedTask.WebApi.TaskHttpClient.RaisePlanEventAsync[T](Guid scopeIdentifier, String planType, Guid planId, T eventData, CancellationToken cancellationToken, Object userState)
   at GitHub.Runner.Worker.JobRunner.CompleteJobAsync(IJobServer jobServer, IExecutionContext jobContext, AgentJobRequestMessage message, Nullable 1 taskResult)
`

**Comment by acezen** [comment]
We are also facing the same issues.  See https://github.com/alibaba/GraphScope/actions/runs/1562610611

**Comment by Kaspik** [comment]
Seeing the same issues with all our macOS runners.

```
[2021-12-10 09:52:56Z INFO JobDispatcher] Successfully renew job request 31886, job is valid till 12/10/2021 10:02:56
[2021-12-10 09:53:56Z INFO JobDispatcher] Successfully renew job request 31886, job is valid till 12/10/2021 10:03:56
[2021-12-10 09:54:56Z ERR  GitHubActionsService] PATCH request to https://pipelines.actions.githubusercontent.com/URFC1Mo04WVpqks7vdrv6ocHbpRwZ0WwZrOQSDQlLLU6LmbltN/_apis/distributedtask/pools/1/jobrequests/31886?lockToken=00000000-0000-0000-0000-000000000000 failed. HTTP Status: BadRequest, AFD Ref: Ref A: E92CED7CB107493C80358F9EB3CDAA58 Ref B: ATL331000101031 Ref C: 2021-12-10T09:54:56Z
[2021-12-10 09:54:56Z INFO JobDispatcher] TaskAgentJobTokenExpiredException received renew job request 31886, job is no longer valid, stop renew job request.
[2021-12-10 09:54:56Z INFO JobDispatcher] Send job cancellation message to worker for job 832b0204-66bc-5239-0b20-d0854358b9c1.
[2021-12-10 09:54:56Z INFO ProcessChannel] Sending message of length 0, with hash 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
[2021-12-10 09:55:46Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2021-12-10 09:55:46Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2021-12-10 09:55:46Z INFO ProcessInvokerWrapper] Finished process 565 with exit code 102, and elapsed time 00:15:51.9483529.
[2021-12-10 09:55:46Z INFO JobDispatcher] finish job request for job 832b0204-66bc-5239-0b20-d0854358b9c1 with result: Abandoned
[2021-12-10 09:55:46Z INFO Terminal] WRITE LINE: 2021-12-10 09:55:46Z: Job Build and upload release completed with result: Abandoned
[2021-12-10 09:55:46Z INFO JobDispatcher] Stop renew job request for job 832b0204-66bc-5239-0b20-d0854358b9c1.
[2021-12-10 09:55:46Z INFO JobNotification] Entering JobCompleted Notification
[2021-12-10 09:55:46Z INFO JobNotification] Entering EndMonitor
[2021-12-10 10:02:52Z INFO RSAFileKeyManager] Loading RSA key parameters from file /Users/administrator/actions-runner-1/.credentials_rsaparams
[2021-12-10 10:02:52Z INFO MessageListener] Message '5730' received from session '589c6df3-098c-40a8-8d03-16a1c1affc9a'.
[2021-12-10 10:02:52Z INFO JobDispatcher] Job request 31891 for plan 7202b692-6dad-4498-8e0c-ba56305f18b8 job a55bcc0b-99fd-5c08-6029-521d815eb551 received.
[2021-12-10 10:02:52Z INFO JobDispatcher] Pull OrchestrationId 7202b692-6dad-4498-8e0c-ba56305f18b8.build_tests.__default from JWT claims
[2021-12-10 10:02:52Z INFO JobDispatcher] Job request 832b0204-66bc-5239-0b20-d0854358b9c1 processed succeed.
[2021-12-10 10:02:52Z INFO Terminal] WRITE LINE: 2021-12-10 10:02:52Z: Running job: Run ClassDojo tests
[2021-12-10 10:02:52Z INFO JobDispatcher] Start renew job request 31891 for job a55bcc0b-99fd-5c08-6029-521d815eb551.
[2021-12-10 10:02:52Z INFO JobDispatcher] Successfully renew job request 31891, job is valid till 12/10/2021 10:12:52
[2021-12-10 10:02:52Z INFO HostContext] Well known directory 'Bin': '/Users/administrator/actions-runner-1/bin.2.285.1'
[2021-12-10 10:02:52Z INFO ProcessInvokerWrapper] Starting process:
[2021-12-10 10:02:52Z INFO ProcessInvokerWrapper]   File name: '/Users/administrator/actions-runner-1/bin.2.285.1/Runner.Worker'
[2021-12-10 10:02:52Z INFO ProcessInvokerWrapper]   Arguments: 'spawnclient 101 106'
[2021-12-10 10:02:52Z INFO ProcessInvokerWrapper]   Working directory: '/Users/administrator/actions-runner-1/bin.2.285.1'
[2021-12-10 10:02:52Z INFO ProcessInvokerWrapper]   Require exit code zero: 'False'
[2021-12-10 10:02:52Z INFO ProcessInvokerWrapper]   Encoding web name:  ; code page: ''
[2021-12-10 10:02:52Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'True'
[2021-12-10 10:02:52Z INFO ProcessInvokerWrapper]   Redirected STDIN: 'False'
[2021-12-10 10:02:52Z INFO ProcessInvokerWrapper]   Persist current code page: 'False'
[2021-12-10 10:02:52Z INFO ProcessInvokerWrapper]   Keep redirected STDIN open: 'False'
[2021-12-10 10:02:52Z INFO ProcessInvokerWrapper]   High priority process: 'True'
[2021-12-10 10:02:52Z INFO ProcessInvokerWrapper] Process started with process id 16576, waiting for process exit.
[2021-12-10 10:02:52Z INFO JobDispatcher] Send job request message to worker for job a55bcc0b-99fd-5c08-6029-521d815eb551.
[2021-12-10 10:02:52Z INFO ProcessChannel] Sending message of length 41631, with hash '51780fbb33ffd911ca71d12448618f779302726b36084330b59a3f60bacd423b'
[2021-12-10 10:02:53Z INFO JobNotification] Entering JobStarted Notification
[2021-12-10 10:02:53Z INFO JobNotification] Entering StartMonitor
[2021-12-10 10:03:53Z INFO JobDispatcher] Successfully renew job request 31891, job is valid till 12/10/2021 10:13:53
```

Process is usually killed ~15mins, we are not even able to load the logs in UI.

**Comment by JulianGro** [comment]
Same issue here on aarch64 Linux.
Runner abandons or cancels jobs after ~15 minutes. The GHA web UI only says that it "lost communication with the server"

**Comment by VGomis** [comment]
I have the same problem, could it be due to a recent runner update?

**Comment by JulianGro** [comment]
Either that, or a GitHub Server issue.
Considering I noticed the issue only a day after updating, the runner update seems like a good assumption.

**Comment by sea212** [comment]
Same happening here. First occurence was about 7pm (UTC) 09. Dec 2021. Worker logs from _diag folder:
```
[2021-12-10 10:35:21Z INFO JobServerQueue] Uploading 3 files in one shot.
[2021-12-10 10:35:22Z INFO JobServerQueue] Try to upload 3 log files or attachments, success rate: 3/3.
[2021-12-10 10:35:22Z INFO JobServerQueue] File upload queue drained.
[2021-12-10 10:35:22Z INFO JobServerQueue] Timeline update queue drained.
[2021-12-10 10:35:22Z INFO JobServerQueue] All queue process tasks have been stopped, and all queues are drained.
[2021-12-10 10:35:22Z INFO TempDirectoryManager] Cleaning runner temp folder: /services/github-runner/_work/_temp
[2021-12-10 10:35:22Z INFO HostContext] Well known directory 'Bin': '/services/github-runner/bin'
[2021-12-10 10:35:22Z INFO HostContext] Well known directory 'Root': '/services/github-runner'
[2021-12-10 10:35:22Z INFO HostContext] Well known directory 'Diag': '/services/github-runner/_diag'
[2021-12-10 10:35:22Z INFO HostContext] Well known config file 'Telemetry': '/services/github-runner/_diag/.telemetry'
[2021-12-10 10:35:22Z INFO JobRunner] Raising job completed event.
[2021-12-10 10:35:22Z ERR  GitHubActionsService] POST request to https://pipelines.actions.githubusercontent.com/JXpbQ6DX3J60aG0ZOnNOfiCcofhOaItSP6R03SNZpAtF0GnewE/00000000-0000-0000-0000-000000000000/_apis/distributedtask/hubs/Actions/plans/3b580d24-8df8-4f4e-9cac-3554762cfe71/events failed. HTTP Status: BadRequest, AFD Ref: Ref A: 432111DB5E364FE0A6D16DB085059A8C Ref B: FRAEDGE1317 Ref C: 2021-12-10T10:35:22Z
[2021-12-10 10:35:22Z ERR  JobRunner] TaskOrchestrationPlanTerminatedException received, while attempting to raise JobCompletedEvent for job 9ef21fd1-5d60-5fa4-f8b2-6dc79e173863.
[2021-12-10 10:35:22Z ERR  JobRunner] GitHub.DistributedTask.WebApi.TaskOrchestrationPlanTerminatedException: Orchestration plan 3b580d24-8df8-4f4e-9cac-3554762cfe71 is not in a runnable state.
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpMethod method, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.DistributedTask.WebApi.TaskHttpClient.RaisePlanEventAsync[T](Guid scopeIdentifier, String planType, Guid planId, T eventData, CancellationToken cancellationToken, Object userState)
   at GitHub.Runner.Worker.JobRunner.CompleteJobAsync(IJobServer jobServer, IExecutionContext jobContext, AgentJobRequestMessage message, Nullable`1 taskResult)
```

**Comment by pp-gtroshin** [comment]
Same here. Linux x64, 2.285.1

```
Dec 10 10:30:40 *** runsvc.sh[616]: √ Connected to GitHub
Dec 10 10:30:40 *** runsvc.sh[616]: Current runner version: '2.285.1'
Dec 10 10:30:40 *** runsvc.sh[616]: 2021-12-10 10:30:40Z: Listening for Jobs
Dec 10 10:32:48 *** runsvc.sh[616]: 2021-12-10 10:32:48Z: Running job: bootstrap
Dec 10 10:48:04 *** runsvc.sh[616]: 2021-12-10 10:48:04Z: Job bootstrap completed with result: Abandoned
```

**Comment by jupe** [comment]
Same problem here. Self-hosted, linux x64. Current runner version: '2.285.1'

**Comment by foxylion** [comment]
We experience the same issue here for us. A lot of tests are failing, because the total duration of the job is above 15 minutes.

**Comment by mmuth** [comment]
Same issues. Huge problem for our CI pipeline :/

**Comment by ahilton-godaddy** [comment]
we are seeing this too, same fifteen minute timeouts

**Comment by Kaspik** [comment]
Opened a support ticket to Github Supported with ID #1422988.

**Comment by andrewgbell** [comment]
Seeing the same with local builds using the runner, GitHub hosted agents don't seem to have the issue.

**Comment by JohnLBergqvist** [comment]
I don't think the problem is the runner version. `2.285.1` was working fine for me up until yesterday evening, and I've seen the problem happening on runners still using `2.285.0`.

**Comment by ahilton-godaddy** [comment]
pelase note, i believe this is the same issue in here effecting pytorch and rust
https://github.com/actions/runner/issues/1545
https://github.com/pytorch/pytorch/issues/69722

**Comment by mglettig** [comment]
Exactly the same for me. I was also testing that my machine actually permanently reaches the internet by running a periodic ping while the test was running. My jobs are also usually killed around ~15 minutes.

**Comment by philipwigg** [comment]
We're also experiencing this issue.

**Comment by vrutberg** [comment]
We're also experiencing this issue with our self-hosted Intel Mac runners.

**Comment by arihannu** [comment]
Same here!

**Comment by xroche** [comment]
Same issue here: `Job result after all job steps finish: Canceled`

```
[2021-12-10 13:55:16Z INFO JobRunner] Job result after all job steps finish: Canceled
[2021-12-10 13:55:16Z INFO JobRunner] Completing the job execution context.
[2021-12-10 13:55:16Z INFO JobRunner] Shutting down the job server queue.
[2021-12-10 13:55:16Z INFO JobServerQueue] Fire signal to shutdown all queues.
[2021-12-10 13:55:16Z INFO JobServerQueue] Try to append 1 batches web console lines for record '928ba1f9-5b0d-5089-094a-7ac1eb9fb407', success rate: 1/1.
[2021-12-10 13:55:16Z INFO JobServerQueue] Try to append 1 batches web console lines for record '1961d96d-ba91-488b-b208-5c37563f3fca', success rate: 1/1.
[2021-12-10 13:55:16Z INFO JobServerQueue] Try to append 1 batches web console lines for record '45291083-0ac3-4d78-92c9-b6e17c1d9268', success rate: 1/1.
[2021-12-10 13:55:17Z INFO JobServerQueue] All queue process task stopped.
[2021-12-10 13:55:17Z INFO JobServerQueue] Web console line queue drained.
[2021-12-10 13:55:17Z INFO JobServerQueue] Uploading 5 files in one shot.
[2021-12-10 13:55:19Z INFO JobServerQueue] Try to upload 5 log files or attachments, success rate: 5/5.
[2021-12-10 13:55:19Z INFO JobServerQueue] File upload queue drained.
[2021-12-10 13:55:19Z INFO JobServerQueue] Timeline update queue drained.
[2021-12-10 13:55:19Z INFO JobServerQueue] All queue process tasks have been stopped, and all queues are drained.
[2021-12-10 13:55:19Z INFO TempDirectoryManager] Cleaning runner temp folder: /home/github-actions-runner/algoliasaas-ci-actions-runner-3-3/work_dir/_temp
[2021-12-10 13:55:19Z INFO HostContext] Well known directory 'Bin': '/home/github-actions-runner/algoliasaas-ci-actions-runner-3-3/bin.2.285.1'
[2021-12-10 13:55:19Z INFO HostContext] Well known directory 'Root': '/home/github-actions-runner/algoliasaas-ci-actions-runner-3-3'
[2021-12-10 13:55:19Z INFO HostContext] Well known directory 'Diag': '/home/github-actions-runner/algoliasaas-ci-actions-runner-3-3/_diag'
[2021-12-10 13:55:19Z INFO HostContext] Well known config file 'Telemetry': '/home/github-actions-runner/algoliasaas-ci-actions-runner-3-3/_diag/.telemetry'
[2021-12-10 13:55:19Z INFO JobRunner] Raising job completed event.
[2021-12-10 13:55:19Z ERR  GitHubActionsService] POST request to https://pipelines.actions.githubusercontent.com/nTgZIRokmigLFkg861BgmkUzvkGAR6h3HKpjJWgjjKJoUrIrJd/00000000-0000-0000-0000-000000000000/_apis/distributedtask/hubs/Actions/plans/a369e0c7-f9e5-479f-a623-e74f0142952b/events failed. HTTP Status: BadRequest, AFD Ref: Ref A: 7C624754DF704B2CBA84E1B87C81D65E Ref B: AMBEDGE0820 Ref C: 2021-12-10T13:55:19Z
[2021-12-10 13:55:19Z ERR  JobRunner] TaskOrchestrationPlanTerminatedException received, while attempting to raise JobCompletedEvent for job 49e1be30-89cb-5d09-2a2a-76b9048524da.
[2021-12-10 13:55:19Z ERR  JobRunner] GitHub.DistributedTask.WebApi.TaskOrchestrationPlanTerminatedException: Orchestration plan a369e0c7-f9e5-479f-a623-e74f0142952b is not in a runnable state.
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpMethod method, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.DistributedTask.WebApi.TaskHttpClient.RaisePlanEventAsync[T](Guid scopeIdentifier, String planType, Guid planId, T eventData, CancellationToken cancellationToken, Object userState)
   at GitHub.Runner.Worker.JobRunner.CompleteJobAsync(IJobServer jobServer, IExecutionContext jobContext, AgentJobRequestMessage message, Nullable`1 taskResult)
```

**Comment by wslusarczyk-ICG** [comment]
Same :(

**Comment by olmakarov** [comment]
Same

**Comment by marco-scoppetta-qatalog** [comment]
Same problem!

**Comment by baparham** [comment]
They seem to know about it now at least: https://www.githubstatus.com/

**Comment by Burzok** [comment]
Same

**Comment by thboop** [comment]
Related to https://github.com/actions/runner/issues/1545#issuecomment-991053927

We are aware of this issue and working on a fix.

**Comment by xroche** [comment]
:information_source: Related incident page: https://www.githubstatus.com/incidents/tc051c121cs7

**Comment by thboop** [comment]
Thanks @xroche.

This is caused by a server side change we rolled out, we are rolling that back now and hope to have it resolved shortly. Please follow the [incident page](https://www.githubstatus.com/incidents/tc051c121cs7?utm_ts=1639148818) for further updates.

I'll close out this issue once it is resolved.

**Comment by weimingzha0** [comment]
CI is back to business now :)

**Comment by joshuapinter** [comment]
I concur. Thanks!

**Comment by bleshik** [comment]
Is there any chance this issue is back? Our job is hanging all of the sudden with this in logs:
```
[2021-12-28 16:07:55Z INFO JobDispatcher] Successfully renew job request 7689, job is valid till 12/28/2021 4:17:55 PM
[2021-12-28 16:08:55Z INFO JobDispatcher] Successfully renew job request 7689, job is valid till 12/28/2021 4:18:55 PM
[2021-12-28 16:09:56Z INFO JobDispatcher] Successfully renew job request 7689, job is valid till 12/28/2021 4:19:56 PM
[2021-12-28 16:10:56Z INFO JobDispatcher] Successfully renew job request 7689, job is valid till 12/28/2021 4:20:56 PM
[2021-12-28 16:11:56Z INFO JobDispatcher] Successfully renew job request 7689, job is valid till 12/28/2021 4:21:56 PM
[2021-12-28 16:12:56Z INFO JobDispatcher] Successfully renew job request 7689, job is valid till 12/28/2021 4:22:56 PM
[2021-12-28 16:13:57Z INFO JobDispatcher] Successfully renew job request 7689, job is valid till 12/28/2021 4:23:57 PM
[2021-12-28 16:14:57Z INFO JobDispatcher] Successfully renew job request 7689, job is valid till 12/28/2021 4:24:57 PM
[2021-12-28 16:15:57Z INFO JobDispatcher] Successfully renew job request 7689, job is valid till 12/28/2021 4:25:57 PM
[2021-12-28 16:16:58Z INFO JobDispatcher] Successfully renew job request 7689, job is valid till 12/28/2021 4:26:58 PM
[2021-12-28 16:17:58Z INFO JobDispatcher] Successfully renew job request 7689, job is valid till 12/28/2021 4:27:58 PM
[2021-12-28 16:18:58Z INFO JobDispatcher] Successfully renew job request 7689, job is valid till 12/28/2021 4:28:58 PM
[2021-12-28 16:19:59Z INFO JobDispatcher] Successfully renew job request 7689, job is valid till 12/28/2021 4:29:59 PM
[2021-12-28 16:20:59Z INFO JobDispatcher] Successfully renew job request 7689, job is valid till 12/28/2021 4:30:59 PM
[2021-12-28 16:21:59Z INFO JobDispatcher] Successfully renew job request 7689, job is valid till 12/28/2021 4:31:59 PM
[2021-12-28 16:22:59Z INFO JobDispatcher] Successfully renew job request 7689, job is valid till 12/28/2021 4:32:59 PM
[2021-12-28 16:24:00Z INFO JobDispatcher] Successfully renew job request 7689, job is valid till 12/28/2021 4:34:00 PM
[2021-12-28 16:25:00Z INFO JobDispatcher] Successfully renew job request 7689, job is valid till 12/28/2021 4:35:00 PM
```

**Comment by JulianGro** [comment]
That looks like a separate issue. The issue here was that the job would start but be abandoned after a while. Your issue looks like the job never starts.

**Comment by winhits** [comment]
same here the job kill after 1h

**Comment by andrewgbell** [comment]
> same here the job kill after 1h

Think that's normal, you need something like:
    runs-on: ubuntu-latest
    timeout-minutes: 120

**Comment by shiranhodeda** [comment]
And also get the same message you do in Github Actions website:

The self-hosted runner: XXXXXX lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.

**Comment by pinggao187** [comment]
same error
~~~
The self-hosted runner: github-runner-deployment-alpha-z270-docker-1 lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
~~~

**Comment by seantleonard** [comment]
I get the same error, I would argue this issue should be reopened, due to all the corroborating reports.
```
The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.

The self-hosted runner: <ID> lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error

```

**Comment by philipwigg** [comment]
There was a day when everyone was receiving this error, hence this issue, and it was a problem with GitHub Actions.

However, it's a "normal" error to receive if, say, your self-hosted runner ran out of memory and the process was killed by the kernel.

I see this error when we use spot instances in GCP, and the instance is preempted.

**Comment by badrinathpatchikolla** [comment]
Same issue

```
The self-hosted runner: bot3-modak lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```

**Comment by xer0x** [comment]
Same issue, are folks seeing more of this error around Sept 15th w/ AWS self-hosted runners?

**Comment by zaknafein83** [comment]
I use a free plan on EC2 (and i think it's enough) and get same error 
![image](https://user-images.githubusercontent.com/5946567/190671162-029adf8c-fef5-4286-9ca1-1ddfda6a4a23.png)


this is log
`[2022-09-16 10:42:53Z INFO JobServerQueue] All queue process tasks have been stopped, and all queues are drained.
[2022-09-16 10:42:53Z INFO TempDirectoryManager] Cleaning runner temp folder: /home/ubuntu/actions-runner/_work/_temp
[2022-09-16 10:42:53Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/actions-runner/bin'
[2022-09-16 10:42:53Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/actions-runner'
[2022-09-16 10:42:53Z INFO HostContext] Well known directory 'Diag': '/home/ubuntu/actions-runner/_diag'
[2022-09-16 10:42:53Z INFO HostContext] Well known config file 'Telemetry': '/home/ubuntu/actions-runner/_diag/.telemetry'
[2022-09-16 10:42:53Z INFO JobRunner] Raising job completed event
[2022-09-16 10:42:53Z ERR  GitHubActionsService] POST request to https://pipelines.actions.githubusercontent.com/HCYdTxD8O2BMG4LvM5MKcb35EY0sH1wNedn0yWzJce2QlAajYJ/00000000-0000-0000-0000-000000000000/_apis/distributedtask/hubs/Actions/plans/3c6e1db1-0d9c-4bbe-b2fe-376050e30856/events failed. HTTP Status: BadRequest, AFD Ref: Ref A: 0FFF862B7A304ECE8208266780675163 Ref B: MIL30EDGE1321 Ref C: 2022-09-16T10:42:53Z
[2022-09-16 10:42:53Z ERR  JobRunner] TaskOrchestrationPlanTerminatedException received, while attempting to raise JobCompletedEvent for job ca395085-040a-526b-2ce8-bdc85f692774.
[2022-09-16 10:42:53Z ERR  JobRunner] GitHub.DistributedTask.WebApi.TaskOrchestrationPlanTerminatedException: Orchestration plan 3c6e1db1-0d9c-4bbe-b2fe-376050e30856 is not in a runnable state.
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpMethod method, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.DistributedTask.WebApi.TaskHttpClient.RaisePlanEventAsync[T](Guid scopeIdentifier, String planType, Guid planId, T eventData, CancellationToken cancellationToken, Object userState)
   at GitHub.Runner.Worker.JobRunner.CompleteJobAsync(IJobServer jobServer, IExecutionContext jobContext, AgentJobRequestMessage message, Nullable1 taskResult)
`

**Comment by thapaashesh** [comment]
All,

I used to have a 'Re-run all jobs' button in my GitHub runner, but it seems to have disappeared. I would appreciate any help in finding out how to get this button back.

**Comment by maxisam** [comment]
Just got this problem as well 

![image](https://github.com/actions/runner/assets/456807/4d138ae6-a4f1-4097-9a48-bc4b278495fe)


Anyone?

**Comment by npushkarskii** [comment]
We got the same issue, Feb 1, 2024. Not sure if it's only us or the issue is on GH's end.

**Comment by VanTrangDinh** [comment]
**Clear npm cache before running npm ci to ensure consistency across runs**


# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Clean npm cache
      run: npm cache clean --force
    - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test

**Comment by korsour** [comment]
Still same here for `actions/upload-artifact@v4`

**Comment by JCMais** [comment]
In my specific case, this was caused by using spot VMs on GKE. When the VM is shut down, the pod will be stopped with a 15s graceful shutdown, and GH marks the job as canceled.
