### ISSUE TITLE
Runner fails to configure

### ISSUE THREAD

**Issue by berkaycagir** [actions/runner#1569]
**Describe the bug**
Runner fails to configure; outputting a `System.Runtime.InteropServices.SEHException`.

**To Reproduce**
1. Follow guide on the runner creation page of a repo/organization/etc.
2. Run `./config.sh --url https://github.com/xxx --token xxx`
3. See error

**Expected behavior**
I expected the runner to successfully configure and get added to my repo/organization/etc.

## Runner Version and Platform
Version of your runner?
`2.285.1`

OS of the machine running the runner? OSX/Windows/Linux/...
`Linux xxx 4.4.1 #3 SMP Sun Sep 25 13:12:50 CEST 2016 armv7l GNU/Linux`

## Job Log Output

```
--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication

Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at System.Net.Http.ConnectHelper+ConnectEventArgs.set_CancellationToken(System.Threading.CancellationToken)
   at System.Net.Http.ConnectHelper+ConnectEventArgs.Initialize(System.Threading.CancellationToken)
   at System.Net.Http.ConnectHelper+<ConnectAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Net.Http.ConnectHelper+<ConnectAsync>d__1, System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<ConnectAsync>d__1 ByRef)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.Net.Http.ConnectHelper+<ConnectAsync>d__1, System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<ConnectAsync>d__1 ByRef)
   at System.Net.Http.ConnectHelper.ConnectAsync(System.String, Int32, System.Threading.CancellationToken)
   at System.Net.Http.HttpConnectionPool+<ConnectAsync>d__52.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Net.Http.HttpConnectionPool+<ConnectAsync>d__52, System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<ConnectAsync>d__52 ByRef)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1[[System.ValueTuple`4[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.Net.Http.HttpConnectionPool+<ConnectAsync>d__52, System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<ConnectAsync>d__52 ByRef)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(System.Net.Http.HttpRequestMessage, Boolean, System.Threading.CancellationToken)
   at System.Net.Http.HttpConnectionPool+<CreateHttp11ConnectionAsync>d__53.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Net.Http.HttpConnectionPool+<CreateHttp11ConnectionAsync>d__53, System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<CreateHttp11ConnectionAsync>d__53 ByRef)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.Net.Http.HttpConnectionPool+<CreateHttp11ConnectionAsync>d__53, System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<CreateHttp11ConnectionAsync>d__53 ByRef)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
   at System.Net.Http.HttpConnectionPool+<GetHttpConnectionAsync>d__45.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Net.Http.HttpConnectionPool+<GetHttpConnectionAsync>d__45, System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<GetHttpConnectionAsync>d__45 ByRef)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1[[System.ValueTuple`3[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.Net.Http.HttpConnectionPool+<GetHttpConnectionAsync>d__45, System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<GetHttpConnectionAsync>d__45 ByRef)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
   at System.Net.Http.HttpConnectionPool+<SendWithRetryAsync>d__47.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Net.Http.HttpConnectionPool+<SendWithRetryAsync>d__47, System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<SendWithRetryAsync>d__47 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.Net.Http.HttpConnectionPool+<SendWithRetryAsync>d__47, System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<SendWithRetryAsync>d__47 ByRef)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(System.Net.Http.HttpRequestMessage, Boolean, System.Threading.CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithProxyAuthAsync(System.Net.Http.HttpRequestMessage, Boolean, System.Threading.CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendAsync(System.Net.Http.HttpRequestMessage, Boolean, System.Threading.CancellationToken)
   at System.Net.Http.HttpConnectionPoolManager.SendAsyncCore(System.Net.Http.HttpRequestMessage, System.Uri, Boolean, Boolean, System.Threading.CancellationToken)
   at System.Net.Http.HttpConnectionPoolManager.SendAsync(System.Net.Http.HttpRequestMessage, Boolean, System.Threading.CancellationToken)
   at System.Net.Http.HttpConnectionHandler.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
   at System.Net.Http.RedirectHandler+<SendAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Net.Http.RedirectHandler+<SendAsync>d__4, System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<SendAsync>d__4 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.Net.Http.RedirectHandler+<SendAsync>d__4, System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<SendAsync>d__4 ByRef)
   at System.Net.Http.RedirectHandler.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
   at System.Net.Http.SocketsHttpHandler.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
   at System.Net.Http.HttpClientHandler.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
   at System.Net.Http.HttpClient.SendAsync(System.Net.Http.HttpRequestMessage, System.Net.Http.HttpCompletionOption, System.Threading.CancellationToken)
   at System.Net.Http.HttpClient.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
   at System.Net.Http.HttpClient.PostAsync(System.Uri, System.Net.Http.HttpContent, System.Threading.CancellationToken)
   at System.Net.Http.HttpClient.PostAsync(System.String, System.Net.Http.HttpContent)
   at GitHub.Runner.Listener.Configuration.ConfigurationManager+<GetTenantCredential>d__14.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[GitHub.Runner.Listener.Configuration.ConfigurationManager+<GetTenantCredential>d__14, Runner.Listener, Version=2.285.1.0, Culture=neutral, PublicKeyToken=null]](<GetTenantCredential>d__14 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[GitHub.Runner.Listener.Configuration.ConfigurationManager+<GetTenantCredential>d__14, Runner.Listener, Version=2.285.1.0, Culture=neutral, PublicKeyToken=null]](<GetTenantCredential>d__14 ByRef)
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.GetTenantCredential(System.String, System.String, System.String)
   at GitHub.Runner.Listener.Configuration.ConfigurationManager+<ConfigureAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[GitHub.Runner.Listener.Configuration.ConfigurationManager+<ConfigureAsync>d__6, Runner.Listener, Version=2.285.1.0, Culture=neutral, PublicKeyToken=null]](<ConfigureAsync>d__6 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[GitHub.Runner.Listener.Configuration.ConfigurationManager+<ConfigureAsync>d__6, Runner.Listener, Version=2.285.1.0, Culture=neutral, PublicKeyToken=null]](<ConfigureAsync>d__6 ByRef)
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.ConfigureAsync(GitHub.Runner.Listener.CommandSettings)
   at GitHub.Runner.Listener.Runner+<ExecuteCommand>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[GitHub.Runner.Listener.Runner+<ExecuteCommand>d__5, Runner.Listener, Version=2.285.1.0, Culture=neutral, PublicKeyToken=null]](<ExecuteCommand>d__5 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[GitHub.Runner.Listener.Runner+<ExecuteCommand>d__5, Runner.Listener, Version=2.285.1.0, Culture=neutral, PublicKeyToken=null]](<ExecuteCommand>d__5 ByRef)
   at GitHub.Runner.Listener.Runner.ExecuteCommand(GitHub.Runner.Listener.CommandSettings)
   at GitHub.Runner.Listener.Program+<MainAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[GitHub.Runner.Listener.Program+<MainAsync>d__1, Runner.Listener, Version=2.285.1.0, Culture=neutral, PublicKeyToken=null]](<MainAsync>d__1 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[GitHub.Runner.Listener.Program+<MainAsync>d__1, Runner.Listener, Version=2.285.1.0, Culture=neutral, PublicKeyToken=null]](<MainAsync>d__1 ByRef)
   at GitHub.Runner.Listener.Program.MainAsync(GitHub.Runner.Common.IHostContext, System.String[])
   at GitHub.Runner.Listener.Program.Main(System.String[])
./config.sh: line 81:  2797 Aborted                 ./bin/Runner.Listener configure "$@"
```

## Runner and Worker's Diagnostic Logs

```
[2021-12-18 12:41:01Z INFO HostContext] No proxy settings were found based on environmental variables (http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY)
[2021-12-18 12:41:01Z INFO HostContext] Well known directory 'Bin': '/home/gh/actions-runner/bin'
[2021-12-18 12:41:01Z INFO HostContext] Well known directory 'Root': '/home/gh/actions-runner'
[2021-12-18 12:41:01Z INFO HostContext] Well known config file 'Credentials': '/home/gh/actions-runner/.credentials'
[2021-12-18 12:41:01Z INFO HostContext] Well known directory 'Bin': '/home/gh/actions-runner/bin'
[2021-12-18 12:41:01Z INFO HostContext] Well known directory 'Root': '/home/gh/actions-runner'
[2021-12-18 12:41:01Z INFO HostContext] Well known config file 'Runner': '/home/gh/actions-runner/.runner'
[2021-12-18 12:41:01Z INFO Listener] Runner is built for Linux (Arm) - linux-arm.
[2021-12-18 12:41:01Z INFO Listener] RuntimeInformation: Linux 4.4.1 #3 SMP Sun Sep 25 13:12:50 CEST 2016.
[2021-12-18 12:41:02Z INFO Listener] Version: 2.285.1
[2021-12-18 12:41:02Z INFO Listener] Commit: 50afba61b40932c1084e31b5e9e7f5af325cc2ac
[2021-12-18 12:41:02Z INFO Listener] Culture: en-GB
[2021-12-18 12:41:02Z INFO Listener] UI Culture: en-GB
[2021-12-18 12:41:02Z INFO HostContext] Well known directory 'Bin': '/home/gh/actions-runner/bin'
[2021-12-18 12:41:02Z INFO HostContext] Well known directory 'Root': '/home/gh/actions-runner'
[2021-12-18 12:41:02Z INFO Listener] Validating directory permissions for: '/home/gh/actions-runner'
[2021-12-18 12:41:02Z INFO CommandLineParser] Parse
[2021-12-18 12:41:02Z INFO CommandLineParser] Parsing 5 args
[2021-12-18 12:41:02Z INFO CommandLineParser] parsing argument
[2021-12-18 12:41:02Z INFO CommandLineParser] HasArgs: False
[2021-12-18 12:41:02Z INFO CommandLineParser] Adding Command: configure
[2021-12-18 12:41:02Z INFO CommandLineParser] parsing argument
[2021-12-18 12:41:02Z INFO CommandLineParser] HasArgs: True
[2021-12-18 12:41:02Z INFO CommandLineParser] arg: url
[2021-12-18 12:41:02Z INFO CommandLineParser] parsing argument
[2021-12-18 12:41:02Z INFO CommandLineParser] HasArgs: True
[2021-12-18 12:41:03Z INFO CommandLineParser] Adding option 'url': 'https://github.com/xxx'
[2021-12-18 12:41:03Z INFO CommandLineParser] parsing argument
[2021-12-18 12:41:03Z INFO CommandLineParser] HasArgs: True
[2021-12-18 12:41:03Z INFO CommandLineParser] arg: token
[2021-12-18 12:41:03Z INFO CommandLineParser] parsing argument
[2021-12-18 12:41:03Z INFO CommandLineParser] HasArgs: True
[2021-12-18 12:41:03Z INFO CommandLineParser] Adding option 'token': '***'
[2021-12-18 12:41:03Z INFO Listener] Arguments parsed
[2021-12-18 12:41:04Z INFO Runner] ExecuteCommand
[2021-12-18 12:41:04Z INFO ConfigurationStore] currentAssemblyLocation: /home/gh/actions-runner/bin/Runner.Listener.dll
[2021-12-18 12:41:04Z INFO HostContext] Well known directory 'Bin': '/home/gh/actions-runner/bin'
[2021-12-18 12:41:04Z INFO ConfigurationStore] binPath: /home/gh/actions-runner/bin
[2021-12-18 12:41:04Z INFO HostContext] Well known directory 'Bin': '/home/gh/actions-runner/bin'
[2021-12-18 12:41:04Z INFO HostContext] Well known directory 'Root': '/home/gh/actions-runner'
[2021-12-18 12:41:04Z INFO ConfigurationStore] RootFolder: /home/gh/actions-runner
[2021-12-18 12:41:04Z INFO HostContext] Well known directory 'Bin': '/home/gh/actions-runner/bin'
[2021-12-18 12:41:04Z INFO HostContext] Well known directory 'Root': '/home/gh/actions-runner'
[2021-12-18 12:41:04Z INFO HostContext] Well known config file 'Runner': '/home/gh/actions-runner/.runner'
[2021-12-18 12:41:04Z INFO ConfigurationStore] ConfigFilePath: /home/gh/actions-runner/.runner
[2021-12-18 12:41:04Z INFO HostContext] Well known directory 'Bin': '/home/gh/actions-runner/bin'
[2021-12-18 12:41:04Z INFO HostContext] Well known directory 'Root': '/home/gh/actions-runner'
[2021-12-18 12:41:04Z INFO HostContext] Well known config file 'Credentials': '/home/gh/actions-runner/.credentials'
[2021-12-18 12:41:04Z INFO ConfigurationStore] CredFilePath: /home/gh/actions-runner/.credentials
[2021-12-18 12:41:04Z INFO HostContext] Well known directory 'Bin': '/home/gh/actions-runner/bin'
[2021-12-18 12:41:04Z INFO HostContext] Well known directory 'Root': '/home/gh/actions-runner'
[2021-12-18 12:41:04Z INFO HostContext] Well known config file 'MigratedCredentials': '/home/gh/actions-runner/.credentials_migrated'
[2021-12-18 12:41:04Z INFO ConfigurationStore] MigratedCredFilePath: /home/gh/actions-runner/.credentials_migrated
[2021-12-18 12:41:04Z INFO HostContext] Well known directory 'Bin': '/home/gh/actions-runner/bin'
[2021-12-18 12:41:04Z INFO HostContext] Well known directory 'Root': '/home/gh/actions-runner'
[2021-12-18 12:41:04Z INFO HostContext] Well known config file 'Service': '/home/gh/actions-runner/.service'
[2021-12-18 12:41:04Z INFO ConfigurationStore] ServiceConfigFilePath: /home/gh/actions-runner/.service
[2021-12-18 12:41:04Z INFO CommandSettings] Flag 'help': 'False'
[2021-12-18 12:41:04Z INFO CommandSettings] Flag 'version': 'False'
[2021-12-18 12:41:04Z INFO CommandSettings] Flag 'commit': 'False'
[2021-12-18 12:41:04Z INFO CommandSettings] Flag 'check': 'False'
[2021-12-18 12:41:04Z INFO CommandSettings] Command 'configure': 'True'
[2021-12-18 12:41:04Z INFO Terminal] WRITE LINE:
[2021-12-18 12:41:04Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2021-12-18 12:41:04Z INFO Terminal] WRITE LINE: |        ____ _ _   _   _       _          _        _   _                      |
[2021-12-18 12:41:04Z INFO Terminal] WRITE LINE: |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
[2021-12-18 12:41:04Z INFO Terminal] WRITE LINE: |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
[2021-12-18 12:41:04Z INFO Terminal] WRITE LINE: |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
[2021-12-18 12:41:04Z INFO Terminal] WRITE LINE: |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
[2021-12-18 12:41:04Z INFO Terminal] WRITE LINE: |                                                                              |
[2021-12-18 12:41:04Z INFO Terminal] WRITE: |
[2021-12-18 12:41:04Z INFO Terminal] WRITE: Self-hosted runner registration
[2021-12-18 12:41:04Z INFO Terminal] WRITE LINE:                         |
[2021-12-18 12:41:04Z INFO Terminal] WRITE LINE: |                                                                              |
[2021-12-18 12:41:04Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2021-12-18 12:41:04Z INFO ConfigurationManager] ConfigureAsync
[2021-12-18 12:41:04Z INFO ConfigurationStore] IsConfigured()
[2021-12-18 12:41:04Z INFO ConfigurationStore] IsConfigured: False
[2021-12-18 12:41:04Z INFO ConfigurationManager] Is configured: False
[2021-12-18 12:41:04Z INFO CommandSettings] Arg 'url': 'https://github.com/xxx'
[2021-12-18 12:41:04Z INFO CommandSettings] Remove url from Arg dictionary.
[2021-12-18 12:41:04Z INFO CommandSettings] Arg 'token': '***'
[2021-12-18 12:41:04Z INFO CommandSettings] Remove token from Arg dictionary.
```

Runner diag log ends here (I guess) prematurely.

**Comment by TingluoHuang** [comment]
@berkaycagir is this a physical ARM device or a QEMU environment? 
The error is coming from dotnet core runtime which is out really under the runner's control.
I do find a similar issue in the dotnet repository.
https://github.com/dotnet/sdk/issues/11870

**Comment by berkaycagir** [comment]
Thank you very much for the referral @TingluoHuang!

It is indeed a QEMU environment and the problem was about the version of QEMU (4.2). After downgrading it to 4.0, everything works correctly. Thanks again!
