### ISSUE TITLE
System.IO.IOException: Invalid argument

### ISSUE THREAD

**Issue by retzero** [actions/runner#1652]
**Describe the bug**
I am running a job inside a container. (SELF-hosted runner w/ GHES 3.2.6)
However, very occasionally, a step randomly fail due to the following reason;

```Error: Invalid argument```

Here's my workflow snippet;

```yaml
      - name: main; download frontend base model if exist
        uses: CODE-Actions/download-artifact@v2
        if: ${{ matrix.base != '' }}
        with:
          path: /tmp/INBOUND
          name: tmp_frontend_${{ matrix.base }}.result

      - name: temp; list of frontend test results
        run: |
          ls -ARl /tmp/INBOUND
        shell: bash
```

**To Reproduce**
2. Run '....'
3. See error

**Expected behavior**

## Runner Version and Platform
- 2.284.0

OS of the machine running the runner? OSX/Windows/Linux/...
- Ubuntu 20.04.3 LTS
- Docker version 20.10.12, build e91ed57

## What's not working?
Please include error messages and screenshots.

## Job Log Output
- ![image](https://user-images.githubusercontent.com/27608277/152277304-679169a4-510c-4cd1-9b52-7f9296de460b.png)

- Another instance. Very simple listing directory command.
  ![image](https://user-images.githubusercontent.com/27608277/152279038-02b37843-3298-4bd8-b62e-509b0d95331c.png)

## Runner and Worker's Diagnostic Logs

(Editted. Log from the job named **temp; list of frontend test results**)
```
[2022-02-03 03:17:16Z INFO StepsRunner] Current state: job state = ''
[2022-02-03 03:17:16Z INFO StepsRunner] Processing step: DisplayName='temp; list of frontend test results'
[2022-02-03 03:17:16Z INFO StepsRunner] Evaluating: success()
[2022-02-03 03:17:16Z INFO StepsRunner] Result: true
[2022-02-03 03:17:16Z INFO StepsRunner] Starting the step.
[2022-02-03 03:17:16Z INFO HostContext] Well known directory 'Bin': '/home/github/actions-runner/bin'
[2022-02-03 03:17:16Z INFO HostContext] Well known directory 'Root': '/home/github/actions-runner'
[2022-02-03 03:17:16Z INFO HostContext] Well known directory 'Work': '/home/github/actions-runner/_work'
[2022-02-03 03:17:16Z INFO HostContext] Well known directory 'Temp': '/home/github/actions-runner/_work/_temp'
[2022-02-03 03:17:16Z INFO ActionRunner] Write event payload to /home/github/actions-runner/_work/_temp/_github_workflow/event.json
[2022-02-03 03:17:16Z INFO HostContext] Well known directory 'Bin': '/home/github/actions-runner/bin'
[2022-02-03 03:17:16Z INFO HostContext] Well known directory 'Root': '/home/github/actions-runner'
[2022-02-03 03:17:16Z INFO HostContext] Well known directory 'Work': '/home/github/actions-runner/_work'
[2022-02-03 03:17:16Z INFO HostContext] Well known directory 'Temp': '/home/github/actions-runner/_work/_temp'
[2022-02-03 03:17:16Z INFO ExtensionManager] Getting extensions for interface: 'GitHub.Runner.Worker.IFileCommandExtension'
[2022-02-03 03:17:16Z INFO ExtensionManager] Getting extensions for interface: 'GitHub.Runner.Worker.IActionCommandExtension'
[2022-02-03 03:17:16Z INFO ActionCommandManager] Register action command extension for command internal-set-repo-path
[2022-02-03 03:17:16Z INFO ActionCommandManager] Register action command extension for command set-env
[2022-02-03 03:17:16Z INFO ActionCommandManager] Register action command extension for command set-output
[2022-02-03 03:17:16Z INFO ActionCommandManager] Register action command extension for command save-state
[2022-02-03 03:17:16Z INFO ActionCommandManager] Register action command extension for command add-path
[2022-02-03 03:17:16Z INFO ActionCommandManager] Register action command extension for command add-mask
[2022-02-03 03:17:16Z INFO ActionCommandManager] Register action command extension for command add-matcher
[2022-02-03 03:17:16Z INFO ActionCommandManager] Register action command extension for command remove-matcher
[2022-02-03 03:17:16Z INFO ActionCommandManager] Register action command extension for command warning
[2022-02-03 03:17:16Z INFO ActionCommandManager] Register action command extension for command error
[2022-02-03 03:17:16Z INFO ActionCommandManager] Register action command extension for command notice
[2022-02-03 03:17:16Z INFO ActionCommandManager] Register action command extension for command debug
[2022-02-03 03:17:16Z INFO ActionCommandManager] Register action command extension for command group
[2022-02-03 03:17:16Z INFO ActionCommandManager] Register action command extension for command endgroup
[2022-02-03 03:17:16Z INFO ActionCommandManager] Register action command extension for command echo
[2022-02-03 03:17:16Z INFO HostContext] Well known directory 'Bin': '/home/github/actions-runner/bin'
[2022-02-03 03:17:16Z INFO HostContext] Well known directory 'Root': '/home/github/actions-runner'
[2022-02-03 03:17:16Z INFO HostContext] Well known directory 'Work': '/home/github/actions-runner/_work'
[2022-02-03 03:17:16Z INFO HostContext] Well known directory 'Temp': '/home/github/actions-runner/_work/_temp'
[2022-02-03 03:17:16Z INFO ScriptHandler] Which: 'bash'
[2022-02-03 03:17:16Z INFO ScriptHandler] Location: '/usr/bin/bash'
[2022-02-03 03:17:16Z INFO HostContext] [2022-02-03 03:17:16Z ERR  StepsRunner] Caught exception from step: System.IO.IOException: Invalid argument
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.HostContext.GetDirectory(WellKnownDirectory directory)
   at GitHub.Runner.Common.HostContext.GetDirectory(WellKnownDirectory directory)
   at GitHub.Runner.Common.HostContext.GetDirectory(WellKnownDirectory directory)
   at GitHub.Runner.Worker.Handlers.ContainerStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at GitHub.Runner.Worker.Handlers.ScriptHandler.RunAsync(ActionRunStage stage)
   at GitHub.Runner.Worker.ActionRunner.RunAsync()
   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
[2022-02-03 03:17:16Z INFO StepsRunner] Step result: Failed
[2022-02-03 03:17:16Z INFO StepsRunner] Update job result with current step result 'Failed'.
```

**Comment by nikola-jokic** [comment]
Hi @retzero,

Could you please provide an example repository with your workflow that we can fork, so we can reproduce the issue? Simply from this, I could not investigate the root cause of the issue.

Thanks!

**Comment by retzero** [comment]
@nikola-jokic 
Thank you for the feedback.
I'll prepare example workflows soon.

So far... I have 5 failures out of 3,000 jobs.
Looks like there is no easy reproducible scenarios.
It does not occur only in a specific step, but occurs randomly in several places.

**Comment by nikola-jokic** [comment]
Hi @retzero,

Could you please post here your `_diag` logs when the issue arises? I believe that it is pretty hard to reproduce since 5/3000 jobs is a small percentage, but maybe with diagnostic logs, we might get a picture of what is going on when the failure occurs? Keep in mind that diagnostic logs should not contain any sensitive information, but please double check when you post it.

This might be a better course of action to tackle this issue.

**Comment by retzero** [comment]
Hi @nikola-jokic 
I'll reopen this ticket once we can collect the logs.
Thank you for your update.

**Comment by retzero** [comment]
Hi @nikola-jokic 

This keep bothering our developers.
I'm testing w/ below workflow and two more incident happened today. `_diag` logs attached.

Can I have test runner image to debug this issue further?

![image](https://user-images.githubusercontent.com/27608277/155231795-69bb31ae-7d4d-476c-aec8-f882947683a7.png)


```yaml
name: Stress Test

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  upload-test:
    runs-on: "code-xlarge"
    steps:
      - run: |
          mkdir -p /tmp/RESULT
          dd bs=10240 count=4096 </dev/urandom >/tmp/RESULT/test_model.tvn
          dd bs=10240 count=1024 </dev/urandom >/tmp/RESULT/test_model-seq.tvn
        shell: bash
      - run: ls -alh /tmp/RESULT
      - run: echo "start_date=$(date)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: tmp_frontend_test_model.result
          path: /tmp/RESULT
          retention-days: 1
      - name: Upload 시간 측정 (seconds) - 5분 초과 시 Fail
        run: |
          d=$(( $(date -d "$(date)" "+%s") - $(date -d "${{ env.start_date }}" "+%s") ))
          if [ $d -gt 300 ]; then exit 1; fi

  download-test:
    needs: [ upload-test ]
    runs-on: "code-xlarge"
    steps:
      - run: echo "start_date=$(date)" >> $GITHUB_ENV
      - uses: actions/download-artifact@v2
        with:
          path: /tmp/INBOUND
          name: tmp_frontend_test_model.result
      - run: ls -alh /tmp/INBOUND
      - name: Download 시간 측정 (seconds) - 5분 초과 시 Fail
        run: |
          d=$(( $(date -d "$(date)" "+%s") - $(date -d "${{ env.start_date }}" "+%s") ))
          if [ $d -gt 300 ]; then exit 1; fi
```


[code-runner-106-xlarge-3.tar.gz](https://github.com/actions/runner/files/8120606/code-runner-106-xlarge-3.tar.gz)

**Comment by TingluoHuang** [comment]
Does the runner running inside a docker container? if so does the runner folder `/home/github/actions-runner/` under any volume mount?

**Comment by retzero** [comment]
> Does the runner running inside a docker container? if so does the runner folder `/home/github/actions-runner/` under any volume mount?

No. The runner is installed in VM (VirtualBox). We don't use container. There's no mount point.
