### ISSUE TITLE
Got authentication timeout at the beginning of self-hosted runner registration

### ISSUE THREAD

**Issue by yourmoonlight** [actions/runner#1704]
**Describe the bug**
Got authentication timeout at the beginning of self- hosted runner registration,

And try again is useless.

**To Reproduce**

doing this 
> ./config.sh --url xxx --token xxx

then you get the following result.
> The HTTP request timed out after 00:01:00.
Failed to connect.  Try again or ctrl-c to quit

**Comment by ruvceskistefan** [comment]
Hi @yourmoonlight,
I don't have enough information to be able to help you, so I would ask you to send us a `_diag log` file so we can investigate the problem? Please be sure that there is no sensitive information in it.

**Comment by thboop** [comment]
@yourmoonlight , we also have a self check guide on why configuring a runner may not work, can you try the steps [here](https://github.com/actions/runner/blob/main/docs/checks/network.md) and let us know if you are still seeing the issue

**Comment by ruvceskistefan** [comment]
Hi @yourmoonlight,
I'm going to close out this issue until we hear back from you, please let us know if you are still seeing this issue!

**Comment by jkruse14** [comment]
Sorry to resurrect this, but I'm facing a similar issue. When starting up an EC2 instance and trying to authenticate the self-hosted runner, it hangs and eventually times out. Here's out put in the `_diag` log

```
<13>Feb 15 14:36:54 user-data: --------------------------------------------------------------------------------
<13>Feb 15 14:36:54 user-data: |        ____ _ _   _   _       _          _        _   _                      |
<13>Feb 15 14:36:54 user-data: |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
<13>Feb 15 14:36:54 user-data: |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
<13>Feb 15 14:36:54 user-data: |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
<13>Feb 15 14:36:54 user-data: |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
<13>Feb 15 14:36:54 user-data: |                                                                              |
<13>Feb 15 14:36:54 user-data: |                       Self-hosted runner registration                        |
<13>Feb 15 14:36:54 user-data: |                                                                              |
<13>Feb 15 14:36:54 user-data: --------------------------------------------------------------------------------
<13>Feb 15 14:36:54 user-data: 
<13>Feb 15 14:36:54 user-data: # Authentication
<13>Feb 15 14:36:54 user-data: 
<13>Feb 15 14:46:55 user-data: The HTTP request timed out after 00:01:00.
I've seen the _diag logs requested in other issues, so here is the last bit of it (immediately following the logo printout):

2023-02-15 15:20:23Z INFO ConfigurationManager] ConfigureAsync
[2023-02-15 15:20:23Z INFO CommandSettings] Flag 'generateServiceConfig': 'False'
[2023-02-15 15:20:23Z INFO ConfigurationStore] IsConfigured()
[2023-02-15 15:20:23Z INFO ConfigurationStore] IsConfigured: False
[2023-02-15 15:20:23Z INFO ConfigurationManager] Is configured: False
[2023-02-15 15:20:23Z INFO CommandSettings] Arg 'url': 'https://github.com/DoosanBobcatSandbox'
[2023-02-15 15:20:23Z INFO CommandSettings] Remove url from Arg dictionary.
[2023-02-15 15:20:23Z INFO CommandSettings] Arg 'token': '***'
[2023-02-15 15:20:23Z INFO CommandSettings] Remove token from Arg dictionary.
[2023-02-15 15:20:24Z INFO ConfigurationManager] Http response code: OK from 'POST https://api.github.com/actions/runner-registration' (4778:7458:1BDA4C9:3907870:63ECF838)
[2023-02-15 15:20:24Z INFO ConfigurationManager] cred retrieved via GitHub auth
[2023-02-15 15:20:24Z INFO RunnerServer] EstablishVssConnection
[2023-02-15 15:20:24Z INFO RunnerServer] Establish connection with 100 seconds timeout.
[2023-02-15 15:20:24Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-02-15 15:20:24Z INFO RunnerServer] EstablishVssConnection
[2023-02-15 15:20:24Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2023-02-15 15:20:24Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-02-15 15:20:24Z INFO RunnerServer] EstablishVssConnection
[2023-02-15 15:20:24Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2023-02-15 15:20:24Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-02-15 15:21:24Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/WwH58rYm16yb81FWQzkSnD8S3sUx9xj40RpAMo2ZqlfENPswJB/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2023-02-15 15:21:24Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/WwH58rYm16yb81FWQzkSnD8S3sUx9xj40RpAMo2ZqlfENPswJB/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2023-02-15 15:21:24Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-02-15 15:21:24Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-02-15 15:21:24Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-02-15 15:21:24Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
```
I tried again and got a little more from the log:

```
2023-02-15 15:55:02Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-02-15 15:56:02Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/WwH58rYm16yb81FWQzkSnD8S3sUx9xj40RpAMo2ZqlfENPswJB/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2023-02-15 15:56:02Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-02-15 15:56:02Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/WwH58rYm16yb81FWQzkSnD8S3sUx9xj40RpAMo2ZqlfENPswJB/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2023-02-15 15:56:02Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-02-15 15:56:02Z INFO CommandSettings] Flag 'unattended': 'True'
[2023-02-15 15:56:02Z ERR  Runner] System.TimeoutException: The HTTP request timed out after 00:01:00.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at GitHub.Runner.Common.RunnerService.EstablishVssConnection(Uri serverUrl, VssCredentials credentials, TimeSpan timeout)
   at GitHub.Runner.Common.RunnerServer.ConnectAsync(Uri serverUrl, VssCredentials credentials)
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at GitHub.Runner.Listener.Runner.ExecuteCommand(CommandSettings command)
[2023-02-15 15:56:02Z ERR  Runner] #####################################################
[2023-02-15 15:56:02Z ERR  Runner] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[2023-02-15 15:56:02Z ERR  Terminal] WRITE ERROR: The HTTP request timed out after 00:01:00.
[2023-02-15 15:56:02Z INFO Listener] Runner execution has finished with return code 1
```

When I curl the pipleines.actions.githubuserconetent.com URL above, it gives a 200 immediately with a lot of output.

I can also curl all endpoint for the checklist mentioned above ([list here (https://github.com/actions/runner/blob/main/docs/checks/network.md)]

Any advice would be very much appreciated. I also have a discussion started [here](https://github.com/orgs/community/discussions/47563)
