### ISSUE TITLE
Runtime error: Error reading JToken from JsonReader.

### ISSUE THREAD

**Issue by SnowCait** [actions/runner#1722]
**Describe the bug**
`Error reading JToken from JsonReader.` occurs in skipped step.

**To Reproduce**
1. Create a workflow `bug.yml`
```yml
name: Bug

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: step1
        run: echo '::set-output name=json::{"a":1}'
        if: false
      - run: echo $A
        env:
          A: ${{ fromJSON(steps.step1.outputs.json).a }}
        if: false

```
2. Run the workflow
3. See error

**Expected behavior**
Skip all steps without error.

`if` should be evaluated first and skip evaluating other `${{ }}`.

## Runner Version and Platform
Runner version: 2.287.1
OS: Ubuntu 20.04.3 LTS

## What's not working?
Error occurs in 2nd step.
```
Error: .github/workflows/bug.yml (Line: 16, Col: 14):
Error: The template is not valid. .github/workflows/bug.yml (Line: 16, Col: 14): Error reading JToken from JsonReader. Path '', line 0, position 0.
```

## Job Log Output
Minimum reproduction is [here](https://github.com/SnowCait/actions-sandbox/runs/5378050068?check_suite_focus=true).
I paste the logs.

<details>
<summary>Full logs</summary>

```
2022-03-01T15:58:05.1079451Z Requested labels: ubuntu-latest
2022-03-01T15:58:05.1079517Z Job defined at: SnowCait/actions-sandbox/.github/workflows/bug.yml@refs/heads/main
2022-03-01T15:58:05.1079541Z Waiting for a runner to pick up this job...
2022-03-01T15:58:05.7394423Z Job is waiting for a hosted runner to come online.
2022-03-01T15:58:11.1218600Z Job is about to start running on the hosted runner: Hosted Agent (hosted)
2022-03-01T15:58:15.0924054Z ##[debug]Starting: build
2022-03-01T15:58:15.0948987Z ##[debug]Cleaning runner temp folder: /home/runner/work/_temp
2022-03-01T15:58:15.1268827Z ##[debug]Starting: Set up job
2022-03-01T15:58:15.1269235Z Current runner version: '2.287.1'
2022-03-01T15:58:15.1293345Z ##[group]Operating System
2022-03-01T15:58:15.1293885Z Ubuntu
2022-03-01T15:58:15.1294190Z 20.04.3
2022-03-01T15:58:15.1294419Z LTS
2022-03-01T15:58:15.1294799Z ##[endgroup]
2022-03-01T15:58:15.1295081Z ##[group]Virtual Environment
2022-03-01T15:58:15.1295483Z Environment: ubuntu-20.04
2022-03-01T15:58:15.1295769Z Version: 20220220.1
2022-03-01T15:58:15.1296289Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220220.1/images/linux/Ubuntu2004-Readme.md
2022-03-01T15:58:15.1296984Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220220.1
2022-03-01T15:58:15.1297389Z ##[endgroup]
2022-03-01T15:58:15.1297754Z ##[group]Virtual Environment Provisioner
2022-03-01T15:58:15.1298237Z 1.0.0.0-main-20220215-1
2022-03-01T15:58:15.1298581Z ##[endgroup]
2022-03-01T15:58:15.1299598Z ##[group]GITHUB_TOKEN Permissions
2022-03-01T15:58:15.1300188Z Actions: write
2022-03-01T15:58:15.1300477Z Checks: write
2022-03-01T15:58:15.1300769Z Contents: write
2022-03-01T15:58:15.1301088Z Deployments: write
2022-03-01T15:58:15.1301377Z Discussions: write
2022-03-01T15:58:15.1301695Z Issues: write
2022-03-01T15:58:15.1302001Z Metadata: read
2022-03-01T15:58:15.1302291Z Packages: write
2022-03-01T15:58:15.1302611Z Pages: write
2022-03-01T15:58:15.1302894Z PullRequests: write
2022-03-01T15:58:15.1303240Z RepositoryProjects: write
2022-03-01T15:58:15.1303547Z SecurityEvents: write
2022-03-01T15:58:15.1303896Z Statuses: write
2022-03-01T15:58:15.1304214Z ##[endgroup]
2022-03-01T15:58:15.1308279Z Secret source: Actions
2022-03-01T15:58:15.1308847Z ##[debug]Primary repository: SnowCait/actions-sandbox
2022-03-01T15:58:15.1309233Z Prepare workflow directory
2022-03-01T15:58:15.1387551Z ##[debug]Creating pipeline directory: '/home/runner/work/actions-sandbox'
2022-03-01T15:58:15.1389813Z ##[debug]Creating workspace directory: '/home/runner/work/actions-sandbox/actions-sandbox'
2022-03-01T15:58:15.1390732Z ##[debug]Update context data
2022-03-01T15:58:15.1393078Z ##[debug]Evaluating job-level environment variables
2022-03-01T15:58:15.2075369Z ##[debug]Evaluating job container
2022-03-01T15:58:15.2078615Z ##[debug]Evaluating job service containers
2022-03-01T15:58:15.2081039Z ##[debug]Evaluating job defaults
2022-03-01T15:58:15.2155750Z Prepare all required actions
2022-03-01T15:58:15.2438782Z ##[debug]Set step 'step1' display name to: 'Run echo '::set-output name=json::{"a":1}''
2022-03-01T15:58:15.2441918Z ##[debug]Set step '__run' display name to: 'Run echo $A'
2022-03-01T15:58:15.2449829Z ##[debug]Collect running processes for tracking orphan processes.
2022-03-01T15:58:15.2698321Z ##[debug]Finishing: Set up job
2022-03-01T15:58:15.2849907Z ##[debug]Evaluating condition for step: 'Run echo '::set-output name=json::{"a":1}''
2022-03-01T15:58:15.3039887Z ##[debug]Evaluating: (success() && false)
2022-03-01T15:58:15.3046343Z ##[debug]Evaluating And:
2022-03-01T15:58:15.3051236Z ##[debug]..Evaluating success:
2022-03-01T15:58:15.3076091Z ##[debug]..=> true
2022-03-01T15:58:15.3081632Z ##[debug]..Evaluating Boolean:
2022-03-01T15:58:15.3082569Z ##[debug]..=> false
2022-03-01T15:58:15.3083166Z ##[debug]=> false
2022-03-01T15:58:15.3089513Z ##[debug]Expanded: (true && false)
2022-03-01T15:58:15.3090135Z ##[debug]Result: false
2022-03-01T15:58:15.3215655Z ##[debug]Evaluating: fromJSON(steps.step1.outputs.json).a
2022-03-01T15:58:15.3217201Z ##[debug]Evaluating Index:
2022-03-01T15:58:15.3219496Z ##[debug]..Evaluating fromJSON:
2022-03-01T15:58:15.3222730Z ##[debug]....Evaluating Index:
2022-03-01T15:58:15.3223194Z ##[debug]......Evaluating Index:
2022-03-01T15:58:15.3223523Z ##[debug]........Evaluating Index:
2022-03-01T15:58:15.3224165Z ##[debug]..........Evaluating steps:
2022-03-01T15:58:15.3225539Z ##[debug]..........=> Object
2022-03-01T15:58:15.3240978Z ##[debug]..........Evaluating String:
2022-03-01T15:58:15.3241474Z ##[debug]..........=> 'step1'
2022-03-01T15:58:15.3245760Z ##[debug]........=> Object
2022-03-01T15:58:15.3246365Z ##[debug]........Evaluating String:
2022-03-01T15:58:15.3246753Z ##[debug]........=> 'outputs'
2022-03-01T15:58:15.3247204Z ##[debug]......=> Object
2022-03-01T15:58:15.3247514Z ##[debug]......Evaluating String:
2022-03-01T15:58:15.3247917Z ##[debug]......=> 'json'
2022-03-01T15:58:15.3248292Z ##[debug]....=> null
2022-03-01T15:58:15.3273237Z ##[error].github/workflows/bug.yml (Line: 16, Col: 14):
2022-03-01T15:58:15.3308188Z ##[error]The template is not valid. .github/workflows/bug.yml (Line: 16, Col: 14): Error reading JToken from JsonReader. Path '', line 0, position 0.
2022-03-01T15:58:15.3381024Z ##[debug]GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. .github/workflows/bug.yml (Line: 16, Col: 14): Error reading JToken from JsonReader. Path '', line 0, position 0.
2022-03-01T15:58:15.3382150Z ##[debug]   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
2022-03-01T15:58:15.3383525Z ##[debug]   at GitHub.DistributedTask.Pipelines.ObjectTemplating.PipelineTemplateEvaluator.EvaluateStepEnvironment(TemplateToken token, DictionaryContextData contextData, IList`1 expressionFunctions, StringComparer keyComparer)
2022-03-01T15:58:15.3384804Z ##[debug]   at GitHub.Runner.Worker.StepsRunner.RunAsync(IExecutionContext jobContext)
2022-03-01T15:58:15.3502123Z ##[debug]Starting: Complete job
2022-03-01T15:58:15.3504065Z Cleaning up orphan processes
2022-03-01T15:58:15.3671934Z ##[debug]Finishing: Complete job
2022-03-01T15:58:15.3801052Z ##[debug]Finishing: build
```

</details>

**Comment by nikola-jokic** [comment]
Hi @SnowCait,

We will try to reproduce this issue and we will get back to you as soon as we can 😊

**Comment by nikola-jokic** [comment]
Hey @SnowCait,

I looked at this problem and the evaluation occurs for each evaluation expression. Just like when you are writing JS, you should guard for the occurrences when your previous step might fail. A nice workaround would be:
```
name: Bug

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo '::set-output name=json::{"a":1}'
        if: false
      - run: echo $A
        env:
          A: ${{ steps.step1.outputs.json && fromJSON(steps.step1.outputs.json).a }}
        if: false
```
Nevertheless, I will mark this as an enhancement and keep it in our backlog, since your proposal does make sense to me to evaluate conditional first and then to skip the entire step if the conditional is false. Thank you for filing this issue! I will bring this issue to our team, to consider this enhancement in the future 😊

**Comment by SnowCait** [comment]
Hi @nikola-jokic,

Thank you for your quick answer.
I completely understood what you said.

Don't hesitate to change issue title and/or body if needed.
