### ISSUE TITLE
Exception in SelfUpdater

### ISSUE THREAD

**Issue by JakeThurman** [actions/runner#1728]
**Describe the bug**

**To Reproduce**
1. Start the runner.
2. Runner says: 
> Current runner version: '2.287.1'
> 2022-03-03 15:14:10Z: Listening for Jobs
> Runner update in progress, do not shutdown runner.
> Downloading 2.288.1 runner
3. Runner crashes after a few seconds

Exception and some context: (full file attached):

```
[2022-03-03 15:07:07Z INFO SelfUpdater] Download latest runner and unzip into runner root.
[2022-03-03 15:07:07Z INFO Terminal] WRITE LINE: Waiting for current job finish running.
[2022-03-03 15:07:07Z INFO Terminal] WRITE LINE: Runner update process finished.
[2022-03-03 15:07:07Z INFO JobDispatcher] Shutting down JobDispatcher. Make sure all WorkerDispatcher has finished.
[2022-03-03 15:07:07Z ERR  Terminal] WRITE ERROR: An error occurred: The handle is invalid.
[2022-03-03 15:07:07Z ERR  Listener] System.IO.IOException: The handle is invalid.
   at System.ConsolePal.WindowsConsoleStream.Write(ReadOnlySpan`1 buffer)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at GitHub.Runner.Common.Terminal.WriteLine(String line, Nullable`1 colorCode)
   at GitHub.Runner.Listener.SelfUpdater.UpdateRunnerUpdateStateAsync(String currentState)
   at GitHub.Runner.Listener.SelfUpdater.SelfUpdate(AgentRefreshMessage updateMessage, IJobDispatcher jobDispatcher, Boolean restartInteractiveRunner, CancellationToken token)
   at GitHub.Runner.Listener.Runner.RunAsync(RunnerSettings settings, Boolean runOnce)
   at GitHub.Runner.Listener.Runner.RunAsync(RunnerSettings settings, Boolean runOnce)
   at GitHub.Runner.Listener.Runner.RunAsync(RunnerSettings settings, Boolean runOnce)
   at GitHub.Runner.Listener.Runner.ExecuteCommand(CommandSettings command)
   at GitHub.Runner.Listener.Program.MainAsync(IHostContext context, String[] args)
```

**Expected behavior**
Update is successful.

## Runner Version and Platform
**Version of your runner?**
2.287.1, attempting to update to 2.288.1 

**OS of the machine running the runner? OSX/Windows/Linux/...**
Windows, running using `run.cmd`. i.e., not running as a service

## What's not working?
See above.

## Job Log Output
N/A

## Runner and Worker's Diagnostic Logs

[Runner_20220303-150644-utc.log](https://github.com/actions/runner/files/8178847/Runner_20220303-150644-utc.log)

I can attach logs from additional attempts if needed, but they all failed at the same point.

**Comment by TingluoHuang** [comment]
This is fixed by https://github.com/actions/runner/pull/1670

**Comment by JakeThurman** [comment]
Manually installing the update fixed the issue. Thank you @TingluoHuang !

**Comment by JakeThurman** [comment]
> @JakeThurman I have the same issue. How to trigger a manual update? Did I need to delete the old version and install the latest version or there is a simpler way? 
> Thanks...

@krupljaninvedran That is exactly what I had to do, although I renamed the actions-runner directory to actions-runner-old as a backup temporarily
