### ISSUE TITLE
2.288.1 Arm64 Configuration of runner not possible

### ISSUE THREAD

**Issue by T3rm1** [actions/runner#1740]
**Describe the bug**
The configuration step of the runner exists with an error. No helpful information neither in the message nor in the log.

**To Reproduce**
1. EC2 instance of ami-0886e2450125a1f08 (Debian 10 ARM)
2. Follow the installation steps of the runner applications until the configuration

**Expected behavior**
No errors or helpful error messages

## Runner Version and Platform
2.288.1 arm64

## What's not working?
Configuration of the GitHub runner.

## Runner and Worker's Diagnostic Logs
```
[2022-03-09 13:53:27Z INFO HostContext] No proxy settings were found based on environmental variables (http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY)
[2022-03-09 13:53:27Z INFO HostContext] Well known directory 'Bin': '/home/admin/actions-runner/bin'
[2022-03-09 13:53:27Z INFO HostContext] Well known directory 'Root': '/home/admin/actions-runner'
[2022-03-09 13:53:27Z INFO HostContext] Well known config file 'Credentials': '/home/admin/actions-runner/.credentials'
[2022-03-09 13:53:27Z INFO HostContext] Well known directory 'Bin': '/home/admin/actions-runner/bin'
[2022-03-09 13:53:27Z INFO HostContext] Well known directory 'Root': '/home/admin/actions-runner'
[2022-03-09 13:53:27Z INFO HostContext] Well known config file 'Runner': '/home/admin/actions-runner/.runner'
[2022-03-09 13:53:27Z INFO Listener] Runner is built for Linux (Arm64) - linux-arm64.
[2022-03-09 13:53:27Z INFO Listener] RuntimeInformation: Linux 4.19.0-14-arm64 #1 SMP Debian 4.19.171-2 (2021-01-30).
[2022-03-09 13:53:27Z INFO Listener] Version: 2.288.1
[2022-03-09 13:53:27Z INFO Listener] Commit: e95a2b840b74568ec30c993462165ece91040f8e
[2022-03-09 13:53:27Z INFO Listener] Culture:
[2022-03-09 13:53:27Z INFO Listener] UI Culture:
[2022-03-09 13:53:27Z INFO HostContext] Well known directory 'Bin': '/home/admin/actions-runner/bin'
[2022-03-09 13:53:27Z INFO HostContext] Well known directory 'Root': '/home/admin/actions-runner'
[2022-03-09 13:53:27Z INFO Listener] Validating directory permissions for: '/home/admin/actions-runner'
[2022-03-09 13:53:27Z INFO CommandLineParser] Parse
[2022-03-09 13:53:27Z INFO CommandLineParser] Parsing 5 args
[2022-03-09 13:53:27Z INFO CommandLineParser] parsing argument
[2022-03-09 13:53:27Z INFO CommandLineParser] HasArgs: False
[2022-03-09 13:53:27Z INFO CommandLineParser] Adding Command: configure
[2022-03-09 13:53:27Z INFO CommandLineParser] parsing argument
[2022-03-09 13:53:27Z INFO CommandLineParser] HasArgs: True
[2022-03-09 13:53:27Z INFO CommandLineParser] arg: url
[2022-03-09 13:53:27Z INFO CommandLineParser] parsing argument
[2022-03-09 13:53:27Z INFO CommandLineParser] HasArgs: True
[2022-03-09 13:53:27Z INFO CommandLineParser] Adding option 'url': 'https://github.com/***'
[2022-03-09 13:53:27Z INFO CommandLineParser] parsing argument
[2022-03-09 13:53:27Z INFO CommandLineParser] HasArgs: True
[2022-03-09 13:53:27Z INFO CommandLineParser] arg: token
[2022-03-09 13:53:27Z INFO CommandLineParser] parsing argument
[2022-03-09 13:53:27Z INFO CommandLineParser] HasArgs: True
[2022-03-09 13:53:27Z INFO CommandLineParser] Adding option 'token': '***'
[2022-03-09 13:53:27Z INFO Listener] Arguments parsed
[2022-03-09 13:53:27Z INFO Runner] ExecuteCommand
[2022-03-09 13:53:27Z INFO ConfigurationStore] currentAssemblyLocation: /home/admin/actions-runner/bin/Runner.Listener.dll
[2022-03-09 13:53:27Z INFO HostContext] Well known directory 'Bin': '/home/admin/actions-runner/bin'
[2022-03-09 13:53:27Z INFO ConfigurationStore] binPath: /home/admin/actions-runner/bin
[2022-03-09 13:53:27Z INFO HostContext] Well known directory 'Bin': '/home/admin/actions-runner/bin'
[2022-03-09 13:53:27Z INFO HostContext] Well known directory 'Root': '/home/admin/actions-runner'
[2022-03-09 13:53:27Z INFO ConfigurationStore] RootFolder: /home/admin/actions-runner
[2022-03-09 13:53:27Z INFO HostContext] Well known directory 'Bin': '/home/admin/actions-runner/bin'
[2022-03-09 13:53:27Z INFO HostContext] Well known directory 'Root': '/home/admin/actions-runner'
[2022-03-09 13:53:27Z INFO HostContext] Well known config file 'Runner': '/home/admin/actions-runner/.runner'
[2022-03-09 13:53:27Z INFO ConfigurationStore] ConfigFilePath: /home/admin/actions-runner/.runner
[2022-03-09 13:53:27Z INFO HostContext] Well known directory 'Bin': '/home/admin/actions-runner/bin'
[2022-03-09 13:53:27Z INFO HostContext] Well known directory 'Root': '/home/admin/actions-runner'
[2022-03-09 13:53:27Z INFO HostContext] Well known config file 'Credentials': '/home/admin/actions-runner/.credentials'
[2022-03-09 13:53:27Z INFO ConfigurationStore] CredFilePath: /home/admin/actions-runner/.credentials
[2022-03-09 13:53:27Z INFO HostContext] Well known directory 'Bin': '/home/admin/actions-runner/bin'
[2022-03-09 13:53:27Z INFO HostContext] Well known directory 'Root': '/home/admin/actions-runner'
[2022-03-09 13:53:27Z INFO HostContext] Well known config file 'MigratedCredentials': '/home/admin/actions-runner/.credentials_migrated'
[2022-03-09 13:53:27Z INFO ConfigurationStore] MigratedCredFilePath: /home/admin/actions-runner/.credentials_migrated
[2022-03-09 13:53:27Z INFO HostContext] Well known directory 'Bin': '/home/admin/actions-runner/bin'
[2022-03-09 13:53:27Z INFO HostContext] Well known directory 'Root': '/home/admin/actions-runner'
[2022-03-09 13:53:27Z INFO HostContext] Well known config file 'Service': '/home/admin/actions-runner/.service'
[2022-03-09 13:53:27Z INFO ConfigurationStore] ServiceConfigFilePath: /home/admin/actions-runner/.service
[2022-03-09 13:53:27Z INFO CommandSettings] Flag 'help': 'False'
[2022-03-09 13:53:27Z INFO CommandSettings] Flag 'version': 'False'
[2022-03-09 13:53:27Z INFO CommandSettings] Flag 'commit': 'False'
[2022-03-09 13:53:27Z INFO CommandSettings] Flag 'check': 'False'
[2022-03-09 13:53:27Z INFO CommandSettings] Command 'configure': 'True'
[2022-03-09 13:53:27Z INFO Terminal] WRITE LINE:
[2022-03-09 13:53:27Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2022-03-09 13:53:27Z INFO Terminal] WRITE LINE: |        ____ _ _   _   _       _          _        _   _                      |
[2022-03-09 13:53:27Z INFO Terminal] WRITE LINE: |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
[2022-03-09 13:53:27Z INFO Terminal] WRITE LINE: |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
[2022-03-09 13:53:27Z INFO Terminal] WRITE LINE: |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
[2022-03-09 13:53:27Z INFO Terminal] WRITE LINE: |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
[2022-03-09 13:53:27Z INFO Terminal] WRITE LINE: |                                                                              |
[2022-03-09 13:53:27Z INFO Terminal] WRITE: |
[2022-03-09 13:53:27Z INFO Terminal] WRITE: Self-hosted runner registration
[2022-03-09 13:53:27Z INFO Terminal] WRITE LINE:                         |
[2022-03-09 13:53:27Z INFO Terminal] WRITE LINE: |                                                                              |
[2022-03-09 13:53:27Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2022-03-09 13:53:27Z INFO ConfigurationManager] ConfigureAsync
[2022-03-09 13:53:27Z INFO ConfigurationStore] IsConfigured()
[2022-03-09 13:53:27Z INFO ConfigurationStore] IsConfigured: False
[2022-03-09 13:53:27Z INFO ConfigurationManager] Is configured: False
[2022-03-09 13:53:27Z INFO CommandSettings] Arg 'url': 'https://github.com/***'
[2022-03-09 13:53:27Z INFO CommandSettings] Remove url from Arg dictionary.
[2022-03-09 13:53:27Z INFO CommandSettings] Arg 'token': '***'
[2022-03-09 13:53:27Z INFO CommandSettings] Remove token from Arg dictionary.
[2022-03-09 13:53:28Z ERR  Runner] System.NullReferenceException: Object reference not set to an instance of an object.
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at GitHub.Runner.Listener.Runner.ExecuteCommand(CommandSettings command)
[2022-03-09 13:53:28Z ERR  Terminal] WRITE ERROR: Object reference not set to an instance of an object.
[2022-03-09 13:53:28Z INFO Listener] Runner execution has finished with return code 1
```

**Comment by ruvceskistefan** [comment]
Hi @T3rm1,
Are you sure you used a valid repository URL and register token during configuration? I ask because I am working on a [bug](https://github.com/actions/runner/issues/1739) in which a null reference exception has been thrown for this situation.

**Comment by ruvceskistefan** [comment]
Are you sure you didn't have a problem with the network or permissions? Unfortunately, I can't understand the cause of the error from the logs, and this isn't something I can reproduce locally and thus discover the cause.

**Comment by T3rm1** [comment]
How can I test that? I was able to download the runner with curl. And I still get this error. What domains/ports do I need access to?

**Comment by ruvceskistefan** [comment]
Self-hosted runner must be able to communicate with your GitHub Enterprise Server instance over HTTP (port 80) and HTTPS (port 443). I don't believe this is a cause of error, but you can check it out.

**Comment by ruvceskistefan** [comment]
I'm sending you [instructions](https://github.com/actions/runner/tree/main/docs/checks) for self-debugging since it's impossible for me to reproduce this issue locally. Please let me know if any of this helps you or you manage to find out the cause of the problem.

**Comment by T3rm1** [comment]
I couldn't find any networking issue. DNS, ping and traceroute all look fine.
You said you can't reproduce it locally. Did you test it with the image on aws which I mentioned in my initial post?

**Comment by ruvceskistefan** [comment]
No, I haven't done it yet. According to the [documentation](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#supported-architectures-and-operating-systems-for-self-hosted-runners), you shouldn't have any problems with the environment (Debian 10 ARM64), but I will try with image on the AWS as well.

**Comment by ruvceskistefan** [comment]
Hi @T3rm1,
I tried to create an identical environment as you on the AWS (Debian 10 ARM64 image) and I managed to configure the runner without any problems. Have you tried to do configuration again in a new image?

**Comment by T3rm1** [comment]
Yes, it was a new instance. Plus I created a second instance, this time with a public ip address and it had the same problem. So if it worked for you then the issue must be a configuration issue of the instance. Are you able to enhance the logging so we know what exactly does not work and where the null pointer exception comes up?

**Comment by ruvceskistefan** [comment]
I agree that the problem is up to the configuration of the instance, it only makes sense to me. Unfortunately, there is no way to enhance the logging until I reproduce the error, because I have to know in which part of the code null ref exception is thrown. Since the error does not happen in my Debian 10 AMI, there is no way to reproduce it.
You can try with [enabling debug logging](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging), that way you would get more information.

**Comment by T3rm1** [comment]
I was able to solve it. In the end, you were right, it was an issue with the token. I didn't know the token changes over time. I copied all instructions to my editor and always used these. I checked them again and saw that the token changed. With the new token it worked. Sorry for the inconvenience.

**Comment by ruvceskistefan** [comment]
No problem, it's important that we solve it. The PR I mentioned at the beginning will close the bug with the null ref exception, so that error is solved as well.

**Comment by umithyo** [comment]
I encountered this issue and solved it by simply refreshing the page and copying the new token.
