### ISSUE TITLE
Self hosted runner went offline suddenly and it is not connected.

### ISSUE THREAD

**Issue by vyadav3** [actions/runner#1798]
My Windows Github runner was working fine and suddenly from yesterday it is not connecting and is in Offline state. When I try to run it again then it gives this error. 
![image](https://user-images.githubusercontent.com/84782822/161035914-be720b18-30b8-425f-87d1-29fedc351803.png)

Runner Version: 2.277.1

**Also attaching logs:**  I have replaced the tokens with xxxxxxxxxxx in this log

[2022-03-31 09:54:44Z WARN GitHubActionsService] Authentication failed with status code 401.
WWW-Authenticate: Bearer
Strict-Transport-Security: max-age=2592000
X-TFS-ProcessId: 898e726f-7325-4553-89fc-2b86a4016a89
ActivityId: 58c8d4c8-b8b3-4cb6-8b7f-9d8c4f4b3a4b
X-TFS-Session: 80cbef06-47fc-4156-b1fe-6d99d4667230
X-VSS-E2EID: 9a4c489a-91ca-447d-b55e-67f3913e4ad2
X-VSS-SenderDeploymentId: d624195d-30e0-1768-06a5-b10a7879c7db
X-TFS-ServiceError: The+user+%27System%3aPublicAccess%3baaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa%27+is+not+authorized+to+access+this+resource.
X-VSS-S2STargetService: 0000005A-0000-8888-8000-000000000000/visualstudio.com
X-Cache: CONFIG_NOCACHE
X-MSEdge-Ref: Ref A: xxxxx Ref B: xxxxx Ref C: 2022-03-31T09:54:44Z
Date: Thu, 31 Mar 2022 09:54:43 GMT

[2022-03-31 09:54:44Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\Users\Administrator\actions-runner\.credentials_rsaparams
[2022-03-31 09:54:44Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\Users\Administrator\actions-runner\.credentials_rsaparams
[2022-03-31 09:54:44Z ERR  GitHubActionsService] POST request to https://vstoken.actions.githubusercontent.com/_apis/oauth2/token/xxxxxxx failed. HTTP Status: BadRequest, AFD Ref: Ref A: xxxxxxxxxx Ref B: xxxxxx Ref C: 2022-03-31T09:54:44Z
[2022-03-31 09:54:44Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
[2022-03-31 09:54:44Z ERR  MessageListener] Catch exception during create session.
[2022-03-31 09:54:44Z ERR  MessageListener] GitHub.Services.OAuth.VssOAuthTokenRequestException: Registration was not found or is not medium trust. ClientType: 
   at GitHub.Services.OAuth.VssOAuthTokenProvider.OnGetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
   at GitHub.Services.Common.IssuedTokenProvider.GetTokenOperation.GetTokenAsync(VssTraceActivity traceActivity)
   at GitHub.Services.Common.IssuedTokenProvider.GetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Listener.MessageListener.CreateSessionAsync(CancellationToken token)
[2022-03-31 09:54:44Z ERR  MessageListener] Test oauth app registration.
[2022-03-31 09:54:44Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\Users\Administrator\actions-runner\.credentials_rsaparams
[2022-03-31 09:54:44Z ERR  GitHubActionsService] POST request to https://vstoken.actions.githubusercontent.com/_apis/oauth2/token/xxxxxxxxxxx failed. HTTP Status: BadRequest, AFD Ref: Ref A: D5345C6C236940139A4062AF35BBB985 Ref B: BL2EDGE1921 Ref C: 2022-03-31T09:54:44Z
[2022-03-31 09:54:44Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
[2022-03-31 09:54:44Z ERR  Terminal] WRITE ERROR: Failed to create a session. The runner registration has been deleted from the server, please re-configure.
[2022-03-31 09:54:44Z INFO Listener] Runner execution has finished with return code 1

**Comment by fhammerl** [comment]
> Runner Version: 2.277.1

The runner version is quite old. When was the last time it ran a job? (You should see `Worker_TIMESTAMP.log` in your `path_to_runner/_diag` directory).

There is a [mechanism](https://docs.github.com/en/actions/hosting-your-own-runners/removing-self-hosted-runners#:~:text=you%20restart%20the%20runner%20using%20the%20run%20application.-,A%20self%2Dhosted%20runner%20is%20automatically%20removed%20from%20GitHub%20if%20it%20has%20not%20connected%20to%20GitHub%20Actions%20for%20more%20than%2030%20days.,-To%20remove%20a%20self%2Dhosted%20runner%20from%20an) that cleans up runners that haven't run a job in a while.

**Comment by vyadav3** [comment]
@fhammerl Thanks for responding. Runner was not old and almost every day we run this. Also runner version was 20 days old only. But It was stopped working. 

Now it is running as I have removed old runner and created new runner and it started working. Still don't know what was the reason that it was not working before.

Thanks,
Vipin

**Comment by vfranciscatto-ambipar** [comment]
Had a similar issue.
Runner went offline on GitHub, its service wont restart on the vm and got the '... runner registration has been deleted ...'  with the '.\run.cmd' command.
Turns out it was the incorrect system date time

**Comment by Typhon0130** [comment]
How can I create new runner and also how can I remove old runner?

**Comment by piljaechae** [comment]
@vfranciscatto-ambipar How did you figure out whether the issue was related with system time?
