### ISSUE TITLE
No space left on device after upgrading to 2.289.2

### ISSUE THREAD

**Issue by mocsharp** [actions/runner#1807]
**Describe the bug**
Our integration test build step started failing after the runner upgraded to 2.289.2.

**To Reproduce**
_Sorry for the terrible bug description._ 

1. Go to https://github.com/Project-MONAI/monai-deploy-informatics-gateway/actions/runs/2093298340
2. The `docker-compose log` command would eventually time out and the job would get canceled.

```
System.IO.IOException: No space left on device : '/home/runner/runners/2.289.2/_diag/Worker_20220405-003310-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device : '/home/runner/runners/2.289.2/_diag/Worker_20220405-003310-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Error(Exception exception)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.289.2/_diag/Worker_20220405-003310-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)
```

**Expected behavior**
Build step to pass https://github.com/Project-MONAI/monai-deploy-informatics-gateway/actions/runs/2080265670

## Runner Version and Platform
Version of your runner? 2.289.2

OS of the machine running the runner? Linux

## What's not working?
See https://github.com/Project-MONAI/monai-deploy-informatics-gateway/runs/5826064123?check_suite_focus=true

## Job Log Output
Can't get to the output of the step as it spins forever.

## Runner and Worker's Diagnostic Logs
NA

**Comment by ruvceskistefan** [comment]
Hi @mocsharp,

Is it possible that you spent all the disk space by running this workflow?

In the [docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) you can see that Linux virtual machines have 14 GB of SSD disk space. I found a similar issue on the GitHub Community Forum, so [here](https://github.community/t/bug-strange-no-space-left-on-device-ioexceptions-on-github-runners/17616) you can see some useful links and hints.

Please let me know if any of this helped you or if you have any more questions. Thank you!

**Comment by mocsharp** [comment]
We are not using all the disk space, rather, the integration test that runs the actual application reserves 20% of the disk space and stops processing when it hits the watermark.  

I'm guessing some changes were made to the storage allocations for the runners in _v2.289.2_.  In our case, the available storage is now less than 80% (74% from below) thus the failure.

I was able to fix it on my end by changing some settings.  So, please feel free to close the issue.

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   62G   22G  74% /
devtmpfs        3.4G     0  3.4G   0% /dev
tmpfs           3.4G  4.0K  3.4G   1% /dev/shm
tmpfs           695M  1.1M  694M   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.4G     0  3.4G   0% /sys/fs/cgroup
/dev/loop0       62M   62M     0 100% /snap/core20/1376
/dev/loop1       68M   68M     0 100% /snap/lxd/22526
/dev/loop2       44M   44M     0 100% /snap/snapd/15177
/dev/sda15      105M  5.2M  100M   5% /boot/efi
/dev/sdb1        14G  4.1G  9.0G  32% /mnt
```

Thanks🙏

**Comment by ruvceskistefan** [comment]
Thanks for your reply. Then I will close this issue for now, and if there are more users with a similar problem, we will reopen it. Thanks again @mocsharp!

**Comment by semonec** [comment]
@ruvceskistefan 
Hello, I've met similar issue on my system.
While it's running, shutdowned with below error msg
```
Unhandled exception. System.IO.IOException: No space left on device : '/actions-runner/_diag/Runner_20220913-135355-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Terminal.WriteError(String line)
   at GitHub.Runner.Listener.Program.MainAsync(IHostContext context, String[] args)
   at GitHub.Runner.Listener.Program.Main(String[] args)
/actions-runner/run-helper.sh: line 20: 26550 Aborted                 "$DIR"/bin/Runner.Listener run $*
Exiting with unknown error code: 134
Exiting runner...
```
Used action runner version: **2.294.0**

**Comment by jerrychong25** [comment]
In my case, I've used [Free Disk Space Ubuntu](https://github.com/marketplace/actions/free-disk-space-ubuntu) in GitHub Actions to solve my problem.

Free Disk Space Ubuntu GitHub Actions Sample Code:
```
name: sample-github-actions

jobs:
  sample_job:
    # The host should always be Linux
    runs-on: ubuntu-20.04
    name: Build on ubuntu-20.04 armv8
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Free Up GitHub Actions Ubuntu Runner Disk Space 🔧
        uses: jlumbroso/free-disk-space@main
        with:
          # This might remove tools that are actually needed, if set to "true" but frees about 6 GB
          tool-cache: false

          # All of these default to true, but feel free to set to "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
```

Hope this helps those face same issue.
