### ISSUE TITLE
Error: Can't use 'tar -xzf' extract archive file

### ISSUE THREAD

**Issue by vavuthu** [actions/runner#1923]
**Describe the bug**

Can't use runner. getting below error while running actions

Getting action download info
Download action repository 'actions/checkout@v2' (SHA:7884fcad6b5d53d10323aee724dc68d8b9096a2e)
Download action repository 'actions/setup-python@v2' (SHA:7f80679172b057fc5e90d70d197929d454754a5a)
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_fcaba673-8301-4f09-b4c0-658716c016e9/0f75c0dd-581a-4910-aa5c-6a5cc9a53620.tar.gz. return code: 2.

**To Reproduce**
1. run github actions

**Expected behavior**

actions should be complete without any errors

## Runner Version and Platform
Current runner version: '2.291.1'

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
Current runner version: '2.291.1'
Operating System
Virtual Environment
Virtual Environment Provisioner
GITHUB_TOKEN Permissions
Secret source: None
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2' (SHA:7884fcad6b5d53d10323aee724dc68d8b9096a2e)
Download action repository 'actions/setup-python@v2' (SHA:7f80679172b057fc5e90d70d197929d454754a5a)
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_fcaba673-8301-4f09-b4c0-658716c016e9/0f75c0dd-581a-4910-aa5c-6a5cc9a53620.tar.gz. return code: 2.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by kennethlynne** [comment]
Seems like there is an issue with downloads from GitHub now causing this. Not necessarily related to this runner, but no relevant issues show up on the [status page](https://www.githubstatus.com/) yet
```
##[debug]Download 'https://api.github.com/repos/actions/checkout/tarball/7884fcad6b5d53d10323aee724dc68d8b9096a2e' to '/home/runner/work/_actions/_temp_a5[50](https://github.com/repo/runs/6704514689?check_suite_focus=true#step:1:54)142d-0c74-440a-acaf-e526af6ec97d/1fa4ba8b-28e8-4e94-b98c-36df9a67a84d.tar.gz'
##[debug]Unwrap 'actions-checkout-7884fca' to '/home/runner/work/_actions/actions/checkout/v2'
##[debug]Archive '/home/runner/work/_actions/_temp_a550142d-0c74-440a-acaf-e526af6ec97d/1fa4ba8b-28e8-4e94-b98c-36df9a67a84d.tar.gz' has been unzipped into '/home/runner/work/_actions/actions/checkout/v2'.
Download action repository 'cypress-io/github-action@v2' (SHA:f5bea478b80a774068179089247f13d60abc5010)
##[debug]Download 'https://api.github.com/repos/cypress-io/github-action/tarball/f5bea478b80a774068179089247f13d60abc5010' to '/home/runner/work/_actions/_temp_5fbb9635-be9b-4a7b-b73c-0ebccfec2765/58b39741-0df7-42c0-a724-c399f0b53d[52](https://github.com/repo/runs/6704514689?check_suite_focus=true#step:1:56).tar.gz'
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_5fbb9635-be9b-4a7b-b73c-0ebccfec2765/58b39741-0df7-42c0-a724-c399f0b[53](https://github.com/repo/runs/6704514689?check_suite_focus=true#step:1:57)d52.tar.gz. return code: 2.
##[debug]System.NotSupportedException: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_5fbb9635-be9b-4a7b-b73c-0ebccfec2765/58b39741-0df7-42c0-a724-c399f0b53d52.tar.gz. return code: 2.
```

**Comment by levrik** [comment]
@kennethlynne We're also hit by this issue and I just saw that you're also using the `cypress-io/github-action` in your flow which we're using as well. All other flows not using this particular action are working fine.

**Comment by claudesky** [comment]
@levrik I had the same issue with actions/cache , it might not be something specific to that action

```
2022-06-02T07:31:37.9410277Z Requested labels: ubuntu-latest
2022-06-02T07:31:37.9410326Z Job defined at: human-incubator/hii-berben-api/.github/workflows/api_deep_testing.yml@refs/pull/135/merge
2022-06-02T07:31:37.9410360Z Waiting for a runner to pick up this job...
2022-06-02T07:31:38.4804160Z Job is waiting for a hosted runner to come online.
2022-06-02T07:31:41.7120304Z Job is about to start running on the hosted runner: GitHub Actions 2 (hosted)
2022-06-02T07:31:45.3932730Z Current runner version: '2.291.1'
2022-06-02T07:31:45.3957556Z ##[group]Operating System
2022-06-02T07:31:45.3958149Z Ubuntu
2022-06-02T07:31:45.3958384Z 20.04.4
2022-06-02T07:31:45.3958661Z LTS
2022-06-02T07:31:45.3958942Z ##[endgroup]
2022-06-02T07:31:45.3959326Z ##[group]Virtual Environment
2022-06-02T07:31:45.3959720Z Environment: ubuntu-20.04
2022-06-02T07:31:45.3960011Z Version: 20220515.1
2022-06-02T07:31:45.3960524Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220515.1/images/linux/Ubuntu2004-Readme.md
2022-06-02T07:31:45.3961171Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220515.1
2022-06-02T07:31:45.3961659Z ##[endgroup]
2022-06-02T07:31:45.3962014Z ##[group]Virtual Environment Provisioner
2022-06-02T07:31:45.3962371Z 1.0.0.0-main-20220516-1
2022-06-02T07:31:45.3962633Z ##[endgroup]
2022-06-02T07:31:45.3963338Z ##[group]GITHUB_TOKEN Permissions
2022-06-02T07:31:45.3963864Z Checks: write
2022-06-02T07:31:45.3964324Z Contents: read
2022-06-02T07:31:45.3964909Z Issues: read
2022-06-02T07:31:45.3965215Z Metadata: read
2022-06-02T07:31:45.3965482Z PullRequests: write
2022-06-02T07:31:45.3965797Z ##[endgroup]
2022-06-02T07:31:45.3969324Z Secret source: Actions
2022-06-02T07:31:45.3969865Z Prepare workflow directory
2022-06-02T07:31:45.4828344Z Prepare all required actions
2022-06-02T07:31:45.5012540Z Getting action download info
2022-06-02T07:31:45.7359967Z Download action repository 'actions/checkout@v2' (SHA:7884fcad6b5d53d10323aee724dc68d8b9096a2e)
2022-06-02T07:31:46.3806597Z Download action repository 'actions/cache@v2' (SHA:937d24475381cd9c75ae6db12cb4e79714b926ed)
2022-06-02T07:31:46.7458476Z ##[error]Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_cf1ffd67-1857-4283-a39e-49599b0ee39d/06579d60-f1f2-4519-945b-48dd8cee9f01.tar.gz. return code: 2.
```

**Comment by levrik** [comment]
@claudesky Then just coincidence that that first log I saw here was failing on the exact same action. Still weird that the workflows using the Cypress action are the only ones failing for us... at least so far.

**Comment by claudesky** [comment]
My failing and succeeding run differ in that the failing run ran on `Github Actions 2 (hosted)` while the succeeding one ran on `Hosted Agent (hosted)`

Successful run:
```
2022-06-02T08:04:16.7646023Z Requested labels: ubuntu-latest
2022-06-02T08:04:16.7646082Z Job defined at: ***
2022-06-02T08:04:16.7646107Z Waiting for a runner to pick up this job...
2022-06-02T08:04:17.2154105Z Job is waiting for a hosted runner to come online.
2022-06-02T08:04:21.3465203Z Job is about to start running on the hosted runner: Hosted Agent (hosted)
2022-06-02T08:04:24.8974587Z Current runner version: '2.291.1'
2022-06-02T08:04:24.9001536Z ##[group]Operating System
2022-06-02T08:04:24.9002087Z Ubuntu
2022-06-02T08:04:24.9002364Z 20.04.4
2022-06-02T08:04:24.9002750Z LTS
2022-06-02T08:04:24.9003065Z ##[endgroup]
2022-06-02T08:04:24.9003431Z ##[group]Virtual Environment
2022-06-02T08:04:24.9003829Z Environment: ubuntu-20.04
2022-06-02T08:04:24.9004218Z Version: 20220515.1
2022-06-02T08:04:24.9004721Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220515.1/images/linux/Ubuntu2004-Readme.md
2022-06-02T08:04:24.9005424Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220515.1
2022-06-02T08:04:24.9005902Z ##[endgroup]
2022-06-02T08:04:24.9006302Z ##[group]Virtual Environment Provisioner
2022-06-02T08:04:24.9006694Z 1.0.0.0-main-20220516-1
2022-06-02T08:04:24.9007033Z ##[endgroup]
2022-06-02T08:04:24.9007734Z ##[group]GITHUB_TOKEN Permissions
2022-06-02T08:04:24.9008378Z Checks: write
2022-06-02T08:04:24.9008848Z Contents: read
2022-06-02T08:04:24.9009258Z Issues: read
2022-06-02T08:04:24.9009595Z Metadata: read
2022-06-02T08:04:24.9009954Z PullRequests: write
2022-06-02T08:04:24.9010250Z ##[endgroup]
2022-06-02T08:04:24.9013851Z Secret source: Actions
2022-06-02T08:04:24.9014370Z Prepare workflow directory
2022-06-02T08:04:24.9848513Z Prepare all required actions
2022-06-02T08:04:25.0042811Z Getting action download info
2022-06-02T08:04:25.3987128Z Download action repository 'actions/checkout@v2' (SHA:7884fcad6b5d53d10323aee724dc68d8b9096a2e)
2022-06-02T08:04:25.7042374Z Download action repository 'actions/cache@v2' (SHA:937d24475381cd9c75ae6db12cb4e79714b926ed)
2022-06-02T08:04:25.9498455Z Download action repository 'docker/setup-buildx-action@v2' (SHA:dc7b9719a96d48369863986a06765841d7ea23f6)
2022-06-02T08:04:26.1268791Z Download action repository 'EnricoMi/publish-unit-test-result-action@v1.36' (SHA:c8ce9bba212f019b0449ca319e8fecef2f06cd66)
```

**Comment by levrik** [comment]
I can confirm that `GitHub Actions 2` seems to always fail. Succeeding runs were on `GitHub Actions 5` for me.

**Comment by boegel** [comment]
For anyone hitting this in workflows using `actions/cache` (like I am), apparently bumping to v3 could fix the issue, see https://github.com/actions/cache/issues/811

**Comment by levrik** [comment]
@boegel We're on `actions/cache@3` already and are still hit by this.

**Comment by claudesky** [comment]
mentioned in zeromq/pyzmq#1709

they have a macOS runner that also failed with a similar error, this on GitHub Actions 3

```
2022-06-02T07:00:58.6695522Z The agent pool assigned to this job has hit their MacOs concurrency limits
2022-06-02T07:00:58.7054247Z Requested labels: macos-10.15
2022-06-02T07:00:58.7054346Z Job defined at: zeromq/pyzmq/.github/workflows/test.yml@refs/pull/1709/merge
2022-06-02T07:00:58.7054404Z Waiting for a runner to pick up this job...
2022-06-02T07:05:31.0287470Z Job is waiting for a hosted runner to come online.
2022-06-02T07:05:39.0406102Z Job is about to start running on the hosted runner: GitHub Actions 3 (hosted)
2022-06-02T07:05:43.4575320Z Current runner version: '2.291.1'
2022-06-02T07:05:43.4613380Z ##[group]Operating System
2022-06-02T07:05:43.4613890Z Mac OS X
2022-06-02T07:05:43.4614090Z 10.15.7
2022-06-02T07:05:43.4614290Z 19H1922
2022-06-02T07:05:43.4614500Z ##[endgroup]
2022-06-02T07:05:43.4614740Z ##[group]Virtual Environment
2022-06-02T07:05:43.4615030Z Environment: macos-10.15
2022-06-02T07:05:43.4615280Z Version: 20220523.3
2022-06-02T07:05:43.4615700Z Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20220523.3/images/macos/macos-10.15-Readme.md
2022-06-02T07:05:43.4616290Z Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-10.15%2F20220523.3
2022-06-02T07:05:43.4616660Z ##[endgroup]
2022-06-02T07:05:43.4616920Z ##[group]Virtual Environment Provisioner
2022-06-02T07:05:43.4617200Z 1.0.0.0-main-20220516-1
2022-06-02T07:05:43.4617430Z ##[endgroup]
2022-06-02T07:05:43.4618240Z ##[group]GITHUB_TOKEN Permissions
2022-06-02T07:05:43.4618870Z Actions: read
2022-06-02T07:05:43.4619150Z Checks: read
2022-06-02T07:05:43.4619360Z Contents: read
2022-06-02T07:05:43.4619590Z Deployments: read
2022-06-02T07:05:43.4619830Z Discussions: read
2022-06-02T07:05:43.4620050Z Issues: read
2022-06-02T07:05:43.4620260Z Metadata: read
2022-06-02T07:05:43.4620490Z Packages: read
2022-06-02T07:05:43.4620700Z Pages: read
2022-06-02T07:05:43.4620960Z PullRequests: read
2022-06-02T07:05:43.4621220Z RepositoryProjects: read
2022-06-02T07:05:43.4621470Z SecurityEvents: read
2022-06-02T07:05:43.4621710Z Statuses: read
2022-06-02T07:05:43.4621940Z ##[endgroup]
2022-06-02T07:05:43.4626520Z Secret source: None
2022-06-02T07:05:43.4626940Z Prepare workflow directory
2022-06-02T07:05:43.5776070Z Prepare all required actions
2022-06-02T07:05:43.6024590Z Getting action download info
2022-06-02T07:05:43.8723910Z Download action repository 'actions/checkout@v2' (SHA:7884fcad6b5d53d10323aee724dc68d8b9096a2e)
2022-06-02T07:05:45.1118780Z Download action repository 'actions/setup-python@v2' (SHA:7f80679172b057fc5e90d70d197929d454754a5a)
2022-06-02T07:05:46.6042040Z Download action repository 'actions/cache@v2' (SHA:937d24475381cd9c75ae6db12cb4e79714b926ed)
2022-06-02T07:05:47.0771680Z ##[error]'/Users/runner/work/_actions/_temp_23eddb76-7d0e-4382-8fb0-98dd3c7e0a0e/80457705-8335-4c45-9891-822f66654c90.tar.gz' contains '0' directories
```

**Comment by tguilpain** [comment]
It seems to be that the downloaded tar archive is empty

**Comment by levrik** [comment]
Might be fixed according to https://github.com/actions/cache/issues/811#issuecomment-1144590383

**Comment by azarudeena** [comment]
https://github.com/actions/cache/issues/811

Referencing this even v3 has still issues

**Comment by levrik** [comment]
Workflow runs are reliably passing for me now without any changes.

**Comment by vavuthu** [comment]
checks are still failing
```
##[debug]Starting: Set up job
Current runner version: '2.291.1'
Operating System
Virtual Environment
Virtual Environment Provisioner
GITHUB_TOKEN Permissions
Secret source: None
##[debug]Primary repository: red-hat-storage/ocs-ci
Prepare workflow directory
##[debug]Creating pipeline directory: '/home/runner/work/ocs-ci'
##[debug]Creating workspace directory: '/home/runner/work/ocs-ci/ocs-ci'
##[debug]Update context data
##[debug]Evaluating job-level environment variables
##[debug]Evaluating job container
##[debug]Evaluating job service containers
##[debug]Evaluating job defaults
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2' (SHA:7884fcad6b5d53d10323aee724dc68d8b9096a2e)
##[debug]Download 'https://api.github.com/repos/actions/checkout/tarball/7884fcad6b5d53d10323aee724dc68d8b9096a2e' to '/home/runner/work/_actions/_temp_7ce008a5-e7a4-43ef-97b6-188050aae9f1/4d15c2cf-20ad-464c-bbd8-df3d870392fe.tar.gz'
##[debug]Unwrap 'actions-checkout-7884fca' to '/home/runner/work/_actions/actions/checkout/v2'
##[debug]Archive '/home/runner/work/_actions/_temp_7ce008a5-e7a4-43ef-97b6-188050aae9f1/4d15c2cf-20ad-464c-bbd8-df3d870392fe.tar.gz' has been unzipped into '/home/runner/work/_actions/actions/checkout/v2'.
Download action repository 'actions/setup-python@v2' (SHA:7f80679172b057fc5e90d70d197929d454754a5a)
##[debug]Download 'https://api.github.com/repos/actions/setup-python/tarball/7f80679172b057fc5e90d70d197929d454754a5a' to '/home/runner/work/_actions/_temp_da92c613-1ac4-4e3f-b7c5-5a4f6fdbb61c/c6da0c38-1812-4000-a493-43ac0256b3dd.tar.gz'
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_da92c613-1ac4-4e3f-b7c5-5a4f6fdbb61c/c6da0c38-1812-4000-a493-43ac0256b3dd.tar.gz. return code: 2.
##[debug]System.NotSupportedException: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_da92c613-1ac4-4e3f-b7c5-5a4f6fdbb61c/c6da0c38-1812-4000-a493-43ac0256b3dd.tar.gz. return code: 2.
##[debug]   at GitHub.Runner.Worker.ActionManager.DownloadRepositoryActionAsync(IExecutionContext executionContext, ActionDownloadInfo downloadInfo, String destDirectory)
##[debug]   at GitHub.Runner.Worker.ActionManager.DownloadRepositoryActionAsync(IExecutionContext executionContext, ActionDownloadInfo downloadInfo)
##[debug]   at GitHub.Runner.Worker.ActionManager.PrepareActionsRecursiveAsync(IExecutionContext executionContext, PrepareActionsState state, IEnumerable`1 actions, Int32 depth, Guid parentStepId)
##[debug]   at GitHub.Runner.Worker.ActionManager.PrepareActionsAsync(IExecutionContext executionContext, IEnumerable`1 steps, Guid rootStepId)
##[debug]   at GitHub.Runner.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
##[debug]Finishing: Set up job```

**Comment by sugatoray** [comment]
It seems that this issue has been fixed now. My latest job ran past the failure it halted at earlier.

- [Before: `FAILED` :red_circle:](https://github.com/danoneata/chalk/runs/6704722439?check_suite_focus=true#step:1:37)
- [Now: `PASSED` :green_circle:](https://github.com/danoneata/chalk/runs/6705697977?check_suite_focus=true)

**Comment by thboop** [comment]
Hey folks,

A server side bug caused this issue, we've since mitigated the problem, please let us know if you see it again. 

Thank you for your patience while we addressed it and sorry for the trouble it may have caused you

**Comment by vavuthu** [comment]
actions are running as expected.

**Comment by aliakb** [comment]
@thboop Just got this error as well - 5 times in a row. The log looks like this:
```
Current runner version: '2.294.0'
Operating System
Virtual Environment
Virtual Environment Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:[2](https://github.com/discoveryinc-ds/pergola-gql-rest-router/runs/7308685841?check_suite_focus=true#step:1:2)541b1294d2704b09[6](https://github.com/discoveryinc-ds/pergola-gql-rest-router/runs/7308685841?check_suite_focus=true#step:1:7)48[13](https://github.com/discoveryinc-ds/pergola-gql-rest-router/runs/7308685841?check_suite_focus=true#step:1:16)337f33b291d3f8596b)
Download action repository 'actions/setup-node@v3' (SHA:5b949b50c3461bbcd5a540b150c368[27](https://github.com/discoveryinc-ds/pergola-gql-rest-router/runs/7308685841?check_suite_focus=true#step:1:31)8160234a)
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_0cf9b0a3-10f2-46b3-81[32](https://github.com/discoveryinc-ds/pergola-gql-rest-router/runs/7308685841?check_suite_focus=true#step:1:36)-27faac882c0e/8f805591-5395-496d-8369-581d68f44808.tar.gz. return code: 2.
```

**Comment by TingluoHuang** [comment]
we are looking at this now...

**Comment by niconiahi** [comment]
same here

**Comment by TingluoHuang** [comment]
`actions/setup-node@v3` was not downloaded properly due to a server side bug.
We applied a server side fix and this should be good now base on our telemetry.
Sorry for the inconvenice. 🙇

**Comment by abroadwin** [comment]
Thanks! Confirmed that builds are back to green :)

**Comment by aliakb** [comment]
Thank you; appreciate your instant response!

**Comment by fabiofdsantos** [comment]
@TingluoHuang Still happening: https://github.com/upptime/upptime/actions/runs/2747365664

**Comment by TingluoHuang** [comment]
@fabiofdsantos sorry for the trouble... I am looking into this.

**Comment by TingluoHuang** [comment]
@fabiofdsantos we clean up the bad cache, things should be back to normal.

**Comment by valberg** [comment]
We are currently experiencing this

```
##[debug]Starting: Set up job
Current runner version: '2.297.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
##[debug]Primary repository: org/proj
Prepare workflow directory
##[debug]Creating pipeline directory: '/home/runner/work/proj'
##[debug]Creating workspace directory: '/home/runner/work/proj'
##[debug]Update context data
##[debug]Evaluating job-level environment variables
##[debug]Evaluating job container
##[debug]Evaluating job service containers
##[debug]Evaluating job defaults
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:2541b1294d2704b0964813337f33b291d3f8596b)
##[debug]Download 'https://api.github.com/repos/actions/checkout/tarball/2541b1294d2704b0964813337f33b291d3f8596b' to '/home/runner/work/_actions/_temp_52482ad0-4f93-4a60-aeca-7f85e8ecda10/1c831ab4-546d-4df1-ad0d-10723147d72f.tar.gz'
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_52482ad0-4f93-4a60-aeca-7f85e8ecda10/1c831ab4-546d-4df1-ad0d-10723147d72f.tar.gz. return code: 2.
##[debug]System.NotSupportedException: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_52482ad0-4f93-4a60-aeca-7f85e8ecda10/1c831ab4-546d-4df1-ad0d-10723147d72f.tar.gz. return code: 2.
##[debug]   at GitHub.Runner.Worker.ActionManager.DownloadRepositoryActionAsync(IExecutionContext executionContext, ActionDownloadInfo downloadInfo, String destDirectory)
##[debug]   at GitHub.Runner.Worker.ActionManager.DownloadRepositoryActionAsync(IExecutionContext executionContext, ActionDownloadInfo downloadInfo)
##[debug]   at GitHub.Runner.Worker.ActionManager.PrepareActionsRecursiveAsync(IExecutionContext executionContext, PrepareActionsState state, IEnumerable`1 actions, Int32 depth, Guid parentStepId)
##[debug]   at GitHub.Runner.Worker.ActionManager.PrepareActionsAsync(IExecutionContext executionContext, IEnumerable`1 steps, Guid rootStepId)
##[debug]   at GitHub.Runner.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
##[debug]Finishing: Set up job
```

**Comment by valberg** [comment]
Our workflow is running again - maybe someone cleaned up the cache?

**Comment by RobPasMue** [comment]
I confirm that there are multiple users experiencing this issue again
https://github.com/orgs/community/discussions/26321

**Comment by DragosRomaniuc** [comment]
This issue is happening again for me.

**Comment by mazenkhalil** [comment]
For me the issue is happening when concurrent tasks are running utilizing actions/checkout@v3.

**Comment by j-nix** [comment]
This particular issue seems to be back

**Comment by Fxou** [comment]
Yes, I agree with @j-nix : the same error come back on my workflow today.

**Comment by Peter-developer01** [comment]
Same error. Just when I need workflows, everything hinders me.

**Comment by asdcamargo** [comment]
All workflows are broken and not running, github should treat this as a major incident and update their status page: https://www.githubstatus.com/

**Comment by Peter-developer01** [comment]
It appears to be running again.

**Comment by sergii-rybin-tfs** [comment]
Again for us. Nothing is working.

**Comment by Thor99** [comment]
Same error for us... @caioarruda look at him!

**Comment by arrudacaio** [comment]
Nothing is running here

**Comment by 3nilorac** [comment]
Same error here!

**Comment by Peter-developer01** [comment]
Well, here we go again.

**Comment by raphael1-souza** [comment]
The problem returned to us

**Comment by AlexanderSehr** [comment]
Didn't even make it to the first line of code 😄 
![image](https://github.com/actions/runner/assets/5365358/3772f536-4080-44c2-b04b-ca7c0cb346be)

**Comment by bhargavms** [comment]
same here we are suffering.

**Comment by PietroPasotti** [comment]
we're all on the same container it seems

**Comment by filipnavara** [comment]
> we're all on the same container it seems

Happens on our self-hosted CI machines too.

**Comment by filipnavara** [comment]
Tracked on https://www.githubstatus.com/ now.

**Comment by Peter-developer01** [comment]
Nice, thanks for involving. Hope the problem will be solved.

**Comment by pgupta-swi** [comment]
Thanks for the update, waiting for the fix.

**Comment by igoritos22** [comment]
This issue is back, guys!
All workflows have failed for me.

**Comment by Peter-developer01** [comment]
The incident has been resolved. Thank you.

**Comment by mx2s** [comment]
I started to experience this too since about an hour ago

**Comment by kevinbarabash** [comment]
I've been seeing on and off starting today.

**Comment by rharkor** [comment]
And it's back..

**Comment by Erik312** [comment]
yup back forsake

**Comment by atticusrussell** [comment]
glad to see it's not just me

**Comment by Pickra** [comment]
same for me

**Comment by ezbeazy** [comment]
ditto

**Comment by sarnold** [comment]
fails for me on about 30% of matrix jobs

**Comment by Firefds** [comment]
Experiencing this on both cloud and self-hosted runners since ~15 min ago.

**Comment by Peter-developer01** [comment]
The incident has been resolved again. :+1:

**Comment by pgupta-swi** [comment]
We can see the issue started appearing again.

**Comment by mmhsavolai** [comment]
We're experiencing this too with many of our Linux runner actions right now.

**Comment by martin-g** [comment]
using `actions/checkout@v4` solved the problem for me

**Comment by galib120** [comment]
[Pergolas DEFRA Shades](https://defra.ae/)
Costum Outdoor Infrastructure Design & Installation
More than a outdoor patio, an awning, a umbela or a veranda, pergolas with louvered roof happen to be the ultimate answer to your outdoor living satisfaction. You will need louvered pergola to: affect the amount from sunlight by partially beginning the top louvered rotor blades boostwinter temperatures through your house by pointing the baldes for the home and letting the sun’s rays in guardhome and exterior furniture by fading and deterioration enhance the value of the property.

https://defra.ae/

**Comment by EagleoutIce** [comment]
I again have this issue using `actions/checkout@v4` - maybe because the action is located in the same repository? The issue however is flaky and only appears randomly in ~50% of the jobs per run.
