### ISSUE TITLE
Can't install runner with proxy - Only the 'http', 'socks4', 'socks4a' and 'socks5' schemes are allowed for proxies

### ISSUE THREAD

**Issue by kevin-brashears** [actions/runner#2000]
**Describe the bug**
When installing Runner on a server behind a firewall, need to use proxy for all aspects of the install, not just the normal running.

**To Reproduce**
1. Extract zip file
2. Create .env file with `https_proxy` properly set
3. Run comfig.cmd (there aren't any --proxyurl switches, which is what I would have expected - this was the case for ADO agents)
4. Fails with 'Only the 'http', 'socks4', 'socks4a' and 'socks5' schemes are allowed for proxies.'
5. I can tell from firewall & proxy logs that it is not respecting the `https_proxy` settings in the `.env` file
6. Have tried variations of https_proxy, http_proxy, and no_proxy configurations to no avail

**Expected behavior**
All aspects of the install and everyday operation should use proxy settings

## Runner Version and Platform
Trying to install 2.294.0

OS of the machine running the runner? OSX/Windows/Linux/...
Windows

## What's not working?
Only the 'http', 'socks4', 'socks4a' and 'socks5' schemes are allowed for proxies.

## Job Log Output
[2022-07-13 17:08:31Z INFO HostContext] Configuring anonymous proxy https://{} for all HTTPS requests.
[2022-07-13 17:08:31Z INFO HostContext] Well known directory 'Bin': 'C:\github-actions\bin'
[2022-07-13 17:08:31Z INFO HostContext] Well known directory 'Root': 'C:\github-actions'
[2022-07-13 17:08:31Z INFO HostContext] Well known config file 'Credentials': 'C:\github-actions\.credentials'
[2022-07-13 17:08:31Z INFO HostContext] Well known directory 'Bin': 'C:\github-actions\bin'
[2022-07-13 17:08:31Z INFO HostContext] Well known directory 'Root': 'C:\github-actions'
[2022-07-13 17:08:31Z INFO HostContext] Well known config file 'Runner': 'C:\github-actions\.runner'
[2022-07-13 17:08:31Z INFO Listener] Runner is built for Windows (X64) - win-x64.
[2022-07-13 17:08:31Z INFO Listener] RuntimeInformation: Microsoft Windows 10.0.14393.
[2022-07-13 17:08:31Z INFO Listener] Version: 2.294.0
[2022-07-13 17:08:31Z INFO Listener] Commit: {}
[2022-07-13 17:08:31Z INFO Listener] Culture: en-US
[2022-07-13 17:08:31Z INFO Listener] UI Culture: en-US
[2022-07-13 17:08:31Z INFO HostContext] Well known directory 'Bin': 'C:\github-actions\bin'
[2022-07-13 17:08:31Z INFO HostContext] Well known directory 'Root': 'C:\github-actions'
[2022-07-13 17:08:31Z INFO Listener] Validating directory permissions for: 'C:\github-actions'
[2022-07-13 17:08:31Z INFO CommandLineParser] Parse
[2022-07-13 17:08:31Z INFO CommandLineParser] Parsing 9 args
[2022-07-13 17:08:31Z INFO CommandLineParser] parsing argument
[2022-07-13 17:08:31Z INFO CommandLineParser] HasArgs: False
[2022-07-13 17:08:31Z INFO CommandLineParser] Adding Command: configure
[2022-07-13 17:08:31Z INFO CommandLineParser] parsing argument
[2022-07-13 17:08:31Z INFO CommandLineParser] HasArgs: True
[2022-07-13 17:08:31Z INFO CommandLineParser] arg: url
[2022-07-13 17:08:31Z INFO CommandLineParser] parsing argument
[2022-07-13 17:08:31Z INFO CommandLineParser] HasArgs: True
[2022-07-13 17:08:31Z INFO CommandLineParser] Adding option 'url': '{}'
[2022-07-13 17:08:31Z INFO CommandLineParser] parsing argument
[2022-07-13 17:08:31Z INFO CommandLineParser] HasArgs: True
[2022-07-13 17:08:31Z INFO CommandLineParser] arg: token
[2022-07-13 17:08:31Z INFO CommandLineParser] parsing argument
[2022-07-13 17:08:31Z INFO CommandLineParser] HasArgs: True
[2022-07-13 17:08:31Z INFO CommandLineParser] Adding option 'token': ''
[2022-07-13 17:08:31Z INFO CommandLineParser] parsing argument
[2022-07-13 17:08:31Z INFO CommandLineParser] HasArgs: True
[2022-07-13 17:08:31Z INFO CommandLineParser] arg: unattended
[2022-07-13 17:08:31Z INFO CommandLineParser] parsing argument
[2022-07-13 17:08:31Z INFO CommandLineParser] HasArgs: True
[2022-07-13 17:08:31Z INFO CommandLineParser] arg: labels
[2022-07-13 17:08:31Z INFO CommandLineParser] Adding flag: unattended
[2022-07-13 17:08:31Z INFO CommandLineParser] parsing argument
[2022-07-13 17:08:31Z INFO CommandLineParser] HasArgs: True
[2022-07-13 17:08:31Z INFO CommandLineParser] Adding option 'labels': 'dev,nurse'
[2022-07-13 17:08:31Z INFO CommandLineParser] parsing argument
[2022-07-13 17:08:31Z INFO CommandLineParser] HasArgs: True
[2022-07-13 17:08:31Z INFO CommandLineParser] arg: runasservice
[2022-07-13 17:08:31Z INFO Listener] Arguments parsed
[2022-07-13 17:08:31Z INFO Runner] ExecuteCommand
[2022-07-13 17:08:31Z INFO ConfigurationStore] currentAssemblyLocation: C:\github-actions\bin\Runner.Listener.dll
[2022-07-13 17:08:31Z INFO HostContext] Well known directory 'Bin': 'C:\github-actions\bin'
[2022-07-13 17:08:31Z INFO ConfigurationStore] binPath: C:\github-actions\bin
[2022-07-13 17:08:31Z INFO HostContext] Well known directory 'Bin': 'C:\github-actions\bin'
[2022-07-13 17:08:31Z INFO HostContext] Well known directory 'Root': 'C:\github-actions'
[2022-07-13 17:08:31Z INFO ConfigurationStore] RootFolder: C:\github-actions
[2022-07-13 17:08:31Z INFO HostContext] Well known directory 'Bin': 'C:\github-actions\bin'
[2022-07-13 17:08:31Z INFO HostContext] Well known directory 'Root': 'C:\github-actions'
[2022-07-13 17:08:31Z INFO HostContext] Well known config file 'Runner': 'C:\github-actions\.runner'
[2022-07-13 17:08:31Z INFO ConfigurationStore] ConfigFilePath: C:\github-actions\.runner
[2022-07-13 17:08:31Z INFO HostContext] Well known directory 'Bin': 'C:\github-actions\bin'
[2022-07-13 17:08:31Z INFO HostContext] Well known directory 'Root': 'C:\github-actions'
[2022-07-13 17:08:31Z INFO HostContext] Well known config file 'Credentials': 'C:\github-actions\.credentials'
[2022-07-13 17:08:31Z INFO ConfigurationStore] CredFilePath: C:\github-actions\.credentials
[2022-07-13 17:08:31Z INFO HostContext] Well known directory 'Bin': 'C:\github-actions\bin'
[2022-07-13 17:08:31Z INFO HostContext] Well known directory 'Root': 'C:\github-actions'
[2022-07-13 17:08:31Z INFO HostContext] Well known config file 'MigratedCredentials': 'C:\github-actions\.credentials_migrated'
[2022-07-13 17:08:31Z INFO ConfigurationStore] MigratedCredFilePath: C:\github-actions\.credentials_migrated
[2022-07-13 17:08:31Z INFO HostContext] Well known directory 'Bin': 'C:\github-actions\bin'
[2022-07-13 17:08:31Z INFO HostContext] Well known directory 'Root': 'C:\github-actions'
[2022-07-13 17:08:31Z INFO HostContext] Well known config file 'Service': 'C:\github-actions\.service'
[2022-07-13 17:08:31Z INFO ConfigurationStore] ServiceConfigFilePath: C:\github-actions\.service
[2022-07-13 17:08:31Z INFO CommandSettings] Flag 'help': 'False'
[2022-07-13 17:08:31Z INFO CommandSettings] Flag 'version': 'False'
[2022-07-13 17:08:31Z INFO CommandSettings] Flag 'commit': 'False'
[2022-07-13 17:08:31Z INFO CommandSettings] Flag 'check': 'False'
[2022-07-13 17:08:31Z INFO CommandSettings] Command 'configure': 'True'
[2022-07-13 17:08:31Z INFO Terminal] WRITE LINE: 
[2022-07-13 17:08:31Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2022-07-13 17:08:31Z INFO Terminal] WRITE LINE: |        ____ _ _   _   _       _          _        _   _                      |
[2022-07-13 17:08:31Z INFO Terminal] WRITE LINE: |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
[2022-07-13 17:08:31Z INFO Terminal] WRITE LINE: |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
[2022-07-13 17:08:31Z INFO Terminal] WRITE LINE: |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
[2022-07-13 17:08:31Z INFO Terminal] WRITE LINE: |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
[2022-07-13 17:08:31Z INFO Terminal] WRITE LINE: |                                                                              |
[2022-07-13 17:08:31Z INFO Terminal] WRITE: |                       
[2022-07-13 17:08:31Z INFO Terminal] WRITE: Self-hosted runner registration
[2022-07-13 17:08:31Z INFO Terminal] WRITE LINE:                         |
[2022-07-13 17:08:31Z INFO Terminal] WRITE LINE: |                                                                              |
[2022-07-13 17:08:31Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2022-07-13 17:08:31Z INFO ConfigurationManager] ConfigureAsync
[2022-07-13 17:08:31Z INFO ConfigurationStore] IsConfigured()
[2022-07-13 17:08:31Z INFO ConfigurationStore] IsConfigured: False
[2022-07-13 17:08:31Z INFO ConfigurationManager] Is configured: False
[2022-07-13 17:08:31Z INFO CommandSettings] Arg 'url': '{}'
[2022-07-13 17:08:31Z INFO CommandSettings] Remove url from Arg dictionary.
[2022-07-13 17:08:31Z INFO CommandSettings] Arg 'token': '***'
[2022-07-13 17:08:31Z INFO CommandSettings] Remove token from Arg dictionary.
[2022-07-13 17:08:31Z ERR  ConfigurationManager] Failed to get tenant credentials -- Atempt: 1
[2022-07-13 17:08:31Z ERR  ConfigurationManager] System.NotSupportedException: Only the 'http', 'socks4', 'socks4a' and 'socks5' schemes are allowed for proxies.
   at System.Net.Http.HttpConnectionPoolManager.SendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.GetTenantCredential(String githubUrl, String githubToken, String runnerEvent)
[2022-07-13 17:08:31Z INFO ConfigurationManager] Retrying in 2 seconds
[2022-07-13 17:08:33Z ERR  ConfigurationManager] Failed to get tenant credentials -- Atempt: 2
[2022-07-13 17:08:33Z ERR  ConfigurationManager] System.NotSupportedException: Only the 'http', 'socks4', 'socks4a' and 'socks5' schemes are allowed for proxies.
   at System.Net.Http.HttpConnectionPoolManager.SendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.GetTenantCredential(String githubUrl, String githubToken, String runnerEvent)
[2022-07-13 17:08:33Z INFO ConfigurationManager] Retrying in 4 seconds

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by kevin-brashears** [comment]
I redacted the IP with {}

I figured it out - I was using a https://{} going to a proxy that is only HTTP, not HTTPS.

Setting `.env` file looking like this works:
```
https_proxy=http://servername:port
http_proxy=http://servername:port
```
