### ISSUE TITLE
Self-hosted runner registration for windows fail

### ISSUE THREAD

**Issue by Ankit-Sharma-ggn** [actions/runner#2032]
### Discussed in https://github.com/actions/runner/discussions/2024

<div type='discussions-op-text'>

<sup>Originally posted by **Ankit-Sharma-ggn** July 26, 2022</sup>
I am trying to register the self-hosted runner in our Windows server. While running the  ./config.cmd command, I am getting error.

The SSL connection could not be established, see inner exception.
Failed to connect.  Try again or ctrl-c to quit

After checking the logs I found errors related to connection close by remote host.

`[2022-07-26 15:56:57Z INFO Terminal] WRITE: Self-hosted runner registration
[2022-07-26 15:56:57Z INFO Terminal] WRITE LINE:                         |
[2022-07-26 15:56:57Z INFO Terminal] WRITE LINE: |                                                                              |
[2022-07-26 15:56:57Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2022-07-26 15:56:57Z INFO ConfigurationManager] ConfigureAsync
[2022-07-26 15:56:57Z INFO ConfigurationStore] IsConfigured()
[2022-07-26 15:56:57Z INFO ConfigurationStore] IsConfigured: False
[2022-07-26 15:56:57Z INFO ConfigurationManager] Is configured: False
[2022-07-26 15:56:57Z INFO CommandSettings] Arg 'url': 'https://github.com/Ankit-Sharma-ggn/Github_actions'
[2022-07-26 15:56:57Z INFO CommandSettings] Remove url from Arg dictionary.
[2022-07-26 15:56:57Z INFO CommandSettings] Arg 'token': '***'
[2022-07-26 15:56:57Z INFO CommandSettings] Remove token from Arg dictionary.
[2022-07-26 15:56:58Z INFO ConfigurationManager] Http response code: OK from 'POST https://api.github.com/actions/runner-registration'
[2022-07-26 15:56:58Z INFO ConfigurationManager] cred retrieved via GitHub auth
[2022-07-26 15:56:58Z INFO RunnerServer] Establish connection with 100 seconds timeout.
[2022-07-26 15:56:58Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2022-07-26 15:56:58Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2022-07-26 15:56:58Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2022-07-26 15:56:58Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2022-07-26 15:56:58Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2022-07-26 15:56:58Z WARN GitHubActionsService] Attempt 1 of GET request to https://pipelines.actions.githubusercontent.com/7cvDTiRKLtnerfIGjQksW9pkQDtOWCyewvS0vzSS0JUCSy4CNR/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: ConnectionReset). The operation will be retried in 10.918 seconds.
[2022-07-26 15:56:58Z WARN GitHubActionsService] Attempt 1 of GET request to https://pipelines.actions.githubusercontent.com/7cvDTiRKLtnerfIGjQksW9pkQDtOWCyewvS0vzSS0JUCSy4CNR/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: ConnectionReset). The operation will be retried in 11.047 seconds.
[2022-07-26 15:56:58Z WARN GitHubActionsService] Attempt 1 of GET request to https://pipelines.actions.githubusercontent.com/7cvDTiRKLtnerfIGjQksW9pkQDtOWCyewvS0vzSS0JUCSy4CNR/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: ConnectionReset). The operation will be retried in 10.891 seconds.
[2022-07-26 15:57:09Z WARN GitHubActionsService] Attempt 2 of GET request to https://pipelines.actions.githubusercontent.com/7cvDTiRKLtnerfIGjQksW9pkQDtOWCyewvS0vzSS0JUCSy4CNR/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: ConnectionReset). The operation will be retried in 13.177 seconds.
[2022-07-26 15:57:09Z WARN GitHubActionsService] Attempt 2 of GET request to https://pipelines.actions.githubusercontent.com/7cvDTiRKLtnerfIGjQksW9pkQDtOWCyewvS0vzSS0JUCSy4CNR/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: ConnectionReset). The operation will be retried in 12.829 seconds.
[2022-07-26 15:57:09Z WARN GitHubActionsService] Attempt 2 of GET request to https://pipelines.actions.githubusercontent.com/7cvDTiRKLtnerfIGjQksW9pkQDtOWCyewvS0vzSS0JUCSy4CNR/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: ConnectionReset). The operation will be retried in 13.24 seconds.
[2022-07-26 15:57:22Z WARN GitHubActionsService] Attempt 3 of GET request to https://pipelines.actions.githubusercontent.com/7cvDTiRKLtnerfIGjQksW9pkQDtOWCyewvS0vzSS0JUCSy4CNR/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: ConnectionReset). The operation will be retried in 17.756 seconds.
[2022-07-26 15:57:22Z WARN GitHubActionsService] Attempt 3 of GET request to https://pipelines.actions.githubusercontent.com/7cvDTiRKLtnerfIGjQksW9pkQDtOWCyewvS0vzSS0JUCSy4CNR/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: ConnectionReset). The operation will be retried in 17.805 seconds.
[2022-07-26 15:57:22Z WARN GitHubActionsService] Attempt 3 of GET request to https://pipelines.actions.githubusercontent.com/7cvDTiRKLtnerfIGjQksW9pkQDtOWCyewvS0vzSS0JUCSy4CNR/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: ConnectionReset). The operation will be retried in 17.133 seconds.
[2022-07-26 15:57:39Z ERR  GitHubActionsService] Attempt 4 of GET request to https://pipelines.actions.githubusercontent.com/7cvDTiRKLtnerfIGjQksW9pkQDtOWCyewvS0vzSS0JUCSy4CNR/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: ConnectionReset). The maximum number of attempts has been reached.
[2022-07-26 15:57:39Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2022-07-26 15:57:39Z INFO RunnerServer] Catch exception during connect. 4 attempt left.
[2022-07-26 15:57:39Z ERR  RunnerServer] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|187_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---`</div>

**Comment by nikola-jokic** [comment]
Hey @Ankit-Sharma-ggn,

Did you check your network connection using [this](https://github.com/actions/runner/blob/main/docs/checks/network.md) guide?

**Comment by nikola-jokic** [comment]
I am going to close this issue now until we hear back from you. Please, let us know if you managed to solve it
