### ISSUE TITLE
Runner fails to pick up workflows on GitHub Enterprise

### ISSUE THREAD

**Issue by rasmus** [actions/runner#2051]
**Describe the bug**
GitHub runner fails to pick up jobs on GitHub Enterprise after following the recommended approach for setting up runners in AWS.

From what I can read, the token is created using `.actions.createRegistrationTokenForRepo` from the Octo client.

P.S.: I know this is a long shot, but hope you can point in the right direction.

**To Reproduce**

1. Setup GitHub runners using [the recommended partner](https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners#recommended-autoscaling-solutions)
2. Create a GitHub App in one GitHub organization
3. Install the GitHub App in another organization

**Expected behavior**
Workflows are executed.

## Runner Version and Platform
Version 2.294.0 on Ubuntu 22.04

## What's not working?
Workflows aren't picked up, but following the audit logs from the GitHub App from the GitHub management, the runner is registered.

## Job Log Output
None, doesn't get that far.

## Runner and Worker's Diagnostic Logs
Log output from a working run started from a repository within the App owning organization
```
[2022-08-10 09:00:06Z INFO Terminal] WRITE LINE: 2022-08-10 09:00:06Z: Listening for Jobs
[2022-08-10 09:00:05Z INFO Listener] Runner execution has finished with return code 0
[2022-08-10 09:00:06Z INFO JobDispatcher] Set runner/worker IPC timeout to 30 seconds.
[2022-08-10 09:00:10Z INFO RSAFileKeyManager] Loading RSA key parameters from file /opt/actions-runner/.credentials_rsaparams
[2022-08-10 09:00:10Z INFO MessageListener] Message '1' received from session '5c5a9842-863e-4790-b5e6-1a6173fff763'.
[2022-08-10 09:00:10Z INFO Runner] Received job message of length 47589 from service, with hash '808e5d3fd2321237dcf7386f2623504ee52b43e14879caf5570b0c7084ff42ea'"
[2022-08-10 09:00:10Z INFO JobDispatcher] Job request 112 for plan 6c258cf2-e964-4a96-bc4f-9ab057f42cdb job ca395085-040a-526b-2ce8-bdc85f692774 received.
```

Log output from a runner started via a workflow when the App is installed in another organization.
```
[2022-08-10 07:48:51Z INFO Terminal] WRITE LINE: Current runner version: '2.294.0'
[2022-08-10 07:48:51Z INFO Terminal] WRITE LINE: 2022-08-10 07:48:51Z: Listening for Jobs
[2022-08-10 07:48:49Z INFO Listener] Runner execution has finished with return code 0
[2022-08-10 07:48:51Z INFO JobDispatcher] Set runner/worker IPC timeout to 30 seconds.
[2022-08-10 07:52:34Z ERR  GitHubActionsService] GET request to https://github.schibsted.io/_services/pipelines/0lZ6HfmBqhea7YYwAgKjEpGlqlf9vZ9PVsikv0KCKEtsb8SPYh/_apis/distributedtask/pools/1/messages?sessionId=a674ecf8-aae2-4f12-acbb-39607411145c failed. HTTP Status: Forbidden
[2022-08-10 07:52:34Z ERR  MessageListener] Catch exception during get next message.
[2022-08-10 07:52:34Z ERR  MessageListener] GitHub.DistributedTask.WebApi.AccessDeniedException: Access denied. System:ServiceIdentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD needs View permissions to perform the action.
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Listener.MessageListener.GetNextMessageAsync(CancellationToken token)"
```

**Comment by rasmus** [comment]
Seems like the issue is related to the repository visibility. Internals and private are working, but public is having problems.  Also if the checkmark is ticked

![image](https://user-images.githubusercontent.com/18956/183908353-3bedd7eb-9123-4f8d-8479-0a0f6d50a2c1.png)

**Comment by neethu-p** [comment]
By default self hosted-runner groups are enabled only for internal/private repositories.For using for public repos we need to explicitly enable the runner group under : org settings -> actions -> runners.

**Comment by rasmus** [comment]
We solved our issue. Maybe the runner could check that it is actually able to run and provide a better log message if not.
