### ISSUE TITLE
Self-hosted runner on arm64 doesn't use proxy to download artifacts.

### ISSUE THREAD

**Issue by qtxie** [actions/runner#2183]
**Describe the bug**

Self-hosted runner on arm64 doesn't use proxy to download artifacts.

See the logs below, it doesn't use the proxy, so the connect got reset once.

## Job Log Output
```
Current runner version: '2.297.0'
Machine name: 'armbian'
GITHUB_TOKEN Permissions
Secret source: Actions
Runner is running behind proxy server 'http://127.0.0.1:1235/' for all HTTP requests.
Runner is running behind proxy server 'http://127.0.0.1:1235/' for all HTTPS requests.

Run actions/download-artifact@v2
Starting download for rpi-rs-bin
Directory structure has been setup for the artifact
Total number of files that will be downloaded: 38
Total file count: 38 ---- Processed file #0 (0.0%)
Total file count: 38 ---- Processed file #2 (5.2%)
Total file count: 38 ---- Processed file #3 (7.8%)
Total file count: 38 ---- Processed file #4 (10.5%)
Total file count: 38 ---- Processed file #5 (13.1%)
Total file count: 38 ---- Processed file #5 (13.1%)
Total file count: 38 ---- Processed file #6 (15.7%)
Total file count: 38 ---- Processed file #7 (18.4%)
Total file count: 38 ---- Processed file #8 (21.0%)
Total file count: 38 ---- Processed file #9 (23.6%)
Total file count: 38 ---- Processed file #10 (26.3%)
Total file count: 38 ---- Processed file #11 (28.9%)
Total file count: 38 ---- Processed file #11 (28.9%)
Total file count: 38 ---- Processed file #12 (31.5%)
Total file count: 38 ---- Processed file #13 (34.2%)
Total file count: 38 ---- Processed file #13 (34.2%)
Total file count: 38 ---- Processed file #14 (36.8%)
Total file count: 38 ---- Processed file #15 (39.4%)
Total file count: 38 ---- Processed file #16 (42.1%)
Total file count: 38 ---- Processed file #17 (44.7%)
Total file count: 38 ---- Processed file #18 (47.3%)
Total file count: 38 ---- Processed file #18 (47.3%)
Total file count: 38 ---- Processed file #19 (50.0%)
Total file count: 38 ---- Processed file #20 (52.6%)
Total file count: 38 ---- Processed file #20 (52.6%)
Total file count: 38 ---- Processed file #21 (55.2%)
Total file count: 38 ---- Processed file #22 (57.8%)
Total file count: 38 ---- Processed file #23 (60.5%)
Total file count: 38 ---- Processed file #24 (63.1%)
Total file count: 38 ---- Processed file #24 (63.1%)
Total file count: 38 ---- Processed file #25 (65.7%)
Total file count: 38 ---- Processed file #26 (68.4%)
Total file count: 38 ---- Processed file #27 (71.0%)
Total file count: 38 ---- Processed file #28 (73.6%)
Total file count: 38 ---- Processed file #28 (73.6%)
Total file count: 38 ---- Processed file #29 (76.3%)
Total file count: 38 ---- Processed file #30 (78.9%)
Total file count: 38 ---- Processed file #31 (81.5%)
Total file count: 38 ---- Processed file #31 (81.5%)
Total file count: 38 ---- Processed file #32 (84.2%)
Total file count: 38 ---- Processed file #33 (86.8%)
Total file count: 38 ---- Processed file #34 (89.4%)
Total file count: 38 ---- Processed file #35 (92.1%)
Total file count: 38 ---- Processed file #36 (94.7%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
An error occurred while attempting to download a file
Error: tunneling socket could not be established, statusCode=504
    at ClientRequest.onConnect (/home/qt/actions-runner/_work/_actions/actions/download-artifact/v2/dist/index.js:1975:19)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at Socket.socketOnData (_http_client.js:508:11)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  code: 'ECONNRESET'
}
Exponential backoff for retry #1. Waiting for 6334 milliseconds before continuing the download
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Total file count: 38 ---- Processed file #37 (97.3%)
Finished backoff for retry #1, continuing with download
Total file count: 38 ---- Processed file #37 (97.3%)
```

## Runner Version and Platform
Runner version: '2.297.0' on armbian ARM64

**Comment by nikola-jokic** [comment]
Hey @qtxie,

Thank you for reporting this issue! This is a duplicate issue of #2166, so I will close it now. For updates, please refer to the liked issue :relaxed:
