### ISSUE TITLE
How to set the cert path for runner config.sh. Need to tell it where to pick up the certificates from in-order to overcome HTTP 407

### ISSUE THREAD

**Issue by dinesh-pillai-db** [actions/runner#2220]
**Describe the enhancement**
I am trying to set up the self hosted runner within my company and is behind a proxy. I will need to authenticate with the proxy first and this is done through a certificate. However I am not sure how to provide the path to the certificate. I am able to run the other command to retrieve the registration token. That uses a curl command which allows me to pass in the certificate path and hence able to authenticate with the proxy

**Code Snippet**
the code that is being run is the following:
 ./config.sh --check --url https://github.com/2sim-yst5/pace-ci-cd --pat ****************************************

**Additional information**
The above command fails for all checks except the Github CLI

NOTE: if the feature request has been agreed upon then the assignee will create an ADR.   See docs/adrs/README.md

**Comment by dinesh-pillai-db** [comment]
2022-10-21T07:25:04.7419081Z ***************************************************************************************************************
2022-10-21T07:25:04.7419390Z ****                                                                                                       ****
2022-10-21T07:25:04.7419401Z ****     !!! WARNING !!!
2022-10-21T07:25:04.7419406Z ****     DO NOT share the log in public place! The log may contains secrets in plain text.
2022-10-21T07:25:04.7419408Z ****     !!! WARNING !!!
2022-10-21T07:25:04.7419424Z ****                                                                                                       ****
2022-10-21T07:25:04.7419519Z ***************************************************************************************************************
2022-10-21T07:25:04.7516040Z ***************************************************************************************************************
2022-10-21T07:25:04.7516105Z ****                                                                                                       ****
2022-10-21T07:25:04.7516108Z ****     Runner is behind web proxy http://sp-surf-proxy.intranet.db.com:8080/
2022-10-21T07:25:04.7516153Z ****                                                                                                       ****
2022-10-21T07:25:04.7516156Z ***************************************************************************************************************
2022-10-21T07:25:04.7592305Z ***************************************************************************************************************
2022-10-21T07:25:04.7592373Z ****                                                                                                       ****
2022-10-21T07:25:04.7592377Z ****     Try DNS lookup for api.github.com
2022-10-21T07:25:04.7592857Z ****                                                                                                       ****
2022-10-21T07:25:04.7592860Z ***************************************************************************************************************
2022-10-21T07:25:04.7743643Z Resolved DNS for api.github.com to '140.82.121.5'
2022-10-21T07:25:04.7722444Z ***************************************************************************************************************
2022-10-21T07:25:04.7722519Z ****                                                                                                       ****
2022-10-21T07:25:04.7722524Z ****     Send HTTPS Request (GET) to https://api.github.com
2022-10-21T07:25:04.7722530Z ****                                                                                                       ****
2022-10-21T07:25:04.7722533Z ***************************************************************************************************************
2022-10-21T07:25:04.9107994Z ***************************************************************************************************************
2022-10-21T07:25:04.9108053Z ****                                                                                                       ****
2022-10-21T07:25:04.9108083Z ****     Https request 'GET' to https://api.github.com failed with error: System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://sp-surf-proxy.intranet.db.com:8080/' failed with status code '407'."
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GitHub.Runner.Listener.Check.CheckUtil.CheckHttpsGetRequests(IHostContext hostContext, String url, String pat, String expectedHeader)
