### ISSUE TITLE
Self Hosted Runner Failing to POST Log Output

### ISSUE THREAD

**Issue by karimtabet** [actions/runner#2228]
**Describe the bug**
I've an organisation-level self hosted runner on an Ubuntu 22.04 host. It's successfully authenticated with the organisation and some jobs run successfully. However, logs aren't being sent from the runner to GitHub Enterprise, job success or failure. I've had a look at the Worker logs (at _diag/Worker_<date>.log) and can see lot's of this:

```
[2022-10-25 21:28:17Z ERR  GitHubActionsService] POST request to https://github.grlab.co.uk/_services/pipelines/kS8cHJOCPXwsg1CYr1cagBaajHbUQl0sxc6fIBPrkc8vIRLjlI/00000000-0000-0000-0000-000000000000/_apis/distributedtask/hubs/Actions/plans/28c2d1c9-6d56-4d70-a8d9-31c7277ce09e/logs/2 failed. HTTP Status: InternalServerError
[2022-10-25 21:28:17Z INFO JobServerQueue] Catch exception during log or attachment file upload, keep going since the process is best effort.
[2022-10-25 21:28:17Z ERR  JobServerQueue] GitHub.Services.Common.VssServiceException: An Internal Error Occurred. Activity Id: c0fbdcfd-cc2a-4050-b894-fc99a5ef0fbf.
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Common.JobServerQueue.UploadFile(UploadFileInfo file)
   at GitHub.Runner.Common.JobServerQueue.ProcessFilesUploadQueueAsync(Boolean runOnce)
[2022-10-25 21:28:17Z INFO JobServerQueue] Try to upload 2 log files or attachments, success rate: 0/2.
[2022-10-25 21:28:17Z INFO JobServerQueue] File upload queue drained.
[2022-10-25 21:28:17Z INFO JobServerQueue] Timeline update queue drained.
[2022-10-25 21:28:17Z INFO JobServerQueue] Disposing job server ...
[2022-10-25 21:28:17Z INFO JobServerQueue] All queue process tasks have been stopped, and all queues are drained.
[2022-10-25 21:28:17Z INFO TempDirectoryManager] Cleaning runner temp folder: /home/tigadmin/actions-runner/_work/_temp
[2022-10-25 21:28:17Z INFO HostContext] Well known directory 'Bin': '/home/tigadmin/actions-runner/bin'
[2022-10-25 21:28:17Z INFO HostContext] Well known directory 'Root': '/home/tigadmin/actions-runner'
[2022-10-25 21:28:17Z INFO HostContext] Well known directory 'Diag': '/home/tigadmin/actions-runner/_diag'
[2022-10-25 21:28:17Z INFO HostContext] Well known config file 'Telemetry': '/home/tigadmin/actions-runner/_diag/.telemetry'
[2022-10-25 21:28:17Z INFO JobRunner] Raising job completed event
[2022-10-25 21:28:17Z INFO Worker] Job completed.
```

Seems I keep getting an InternalServerError when trying to POST to Enterprise's logs endpoint. I've tried uninstalling the runner and creating a new one with a new token but have the same issue.

**To Reproduce**
1. `mkdir actions-runner && cd actions-runner`
2. `curl -o actions-runner-linux-x64-2.289.3.tar.gz -L -H 'Authorization: Bearer ***' https://github.grlab.co.uk/_services/pipelines/_apis/distributedtask/packagedownload/agent/linux-x64/2.289.3`
3. `tar xzf ./actions-runner-linux-x64-2.289.3.tar.gz`
4. `./config.sh --url https://github.grlab.co.uk/TIG-Team --token ***`
5. `sudo ./svc.sh install admin`
6. `sudo ./svc.sh start`
7. See that the Runner is authenticated and Idle in the GH Enterprise UI.
8. Run a job against the Runner.
9. See Job succeed or fail but no log output.
10. Check runner logs: `less _diag/Worker_20221025-212811-utc.log`

**Expected behavior**
The log output should be available in the UI. I should be able to click on each stage of the workflow and see the log output. There should be no InternalServerError when trying to POST logs. Success rate should be 2/2 when `Try to upload 2 log files or attachments, success rate: 0/2.`.

## Runner Version and Platform
I'm using actions-runner-linux-x64-2.289.3.

Ubuntu 22.04.

## Job Log Output
NA.

## Runner and Worker's Diagnostic Logs
```
[2022-10-25 21:28:17Z ERR  GitHubActionsService] POST request to https://github.grlab.co.uk/_services/pipelines/kS8cHJOCPXwsg1CYr1cagBaajHbUQl0sxc6fIBPrkc8vIRLjlI/00000000-0000-0000-0000-000000000000/_apis/distributedtask/hubs/Actions/plans/28c2d1c9-6d56-4d70-a8d9-31c7277ce09e/logs/2 failed. HTTP Status: InternalServerError
[2022-10-25 21:28:17Z INFO JobServerQueue] Catch exception during log or attachment file upload, keep going since the process is best effort.
[2022-10-25 21:28:17Z ERR  JobServerQueue] GitHub.Services.Common.VssServiceException: An Internal Error Occurred. Activity Id: c0fbdcfd-cc2a-4050-b894-fc99a5ef0fbf.
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Common.JobServerQueue.UploadFile(UploadFileInfo file)
   at GitHub.Runner.Common.JobServerQueue.ProcessFilesUploadQueueAsync(Boolean runOnce)
```

**Comment by Binternet** [comment]
+1 on this
Did you manage to solve this?

**Comment by tdudlak4918ab** [comment]
@karimtabet Could you please update if it is still happening for you?
