### ISSUE TITLE
Job goes from Queued to Failed without posting any logs to the web

### ISSUE THREAD

**Issue by andresperezl** [actions/runner#2270]
**Describe the bug**
I have a self-hosted runner, and it was working until I decided to move my private repo to an Organization, but then return it back to my personal user. The Runner was registering correctly as it was showing as Idle in the settings, but then Job is just not running. I can see in the logs that the Runner takes the job, but then nothing happens. The status goes from Queued to Failed after around 1min.

Also to note that I set `GITHUB_ACTIONS_RUNNER_TLS_NO_VERIFY=1` and `DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0` as the runner has issues communicating with Github itself (else it won't even start, but I had that even after moving the repo back and forth)

I also tried by removing and registering again the runner, and by completely removing all the files from my host, but with the same results.

**To Reproduce**
1. Create and register a self-hosted runner
2. Transfer to repository linked to the self-hosted runner to another account
3. Transfer it back to its original owner
4. Jobs are not running

**Expected behavior**
Jobs should run and execute

## Runner Version and Platform
Version of your runner? 2.299.1

OS of the machine running the runner? Linux

## What's not working?

Job goes from queue to failed without any output in the web

```
Nov 18 20:31:19 localhost.localdomain systemd[1]: Started GitHub Actions Runner (andresperezl-botstuff.carp.wtf).
Nov 18 20:31:19 localhost.localdomain runsvc.sh[290217]: .path=/usr/local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/var/lib/snapd/snap/bin
Nov 18 20:31:19 localhost.localdomain runsvc.sh[290220]: Starting Runner listener with startup type: service
Nov 18 20:31:19 localhost.localdomain runsvc.sh[290220]: Started listener process, pid: 290229
Nov 18 20:31:19 localhost.localdomain runsvc.sh[290220]: Started running service
Nov 18 20:31:21 localhost.localdomain runsvc.sh[290220]: √ Connected to GitHub
Nov 18 20:31:22 localhost.localdomain runsvc.sh[290220]: Current runner version: '2.299.1'
Nov 18 20:31:22 localhost.localdomain runsvc.sh[290220]: 2022-11-19 02:31:22Z: Listening for Jobs
Nov 18 20:32:04 localhost.localdomain runsvc.sh[290220]: 2022-11-19 02:32:04Z: Running job: release
Nov 18 20:32:42 localhost.localdomain runsvc.sh[290220]: 2022-11-19 02:32:42Z: Job release completed with result: Failed
```

## Job Log Output
None

## Runner and Worker's Diagnostic Logs
Worker log

```
[2022-11-19 03:02:14Z INFO JobServer] Websocket is not open, let's attempt to connect back again with random backoff 00:00:00.1160000 ms (total calls: 4, failed calls: 4).
[2022-11-19 03:02:14Z INFO JobServer] Creating websocket client ...wss://pipelines.actions.githubusercontent.com/bdnBLyuN21wzPoRhgvSZcljRfKhatprejlWM0FEkUCftvA1zDv/00000000-0000-0000-0000-000000000000/_apis/distributedtask/hubs/Actions/plans/d934b227-e67f-489f-b19e-1cdd92f21a4d/timelines/d934b227-e67f-489f-b19e-1cdd92f21a4d/records/8d802004-fbbb-5f17-b73e-f23de0c1dec8/feedstream?api-version=6.0-preview
[2022-11-19 03:02:14Z INFO JobServer] Attempting to start websocket client with delay 00:00:00.1160000.
[2022-11-19 03:02:14Z INFO AddMaskCommandExtension] Add new secret mask with length of 76
[2022-11-19 03:02:14Z INFO JobServerQueue] Try to append 1 batches web console lines for record '89c84761-4015-5c51-5570-e5c7698f410c', success rate: 1/1.
[2022-11-19 03:02:14Z INFO JobServerQueue] Try to upload 1 log files or attachments, success rate: 1/1.
[2022-11-19 03:02:14Z INFO JobServer] Exception caught during websocket client connect, fallback of HTTP would be used now instead of websocket.
[2022-11-19 03:02:14Z ERR  JobServer] System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: NotSignatureValid
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
....
[2022-11-19 03:02:52Z INFO StepsRunner] Step result: Failed
[2022-11-19 03:02:52Z INFO ExecutionContext] Publish step telemetry for current step {
  "action": "actions/checkout",
  "ref": "v3",
  "type": "node16",
  "stage": "Main",
  "stepId": "89c84761-4015-5c51-5570-e5c7698f410c",
  "stepContextName": "__actions_checkout",
  "hasPreStep": false,
  "hasPostStep": true,
  "result": "failed",
  "errorMessages": [
    "ambiguous argument 'HEAD': unknown revision or path not in the working tree.",
    "Unable to clean or reset the repository. The repository will be recreated instead.",
    "repository 'https://github.com/andresperezl/botstuff/' not found"
  ],
  "executionTimeInSeconds": 39,
  "startTime": "2022-11-19T03:02:14.5056492Z",
  "finishTime": "2022-11-19T03:02:52.6626205Z"
}.
```

**Comment by andresperezl** [comment]
Well, now it started posting logs to the web, and I see the error shown in the worker

```
"repository 'https://github.com/andresperezl/botstuff/' not found"
```

But the repository does exists, as it is from where the job is getting triggered.

Only thing particular about that repo is that is private, but again that was working before I moved it back and forth

**Comment by andresperezl** [comment]
I went into my Repo Setting -> Actions -> General -> Workflow Permissions

I switched to Read Permissions and saved, and then back to Read and Write Permissions and saved, and now my Job was able to clone the repo
