### ISSUE TITLE
Frequent intermittent failure `Error: The operation was canceled.` which stops Github Actions job

### ISSUE THREAD

**Issue by azriel91** [actions/runner#2323]
**Describe the bug**

There is a frequent intermittent failure `Error: The operation was canceled.`, which stops the Github Actions job.

Example failures:

* https://github.com/azriel91/peace/actions/runs/3717945530/jobs/6305883573
* https://github.com/azriel91/peace/actions/runs/3717677987/jobs/6305329488

**To Reproduce**

1. Push a branch to https://github.com/azriel91/peace
2. Look at the [CI](https://github.com/azriel91/peace/blob/646bbf35829702cf258e40e8cb69c4a1400b9489/.github/workflows/ci.yml) / [Docs and Spell Check](https://github.com/azriel91/peace/blob/646bbf35829702cf258e40e8cb69c4a1400b9489/.github/workflows/ci.yml#L42) job. 
3. 100% of the time the error occurs on the first run during the [`cargo doc` step](https://github.com/azriel91/peace/blob/646bbf35829702cf258e40e8cb69c4a1400b9489/.github/workflows/ci.yml#L61-L65). 50% chance of success on subsequent runs.

This has been happening for months, but I just kept re-running the job. I cannot find a solution through reading other [existing issues](https://github.com/actions/runner/issues?q=is%3Aissue+sort%3Aupdated-desc+Error%3A+The+operation+was+canceled.) and [this discussion](https://github.com/orgs/community/discussions/36292).

**Expected behavior**

The job succeeds 100% of the time.

## Runner Version and Platform

The public Github actions runner:

```
Current runner version: '2.299.1'
Operating System
  Ubuntu
  22.04.1
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20221212.1
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20221212.1/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20221212.1
Runner Image Provisioner
  2.0.91.1
```

## What's not working?

The `cargo doc` command fails while it compiles code while generating documentation.

## Job Log Output

```bash
::add-matcher::/home/runner/work/_actions/r3-os/actions-rust-cargo/fb222fe18dc90e381546d012f9e3d6f353f0f627/dist/.matchers/rust.json
##[debug]Added matchers: 'rust'. Problem matchers scan action output for known warning or error strings and report these inline.
/home/runner/.cargo/bin/cargo doc --no-deps
    Updating crates.io index
 Downloading crates ...
# .. omitted for clarity
# see <https://github.com/azriel91/peace/actions/runs/3717945530/jobs/6305883573>
   Compiling aho-corasick v0.7.20
    Checking downcast-rs v1.2.0
   Compiling resman v0.15.0
   Compiling erased-serde v0.3.23
    Checking fixedbitset v0.4.2
    Checking bytes v1.3.0
   Compiling regex-syntax v0.6.28
    Checking rt_ref v0.2.0
    Checking rt_map v0.5.2
##[debug]Re-evaluate condition on job cancellation for step: 'Run r3-os/actions-rust-cargo@fb222fe18dc90e381546d012f9e3d6f353f0f627'.
Error: The operation was canceled.
##[debug]System.OperationCanceledException: The operation was canceled.
##[debug]   at System.Threading.CancellationToken.ThrowOperationCanceledException()
##[debug]   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.DefaultStepHost.ExecuteAsync(IExecutionContext context, String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, String standardInInput, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.NodeScriptActionHandler.RunAsync(ActionRunStage stage)
##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[debug]Finishing: Run r3-os/actions-rust-cargo@fb222fe18dc90e381546d012f9e3d6f353f0f627
```

## Runner and Worker's Diagnostic Logs

If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by azriel91** [comment]
Turns out it's a timeout, this message was in the actions summary, at the bottom of the page:

> The job running on runner Hosted Agent has exceeded the maximum execution time of 3 minutes.

I guess an improvement would be to actually indicate why the job failed in the job's logs.
