### ISSUE TITLE
Workflow don't start on self hosted runner

### ISSUE THREAD

**Issue by starverdiyev** [actions/runner#2376]
**Describe the bug**
We are using self hosted runner. After push to master, workflow doesn't start running, and has got status in Queued. Problem reoccurs once a week.

**To Reproduce**
1. After merge PR to master, workflow must begin running. 
2. Workflow have got status Queued
3. Github action runner working as a service, with a command sudo ./svc.sh start

**Expected behavior**
Workflow must run, and go to status In Progress

## Runner Version and Platform
V2.300.2

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

## Job Log Output

```

[2023-01-17 08:11:58Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-01-17 08:11:58Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-01-17 08:13:38Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/LiPvOEqVDHnB8f0MfsWaL2lCKf1zmCckzivkJxEOWAnQAONO7A/_apis/connectionData?connectOptions=1&lastChangeId=116858881&lastChangeId64=116858881 timed out after 100 seconds.
[2023-01-17 08:13:38Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-01-17 08:13:38Z INFO JobServer] Catch exception during connect. 2 attempts left.
[2023-01-17 08:13:38Z ERR  JobServer] System.TimeoutException: The HTTP request timed out after 00:01:40.
```

**Comment by thiago-scherrer** [comment]
Same here:
Amazon linux:
```sh
hostnamectl
   Static hostname: ip-172-31-71-116.ec2.internal
         Icon name: computer-vm
           Chassis: vm
        Machine ID: ec2b61f81a781ec246ec8108b04ef88b
           Boot ID: 7a5c6d998bd84cf689d6c2c469c26bc5
    Virtualization: amazon
  Operating System: Amazon Linux 2
       CPE OS Name: cpe:2.3:o:amazon:amazon_linux:2
            Kernel: Linux 5.10.157-139.675.amzn2.x86_64
      Architecture: x86-64
```
Runner job:

![runner1](https://user-images.githubusercontent.com/46422437/212904869-19cf2775-55ff-44f2-8ec5-af23ad5a5761.png)

![runner2](https://user-images.githubusercontent.com/46422437/212904918-74e0f0bc-7bf4-47b1-aadf-9fbd1aaf2ecc.png)

**Comment by starverdiyev** [comment]
@thiago-scherrer please, can you also check the logs in _dig? Interesting, what happened on runner side

**Comment by thiago-scherrer** [comment]
> @thiago-scherrer please, can you also check the logs in _dig? Interesting, what happened on runner side

```sh
[2023-01-16 20:45:15Z INFO Runner] Received job message of length 25162 from service, with hash 'xxxxxx'
[2023-01-16 20:45:15Z INFO JobDispatcher] Job request 207829 for plan xxxxxx job xxxx received.
[2023-01-16 20:45:15Z INFO JobDispatcher] Pull OrchestrationId xxxxxx.send-helm-chart-to-xxxx-xxxx.__default from JWT claims
[2023-01-16 20:45:15Z ERR  JobDispatcher] Worker Dispatch failed with an exception for job request xxxx.
[2023-01-16 20:45:15Z ERR  JobDispatcher] System.IO.IOException: Input/output error
   at System.ConsolePal.Write(SafeFileHandle fd, ReadOnlySpan`1 buffer, Boolean mayChangeCursorPosition)
   at System.ConsolePal.UnixConsoleStream.Write(ReadOnlySpan`1 buffer)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at GitHub.Runner.Common.Terminal.WriteLine(String line, Nullable`1 colorCode, Boolean skipTracing)
   at GitHub.Runner.Listener.JobDispatcher.RunAsync(AgentJobRequestMessage message, String orchestrationId, WorkerDispatcher previousJobDispatch, CancellationToken jobRequestCancellationToken, CancellationToken workerCancelTimeoutKillToken)
   at GitHub.Runner.Listener.JobDispatcher.EnsureDispatchFinished(WorkerDispatcher jobDispatch, Boolean cancelRunningJob)
```

And this when we restart the runner =>

```sh
[2023-01-17 12:38:15Z ERR  JobDispatcher] Worker Dispatch failed with an exception for job request xxxx.
[2023-01-17 12:38:15Z ERR  JobDispatcher] System.IO.IOException: Input/output error
   at System.ConsolePal.Write(SafeFileHandle fd, ReadOnlySpan`1 buffer, Boolean mayChangeCursorPosition)
   at System.ConsolePal.UnixConsoleStream.Write(ReadOnlySpan`1 buffer)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at GitHub.Runner.Common.Terminal.WriteLine(String line, Nullable`1 colorCode, Boolean skipTracing)
   at GitHub.Runner.Listener.JobDispatcher.RunAsync(AgentJobRequestMessage message, String orchestrationId, WorkerDispatcher previousJobDispatch, CancellationToken jobRequestCancellationToken, CancellationToken workerCancelTimeoutKillToken)
   at GitHub.Runner.Listener.JobDispatcher.EnsureDispatchFinished(WorkerDispatcher jobDispatch, Boolean cancelRunningJob)
```

**Comment by fhammerl** [comment]
Hi @starverdiyev 👋 Thanks for putting this issue together.
The root cause of this timeout is likely on the server side and we're already investigating and tracking it internally.

@thiago-scherrer the original issue is about a timeouts, while yours seems to be caused by an IO error. Would you mind filing it in a different issue with the following context:

- Are you running as a service?
  - If yes, are the user who configured / installed the service the same as the one running it? (if not, that would explain your IO error)
  - If not, are you running the runner through an ssh session?
- Are you running any anti-virus?
- Do you have any other runners on this VM?

**Comment by thiago-scherrer** [comment]
Hi @fhammerl !


>Are you running as a service?
>If yes, are the user who configured / installed the service the same as the one running it? (if not, that would explain your IO >error)
>If not, are you running the runner through an ssh session?

No, this is a ec2 linux. Im running with `./run.sh &` after `./config.sh --url https://github.com/xxx`

> Are you running any anti-virus?

No

>Do you have any other runners on this VM?

No

**Comment by Pragyat-Gupta** [comment]
@thiago-scherrer @fhammerl Facing the same issue. Is there any RCA or resolution for this?

**Comment by thiago-scherrer** [comment]
> @thiago-scherrer @fhammerl Facing the same issue. Is there any RCA or resolution for this? Thanks in advance

@Pragyat-Gupta I solved it by running runner as a service + root  => https://docs.github.com/en/actions/hosting-your-own-runners/configuring-the-self-hosted-runner-application-as-a-service
