### ISSUE TITLE
Wrong  code pages encoding on windows powershell with self-hosted runner

### ISSUE THREAD

**Issue by RunningLeon** [actions/runner#2451]
**Describe the bug**
Hi, guys. We' are setting up a self-hosted runner on windows machine and use powershell as default shell. But due to the default code pages encoding configured by self-hosted runner is `utf-8`, while the system default decoding `gbk`, the decoding failed.

**To Reproduce**
1. Set up a self-hosted runner on windows 10 system and write a simple workflow with `powershell` as default shell python==3.8.0.
2. Add `chcp` on a workflow step and run it and the printed info is `Active code page: 65001`, which means the encoding is `utf-8`, not `cp936`.
3. A python code decoding gbk encoded str would fail on this case.

#### python decoding sample code

```
import locale
import os
import subprocess
from distutils.ccompiler import new_compiler
ccompiler = new_compiler()
ccompiler.initialize()
print(ccompiler.cc) # output 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.33.31629 版 版权所有(C) Microsoft Corporation。保留所有权利。
cc = subprocess.check_output(
    f'{ccompiler.cc}', stderr=subprocess.STDOUT, shell=True)
encoding = locale.getpreferredencoding() # here encoding is 'cp936'
msvc_info = cc.decode(encoding).partition('\n')[0].strip() # failed on this decoding line
```
**Expected behavior**

A config step of github self-hosted runner to set Active code page on powershell.

## Runner Version and Platform
Version of your runner?
2.301.1
OS of the machine running the runner? OSX/Windows/Linux/...
Windows
## What's not working?
Please include error messages and screenshots.
```
Traceback (most recent call last):
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\bin\HostX86\x64\cl.exe
  File "<string>", line 1, in <module>
  File "D:\Runners\r-1\_work\mmdeploy\mmdeploy\temp_py\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\Runners\r-1\_work\mmdeploy\mmdeploy\temp_py\lib\subprocess.py", line 491, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "D:\Runners\r-1\_work\mmdeploy\mmdeploy\temp_py\lib\subprocess.py", line 1011, in communicate
    stdout = self.stdout.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x84 in position 13: illegal multibyte sequence
```
## Job Log Output
log url : https://github.com/open-mmlab/mmdeploy/actions/runs/4192464118/jobs/7268156562

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by RunningLeon** [comment]
Could be fixed by this [anwser](https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window)
