### ISSUE TITLE
Unable to configure new self-hosted runner due to (incorrect) "time out of sync" error

### ISSUE THREAD

**Issue by mckidder** [actions/runner#2483]
**Describe the bug**
When adding a new self-hosted runner; you are able to authenticate/connect to Github but when adding the server you see an error 
`The local machine's clock may be out of sync with the server time by more than five minutes. Please sync your clock with your domain or internet time and try again.`

The issue presents even after verifying the system time is indeed correct, on both macOS Catalina and Windows 10. System/ntp reboots do not resolve the issue.

**Please note: As you see in the diagnostic log the Github HTTP request is 12 minutes ahead of the actual time (verified on different systems, via command line etc.). If you force set your local clock back 12 minutes you are able to work around this.**

**To Reproduce**
1. In the Actions section, add a `New self-hosted runner`
2. Follow the prompts for your OS (verified personally on macOS 10.15 and Win10) in the Download section
3. Run the `./config.cmd --url URL_XX --token TOKEN_XX` configuration command

**Expected behavior**
Your are able to configure and successfully add the runner.

## Runner Version and Platform
win-x64/2.303.0 on Windows 10

Also tested with older versions on the following (same issue):
win-x64/2.293.2 on Windows 10
osx-x64/2.293.2 on macOS 10.15.7

OS of the machine running the runner? OSX/Windows/Linux/...
Attempted on both OSX and Windows

## What's not working?

```
--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication


√ Connected to GitHub

# Runner Registration

Enter the name of the runner group to add this runner to: [press Enter for Default]

Enter the name of runner: [press Enter for Default]

This runner will have the following labels: 'self-hosted', 'Windows', 'X64'
Enter any additional labels (ex. label-1,label-2): [press Enter to skip]

√ Runner successfully added
The local machine's clock may be out of sync with the server time by more than five minutes. Please sync your clock with your domain or internet time and try again.
```

## Job Log Output
Job cannot run due to runner unable to being added

## Runner and Worker's Diagnostic Logs
```
[2023-03-10 16:46:37Z INFO HostContext] No proxy settings were found based on environmental variables (http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY)
[2023-03-10 16:46:37Z INFO HostContext] Well known directory 'Bin': 'C:\actions-runner\bin'
[2023-03-10 16:46:37Z INFO HostContext] Well known directory 'Root': 'C:\actions-runner'
[2023-03-10 16:46:37Z INFO HostContext] Well known config file 'Credentials': 'C:\actions-runner\.credentials'
[2023-03-10 16:46:37Z INFO HostContext] Well known directory 'Bin': 'C:\actions-runner\bin'
[2023-03-10 16:46:37Z INFO HostContext] Well known directory 'Root': 'C:\actions-runner'
[2023-03-10 16:46:37Z INFO HostContext] Well known config file 'Runner': 'C:\actions-runner\.runner'
[2023-03-10 16:46:37Z INFO Listener] Runner is built for Windows (X64) - win-x64.
[2023-03-10 16:46:37Z INFO Listener] RuntimeInformation: Microsoft Windows 10.0.19045.
[2023-03-10 16:46:37Z INFO Listener] Version: 2.303.0
[2023-03-10 16:46:37Z INFO Listener] Commit: e676c7871817c1b484299cd93fabdf4b95e70741
[2023-03-10 16:46:37Z INFO Listener] Culture: en-US
[2023-03-10 16:46:37Z INFO Listener] UI Culture: en-US
[2023-03-10 16:46:37Z INFO HostContext] Well known directory 'Bin': 'C:\actions-runner\bin'
[2023-03-10 16:46:37Z INFO HostContext] Well known directory 'Root': 'C:\actions-runner'
[2023-03-10 16:46:37Z INFO Listener] Validating directory permissions for: 'C:\actions-runner'
[2023-03-10 16:46:37Z INFO CommandLineParser] Parse
[2023-03-10 16:46:37Z INFO CommandLineParser] Parsing 5 args
[2023-03-10 16:46:37Z INFO CommandLineParser] parsing argument
[2023-03-10 16:46:37Z INFO CommandLineParser] HasArgs: False
[2023-03-10 16:46:37Z INFO CommandLineParser] Adding Command: configure
[2023-03-10 16:46:37Z INFO CommandLineParser] parsing argument
[2023-03-10 16:46:37Z INFO CommandLineParser] HasArgs: True
[2023-03-10 16:46:37Z INFO CommandLineParser] arg: url
[2023-03-10 16:46:37Z INFO CommandLineParser] parsing argument
[2023-03-10 16:46:37Z INFO CommandLineParser] HasArgs: True
[2023-03-10 16:46:37Z INFO CommandLineParser] Adding option 'url': 'https://github.whirlpool.com/REDACTED'
[2023-03-10 16:46:37Z INFO CommandLineParser] parsing argument
[2023-03-10 16:46:37Z INFO CommandLineParser] HasArgs: True
[2023-03-10 16:46:37Z INFO CommandLineParser] arg: token
[2023-03-10 16:46:37Z INFO CommandLineParser] parsing argument
[2023-03-10 16:46:37Z INFO CommandLineParser] HasArgs: True
[2023-03-10 16:46:37Z INFO CommandLineParser] Adding option 'token': '***'
[2023-03-10 16:46:37Z INFO Listener] Arguments parsed
[2023-03-10 16:46:37Z INFO Runner] ExecuteCommand
[2023-03-10 16:46:37Z INFO ConfigurationStore] currentAssemblyLocation: C:\actions-runner\bin\Runner.Listener.dll
[2023-03-10 16:46:37Z INFO HostContext] Well known directory 'Bin': 'C:\actions-runner\bin'
[2023-03-10 16:46:37Z INFO ConfigurationStore] binPath: C:\actions-runner\bin
[2023-03-10 16:46:37Z INFO HostContext] Well known directory 'Bin': 'C:\actions-runner\bin'
[2023-03-10 16:46:37Z INFO HostContext] Well known directory 'Root': 'C:\actions-runner'
[2023-03-10 16:46:37Z INFO ConfigurationStore] RootFolder: C:\actions-runner
[2023-03-10 16:46:37Z INFO HostContext] Well known directory 'Bin': 'C:\actions-runner\bin'
[2023-03-10 16:46:37Z INFO HostContext] Well known directory 'Root': 'C:\actions-runner'
[2023-03-10 16:46:37Z INFO HostContext] Well known config file 'Runner': 'C:\actions-runner\.runner'
[2023-03-10 16:46:37Z INFO ConfigurationStore] ConfigFilePath: C:\actions-runner\.runner
[2023-03-10 16:46:37Z INFO HostContext] Well known directory 'Bin': 'C:\actions-runner\bin'
[2023-03-10 16:46:37Z INFO HostContext] Well known directory 'Root': 'C:\actions-runner'
[2023-03-10 16:46:37Z INFO HostContext] Well known config file 'Credentials': 'C:\actions-runner\.credentials'
[2023-03-10 16:46:37Z INFO ConfigurationStore] CredFilePath: C:\actions-runner\.credentials
[2023-03-10 16:46:37Z INFO HostContext] Well known directory 'Bin': 'C:\actions-runner\bin'
[2023-03-10 16:46:37Z INFO HostContext] Well known directory 'Root': 'C:\actions-runner'
[2023-03-10 16:46:37Z INFO HostContext] Well known config file 'MigratedCredentials': 'C:\actions-runner\.credentials_migrated'
[2023-03-10 16:46:37Z INFO ConfigurationStore] MigratedCredFilePath: C:\actions-runner\.credentials_migrated
[2023-03-10 16:46:37Z INFO HostContext] Well known directory 'Bin': 'C:\actions-runner\bin'
[2023-03-10 16:46:37Z INFO HostContext] Well known directory 'Root': 'C:\actions-runner'
[2023-03-10 16:46:37Z INFO HostContext] Well known config file 'Service': 'C:\actions-runner\.service'
[2023-03-10 16:46:37Z INFO ConfigurationStore] ServiceConfigFilePath: C:\actions-runner\.service
[2023-03-10 16:46:37Z INFO CommandSettings] Flag 'help': 'False'
[2023-03-10 16:46:37Z INFO CommandSettings] Flag 'version': 'False'
[2023-03-10 16:46:37Z INFO CommandSettings] Flag 'commit': 'False'
[2023-03-10 16:46:37Z INFO CommandSettings] Flag 'check': 'False'
[2023-03-10 16:46:37Z INFO CommandSettings] Command 'configure': 'True'
[2023-03-10 16:46:37Z INFO Terminal] WRITE LINE: 
[2023-03-10 16:46:37Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2023-03-10 16:46:37Z INFO Terminal] WRITE LINE: |        ____ _ _   _   _       _          _        _   _                      |
[2023-03-10 16:46:37Z INFO Terminal] WRITE LINE: |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
[2023-03-10 16:46:37Z INFO Terminal] WRITE LINE: |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
[2023-03-10 16:46:37Z INFO Terminal] WRITE LINE: |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
[2023-03-10 16:46:37Z INFO Terminal] WRITE LINE: |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
[2023-03-10 16:46:37Z INFO Terminal] WRITE LINE: |                                                                              |
[2023-03-10 16:46:37Z INFO Terminal] WRITE: |                       
[2023-03-10 16:46:37Z INFO Terminal] WRITE: Self-hosted runner registration
[2023-03-10 16:46:37Z INFO Terminal] WRITE LINE:                         |
[2023-03-10 16:46:37Z INFO Terminal] WRITE LINE: |                                                                              |
[2023-03-10 16:46:37Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2023-03-10 16:46:37Z INFO ConfigurationManager] ConfigureAsync
[2023-03-10 16:46:37Z INFO CommandSettings] Flag 'generateServiceConfig': 'False'
[2023-03-10 16:46:37Z INFO ConfigurationStore] IsConfigured()
[2023-03-10 16:46:37Z INFO ConfigurationStore] IsConfigured: False
[2023-03-10 16:46:37Z INFO ConfigurationManager] Is configured: False
[2023-03-10 16:46:37Z INFO CommandSettings] Arg 'url': 'https://github.whirlpool.com/REDACTED'
[2023-03-10 16:46:37Z INFO CommandSettings] Remove url from Arg dictionary.
[2023-03-10 16:46:37Z INFO CommandSettings] Arg 'token': '***'
[2023-03-10 16:46:37Z INFO CommandSettings] Remove token from Arg dictionary.
[2023-03-10 16:46:38Z INFO ConfigurationManager] Http response code: OK from 'POST https://github.whirlpool.com/api/v3/actions/runner-registration' (REDACTED)
[2023-03-10 16:46:38Z INFO ConfigurationManager] cred retrieved via GitHub auth
[2023-03-10 16:46:38Z INFO RunnerServer] EstablishVssConnection
[2023-03-10 16:46:38Z INFO RunnerServer] Establish connection with 100 seconds timeout.
[2023-03-10 16:46:38Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-03-10 16:46:38Z INFO RunnerServer] EstablishVssConnection
[2023-03-10 16:46:38Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2023-03-10 16:46:38Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-03-10 16:46:38Z INFO RunnerServer] EstablishVssConnection
[2023-03-10 16:46:38Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2023-03-10 16:46:38Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-03-10 16:46:38Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-03-10 16:46:38Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-03-10 16:46:38Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-03-10 16:46:38Z INFO Terminal] WRITE LINE: 
[2023-03-10 16:46:38Z INFO ConfigurationManager] Test Connection complete.
[2023-03-10 16:46:38Z INFO HostContext] Well known directory 'Bin': 'C:\actions-runner\bin'
[2023-03-10 16:46:38Z INFO HostContext] Well known directory 'Root': 'C:\actions-runner'
[2023-03-10 16:46:38Z INFO HostContext] Well known config file 'RSACredentials': 'C:\actions-runner\.credentials_rsaparams'
[2023-03-10 16:46:38Z INFO RSAEncryptedFileKeyManager] Found existing RSA key parameters file C:\actions-runner\.credentials_rsaparams
[2023-03-10 16:46:38Z INFO CommandSettings] Arg 'runnergroup': ''
[2023-03-10 16:46:38Z INFO CommandSettings] Flag 'unattended': 'False'
[2023-03-10 16:46:38Z INFO PromptManager] ReadValue
[2023-03-10 16:46:38Z INFO Terminal] WRITE: Enter the name of the runner group to add this runner to: 
[2023-03-10 16:46:38Z INFO Terminal] WRITE: [press Enter for Default] 
[2023-03-10 16:46:38Z INFO Terminal] READ LINE
[2023-03-10 16:46:39Z INFO Terminal] Read value: ''
[2023-03-10 16:46:39Z INFO PromptManager] Falling back to the default: 'Default'
[2023-03-10 16:46:39Z INFO Terminal] WRITE LINE: 
[2023-03-10 16:46:39Z INFO ConfigurationManager] Found a self-hosted runner group with id 1 and name Default
[2023-03-10 16:46:39Z INFO CommandSettings] Flag 'disableupdate': 'False'
[2023-03-10 16:46:39Z INFO CommandSettings] Flag 'ephemeral': 'False'
[2023-03-10 16:46:39Z INFO CommandSettings] Arg 'name': ''
[2023-03-10 16:46:39Z INFO CommandSettings] Flag 'unattended': 'False'
[2023-03-10 16:46:39Z INFO PromptManager] ReadValue
[2023-03-10 16:46:39Z INFO Terminal] WRITE: Enter the name of runner: 
[2023-03-10 16:46:39Z INFO Terminal] WRITE: [press Enter for Default] 
[2023-03-10 16:46:39Z INFO Terminal] READ LINE
[2023-03-10 16:46:41Z INFO Terminal] Read value: ''
[2023-03-10 16:46:41Z INFO PromptManager] Falling back to the default: 'Default'
[2023-03-10 16:46:41Z INFO Terminal] WRITE LINE: 
[2023-03-10 16:46:41Z INFO CommandSettings] Arg 'labels': ''
[2023-03-10 16:46:41Z INFO CommandSettings] Flag 'unattended': 'False'
[2023-03-10 16:46:41Z INFO PromptManager] ReadValue
[2023-03-10 16:46:41Z INFO Terminal] WRITE: This runner will have the following labels: 'self-hosted', 'Windows', 'X64' 
Enter any additional labels (ex. label-1,label-2): 
[2023-03-10 16:46:41Z INFO Terminal] WRITE: [press Enter to skip] 
[2023-03-10 16:46:41Z INFO Terminal] READ LINE
[2023-03-10 16:46:42Z INFO Terminal] Read value: ''
[2023-03-10 16:46:42Z INFO Terminal] WRITE LINE: 
[2023-03-10 16:46:42Z INFO CommandSettings] Flag 'disableupdate': 'False'
[2023-03-10 16:46:42Z INFO CommandSettings] Flag 'disableupdate': 'False'
[2023-03-10 16:46:42Z INFO CommandSettings] Flag 'ephemeral': 'False'
[2023-03-10 16:46:42Z INFO ConfigurationStore] Saving OAuth credential @ C:\actions-runner\.credentials
[2023-03-10 16:46:42Z INFO ConfigurationStore] Delete exist runner credential file.
[2023-03-10 16:46:42Z INFO ConfigurationStore] Credentials Saved.
[2023-03-10 16:46:42Z INFO ConfigurationStore] HasCredentials()
[2023-03-10 16:46:42Z INFO ConfigurationStore] stored True
[2023-03-10 16:46:42Z INFO CredentialManager] GetCredentialProvider
[2023-03-10 16:46:42Z INFO CredentialManager] Creating type OAuth
[2023-03-10 16:46:42Z INFO CredentialManager] Creating credential type: OAuth
[2023-03-10 16:46:42Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\actions-runner\.credentials_rsaparams
[2023-03-10 16:46:42Z INFO RunnerServer] EstablishVssConnection
[2023-03-10 16:46:42Z INFO RunnerServer] Establish connection with 100 seconds timeout.
[2023-03-10 16:46:42Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-03-10 16:46:42Z INFO RunnerServer] EstablishVssConnection
[2023-03-10 16:46:42Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2023-03-10 16:46:42Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-03-10 16:46:42Z INFO RunnerServer] EstablishVssConnection
[2023-03-10 16:46:42Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2023-03-10 16:46:42Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-03-10 16:46:42Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-03-10 16:46:42Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-03-10 16:46:42Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-03-10 16:46:42Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\actions-runner\.credentials_rsaparams
[2023-03-10 16:46:42Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\actions-runner\.credentials_rsaparams
[2023-03-10 16:46:42Z ERR  GitHubActionsService] POST request to https://github.whirlpool.com/_services/vstoken/_apis/oauth2/token/f4570f82-a69b-415b-8427-526d37694409 failed. HTTP Status: BadRequest
[2023-03-10 16:46:42Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
[2023-03-10 16:46:42Z ERR  ConfigurationManager] Catch exception during test agent connection.
[2023-03-10 16:46:42Z ERR  ConfigurationManager] GitHub.Services.OAuth.VssOAuthTokenRequestException: The token is not valid until 03/10/2023 16:46:43. Current server time is 03/10/2023 16:35:04.
   at GitHub.Services.OAuth.VssOAuthTokenProvider.OnGetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
   at GitHub.Services.Common.IssuedTokenProvider.GetTokenOperation.GetTokenAsync(VssTraceActivity traceActivity)
   at GitHub.Services.Common.IssuedTokenProvider.GetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
[2023-03-10 16:46:42Z ERR  Runner] System.Exception: The local machine's clock may be out of sync with the server time by more than five minutes. Please sync your clock with your domain or internet time and try again.
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at GitHub.Runner.Listener.Runner.ExecuteCommand(CommandSettings command)
[2023-03-10 16:46:42Z ERR  Terminal] WRITE ERROR: The local machine's clock may be out of sync with the server time by more than five minutes. Please sync your clock with your domain or internet time and try again.
[2023-03-10 16:46:42Z INFO Listener] Runner execution has finished with return code 1
```

**Comment by mckidder** [comment]
Issue apperas to be resolved server-side. Closing as fixed.
