### ISSUE TITLE
Sporadic donwload issues for the Step actions ClientWebSocket

### ISSUE THREAD

**Issue by krotofil** [actions/runner#2571]
**Describe the bug**
with every second run we get the error that the download section cannot be downloaded. 
As soon as the Github Client is restarted, it works for a few runs

**To Reproduce**
by downloading following step:
Download action repository 'tj-actions/changed-files@v35.8.0' (SHA:7ecfc6730dff8072d1cc5215a24cc9478f55264d)

## Runner Version and Platform
Current runner version: '2.289.3'

OS of the machine running the runner? OSX/Windows/Linux/...
Linux Ubuntu & Windows 10 Pro both machines

## What's not working?
Please include error messages and screenshots.
![grafik](https://user-images.githubusercontent.com/79268370/235109758-519af8a8-98c4-45bc-ae39-46433038cd78.png)

## Runner and Worker's Diagnostic Logs
[2023-04-26 15:48:08Z INFO HostContext] Well known directory 'Work': '/home/road/actions-runner/_work'
[2023-04-26 15:48:08Z INFO HostContext] Well known directory 'Actions': '/home/road/actions-runner/_work/_actions'
[2023-04-26 15:48:08Z INFO ActionManager] Save archive 'https://api.github.com/repos/tj-actions/changed-files/tarball/7ecfc6730dff8072d1cc5215a24cc9478f55264d' into /home/road/actions-runner/_work/_actions/_temp_0bb98adc-3952-4379-a673-ac201050eab4/8eb6736c-4348-4b3c-ac47-a4eb91895765.tar.gz.
[2023-04-26 15:48:09Z INFO JobServer] Caught exception during append web console line to websocket, let's fallback to sending via non-websocket call (total calls: 3, failed calls: 3, websocket state: Closed).
[2023-04-26 15:48:09Z ERR  JobServer] System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.WebSockets.ClientWebSocket'.
   at System.Net.WebSockets.ClientWebSocket.get_ConnectedWebSocket()
   at GitHub.Runner.Common.JobServer.AppendTimelineRecordFeedAsync(Guid scopeIdentifier, String hubName, Guid planId, Guid timelineId, Guid timelineRecordId, Guid stepId, IList`1 lines, Nullable`1 startLine, CancellationToken cancellationToken)
[2023-04-26 15:48:09Z INFO JobServer] Websocket is not open, let's attempt to connect back again with random backoff 00:00:00.2920000 ms (total calls: 3, failed calls: 3).

[2023-04-26 15:49:49Z INFO JobServer] Creating websocket client ...wss://git.i.mercedes-benz.com/_services/pipelines/LY80vMuKiImVcfoipIgFUa99CrRjh9DcNAYB1I9UG
L6Pegvltr/00000000-0000-0000-0000-000000000000/_apis/distributedtask/hubs/Actions/plans/75dc2a8e-4b37-4d60-8cd1-aa595e953e7e/timelines/75dc2a8e-4b37-4d60-8cd1
-aa595e953e7e/records/ff44a1f3-1644-57ab-e2a7-0e81e3613029/feedstream?api-version=6.0-preview
[2023-04-26 15:49:49Z INFO JobServer] Attempting to start websocket client with delay 00:00:00.2510000.
[2023-04-26 15:49:49Z INFO JobServerQueue] Try to append 1 batches web console lines for record '8c33bd2d-db94-44f5-8c08-a1d2888304d2', success rate: 1/1.
[2023-04-26 15:49:49Z INFO JobServer] Exception caught during websocket client connect, fallback of HTTP would be used now instead of websocket.
[2023-04-26 15:49:49Z ERR  JobServer] System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '400' when status code '101' was
expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at GitHub.Runner.Common.JobServer.ConnectWebSocketClient(String feedStreamUrl, TimeSpan delay)
[2023-04-26 15:51:43Z ERR  ActionManager] Fail to download archive 'https://api.github.com/repos/tj-actions/changed-files/tarball/7ecfc6730dff8072d1cc5215a24c
c9478f55264d' -- Attempt: 2
[2023-04-26 15:51:43Z ERR  ActionManager] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 1
00 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.

[2023-04-27 07:45:28Z ERR  GitHubActionsService] POST request to https://git.i.mercedes-benz.com/_services/pipelines/LY80vMuKiImVcfoipIgFUa99CrRjh9DcNAYB1I9UGL6Pegvltr/00000000-0000-0000-0000-000000000000/_apis/distributedtask/hubs/Actions/plans/9c62ab19-b4ba-45e0-b6de-7e1743e1ccb1/logs/20 failed. HTTP Status: InternalServerError
[2023-04-27 07:45:28Z INFO JobServerQueue] Catch exception during log or attachment file upload, keep going since the process is best effort.
[2023-04-27 07:45:28Z ERR  JobServerQueue] GitHub.Services.WebApi.VssServiceResponseException: An Internal Error Occurred. Activity Id: 9db1ad85-2d19-49eb-8913-db8fa864c862.
 ---> System.IO.IOException: An Internal Error Occurred. Activity Id: 9db1ad85-2d19-49eb-8913-db8fa864c862.
   --- End of inner exception stack trace ---
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Common.JobServerQueue.UploadFile(UploadFileInfo file)

**Comment by F-WRunTime** [comment]
Was there any solution to this we're seeing this quite a bit today.
