### ISSUE TITLE
Github actions not updating

### ISSUE THREAD

**Issue by imgfrost** [actions/runner#2572]
The github action application is not updating as it was about 16 hours ago.

This started last night, Runners were using 2.293.0, which previously successfully updated to 2.303.0, however, this suddenly stopped running and we saw 'Peer reset connection' errors in our runner logs.

We then manually updated the image to 2.302.0 (left it a few versions behind to potentially view update errors) and while we are not seeing any errors yet, this still isn't updating.

**To Reproduce**
1. Raise PR / Merge to main
2. newer syntax of Github actions fail due to old version

**Expected behavior**
Runner sees that it is running an old version and autoupdates.

Autoupdates is confirmed to be enabled.

## Runner Version and Platform
3.302.0 - x64

OS of the machine running the runner? OSX/Windows/Linux/...
Linux

## What's not working?
Autoupdates are not successfully updating Runner version.

![image](https://user-images.githubusercontent.com/85688422/235131305-50c8fa7a-bfa4-4dcb-b024-190722d34705.png)

## Runner and Worker's Diagnostic Logs

-- This error may / may not be related.- these are from 2.293.0 - we are not seeing this errors in new version.--

[2023-04-28 08:39:15Z ERR  JobServer] #####################################################
[2023-04-28 08:39:15Z ERR  JobServer] System.Net.Sockets.SocketException (104): Connection reset by peer
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.WriteSingleChunk[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Security.SslStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.WriteToStreamAsync(ReadOnlyMemory`1 source, Boolean async)
   at System.Net.Http.HttpConnection.RawConnectionStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer, Task lockTask, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer, Task lockTask, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, WebSocketMessageFlags messageFlags, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
   at GitHub.Runner.Common.JobServer.AppendTimelineRecordFeedAsync(Guid scopeIdentifier, String hubName, Guid planId, Guid timelineId, Guid timelineRecordId, Guid stepId, IList`1 lines, Nullable`1 startLine, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at GitHub.Runner.Common.JobServer.AppendTimelineRecordFeedAsync(Guid scopeIdentifier, String hubName, Guid planId, Guid timelineId, Guid timelineRecordId, Guid stepId, IList`1 lines, Nullable`1 startLine, CancellationToken cancellationToken)
   at GitHub.Runner.Common.JobServerQueue.ProcessWebConsoleLinesQueueAsync(Boolean runOnce)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.DelayPromise.CompleteTimedOut()
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.UnmanagedThreadPoolWorkItem.ExecuteUnmanagedThreadPoolWorkItem(IntPtr callback, IntPtr state)
   at System.Threading.UnmanagedThreadPoolWorkItem.ExecuteUnmanagedThreadPoolWorkItem(IntPtr callback, IntPtr state)
   at System.Threading.UnmanagedThreadPoolWorkItem.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
--- End of stack trace from previous location ---

[2023-04-28 08:39:15Z INFO JobServer] Websocket is not open, let's attempt to connect back again with random backoff 00:00:00.3820000 ms (total calls: 22, failed calls: 1).
[2023-04-28 08:39:15Z INFO JobServer] Creating websocket client ...wss://pipelines.actions.githubusercontent.com/dZhU5NhB4yqTeYAyIQrYaBEUK0a5ngA10LkEgxQR99SN4nOVmf/00000000-0000-0000-0000-000000000000/_apis/distributedtask/hubs/Actions/plans/bcbe21b3-d4f9-467f-aa54-48720283652b/ti
melines/bcbe21b3-d4f9-467f-aa54-48720283652b/records/80ed3a07-afd1-5a19-6386-267d64db85f1/feedstream?api-version=6.0-preview
[2023-04-28 08:39:15Z INFO JobServer] Attempting to start websocket client with delay 00:00:00.3820000.
[2023-04-28 08:39:15Z INFO JobServerQueue] Try to append 1 batches web console lines for record 'ef5854cf-bdd4-5d6c-d949-99d35fd812df', success rate: 1/1.
[2023-04-28 08:39:16Z INFO JobServer] Successfully started websocket client.
[2023-04-28 08:39:16Z INFO JobServerQueue] Try to append 1 batches web console lines for record 'ef5854cf-bdd4-5d6c-d949-99d35fd812df', success rate: 1/1..

**Comment by BenChiverton-Cal** [comment]
The same issue is happening when we upgrade from `2.296.2` -> `2.304.0`.
`2.296.2` -> `2.303.0` was working fine.

**Comment by BenChiverton-Cal** [comment]
This is now working again for us.

**Comment by Hdom** [comment]
Hey @BenChiverton-Cal did you have to take any steps to resolve this? We are encountering the same issue.

**Comment by BenChiverton-Cal** [comment]
@Hdom sorry my comment was unhelpful, I've updated it now.

**Comment by Hdom** [comment]
We run the same image on multiple instances of github so we cant update manually and with the auto update broken its causing issues with workflow compatibility. Hopefully we heard back from github soon.

**Comment by Hdom** [comment]
Our self hosted runners started to successfully update to 2.304.0 again, no changes made.
