### ISSUE TITLE
GitHub.DistributedTask.WebApi.AccessDeniedException on picking up delayed job

### ISSUE THREAD

**Issue by imishchuk-carbon** [actions/runner#2590]
Hey, team.

**Describe the bug**
We have a job with matrix strategy and a `max-parallel` setting configured with total of 44 jobs expected to run

```
service-test-32:
    name: ct - ${{ matrix.runner }}
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        runner:
          - z1d_xlarge-alpha
          - m6i_2xlarge-alpha
          - m6id_2xlarge-alpha
          - m6a_2xlarge-alpha
          - m5_2xlarge-alpha
          - m5d_2xlarge-alpha
          - m5zn_2xlarge-alpha
          - m5a_2xlarge-alpha
          - m6g_2xlarge-alpha
          - m7g_2xlarge-alpha
          - c6g_4xlarge-alpha
        shard: [0, 1, 2, 3]
    runs-on: ${{ matrix.runner }}
```

First (or two first) batches are executed as expected, i.e. jobs are queued, EC2 instances is spun up, job is picked up and processed.
But next jobs are not picked up - they are stuck in `queued` (I guess next batch of jobs according to `max-parallel`) or `starting` state.
I see that instance for this job has been spun up, but in runner logs there is an error

```
[2023-05-08 08:12:54Z ERR  GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/khYlr4bVg6ylZ6hVkATgX8hlVnaYEnY0AN0Y5ZlBB2OU80U9hE/_apis/distributedtask/pools/1/messages?sessionId=44927790-762b-4758-b6ce-a875d86f3c61&status=Online&runnerVersion=2.304.0 failed. HTTP Status: Forbidden, AFD Ref: Ref A: A361EA0D73CC4AB385EAFFC478B2B886 Ref B: BL2AA2030109053 Ref C: 2023-05-08T08:12:54Z
--
[2023-05-08 08:12:54Z ERR  MessageListener] Catch exception during get next message.
[2023-05-08 08:12:54Z ERR  MessageListener] GitHub.DistributedTask.WebApi.AccessDeniedException: Access denied. System:ServiceIdentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD needs View permissions to perform the action.
  at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
  at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
  at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
  at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
  at GitHub.Runner.Listener.MessageListener.GetNextMessageAsync(CancellationToken token)
```

Full log in attachment. [runner_log.csv](https://github.com/actions/runner/files/11420878/runner_log.csv)

Observations so far - looks like this affects jobs that have been delayed due to `max-parallel` after some time has passed. I was able to find [this](https://github.com/actions/runner/issues/1545) issue but it has been resolved.

**To Reproduce**
1. Have self-hosted github runners (we are using Amazon EC2, based on [philips-labs](https://github.com/philips-labs/terraform-aws-github-runner) terraform module)
2. Create a job with matrix strategy and `max-parallel` setting to delay execution of jobs into several phases
3. Create a job that will run for 10-15 minutes (I guess any dummy shell script will do)
4. Execute workflow

**Expected behavior**
Delayed jobs are picked up and processed as expected

## Runner Version and Platform
`2.304.0`

Ubuntu amd64

## What's not working?
Self hosted github runner is unable to pickup jobs that have been delayed for some time.

I can run additional test to zero in on time when this flow starts to break, if needed.

Thank you.

**Comment by rodrigo-oliveira-silva** [comment]
I am the same problem, but in a different scenario #[3419](https://github.com/philips-labs/terraform-aws-github-runner/issues/3419).

anyone with any solution?
