### ISSUE TITLE
Config.sh getting stuck at the last steps

### ISSUE THREAD

**Issue by GabrielBigardi** [actions/runner#2840]
**Describe the bug**
Whenever i'm trying to setup a self-hosted runner on my own machine, it goes through every step but after it says "√ Runner successfully added" it gets stucked and i get the following message after a minute: "The HTTP request timed out after 00:01:40.".
When looking through the log file, i have the following message:
```
[2023-09-08 21:19:50Z WARN GitHubActionsService] GET request to https://pipelinesghubeus9.actions.githubusercontent.com/62ScAd50ROPlszVlJRnqvsHeGMXN3XZfiyyHwyXvp2ULUR3GJf/_apis/distributedtask/pools?poolType=Automation timed out after 100 seconds.
```
Weird thing is that i can access this link properly, doesn't looks like a firewall/internet problem.
When i access the link directly i get the following JSON:
```
{"$id":"1","innerException":null,"message":"The user 'System:PublicAccess;aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
```

**Expected behavior**
I expect the config.sh file to run and setup my self-hosted runner properly.

## Runner Version and Platform
Linux x64 2.308.0

Running on Ubuntu 22.04

## What's not working?
The config.sh file is freezing at the last step.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
[2023-09-08 21:17:58Z INFO HostContext] No proxy settings were found based on environmental variables (http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY)
[2023-09-08 21:17:58Z INFO HostContext] Well known directory 'Bin': '/home/gabriel/actions-runner/bin'
[2023-09-08 21:17:58Z INFO HostContext] Well known directory 'Root': '/home/gabriel/actions-runner'
[2023-09-08 21:17:58Z INFO HostContext] Well known config file 'Credentials': '/home/gabriel/actions-runner/.credentials'
[2023-09-08 21:17:58Z INFO HostContext] Well known directory 'Bin': '/home/gabriel/actions-runner/bin'
[2023-09-08 21:17:58Z INFO HostContext] Well known directory 'Root': '/home/gabriel/actions-runner'
[2023-09-08 21:17:58Z INFO HostContext] Well known config file 'Runner': '/home/gabriel/actions-runner/.runner'
[2023-09-08 21:17:58Z INFO Listener] Runner is built for Linux (X64) - linux-x64.
[2023-09-08 21:17:58Z INFO Listener] RuntimeInformation: Linux 6.2.0-32-generic #32~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 18 10:40:13 UTC 2.
[2023-09-08 21:17:58Z INFO Listener] Version: 2.308.0
[2023-09-08 21:17:58Z INFO Listener] Commit: 7f7ff150c6d2ee316c523be6325188853dfae45d
[2023-09-08 21:17:58Z INFO Listener] Culture: pt-BR
[2023-09-08 21:17:58Z INFO Listener] UI Culture: pt-BR
[2023-09-08 21:17:58Z INFO HostContext] Well known directory 'Bin': '/home/gabriel/actions-runner/bin'
[2023-09-08 21:17:58Z INFO HostContext] Well known directory 'Root': '/home/gabriel/actions-runner'
[2023-09-08 21:17:58Z INFO Listener] Validating directory permissions for: '/home/gabriel/actions-runner'
[2023-09-08 21:17:58Z INFO CommandLineParser] Parse
[2023-09-08 21:17:58Z INFO CommandLineParser] Parsing 5 args
[2023-09-08 21:17:58Z INFO CommandLineParser] parsing argument
[2023-09-08 21:17:58Z INFO CommandLineParser] HasArgs: False
[2023-09-08 21:17:58Z INFO CommandLineParser] Adding Command: configure
[2023-09-08 21:17:58Z INFO CommandLineParser] parsing argument
[2023-09-08 21:17:58Z INFO CommandLineParser] HasArgs: True
[2023-09-08 21:17:58Z INFO CommandLineParser] arg: url
[2023-09-08 21:17:58Z INFO CommandLineParser] parsing argument
[2023-09-08 21:17:58Z INFO CommandLineParser] HasArgs: True
[2023-09-08 21:17:58Z INFO CommandLineParser] Adding option 'url': 'https://github.com/GabrielBigardi/Humble-Objects'
[2023-09-08 21:17:58Z INFO CommandLineParser] parsing argument
[2023-09-08 21:17:58Z INFO CommandLineParser] HasArgs: True
[2023-09-08 21:17:58Z INFO CommandLineParser] arg: token
[2023-09-08 21:17:58Z INFO CommandLineParser] parsing argument
[2023-09-08 21:17:58Z INFO CommandLineParser] HasArgs: True
[2023-09-08 21:17:58Z INFO CommandLineParser] Adding option 'token': '***'
[2023-09-08 21:17:58Z INFO Listener] Arguments parsed
[2023-09-08 21:17:58Z INFO Runner] ExecuteCommand
[2023-09-08 21:17:58Z INFO ConfigurationStore] currentAssemblyLocation: /home/gabriel/actions-runner/bin/Runner.Listener.dll
[2023-09-08 21:17:58Z INFO HostContext] Well known directory 'Bin': '/home/gabriel/actions-runner/bin'
[2023-09-08 21:17:58Z INFO ConfigurationStore] binPath: /home/gabriel/actions-runner/bin
[2023-09-08 21:17:58Z INFO HostContext] Well known directory 'Bin': '/home/gabriel/actions-runner/bin'
[2023-09-08 21:17:58Z INFO HostContext] Well known directory 'Root': '/home/gabriel/actions-runner'
[2023-09-08 21:17:58Z INFO ConfigurationStore] RootFolder: /home/gabriel/actions-runner
[2023-09-08 21:17:58Z INFO HostContext] Well known directory 'Bin': '/home/gabriel/actions-runner/bin'
[2023-09-08 21:17:58Z INFO HostContext] Well known directory 'Root': '/home/gabriel/actions-runner'
[2023-09-08 21:17:58Z INFO HostContext] Well known config file 'Runner': '/home/gabriel/actions-runner/.runner'
[2023-09-08 21:17:58Z INFO ConfigurationStore] ConfigFilePath: /home/gabriel/actions-runner/.runner
[2023-09-08 21:17:58Z INFO HostContext] Well known directory 'Bin': '/home/gabriel/actions-runner/bin'
[2023-09-08 21:17:58Z INFO HostContext] Well known directory 'Root': '/home/gabriel/actions-runner'
[2023-09-08 21:17:58Z INFO HostContext] Well known config file 'Credentials': '/home/gabriel/actions-runner/.credentials'
[2023-09-08 21:17:58Z INFO ConfigurationStore] CredFilePath: /home/gabriel/actions-runner/.credentials
[2023-09-08 21:17:58Z INFO HostContext] Well known directory 'Bin': '/home/gabriel/actions-runner/bin'
[2023-09-08 21:17:58Z INFO HostContext] Well known directory 'Root': '/home/gabriel/actions-runner'
[2023-09-08 21:17:58Z INFO HostContext] Well known config file 'MigratedCredentials': '/home/gabriel/actions-runner/.credentials_migrated'
[2023-09-08 21:17:58Z INFO ConfigurationStore] MigratedCredFilePath: /home/gabriel/actions-runner/.credentials_migrated
[2023-09-08 21:17:58Z INFO HostContext] Well known directory 'Bin': '/home/gabriel/actions-runner/bin'
[2023-09-08 21:17:58Z INFO HostContext] Well known directory 'Root': '/home/gabriel/actions-runner'
[2023-09-08 21:17:58Z INFO HostContext] Well known config file 'Service': '/home/gabriel/actions-runner/.service'
[2023-09-08 21:17:58Z INFO ConfigurationStore] ServiceConfigFilePath: /home/gabriel/actions-runner/.service
[2023-09-08 21:17:58Z INFO CommandSettings] Flag 'help': 'False'
[2023-09-08 21:17:58Z INFO CommandSettings] Flag 'version': 'False'
[2023-09-08 21:17:58Z INFO CommandSettings] Flag 'commit': 'False'
[2023-09-08 21:17:58Z INFO CommandSettings] Flag 'check': 'False'
[2023-09-08 21:17:58Z INFO CommandSettings] Command 'configure': 'True'
[2023-09-08 21:17:58Z INFO Terminal] WRITE LINE:
[2023-09-08 21:17:58Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2023-09-08 21:17:58Z INFO Terminal] WRITE LINE: |        ____ _ _   _   _       _          _        _   _                      |
[2023-09-08 21:17:58Z INFO Terminal] WRITE LINE: |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
[2023-09-08 21:17:58Z INFO Terminal] WRITE LINE: |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
[2023-09-08 21:17:58Z INFO Terminal] WRITE LINE: |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
[2023-09-08 21:17:58Z INFO Terminal] WRITE LINE: |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
[2023-09-08 21:17:58Z INFO Terminal] WRITE LINE: |                                                                              |
[2023-09-08 21:17:58Z INFO Terminal] WRITE: |
[2023-09-08 21:17:58Z INFO Terminal] WRITE: Self-hosted runner registration
[2023-09-08 21:17:58Z INFO Terminal] WRITE LINE:                         |
[2023-09-08 21:17:58Z INFO Terminal] WRITE LINE: |                                                                              |
[2023-09-08 21:17:58Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2023-09-08 21:17:58Z INFO ConfigurationManager] ConfigureAsync
[2023-09-08 21:17:58Z INFO CommandSettings] Flag 'generateServiceConfig': 'False'
[2023-09-08 21:17:58Z INFO ConfigurationStore] IsConfigured()
[2023-09-08 21:17:58Z INFO ConfigurationStore] IsConfigured: False
[2023-09-08 21:17:58Z INFO ConfigurationManager] Is configured: False
[2023-09-08 21:17:58Z INFO CommandSettings] Arg 'url': 'https://github.com/GabrielBigardi/Humble-Objects'
[2023-09-08 21:17:58Z INFO CommandSettings] Remove url from Arg dictionary.
[2023-09-08 21:17:58Z INFO CommandSettings] Arg 'token': '***'
[2023-09-08 21:17:58Z INFO CommandSettings] Remove token from Arg dictionary.
[2023-09-08 21:18:04Z INFO ConfigurationManager] Http response code: OK from 'POST https://api.github.com/actions/runner-registration' (A6EC:2FA6:126EF36:1399841:64FB8F8C)
[2023-09-08 21:18:04Z INFO ConfigurationManager] Using V2 flow: False
[2023-09-08 21:18:04Z INFO ConfigurationManager] cred retrieved via GitHub auth
[2023-09-08 21:18:04Z INFO RunnerServer] EstablishVssConnection
[2023-09-08 21:18:04Z INFO RunnerServer] Establish connection with 100 seconds timeout.
[2023-09-08 21:18:04Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-09-08 21:18:04Z INFO RunnerServer] EstablishVssConnection
[2023-09-08 21:18:04Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2023-09-08 21:18:04Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-09-08 21:18:04Z INFO RunnerServer] EstablishVssConnection
[2023-09-08 21:18:04Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2023-09-08 21:18:04Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-09-08 21:18:05Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-09-08 21:18:05Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-09-08 21:18:05Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-09-08 21:18:05Z INFO Terminal] WRITE LINE:
[2023-09-08 21:18:05Z INFO ConfigurationManager] Test Connection complete.
[2023-09-08 21:18:05Z INFO HostContext] Well known directory 'Bin': '/home/gabriel/actions-runner/bin'
[2023-09-08 21:18:05Z INFO HostContext] Well known directory 'Root': '/home/gabriel/actions-runner'
[2023-09-08 21:18:05Z INFO HostContext] Well known config file 'RSACredentials': '/home/gabriel/actions-runner/.credentials_rsaparams'
[2023-09-08 21:18:05Z INFO RSAFileKeyManager] Creating new RSA key using 2048-bit key length
[2023-09-08 21:18:05Z INFO RSAFileKeyManager] Successfully saved RSA key parameters to file /home/gabriel/actions-runner/.credentials_rsaparams
[2023-09-08 21:18:05Z INFO RSAFileKeyManager] Which: 'chmod'
[2023-09-08 21:18:05Z INFO RSAFileKeyManager] Location: '/usr/bin/chmod'
[2023-09-08 21:18:05Z INFO HostContext] Well known directory 'Bin': '/home/gabriel/actions-runner/bin'
[2023-09-08 21:18:05Z INFO HostContext] Well known directory 'Root': '/home/gabriel/actions-runner'
[2023-09-08 21:18:05Z INFO ProcessInvokerWrapper] Starting process:
[2023-09-08 21:18:05Z INFO ProcessInvokerWrapper]   File name: '/usr/bin/chmod'
[2023-09-08 21:18:05Z INFO ProcessInvokerWrapper]   Arguments: '600 /home/gabriel/actions-runner/.credentials_rsaparams'
[2023-09-08 21:18:05Z INFO ProcessInvokerWrapper]   Working directory: '/home/gabriel/actions-runner'
[2023-09-08 21:18:05Z INFO ProcessInvokerWrapper]   Require exit code zero: 'False'
[2023-09-08 21:18:05Z INFO ProcessInvokerWrapper]   Encoding web name:  ; code page: ''
[2023-09-08 21:18:05Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'False'
[2023-09-08 21:18:05Z INFO ProcessInvokerWrapper]   Redirected STDIN: 'False'
[2023-09-08 21:18:05Z INFO ProcessInvokerWrapper]   Persist current code page: 'False'
[2023-09-08 21:18:05Z INFO ProcessInvokerWrapper]   Keep redirected STDIN open: 'False'
[2023-09-08 21:18:05Z INFO ProcessInvokerWrapper]   High priority process: 'False'
[2023-09-08 21:18:05Z INFO ProcessInvokerWrapper] Process started with process id 3464, waiting for process exit.
[2023-09-08 21:18:05Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2023-09-08 21:18:05Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2023-09-08 21:18:05Z INFO ProcessInvokerWrapper] Finished process 3464 with exit code 0, and elapsed time 00:00:00.0075107.
[2023-09-08 21:18:05Z INFO RSAFileKeyManager] Successfully set permissions for RSA key parameters file /home/gabriel/actions-runner/.credentials_rsaparams
[2023-09-08 21:18:05Z INFO CommandSettings] Arg 'runnergroup': ''
[2023-09-08 21:18:05Z INFO CommandSettings] Flag 'unattended': 'False'
[2023-09-08 21:18:05Z INFO PromptManager] ReadValue
[2023-09-08 21:18:05Z INFO Terminal] WRITE: Enter the name of the runner group to add this runner to:
[2023-09-08 21:18:05Z INFO Terminal] WRITE: [press Enter for Default]
[2023-09-08 21:18:05Z INFO Terminal] READ LINE
[2023-09-08 21:18:07Z INFO Terminal] Read value: ''
[2023-09-08 21:18:07Z INFO PromptManager] Falling back to the default: 'Default'
[2023-09-08 21:18:07Z INFO Terminal] WRITE LINE:
[2023-09-08 21:18:07Z INFO ConfigurationManager] Found a self-hosted runner group with id 1 and name Default
[2023-09-08 21:18:07Z INFO CommandSettings] Flag 'disableupdate': 'False'
[2023-09-08 21:18:07Z INFO CommandSettings] Flag 'ephemeral': 'False'
[2023-09-08 21:18:07Z INFO CommandSettings] Arg 'name': ''
[2023-09-08 21:18:07Z INFO CommandSettings] Flag 'unattended': 'False'
[2023-09-08 21:18:07Z INFO PromptManager] ReadValue
[2023-09-08 21:18:07Z INFO Terminal] WRITE: Enter the name of runner:
[2023-09-08 21:18:07Z INFO Terminal] WRITE: [press Enter for GabrielUBUNTU]
[2023-09-08 21:18:07Z INFO Terminal] READ LINE
[2023-09-08 21:18:08Z INFO Terminal] Read value: ''
[2023-09-08 21:18:08Z INFO PromptManager] Falling back to the default: 'GabrielUBUNTU'
[2023-09-08 21:18:08Z INFO Terminal] WRITE LINE:
[2023-09-08 21:18:08Z INFO CommandSettings] Arg 'labels': ''
[2023-09-08 21:18:08Z INFO CommandSettings] Flag 'unattended': 'False'
[2023-09-08 21:18:08Z INFO PromptManager] ReadValue
[2023-09-08 21:18:08Z INFO Terminal] WRITE: This runner will have the following labels: 'self-hosted', 'Linux', 'X64'
Enter any additional labels (ex. label-1,label-2):
[2023-09-08 21:18:08Z INFO Terminal] WRITE: [press Enter to skip]
[2023-09-08 21:18:08Z INFO Terminal] READ LINE
[2023-09-08 21:18:09Z INFO Terminal] Read value: ''
[2023-09-08 21:18:09Z INFO Terminal] WRITE LINE:
[2023-09-08 21:18:09Z INFO CommandSettings] Flag 'disableupdate': 'False'
[2023-09-08 21:18:09Z INFO CommandSettings] Flag 'no-default-labels': 'False'
[2023-09-08 21:18:09Z INFO CommandSettings] Flag 'disableupdate': 'False'
[2023-09-08 21:18:09Z INFO CommandSettings] Flag 'ephemeral': 'False'
[2023-09-08 21:18:09Z INFO ConfigurationStore] Saving OAuth credential @ /home/gabriel/actions-runner/.credentials
[2023-09-08 21:18:09Z INFO ConfigurationStore] Credentials Saved.
[2023-09-08 21:18:09Z INFO ConfigurationStore] HasCredentials()
[2023-09-08 21:18:09Z INFO ConfigurationStore] stored True
[2023-09-08 21:18:09Z INFO CredentialManager] GetCredentialProvider
[2023-09-08 21:18:09Z INFO CredentialManager] Creating type OAuth
[2023-09-08 21:18:09Z INFO CredentialManager] Creating credential type: OAuth
[2023-09-08 21:18:09Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/gabriel/actions-runner/.credentials_rsaparams
[2023-09-08 21:18:09Z INFO RunnerServer] EstablishVssConnection
[2023-09-08 21:18:09Z INFO RunnerServer] Establish connection with 100 seconds timeout.
[2023-09-08 21:18:09Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-09-08 21:18:09Z INFO RunnerServer] EstablishVssConnection
[2023-09-08 21:18:09Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2023-09-08 21:18:09Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-09-08 21:18:09Z INFO RunnerServer] EstablishVssConnection
[2023-09-08 21:18:09Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2023-09-08 21:18:09Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-09-08 21:18:10Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-09-08 21:18:10Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-09-08 21:18:10Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-09-08 21:18:10Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/gabriel/actions-runner/.credentials_rsaparams
[2023-09-08 21:18:10Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/gabriel/actions-runner/.credentials_rsaparams
[2023-09-08 21:19:50Z WARN GitHubActionsService] Retrieving an AAD auth token took a long time (99,8856257 seconds)
[2023-09-08 21:19:50Z WARN GitHubActionsService] GET request to https://pipelinesghubeus9.actions.githubusercontent.com/62ScAd50ROPlszVlJRnqvsHeGMXN3XZfiyyHwyXvp2ULUR3GJf/_apis/distributedtask/pools?poolType=Automation timed out after 100 seconds.
[2023-09-08 21:19:50Z ERR  Runner] System.TimeoutException: The HTTP request timed out after 00:01:40.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GitHub.Services.OAuth.VssOAuthTokenHttpClient.GetTokenAsync(VssOAuthGrant grant, VssOAuthClientCredential credential, VssOAuthTokenParameters tokenParameters, CancellationToken cancellationToken)
   at GitHub.Services.OAuth.VssOAuthTokenProvider.OnGetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
   at GitHub.Services.Common.IssuedTokenProvider.GetTokenOperation.GetTokenAsync(VssTraceActivity traceActivity)
   at GitHub.Services.Common.IssuedTokenProvider.GetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at GitHub.Runner.Listener.Runner.ExecuteCommand(CommandSettings command)
[2023-09-08 21:19:50Z ERR  Runner] #####################################################
[2023-09-08 21:19:50Z ERR  Runner] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GitHub.Services.OAuth.VssOAuthTokenHttpClient.GetTokenAsync(VssOAuthGrant grant, VssOAuthClientCredential credential, VssOAuthTokenParameters tokenParameters, CancellationToken cancellationToken)
   at GitHub.Services.OAuth.VssOAuthTokenProvider.OnGetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
   at GitHub.Services.Common.IssuedTokenProvider.GetTokenOperation.GetTokenAsync(VssTraceActivity traceActivity)
   at GitHub.Services.Common.IssuedTokenProvider.GetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[2023-09-08 21:19:50Z ERR  Terminal] WRITE ERROR: The HTTP request timed out after 00:01:40.
[2023-09-08 21:19:50Z INFO Listener] Runner execution has finished with return code 1

**Comment by ctg123** [comment]
I can also confirm this behavior when trying out the runner verison 2.309.0. Disabling IPv6 also fixes it for me. Is this workaround mentioned anywhere?

**Comment by lfgiles** [comment]
Hi,

I know this issue has been reported before but I am getting a Fatal error when I try to configure the self-hosted runner for LINUX X64. As mentioned before the error is : System.Threading.Tasks.TaskCanceledException.  As work-around you did mention that the system administrator should deactivate IPv6 but since I have no superuser rights, the question  is whether there would be anything I could do besides de-activating IPv6 to make it work?

**Comment by ovsds** [comment]
Getting the same issue, the moment we enable ipv6 nat on VM runners go down, reinstalling runners doesn't help since the process just stucks on the exact moment described above.

**Comment by alsutton** [comment]
I've dug into this a big as we're turning down IPv4 addresses given that hosting companies are starting to charge for them.

The `pipelinesghubeus???.actions.githubusercontent.com` hosts seem to only have IPv4 addresses, so, when there is no IPv4 route available, any request that involves them fails.

**Comment by hxw** [comment]
I seem to have run into this problem yesterday. It looks like there is some IPv6 deployment:
```
# host pipelinesghubeus1.actions.githubusercontent.com 
pipelinesghubeus1.actions.githubusercontent.com has address 20.242.179.206

# host pipelinesghubwus1.actions.githubusercontent.com 
pipelinesghubwus1.actions.githubusercontent.com is an alias for star-actions-githubusercontent-com.l-0007.l-msedge.net.
star-actions-githubusercontent-com.l-0007.l-msedge.net is an alias for l-0007.l-msedge.net.
l-0007.l-msedge.net has address 13.107.42.16
l-0007.l-msedge.net has IPv6 address 2620:1ec:21::16
```
But i think IPv6 is not working so runners just hang, for a test I remove IPv6 from iface restarted runner and it is working again.
