### ISSUE TITLE
pipenv install fails with python 3.8.1 and on ubunut-latest 2.164.0

### ISSUE THREAD

**Issue by cat-turner** [actions/runner#287]
**Describe the bug**
pipenv fails on ubunut-latest '2.164.0'. The builds passed in '2.163.0'. The problem seems that it is unable to parse the python requirement version from the pipfile.

**To Reproduce**
```
    - name: Install dependencies
      run: |
        echo "check python version"
        python -V
        python -m pip install --upgrade pip
        python -m pip install pipenv
```
**Expected behavior**
Install pipenv version with python 3.8.1.

## Runner Version and Platform
Version of your runner?

`ubuntu-latest`

```
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8.1"
```

## What's not working?
Please include error messages and screenshots.

## Job Log Output

```
Run echo "check python version"
check python version
Python 3.8.1
Requirement already up-to-date: pip in /opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages (19.3.1)
Collecting pipenv
  Downloading https://files.pythonhosted.org/packages/13/b4/3ffa55f77161cff9a5220f162670f7c5eb00df52e00939e203f601b0f579/pipenv-2018.11.26-py3-none-any.whl (5.2MB)
Requirement already satisfied: setuptools>=36.2.1 in /opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages (from pipenv) (41.2.0)
Collecting virtualenv
  Downloading https://files.pythonhosted.org/packages/05/f1/2e07e8ca50e047b9cc9ad56cf4291f4e041fa73207d000a095fe478abf84/virtualenv-16.7.9-py2.py3-none-any.whl (3.4MB)
Collecting virtualenv-clone>=0.2.5
  Downloading https://files.pythonhosted.org/packages/ba/f8/50c2b7dbc99e05fce5e5b9d9a31f37c988c99acd4e8dedd720b7b8d4011d/virtualenv_clone-0.5.3-py2.py3-none-any.whl
Requirement already satisfied: pip>=9.0.1 in /opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages (from pipenv) (19.3.1)
Collecting certifi
  Downloading https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl (156kB)
Installing collected packages: virtualenv, virtualenv-clone, certifi, pipenv

Successfully installed certifi-2019.11.28 pipenv-2018.11.26 virtualenv-16.7.9 virtualenv-clone-0.5.3
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.1/x64/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/pipenv/cli/command.py", line 235, in install
    retcode = do_install(
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/pipenv/core.py", line 1734, in do_install
    ensure_project(
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/pipenv/core.py", line 584, in ensure_project
    "{0}: Your Pipfile requires {1} {2}, "
TypeError: __str__ returned non-string (type NoneType)
##[error]Process completed with exit code 1.

```

**Comment by TingluoHuang** [comment]
@cat-turner do you have some workflow runs we can take a look? Thanks

**Comment by bryanmacfarlane** [comment]
new virtual-environment images just rolled out so I think this is due to that.  We may want to move this over.

**Comment by cat-turner** [comment]
@TingluoHuang our project is private. You should be able to recreate the error with the steps I have provided I think

**Comment by cat-turner** [comment]
Any status update on this issue? We still seem to have issues with 2.164.0
