### ISSUE TITLE
Jobs on MacOS stop working after a while

### ISSUE THREAD

**Issue by john-jam** [actions/runner#2876]
**Describe the bug**

When restarting the runner machine, the runner successfully starts its service and connects to Github.
Then, when requesting matrix jobs for this runner, it completes 1-2 jobs and then fails with the errors below.

After a job fails, new jobs are not picked up anymore by the runner and the machine needs to be restarted.

**Expected behavior**

All the jobs in the matrix for MacOS succeed.

## Runner Version and Platform

Platform: MacOS 13.0
Runner: 2.309.0

## Job Log Output

No logs for the failing job: `Error: The log was not found. It may have been deleted based on retention settings.`

## Runner and Worker's Diagnostic Logs

Runner logs:
```
[2023-09-22 10:34:10Z INFO ProcessChannel] Sending message of length 45049, with hash '94130937f3cb5135450b8a0b6d43a4e1fb15491c654ef4254e1da4565c2e07f6'
[2023-09-22 10:34:10Z INFO JobNotification] Entering JobStarted Notification
[2023-09-22 10:34:10Z INFO JobNotification] Entering StartMonitor
[2023-09-22 10:35:10Z INFO JobDispatcher] Successfully renew job request 179454, job is valid till 2023/09/22 10:45:10 AM
[2023-09-22 10:36:11Z INFO JobDispatcher] Successfully renew job request 179454, job is valid till 2023/09/22 10:46:11 AM
[2023-09-22 10:53:02Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/RBFgLgAYVdRNSRamDFCgw99DNURAz4VEtDC3sw0Da3vL1sHCCR/_apis/distributedtask/pools/1/messages?sessionId=69a815d3-f2f3-4871-a311-b80a6cf00884&lastMessageId=4&status=Online&runnerVersion=2.309.0 timed out after 60 seconds.
[2023-09-22 10:53:02Z ERR  MessageListener] Catch exception during get next message.
[2023-09-22 10:53:02Z ERR  MessageListener] System.TimeoutException: The HTTP request timed out after 00:01:00.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (89): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Listener.MessageListener.GetNextMessageAsync(CancellationToken token)
[2023-09-22 10:53:02Z ERR  MessageListener] #####################################################
[2023-09-22 10:53:02Z ERR  MessageListener] System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (89): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```

Worker logs:
```
...
[2023-09-22 10:59:10Z INFO JobServerQueue] All queue process tasks have been stopped, and all queues are drained.
[2023-09-22 10:59:10Z INFO TempDirectoryManager] Cleaning runner temp folder: /var/cache/github-actions-runner/_temp
[2023-09-22 10:59:10Z INFO HostContext] Well known directory 'Bin': '/usr/local/share/github-actions-runner/2.309.0/065e1c29ac78deb2f7715e81a5df90915c937ad486cc96a63bf1fcd36c02d41e/bin'
[2023-09-22 10:59:10Z INFO HostContext] Well known directory 'Root': '/usr/local/share/github-actions-runner/2.309.0/065e1c29ac78deb2f7715e81a5df90915c937ad486cc96a63bf1fcd36c02d41e'
[2023-09-22 10:59:10Z INFO HostContext] Well known directory 'Diag': '/usr/local/share/github-actions-runner/2.309.0/065e1c29ac78deb2f7715e81a5df90915c937ad486cc96a63bf1fcd36c02d41e/_diag'
[2023-09-22 10:59:10Z INFO HostContext] Well known config file 'Telemetry': '/usr/local/share/github-actions-runner/2.309.0/065e1c29ac78deb2f7715e81a5df90915c937ad486cc96a63bf1fcd36c02d41e/_diag/.telemetry'
[2023-09-22 10:59:10Z INFO JobRunner] Raising job completed event
[2023-09-22 10:59:10Z ERR  GitHubActionsService] POST request to https://pipelinesghubeus3.actions.githubusercontent.com/vQtJ634IoH6YcEuEnVyccBtby9UOtcguWMRW01pTNyBkPV3oLS/00000000-0000-0000-0000-000000000000/_apis/distributedtask/hubs/Actions/plans/817fad56-a0ae-46f9-a6a6-b488189b7e2f/events failed. HTTP Status: BadRequest
[2023-09-22 10:59:10Z ERR  JobRunner] TaskOrchestrationPlanTerminatedException received, while attempting to raise JobCompletedEvent for job bb98b99b-8ad6-56f6-d33e-e18cffa4e189.
[2023-09-22 10:59:10Z ERR  JobRunner] GitHub.DistributedTask.WebApi.TaskOrchestrationPlanTerminatedException: Orchestration plan 817fad56-a0ae-46f9-a6a6-b488189b7e2f is not in a runnable state.
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpMethod method, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.DistributedTask.WebApi.TaskHttpClient.RaisePlanEventAsync[T](Guid scopeIdentifier, String planType, Guid planId, T eventData, CancellationToken cancellationToken, Object userState)
   at GitHub.Runner.Worker.JobRunner.CompleteJobAsync(IJobServer jobServer, IExecutionContext jobContext, AgentJobRequestMessage message, Nullable`1 taskResult)
```

**Comment by john-jam** [comment]
I disabled the auto logout after some time feature (energy saver) and I think it did the trick :facepalm:
