### ISSUE TITLE
Incorrect self-hosted runners disappeared message

### ISSUE THREAD

**Issue by samdeane** [actions/runner#2967]
**Describe the bug**

I have a runner running in a virtualised mac. Occasionally the VM instance is going to sleep (or the host that it's running on is going to sleep), and the run.sh script is losing its connection or timing out and attempting to retry.

It doesn't manage to retry when the session is restored. If I ctrl-c the script and launch it again, I get the error about the self-hosted runner having disappeared.

This error is spurious in this case. The runner is still registered, and if I restart the VM and re-run the script it works again.

I think the real reason is some sort of token / auth timeout, which is incorrectly being reported.

**To Reproduce**

Install runner in a VM (eg VirtualBuddy using macOS 13.6)
Run the runner and leave it for a while.
When it times out, try to restart the run.sh script.

**Expected behavior**

Ideally the run.sh script should successfully reconnect without needing to be restarted.
In the absence of that, quitting and re-running the script should successfully connect.
In the absence of that (!), a more informative message should be output, explaining the real problem.

## Runner Version and Platform

runner: 2.311.0
virtualized host: macos 13.6
host: macos 13.4 (also tested on 13.6)

## What's not working?

Runner is failing to reconnect, and is reporting that it's been deleted when it hasn't.

## Job Log Output

(not supplied - I don't have a live failure case in front of me but will add this later when I do)

## Runner and Worker's Diagnostic Logs

(not supplied - I don't have a live failure case in front of me but will add this later when I do)

**Comment by cheskayang** [comment]
running into the same issue with arc managed runners, version `v2.315`

**Comment by luismiguelsaez-steercrm** [comment]
I'm deploying the runners to Kubernetes ( EKS ) through Helm, using `gha-runner-scale-set-controller` chart version `0.9.2`. We have a workflow that uses a matrix to create around 60 runners to build different images.

I am experiencing the issue randomly for some of the runners, even though they register successfully to GHA
```
√ Connected to GitHub
```
it fails seconds later while executing the job with the following errors
```
[RUNNER 2024-06-26 14:58:17Z ERR  GitHubActionsService] POST request to https://pipelinesghubeus3.actions.githubusercontent.com/EMdYJ0e8OZvrY3kdHoarqQa5vRx5ItkhbERYlQ35U6MxWjS0e4/_apis/oauth2/token failed. HTTP Status: BadRequest
[RUNNER 2024-06-26 14:58:17Z ERR  Terminal] WRITE ERROR: Failed to create a session. The runner registration has been deleted from the server, please re-configure. Runner registrations are automatically deleted for runners that have not connected to the service recently.
```

GHA is somehow deleting the runner registration, making the job fail with `Error: The operation was canceled.`

I have already read a bunch of issues opened by people experiencing similar problems, but GH is not putting much effort in their resolution. I'm starting to think that they just want people use the GH managed runners, but that is not possible for security reasons, depending on the infrastructure, and we are already paying for the service.

**Comment by celiogafesi** [comment]
Facing something similar. Any news on this?

**Comment by lokesh755** [comment]
@celiogafesi Earlier issues should be resolved now. Can you runner logs of the runner that got deleted?

**Comment by aleonsan** [comment]
We have the same problem here, running:

* EKS `1.30` 
* [gha-runner-scale-set-controller](https://github.com/actions/actions-runner-controller) chart version `0.9.3` 
* [runner](https://github.com/actions/runner) version `2.321.0` 

These runner logs show an error on the runner creating a session 

```
[RUNNER 2024-12-12 13:04:18Z ERR  GitHubActionsService] POST request to https://pipelinesghubeus3.actions.githubusercontent.com/g45wlGxp3pERBo3YEaOyr6oTmk8FBSYND0h8EoLI6SVnsukqTN/_apis/oauth2/token failed. HTTP Status: BadRequest
[RUNNER 2024-12-12 13:04:18Z ERR  MessageListener] Catch exception during create session.
[RUNNER 2024-12-12 13:04:18Z ERR  MessageListener] GitHub.Services.OAuth.VssOAuthTokenRequestException: Registration 80be625f-e5fa-4610-917f-ea35c30036c1 was not found.
[RUNNER 2024-12-12 13:04:18Z ERR  MessageListener]    at GitHub.Services.OAuth.VssOAuthTokenProvider.OnGetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken
[RUNNER 2024-12-12 13:04:18Z ERR  MessageListener]    at GitHub.Services.Common.IssuedTokenProvider.GetTokenOperation.GetTokenAsync(VssTraceActivity traceActivity)
{[RUNNER 2024-12-12 13:04:18Z ERR  MessageListener]    at GitHub.Services.Common.IssuedTokenProvider.GetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
[RUNNER 2024-12-12 13:04:18Z ERR  MessageListener]    at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[RUNNER 2024-12-12 13:04:18Z ERR  MessageListener]    at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[RUNNER 2024-12-12 13:04:18Z ERR  MessageListener]    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[RUNNER 2024-12-12 13:04:18Z ERR  MessageListener]    at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
[RUNNER 2024-12-12 13:04:18Z ERR  MessageListener]    at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
[RUNNER 2024-12-12 13:04:18Z ERR  MessageListener]    at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
[RUNNER 2024-12-12 13:04:18Z ERR  MessageListener]    at GitHub.Runner.Listener.MessageListener.CreateSessionAsync(CancellationToken token)
[RUNNER 2024-12-12 13:04:18Z ERR  Terminal] WRITE ERROR: Failed to create a session. The runner registration has been deleted from the server, please re-configure. Runner registrations are automatically deleted for runners that have not connected to the service recently.
Failed to create a session. The runner registration has been deleted from the server, please re-configure. Runner registrations are automatically deleted for runners that have not connected to the service recently.
Runner listener exit with terminated error, stop the service, no retry needed.
```

but there were some other error logs in the runner beforehand, led by this one around 90 seconds before.
```
[RUNNER 2024-12-12 13:02:45Z WARN GitHubActionsService] GET request to https://broker.actions.githubusercontent.com/message?sessionId=643e945e-ded8-4d98-b878-5ba14c4f0da6&status=Busy&runnerVersion=2.321.0&os=Linux&architecture=X64&disableUpdate=true has been cancelled.
```

And this log found into the listener few seconds later

```
2024-12-12T13:02:57Z\tINFO\tlistener-app.listener\tJob completed message received.\t{\"RequestId\": 34115, \"Result\": \"failed\", \"RunnerId\": 53498, \"RunnerName\": \"github-actions-runner-set-medium-dind-db2k9-runner-6ndhc\"}
```

I will carry on the investigation just in case, but I would appreciate some more context or examples if any.

**Comment by Scalahansolo** [comment]
Recently started to run in this with our runners. Any resolution here?

**Comment by duttabhishek0** [comment]
### Found the Culprit: It’s a Time Sync Issue!

Before you try to force-remove or re-register anything, check your system clock.

Why this happens:

- Security Handshake: GitHub uses time-sensitive tokens (OAuth) for authentication.
- The "Drift": If your local machine’s clock drifts even a few minutes away from GitHub’s server time, the security "handshake" fails.
- Misleading Error: Instead of a "clock error," the runner throws a generic message saying the registration was deleted because it can't complete the login.

Fix:

- Sync the Clock: Open Date & Time settings on your Windows machine and click "Sync now".

- Relaunch: Try running `./run.cmd` or starting your service again.

- Result: In many cases, the runner will reconnect immediately without needing a new removal token or a fresh installation.

This is especially common on Virtual Machines (like OpenStack or AWS) where internal clocks can drift more easily. Syncing the clock restored my connection instantly

**Comment by yasiinakbulut58** [comment]
> ### Found the Culprit: It’s a Time Sync Issue!
> Before you try to force-remove or re-register anything, check your system clock.
> 
> Why this happens:
> 
> * Security Handshake: GitHub uses time-sensitive tokens (OAuth) for authentication.
> * The "Drift": If your local machine’s clock drifts even a few minutes away from GitHub’s server time, the security "handshake" fails.
> * Misleading Error: Instead of a "clock error," the runner throws a generic message saying the registration was deleted because it can't complete the login.
> 
> Fix:
> 
> * Sync the Clock: Open Date & Time settings on your Windows machine and click "Sync now".
> * Relaunch: Try running `./run.cmd` or starting your service again.
> * Result: In many cases, the runner will reconnect immediately without needing a new removal token or a fresh installation.
> 
> This is especially common on Virtual Machines (like OpenStack or AWS) where internal clocks can drift more easily. Syncing the clock restored my connection instantly


this fixed our issue, thank you so much
