### ISSUE TITLE
Diagnostics for `hashFiles` failing on a broken symlink don't describe the problem

### ISSUE THREAD

**Issue by huonw** [actions/runner#3015]
**Describe the bug**

Currently if `hashFiles` hits a broken symlink it fails the step hard with an opaque error: it says that there _is_ a problem, but no guidance about what it was. For instance:

```
Error: The template is not valid. .github/workflows/test.yml (Line: 14, Col: 14): hashFiles('*') failed. Fail to hash files under directory '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics'
```

That is all it says, without debug logging. This is confusing and frustrating, and is even worse with a glob like `some-directory/**/*`: who knows which file somewhere under that directory is the problem.

Given the job is failing, preferably this would do at least one of:

1. include which file(s) is causing the problem
2. suggest how to find more information, e.g. "turn on debug logging". 

Debug logging helps with this, somewhat, _if one knows what to look for_ (I had to find https://github.com/actions/runner/issues/1666 to realise I could search for `ENOENT` in the logs, since there was too much output to look at manually):

```
##[debug]Error: ENOENT: no such file or directory, stat '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics/broken'
##[debug]    at Object.statSync (node:fs:1583:3)
##[debug]    at /home/runner/runners/2.311.0/bin/hashFiles/index.js:84:24
##[debug]    at Generator.next (<anonymous>)
##[debug]    at fulfilled (/home/runner/runners/2.311.0/bin/hashFiles/index.js:35:58) {
##[debug]  errno: -2,
##[debug]  syscall: 'stat',
##[debug]  code: 'ENOENT',
##[debug]  path: '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics/broken'
##[debug]}
```

**To Reproduce**

1. Have a broken symlink somehow
2. Have a `hashFiles` call in the workflow that includes that symlink
4. See error and then struggle to understand what needs to be changed to fix the problem

Example: https://github.com/huonw/GitHub-runner-broken-symlink-diagnostics

- run without debug logging: https://github.com/huonw/GitHub-runner-broken-symlink-diagnostics/actions/runs/7028745161/job/19125215085
- run _with_ debug logging: https://github.com/huonw/GitHub-runner-broken-symlink-diagnostics/actions/runs/7028745161/job/19125266914

**Expected behavior**

It would be better if the error message said:

1. which files are a problem (preferably if there's multiple files that are a problem, highlight them all)
2. _why_ they're a problem (e.g. "symlink to file that doesn't exist")

1 is most critical, but 2 would be great.

## Runner Version and Platform
```
Current runner version: '2.311.0'
Operating System
  Ubuntu
  22.04.3
  LTS
```
## What's not working?

The error is opaque, currently:
```
Error: The template is not valid. .github/workflows/test.yml (Line: 14, Col: 14): hashFiles('*') failed. Fail to hash files under directory '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics'
```

## Job Log Output

- run without debug logging: https://github.com/huonw/GitHub-runner-broken-symlink-diagnostics/actions/runs/7028745161/job/19125215085
- run _with_ debug logging: https://github.com/huonw/GitHub-runner-broken-symlink-diagnostics/actions/runs/7028745161/job/19125266914

## Runner and Worker's Diagnostic Logs
N/A

**Comment by oldgalileo** [comment]
This is still an issue. Any advice on workarounds or resolutions would be much appreciated!

**Comment by huonw** [comment]
You can currently debug this by turning on debug logs and searching for `ENOENT`. If there's no results, you may be affected by a different problem, or be running on a different system.

**Comment by huonw** [comment]
I've retried the reproducer just now. The problem still exists: the diagnostics are basically the same.

Without debug logging: https://github.com/huonw/GitHub-runner-broken-symlink-diagnostics/actions/runs/14698981460/job/41245026404

```
Warning: Encountered an error when evaluating display name ${{ format('echo {0}
', hashFiles('*')) }}. The template is not valid. .github/workflows/test.yml (Line: 14, Col: 14): hashFiles('*') failed. Fail to hash files under directory '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics'
Error: The template is not valid. .github/workflows/test.yml (Line: 14, Col: 14): hashFiles('*') failed. Fail to hash files under directory '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics'
```

With debug logging: https://github.com/huonw/GitHub-runner-broken-symlink-diagnostics/actions/runs/14698981460/job/41245059869

<details>

```
##[debug]Evaluating condition for step: 'Run echo ${{ hashFiles('*') }}'
##[debug]Evaluating: format('echo {0}
##[debug]', hashFiles('*'))
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> 'echo {0}
##[debug]'
##[debug]..Evaluating hashFiles:
##[debug]....Evaluating String:
##[debug]....=> '*'
##[debug]Search root directory: '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics'
##[debug]Search pattern: '*'
##[debug]Starting process:
##[debug]  File name: '/home/runner/runners/2.323.0/externals/node20/bin/node'
##[debug]  Arguments: '"/home/runner/runners/2.323.0/bin/hashFiles"'
##[debug]  Working directory: '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics'
##[debug]  Require exit code zero: 'False'
##[debug]  Encoding web name:  ; code page: ''
##[debug]  Force kill process on cancellation: 'False'
##[debug]  Redirected STDIN: 'False'
##[debug]  Persist current code page: 'False'
##[debug]  Keep redirected STDIN open: 'False'
##[debug]  High priority process: 'False'
##[debug]Updated oom_score_adj to 500 for PID: 1746.
##[debug]Process started with process id 1746, waiting for process exit.
##[debug]Match Pattern: *
##[debug]::debug::followSymbolicLinks 'false'
##[debug]::debug::followSymbolicLinks 'false'
##[debug]::debug::implicitDescendants 'true'
##[debug]::debug::matchDirectories 'true'
##[debug]::debug::omitBrokenSymbolicLinks 'true'
##[debug]::debug::Search path '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics'
##[debug]/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics/broken
##[debug]Error: ENOENT: no such file or directory, stat '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics/broken'
##[debug]    at Object.statSync (node:fs:1667:25)
##[debug]    at /home/runner/runners/2.323.0/bin/hashFiles/index.js:84:24
##[debug]    at Generator.next (<anonymous>)
##[debug]    at fulfilled (/home/runner/runners/2.323.0/bin/hashFiles/index.js:35:58) {
##[debug]  errno: -2,
##[debug]  code: 'ENOENT',
##[debug]  syscall: 'stat',
##[debug]  path: '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics/broken'
##[debug]}
##[debug]STDOUT/STDERR stream read finished.
##[debug]STDOUT/STDERR stream read finished.
##[debug]Finished process 1746 with exit code 1, and elapsed time 00:00:00.0998630.
##[debug].github/workflows/test.yml (Line: 14, Col: 14):
Warning: Encountered an error when evaluating display name ${{ format('echo {0}
', hashFiles('*')) }}. The template is not valid. .github/workflows/test.yml (Line: 14, Col: 14): hashFiles('*') failed. Fail to hash files under directory '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics'
##[debug]Set step '__run_2' display name to: ''
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: run
##[debug]Loading inputs
##[debug]Evaluating: format('echo {0}
##[debug]', hashFiles('*'))
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> 'echo {0}
##[debug]'
##[debug]..Evaluating hashFiles:
##[debug]....Evaluating String:
##[debug]....=> '*'
##[debug]Search root directory: '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics'
##[debug]Search pattern: '*'
##[debug]Starting process:
##[debug]  File name: '/home/runner/runners/2.323.0/externals/node20/bin/node'
##[debug]  Arguments: '"/home/runner/runners/2.323.0/bin/hashFiles"'
##[debug]  Working directory: '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics'
##[debug]  Require exit code zero: 'False'
##[debug]  Encoding web name:  ; code page: ''
##[debug]  Force kill process on cancellation: 'False'
##[debug]  Redirected STDIN: 'False'
##[debug]  Persist current code page: 'False'
##[debug]  Keep redirected STDIN open: 'False'
##[debug]  High priority process: 'False'
##[debug]Updated oom_score_adj to 500 for PID: 1757.
##[debug]Process started with process id 1757, waiting for process exit.
##[debug]Match Pattern: *
##[debug]::debug::followSymbolicLinks 'false'
##[debug]::debug::followSymbolicLinks 'false'
##[debug]::debug::implicitDescendants 'true'
##[debug]::debug::matchDirectories 'true'
##[debug]::debug::omitBrokenSymbolicLinks 'true'
##[debug]::debug::Search path '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics'
##[debug]/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics/broken
##[debug]Error: ENOENT: no such file or directory, stat '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics/broken'
##[debug]    at Object.statSync (node:fs:1667:25)
##[debug]    at /home/runner/runners/2.323.0/bin/hashFiles/index.js:84:24
##[debug]    at Generator.next (<anonymous>)
##[debug]    at fulfilled (/home/runner/runners/2.323.0/bin/hashFiles/index.js:35:58) {
##[debug]  errno: -2,
##[debug]  code: 'ENOENT',
##[debug]  syscall: 'stat',
##[debug]  path: '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics/broken'
##[debug]}
##[debug]STDOUT/STDERR stream read finished.
##[debug]STDOUT/STDERR stream read finished.
##[debug]Finished process 1757 with exit code 1, and elapsed time 00:00:00.0462120.
##[debug].github/workflows/test.yml (Line: 14, Col: 14):
Error: The template is not valid. .github/workflows/test.yml (Line: 14, Col: 14): hashFiles('*') failed. Fail to hash files under directory '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics'
##[debug]GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. .github/workflows/test.yml (Line: 14, Col: 14): hashFiles('*') failed. Fail to hash files under directory '/home/runner/work/GitHub-runner-broken-symlink-diagnostics/GitHub-runner-broken-symlink-diagnostics'
##[debug]   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
##[debug]   at GitHub.DistributedTask.Pipelines.ObjectTemplating.PipelineTemplateEvaluator.EvaluateStepInputs(TemplateToken token, DictionaryContextData contextData, IList`1 expressionFunctions)
##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[debug]Finishing: run
```

</details>
