### ISSUE TITLE
Get an error `Access to the path '/home/runner/work/_temp/_github_workflow/event.json' is denied` on `Post run checkout@v3`

### ISSUE THREAD

**Issue by zhaoyi0113** [actions/runner#3031]
**Describe the bug**

I have a workflow file to use `actions/checkout@v3` to checkout files from github repo. The build passed successfully but the workflow fails on `Post run @actions/checkout@v3` with this error:

```
Error: Access to the path '/home/runner/work/_temp/_github_workflow/event.json' is denied.
```

I don't have any where to access this file. What does `Post run` action do?

**To Reproduce**
2. Run '....'
3. See error

**Expected behavior**

## Runner Version and Platform
Version of your runner?

2.311.0

OS of the machine running the runner? OSX/Windows/Linux/...
ubuntu-latest

## What's not working?
Please include error messages and screenshots.

<img width="824" alt="image" src="https://github.com/actions/runner/assets/3355579/8b23fd63-26f8-4b38-ba9d-14fad6979f96">

The debug level logs I got is:

```
##[debug]Evaluating condition for step: 'Post Run actions/checkout@v3'
##[debug]Evaluating: always()
##[debug]Evaluating always:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Post Run actions/checkout@v3
Error: Access to the path '/home/runner/work/_temp/_github_workflow/event.json' is denied.
##[debug]System.UnauthorizedAccessException: Access to the path '/home/runner/work/_temp/_github_workflow/event.json' is denied.
##[debug] ---> System.IO.IOException: Permission denied
##[debug]   --- End of inner exception stack trace ---
##[debug]   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`[2](https://github.com/zeller-engineering/component-bff/actions/runs/7161184941/job/19496764108#step:10:2) errorRewriter)
##[debug]   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
##[debug]   at Microsoft.Win[3](https://github.com/zeller-engineering/component-bff/actions/runs/7161184941/job/19496764108#step:10:3)2.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
##[debug]   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int6[4](https://github.com/zeller-engineering/component-bff/actions/runs/7161184941/job/19496764108#step:10:4) preallocationSize)
##[debug]   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int[6](https://github.com/zeller-engineering/component-bff/actions/runs/7161184941/job/19496764108#step:10:6)4 preallocationSize)
##[debug]   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
##[debug]   at GitHub.Runner.Worker.ExecutionContext.WriteWebhookPayload()
##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[debug]Finishing: Post Run actions/checkout@v3
```

**Comment by zhaoyi0113** [comment]
It seems relate to a 3rd part action.

**Comment by adrian-livefront** [comment]
@erlichmen for us (and apparently also @zhaoyi0113 ) the culprit turned out to be [SonarCloud](https://github.com/SonarSource/sonarcloud-github-action/commit/e2a1ee7c31ee491f1e09c74535b1c0d3e9f5cd82#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R26), hope this helps.

**Comment by erlichmen** [comment]
thnaks @adrian-livefront indeed that was the problem for us also

**Comment by zhaoyi0113** [comment]
It is the sonar cloud action issue.

**Comment by fdx-alberto-miranda** [comment]
I have raised a PR to fix this issue in the SonarCloud GH Action, this adds proper handling of this exception:

https://github.com/SonarSource/sonarcloud-github-action/pull/58/files
