### ISSUE TITLE
Early termination of long running action runners with "Re-evaluate condition on job cancellation for step"

### ISSUE THREAD

**Issue by panbanda** [actions/runner#3134]
**Describe the bug**

When running an action that usually takes around 30m we're seeing this error consistently happen around 15-20m.  We were seeing this with hooks @ 0.5.0 but then upgraded 0.5.1 and started seeing a more helpful error message (evaluation part) so I wanted to post it here to see what could be causing this early termination?

```
##[debug]Re-evaluate condition on job cancellation for step: 'Build Android'.
##[debug]Skip Re-evaluate condition on runner shutdown.
Error: The operation was canceled.
##[debug]System.OperationCanceledException: The operation was canceled.
##[debug]   at System.Threading.CancellationToken.ThrowOperationCanceledException()
##[debug]   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.ContainerStepHost.ExecuteAsync(IExecutionContext context, String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, String standardInInput, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.ScriptHandler.RunAsync(ActionRunStage stage)
##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[debug]Finishing: Build Android
```

**To Reproduce**

I am using a runner image with the following versions:

```
# Source: https://github.com/dotnet/dotnet-docker
FROM mcr.microsoft.com/dotnet/runtime-deps:6.0-jammy as build

ARG TARGETOS=linux
ARG TARGETARCH=amd64
ARG RUNNER_VERSION=2.312.0
ARG RUNNER_CONTAINER_HOOKS_VERSION=0.5.1
ARG DOCKER_VERSION=24.0.9
ARG BUILDX_VERSION=0.12.1
```

Using gha-runner-scale-set & controller at v0.8.2

I have tried 8.0-jammy.

I also tried various memory/cpu configurations thinking it was related to https://github.com/actions/runner/issues/1546, https://github.com/actions/runner-images/discussions/7188.  We're now running the job with 64Gi available to it but still fails, so not a swap issue. At the time of the failure the fs still had 15G available, and memory for runner and dind still had 9.4GB

Here is our scale set config:

```
      runnerGroup: ${var.runner_group}
      githubConfigUrl: ${var.github_config_url}
      githubConfigSecret:
        github_token: ${var.github_token}
      maxRunners: ${var.max_runners}
      minRunners: ${var.min_runners}

      containerMode:
        type: dind

      template:
        spec:
          tolerations:
            - key: "x.com/nodegroup"
              operator: "Equal"
              value: "github-runners"
              effect: "NoSchedule"
          containers:
            - name: runner
              image: "${var.actions_runner_container}"
              command: ["/home/runner/run.sh"]
              resources:
                requests:
                  cpu: "${var.limit_cpu}"
                  # memory: "${var.limit_memory}"
```

**Expected behavior**

Completes the build process successfully

## What's not working?

Jobs that take a while don't complete and fail at random times.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by deepakjotwani15** [comment]
Facing same issue the pod abruptly get terminated for long running jobs and no proper error is displayed

**Comment by panbanda** [comment]
So we finally got to the bottom of our issue.  We thought we had enough disk space but we were using karpenter and it was only giving us 15GB ephemeral by default.  We increased it to allow multiple jobs to be working in parallel

**Comment by yourmoonlight** [comment]
> So we finally got to the bottom of our issue. We thought we had enough disk space but we were using karpenter and it was only giving us 15GB ephemeral by default. We increased it to allow multiple jobs to be working in parallel

how to find that, any logs indicates?

**Comment by deepakjotwani15** [comment]
@panbanda Can you please let us know what steps you followed for finding the issue also what steps did you take to fix it as I can see karpenter providing the nodes has 200gb of volume.

**Comment by Igor992** [comment]
👋 @panbanda we're getting the same `debug` trace on our playwright regression testing workflow. Difference is that instead of `dind` mode we use `kubernetes` one with `ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER` set to `false` as we want to run on the same runner workflow.

```
##[debug]Re-evaluate condition on job cancellation for step: 'Run playwright tests'.
Error: The operation was canceled.
##[debug]System.OperationCanceledException: The operation was canceled.
##[debug]   at System.Threading.CancellationToken.ThrowOperationCanceledException()
##[debug]   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.DefaultStepHost.ExecuteAsync(IExecutionContext context, String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, String standardInInput, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.ScriptHandler.RunAsync(ActionRunStage stage)
##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[debug]Finishing: Run playwright tests
```

Could you elaborate more on what storage type you use below on those ephemeral runner pods? We have EFS for those runners, but we stil getting those errors 🤔 

Thanks!

**Comment by MicahRCM** [comment]
@panbanda we're also getting the same debug trace during our playwright testing. Did you ever get to the bottom of what was going on?

```
##[debug]Re-evaluate condition on job cancellation for step: 'Run Playwright tests'.
Error: The operation was canceled.
##[debug]System.OperationCanceledException: The operation was canceled.
##[debug]   at System.Threading.CancellationToken.ThrowOperationCanceledException()
##[debug]   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.DefaultStepHost.ExecuteAsync(IExecutionContext context, String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, String standardInInput, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.ScriptHandler.RunAsync(ActionRunStage stage)
##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
```

**Comment by panbanda** [comment]
Trying to remember as our infra has evolved since this was posted but IIRC there were some key fixes in latest versions of runners, hooks, etc. So we built a new image with the latest stuff And then started giving it more adequate memory and things seem to work pretty well
