### ISSUE TITLE
On self-hosted runners all workflow job failures report

### ISSUE THREAD

**Issue by joshgc** [actions/runner#3178]
**Describe the bug**
When the CI job correctly returns a non-zero exit code (ie pylint find a problem) on a self-hosted runner the ContainerHookManager still requests users to contact their self-hosted runner administrator. I believe the error is coming from here https://github.com/actions/runner/blob/aa90563caecb8fcd2a1a84fc9c7833a56f6c40f4/src/Runner.Worker/Container/ContainerHooks/ContainerHookManager.cs#L177

**To Reproduce**
1. We're using the GHA helm charts in kubernetes mode
2. Run a CI job that `exit 1` inside bash
3. We get an error as in the attached screenshot (with debug logs) like 
```
Error: Error: failed to run script step: command terminated with non-zero exit code: error executing command [sh -e /__w/_temp/ccaaadc0-d72a-11ee-8141-5bd0b7d29442.sh], exit code 1
Error: Process completed with exit code 1.
Error: Executing the custom container implementation failed. Please contact your self hosted runner administrator.
```

**Expected behavior**
The ContainerHookManager should not consider a job returning non-zero exit codes an infrastructural failure. OR if there is a better way to for CI jobs to "fail" that should be better documented

## Runner Version and Platform
Using the gha-scale-set-{,controller-}0.8.2 and `ghcr.io/actions/actions-runner:2.312.0 ` all Linux

## What's not working?
![6Q3jxiaXZcXTFFH](https://github.com/actions/runner/assets/6219939/c3778472-9fba-476a-a05e-06fae6cd607e)
Please include error messages and screenshots.

## Job Log Output
Here are the debug logs of the `exit 1` job
```
##[debug]Evaluating condition for step: 'Fail on purpose'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Fail on purpose
##[debug]Loading inputs
##[debug]Loading env
Run exit 1
##[debug]Overwrite 'working-directory' base on job defaults.
##[debug]Overwrite 'shell' base on job defaults.
##[debug]bash -e -c "source /root/.bashrc && bash -e /__w/_temp/2395bb1f-561b-438f-8af4-455aa2ba153e.sh"
Run '/home/runner/k8s/index.js'
##[debug]/home/runner/externals/node16/bin/node /home/runner/k8s/index.js
This bashrc in the pyle_env_dev container will set a venv and PYTHONPATH now
##[debug]{"message":"command terminated with non-zero exit code: error executing command [sh -e /__w/_temp/6967fea0-d72c-11ee-982b-1ba0ed66fcbd.sh], exit code 1","details":{"causes":[{"reason":"ExitCode","message":"1"}]}}
##[debug]execPodStep failed: "command terminated with non-zero exit code: error executing command [sh -e /__w/_temp/6967fea0-d72c-11ee-982b-1ba0ed66fcbd.sh], exit code 1"
Error: Error: failed to run script step: command terminated with non-zero exit code: error executing command [sh -e /__w/_temp/6967fea0-d72c-11ee-982b-1ba0ed66fcbd.sh], exit code 1
Error: Process completed with exit code 1.
Error: Executing the custom container implementation failed. Please contact your self hosted runner administrator.
##[debug]System.Exception: Executing the custom container implementation failed. Please contact your self hosted runner administrator.
##[debug] ---> System.Exception: The hook script at '/home/runner/k8s/index.js' running command 'RunScriptStep' did not execute successfully
##[debug]   at GitHub.Runner.Worker.Container.ContainerHooks.ContainerHookManager.ExecuteHookScript[T](IExecutionContext context, HookInput input, ActionRunStage stage, String prependPath)
##[debug]   --- End of inner exception stack trace ---
##[debug]   at GitHub.Runner.Worker.Container.ContainerHooks.ContainerHookManager.ExecuteHookScript[T](IExecutionContext context, HookInput input, ActionRunStage stage, String prependPath)
##[debug]   at GitHub.Runner.Worker.Container.ContainerHooks.ContainerHookManager.RunScriptStepAsync(IExecutionContext context, ContainerInfo container, String workingDirectory, String entryPoint, String entryPointArgs, IDictionary`2 environmentVariables, String prependPath)
##[debug]   at GitHub.Runner.Worker.Handlers.ContainerStepHost.ExecuteAsync(IExecutionContext context, String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, String standardInInput, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.ScriptHandler.RunAsync(ActionRunStage stage)
##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[debug]Finishing: Fail on purpose
```

## Runner and Worker's Diagnostic Logs
I *think* the above covers all the involved logic.

**Comment by austinpray-mixpanel** [comment]
I'm seeing this too using the k8s hook running the 0.11.0 controller + runners at ghcr-io/ghcr.io/actions/actions-runner:2.323.0

![image](https://github.com/user-attachments/assets/6a6d7705-5e4e-4613-b1e8-293bca7416cd)

Sort of blocking our wider rollout because this is definitely gonna cause a flood of tickets to our platform eng team

**Comment by aaronthebaron** [comment]
Definitely still have this issue on runner version 2.332.0 running in K8s mode.
