### ISSUE TITLE
When action repository contains a broken symbolic link, "Set up job" stage will fail

### ISSUE THREAD

**Issue by RadxaYuntian** [actions/runner#3234]
**Describe the bug**
My repository contains other parts of code (unrelated to the action itself) which depends on a git submodule. A symbolic link is created referencing files within this submodule, which when unchecked-out is pointing to a non existent path.

When action tried to download my repository, it won't download the submodule, and causing the action to fail due to broken link.

**To Reproduce**
1. Add a broken symbolic link to an action repo
2. Run workflow using this action
3. See error

**Expected behavior**
For me the broken symbolic link is there by the nature of git submodule and is actually by design, but I understand that changing this will be a breaking change for existing users.

I'd like to see if there is more flexibility to handle this issue (Download submodules? Ignore broken symlink error?) on action writer's end. Though this might be an chicken & egg issue where only after action is downloaded can `runner` process its settings.

## Runner Version and Platform

```
Current runner version: '2.315.0'
Operating System
  Ubuntu
  22.04.4
  LTS
```

## What's not working?
See log below.

## Job Log Output
```
Download action repository 'RadxaOS-SDK/rsdk@main' (SHA:2c1cb39fa7900103f1650d650964361da91f328f)
##[debug]Download 'https://api.github.com/repos/RadxaOS-SDK/rsdk/tarball/2c1cb39fa7900103f1650d650964361da91f328f' to '/home/runner/work/_actions/_temp_88b61f92-0701-4cb5-8354-d8c3d89d1c2e/763e3eae-d30e-400c-bc18-163c19a7d050.tar.gz'
##[debug]Unwrap 'RadxaOS-SDK-rsdk-2c1cb39' to '/home/runner/work/_actions/RadxaOS-SDK/rsdk/main'
Error: Could not find file '/home/runner/work/_actions/_temp_88b61f92-0701-4cb5-8354-d8c3d89d1c2e/_staging/RadxaOS-SDK-rsdk-2c1cb39/src/lib/librtui/tui.sh'.
##[debug]System.IO.FileNotFoundException: Could not find file '/home/runner/work/_actions/_temp_88b61f92-0701-4cb5-8354-d8c3d89d1c2e/_staging/RadxaOS-SDK-rsdk-2c1cb39/src/lib/librtui/tui.sh'.
##[debug]File name: '/home/runner/work/_actions/_temp_88b61f92-0701-4cb5-8354-d8c3d89d1c2e/_staging/RadxaOS-SDK-rsdk-2c1cb39/src/lib/librtui/tui.sh'
##[debug]   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
##[debug]   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
##[debug]   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
##[debug]   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
##[debug]   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
##[debug]   at GitHub.Runner.Sdk.IOUtil.CopyDirectory(String source, String target, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Sdk.IOUtil.CopyDirectory(String source, String target, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Sdk.IOUtil.CopyDirectory(String source, String target, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Sdk.IOUtil.CopyDirectory(String source, String target, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.ActionManager.DownloadRepositoryActionAsync(IExecutionContext executionContext, ActionDownloadInfo downloadInfo)
##[debug]   at GitHub.Runner.Worker.ActionManager.PrepareActionsRecursiveAsync(IExecutionContext executionContext, PrepareActionsState state, IEnumerable`1 actions, Int32 depth, Guid parentStepId)
##[debug]   at GitHub.Runner.Worker.ActionManager.PrepareActionsAsync(IExecutionContext executionContext, IEnumerable`1 steps, Guid rootStepId)
##[debug]   at GitHub.Runner.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
##[debug]Finishing: Set up job
```

**Comment by tianon** [comment]
I haven't tested it recently, but I don't think this is fixed. Maybe someone from the team could at least glance at it before it gets auto-closed by the bot? 🫤

**Comment by black-desk** [comment]
I confirm that this issue still exists.

**Comment by black-desk** [comment]
I tried to fix this and submitted a PR: #3914

I don't have any C# development experience, so it would be a pleasure if someone could help review my changes.

**Comment by serpro69** [comment]
Any chance this could be fixed soon? Facing the same issue

**Comment by bigwheel** [comment]
@black-desk I appreciate your persistent efforts. I also wish to solve this problem.
