### ISSUE TITLE
Runner not able to configure itself using a custom image based on official image

### ISSUE THREAD

**Issue by arslan-autoscout24** [actions/runner#3287]
**Describe the bug**
Runner fails with error "WRITE ERROR: An error occurred: Not configured."

**To Reproduce**
1. Create a new docker image
Dockerfile:
`FROM ghcr.io/actions/actions-runner:latest`
Build command: 
`docker build -t github-runners/base:7 --platform "linux/amd64" --build-arg="RUNNER_VERSION=2.316.1"   -f Dockerfile .`
2. Use the image in values.yaml
```
spec:
    containers:
      - name: runner-name
        image: ghcr.io/<org>/github-runners/base:7
        command: ["/home/runner/run.sh"]

```
3. Modify the job to use the custom runner and execute
4. Error log in pod
```
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] No proxy settings were found based on environmental variables (http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY)
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known directory 'Root': '/home/runner'
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known config file 'Credentials': '/home/runner/.credentials'
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known directory 'Root': '/home/runner'
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known config file 'Runner': '/home/runner/.runner'
[RUNNER 2024-05-15 17:14:42Z INFO Listener] Runner is built for Linux (X64) - linux-x64.
[RUNNER 2024-05-15 17:14:42Z INFO Listener] RuntimeInformation: Linux 5.10.213-201.855.amzn2.x86_64 #1 SMP Mon Mar 25 18:16:11 UTC 2024.
[RUNNER 2024-05-15 17:14:42Z INFO Listener] Version: 2.316.1
[RUNNER 2024-05-15 17:14:42Z INFO Listener] Commit: 9ac138d10eac15c71493f004f1b1bc919ead40de
[RUNNER 2024-05-15 17:14:42Z INFO Listener] Culture: 
[RUNNER 2024-05-15 17:14:42Z INFO Listener] UI Culture: 
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known directory 'Root': '/home/runner'
[RUNNER 2024-05-15 17:14:42Z INFO Listener] Validating directory permissions for: '/home/runner'
[RUNNER 2024-05-15 17:14:42Z INFO CommandLineParser] Parse
[RUNNER 2024-05-15 17:14:42Z INFO CommandLineParser] Parsing 1 args
[RUNNER 2024-05-15 17:14:42Z INFO CommandLineParser] parsing argument
[RUNNER 2024-05-15 17:14:42Z INFO CommandLineParser] HasArgs: False
[RUNNER 2024-05-15 17:14:42Z INFO CommandLineParser] Adding Command: run
[RUNNER 2024-05-15 17:14:42Z INFO Listener] Arguments parsed
[RUNNER 2024-05-15 17:14:42Z INFO Runner] ExecuteCommand
[RUNNER 2024-05-15 17:14:42Z INFO ConfigurationStore] currentAssemblyLocation: /home/runner/bin/Runner.Listener.dll
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[RUNNER 2024-05-15 17:14:42Z INFO ConfigurationStore] binPath: /home/runner/bin
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known directory 'Root': '/home/runner'
[RUNNER 2024-05-15 17:14:42Z INFO ConfigurationStore] RootFolder: /home/runner
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known directory 'Root': '/home/runner'
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known config file 'Runner': '/home/runner/.runner'
[RUNNER 2024-05-15 17:14:42Z INFO ConfigurationStore] ConfigFilePath: /home/runner/.runner
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known directory 'Root': '/home/runner'
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known config file 'Credentials': '/home/runner/.credentials'
[RUNNER 2024-05-15 17:14:42Z INFO ConfigurationStore] CredFilePath: /home/runner/.credentials
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known directory 'Root': '/home/runner'
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known config file 'MigratedCredentials': '/home/runner/.credentials_migrated'
[RUNNER 2024-05-15 17:14:42Z INFO ConfigurationStore] MigratedCredFilePath: /home/runner/.credentials_migrated
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known directory 'Root': '/home/runner'
[RUNNER 2024-05-15 17:14:42Z INFO HostContext] Well known config file 'Service': '/home/runner/.service'
[RUNNER 2024-05-15 17:14:42Z INFO ConfigurationStore] ServiceConfigFilePath: /home/runner/.service
[RUNNER 2024-05-15 17:14:42Z INFO CommandSettings] Flag 'help': 'False'
[RUNNER 2024-05-15 17:14:42Z INFO CommandSettings] Flag 'version': 'False'
[RUNNER 2024-05-15 17:14:42Z INFO CommandSettings] Flag 'commit': 'False'
[RUNNER 2024-05-15 17:14:42Z INFO CommandSettings] Flag 'check': 'False'
[RUNNER 2024-05-15 17:14:42Z INFO CommandSettings] Command 'configure': 'False'
[RUNNER 2024-05-15 17:14:42Z INFO CommandSettings] Command 'remove': 'False'
[RUNNER 2024-05-15 17:14:42Z INFO CommandSettings] Command 'warmup': 'False'
[RUNNER 2024-05-15 17:14:42Z INFO ConfigurationManager] LoadSettings
[RUNNER 2024-05-15 17:14:42Z INFO ConfigurationStore] IsConfigured()
[RUNNER 2024-05-15 17:14:42Z INFO ConfigurationStore] IsConfigured: False
[RUNNER 2024-05-15 17:14:42Z INFO ConfigurationManager] Is configured: False
[RUNNER 2024-05-15 17:14:42Z ERR  Terminal] WRITE ERROR: An error occurred: Not configured. Run config.(sh/cmd) to configure the runner.
An error occurred: Not configured. Run config.(sh/cmd) to configure the runner.
[RUNNER 2024-05-15 17:14:42Z ERR  Listener] GitHub.Runner.Common.NonRetryableException: Not configured. Run config.(sh/cmd) to configure the runner.
[RUNNER 2024-05-15 17:14:42Z ERR  Listener]    at GitHub.Runner.Listener.Configuration.ConfigurationManager.LoadSettings()
[RUNNER 2024-05-15 17:14:42Z ERR  Listener]    at GitHub.Runner.Listener.Runner.ExecuteCommand(CommandSettings command)
[RUNNER 2024-05-15 17:14:42Z ERR  Listener]    at GitHub.Runner.Listener.Program.MainAsync(IHostContext context, String[] args)
Runner listener exit with terminated error, stop the service, no retry needed.
Exiting runner...
```

**Expected behavior**
Using the custom built image works 

## Runner Version and Platform
2.316.1
Kubernetes

OS of the machine running the runner? 
Linux

**Comment by arslan-autoscout24** [comment]
> Changing the container name to:
> 
> > * name: runner
> 
> Should fix the issue.

This actually worked. Many thanks.
