### ISSUE TITLE
When workflow was triggered , it failed multiple times with message - "The operation was canceled."

### ISSUE THREAD

**Issue by shriyakk** [actions/runner#3400]
**Describe the bug**
When reusable workflow is triggered on self hosted runner, the workflow suddenly fails with the Error message - The operation was canceled.
<img width="199" alt="image" src="https://github.com/user-attachments/assets/25931a99-3953-4a9e-ae8c-5fb8b1a1d418">

The workflow was working fine and suddenly I have started facing this issue.

**To Reproduce**
1. Go to Settings , setup the Linux runner (self-hosted). Run ./svc.sh service.
2. Go to Actions and run the workflow.
3. After sometime this issue occurs.

**Expected behavior**
The workflow should execute without any cancellations.

## Runner Version and Platform
Self hosted runner.
OS : Ubuntu 20.04
Current runner version: '2.317.0'

Runner -
Image: ubuntu-22.04
Version: 20240721.1.0

OS of the machine running the runner? OSX/Windows/Linux/...
Linux - Ubuntu 
## What's not working?
<img width="658" alt="image" src="https://github.com/user-attachments/assets/2f574e84-59d5-4094-a054-f032029c95d2">

## Job Log Output
2024-07-25T10:37:00.6701922Z Current runner version: '2.317.0'
2024-07-25T10:37:00.6710011Z Runner name: 'desktop'
2024-07-25T10:37:00.6710660Z Runner group name: 'Install'
2024-07-25T10:37:00.6711588Z Machine name: 'test-ThinkCentre-M92p'
2024-07-25T10:37:00.6714956Z ##[group]GITHUB_TOKEN Permissions
2024-07-25T10:37:00.6716863Z Contents: read
2024-07-25T10:37:00.6717285Z Metadata: read
2024-07-25T10:37:00.6717679Z ##[endgroup]
2024-07-25T10:37:00.6721414Z Secret source: Actions
2024-07-25T10:37:00.6722034Z Prepare workflow directory
2024-07-25T10:37:00.8562692Z ##[error]The operation was canceled.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by shriyakk** [comment]
Also sharing log snippet where the Operation was canceled again.

-------------------
2024-07-26T10:24:08.0232876Z ##[error]The operation was canceled.
2024-07-26T10:24:08.0243900Z ##[debug]System.OperationCanceledException: The operation was canceled.
2024-07-26T10:24:08.0245339Z ##[debug]   at System.Threading.CancellationToken.ThrowOperationCanceledException()
2024-07-26T10:24:08.0248134Z ##[debug]   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
2024-07-26T10:24:08.0252629Z ##[debug]   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
2024-07-26T10:24:08.0257000Z ##[debug]   at GitHub.Runner.Worker.Handlers.DefaultStepHost.ExecuteAsync(IExecutionContext context, String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, String standardInInput, CancellationToken cancellationToken)
2024-07-26T10:24:08.0259619Z ##[debug]   at GitHub.Runner.Worker.Handlers.ScriptHandler.RunAsync(ActionRunStage stage)
2024-07-26T10:24:08.0260505Z ##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
2024-07-26T10:24:08.0261509Z ##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2024-07-26T10:24:08.0263189Z ##[debug]Finishing: Current workspace
2024-07-26T10:24:08.0285048Z ##[debug]Evaluating condition for step: 'Run actions/upload-artifact@v3'
2024-07-26T10:24:08.0286688Z ##[debug]Evaluating: success()
2024-07-26T10:24:08.0287219Z ##[debug]Evaluating success:
2024-07-26T10:24:08.0287885Z ##[debug]=> false
-----------------------------
