### ISSUE TITLE
fromJSON / OUTPUT file regression: The template is not valid. Newtonsoft.Json.JsonReaderException: Error reading JToken from JsonReade

### ISSUE THREAD

**Issue by ForbesLindesay** [actions/runner#3417]
## Runner Version and Platform

Default hosted GitHub runner for `ubuntu-latest`

## What's not working?

An error occurs when attempting to run a step with the condition:

```yaml
if: ${{ fromJSON(steps.my_step.outputs.my_output_variable) }}
```

The output is set using node.js with the following code:

```js
appendFileSync(
  process.env.GITHUB_OUTPUT,
  `my_output_variable=${JSON.stringify(value)}\n`
)
```

where `value` is either `true` or `false`.

This started failing intermittently on 2024-08-01 and now appears to fail almost every time.

My current theory is that GitHub somehow things that `true` is a secret within our repository, so it's attempting to obfuscate that/strip it from the output before parsing it as JSON.

## Job Log Output

```
Error: The template is not valid. Newtonsoft.Json.JsonReaderException: Error reading JToken from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader)
   at GitHub.DistributedTask.Expressions[2](https://github.com/Mavenoid/troubleshooter/actions/runs/10247184504/job/28345888607#step:10:2).Sdk.Functions.FromJson.EvaluateCore(EvaluationContext context, ResultMemory& resultMemory)
   at GitHub.DistributedTask.Expressions2.Sdk.ExpressionNode.Evaluate(EvaluationContext context)
   at GitHub.DistributedTask.Expressions2.Sdk.Operators.And.EvaluateCore(EvaluationContext context, ResultMemory& resultMemory)
   at GitHub.DistributedTask.Expressions2.Sdk.ExpressionNode.Evaluate(EvaluationContext context)
   at GitHub.DistributedTask.Expressions2.Sdk.ExpressionNode.GitHub.DistributedTask.Expressions2.IExpressionNode.Evaluate(ITraceWriter trace, ISecretMasker secretMasker, Object state, EvaluationOptions options)
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateToken.EvaluateTemplateToken(TemplateContext context, String expression, Int[3](https://github.com/Mavenoid/troubleshooter/actions/runs/10247184504/job/28345888607#step:10:3)2& bytes)
   at GitHub.DistributedTask.ObjectTemplating.Tokens.BasicExpressionToken.EvaluateTemplateToken(TemplateContext context, Int32& bytes)
   at GitHub.DistributedTask.ObjectTemplating.TemplateUnraveler.RootBasicExpression()
```

**Comment by ForbesLindesay** [comment]
Actually, I think this might be being caused by https://github.com/actions/runner-images/issues/9692
