### ISSUE TITLE
self-hosted runner NOT coming online with OS SLES15 (suse)

### ISSUE THREAD

**Issue by koteswara-kelam** [actions/runner#3434]
**Describe the bug**
Added a SLES15 VM as runner.
Run "sudo ./svc.sh install"
Run "sudo ./svc.sh start" but failed with access denied error.

Tried following commands:
sudo chcon system_u:object_r:usr_t:s0 ./svc.sh
sudo chcon system_u:object_r:usr_t:s0 ./runsvc.sh

Now service started:
actions-runner> sudo ./svc.sh start

/etc/systemd/system/actions.runner.hpe-hcss-gl-gateway-prod-deploy.gl-fortcollins-k3s-master-vm2.service
● actions.runner.hpe-hcss-gl-gateway-prod-deploy.gl-fortcollins-k3s-master-vm2.service - GitHub Actions Runner (hpe-hcss-gl-gateway-prod-deploy.gl-fortcollins-k3s-master-vm2)
     Loaded: loaded (/etc/systemd/system/actions.runner.hpe-hcss-gl-gateway-prod-deploy.gl-fortcollins-k3s-master-vm2.service; enabled; vendor preset: disabled)
     Active: active (running) since Mon 2024-08-19 05:05:20 MDT; 8ms ago
   Main PID: 13034 (runsvc.sh)
      Tasks: 7
     CGroup: /system.slice/actions.runner.hpe-hcss-gl-gateway-prod-deploy.gl-fortcollins-k3s-master-vm2.service
             ├─13034 /bin/bash /home/hpemon/actions-runner/runsvc.sh
             └─13044 ./externals/node16/bin/node ./bin/RunnerService.js

Aug 19 05:05:20 gl-fortcollins-k3s-master-vm2 systemd[1]: Started GitHub Actions Runner (hpe-hcss-gl-gateway-prod-depl…r-vm2).
Aug 19 05:05:20 gl-fortcollins-k3s-master-vm2 runsvc.sh[13034]: .path=/usr/local/bin:/bin:/usr/bin ENV_ROOTPATH /usr/lo…sr/bin
Hint: Some lines were ellipsized, use -l to show in full.

But I see runner steill OFFLINE in gihub repo.

**Comment by koteswara-kelam** [comment]
I used actions-runner-linux-x64-2.319.1.tar.gz

Tried on ubuntu vm as runner and same issue. service is in RUNNING state but runner is OFFLINE in github repo.

**Comment by koteswara-kelam** [comment]
LOGS:
-----------------
/actions-runner> tail -f _diag/Runner_20240819-132306-utc.log
[2024-08-19 13:29:07Z ERR  RunnerServer] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[2024-08-19 13:29:07Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2024-08-19 13:29:07Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2024-08-19 13:29:19Z WARN GitHubActionsService] Attempt 1 of GET request to https://pipelinesghubeus10.actions.githubusercontent.com/O6KnTHLaKpnpi2Yi9JU5Zv3WKBG34NGnTGvhpJbd5bFFclnEMv/_apis/connectionData?connectOptions=0&lastChangeId=4345859&lastChangeId64=4345859 failed (Socket Error: TimedOut). The operation will be retried in 11.147 seconds.

[2024-08-19 13:30:07Z WARN GitHubActionsService] GET request to https://pipelinesghubeus10.actions.githubusercontent.com/O6KnTHLaKpnpi2Yi9JU5Zv3WKBG34NGnTGvhpJbd5bFFclnEMv/_apis/connectionData?connectOptions=0&lastChangeId=4345859&lastChangeId64=4345859 timed out after 60 seconds.
[2024-08-19 13:30:07Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2024-08-19 13:30:07Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2024-08-19 13:30:07Z WARN GitHubActionsService] GET request to https://pipelinesghubeus10.actions.githubusercontent.com/O6KnTHLaKpnpi2Yi9JU5Zv3WKBG34NGnTGvhpJbd5bFFclnEMv/_apis/connectionData?connectOptions=0&lastChangeId=4345859&lastChangeId64=4345859 timed out after 60 seconds.
[2024-08-19 13:30:07Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2024-08-19 13:30:07Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
