### ISSUE TITLE
Recent instabilities with our self-hosted runners (2.319.1)

### ISSUE THREAD

**Issue by Fgerthoffert** [actions/runner#3435]
**Describe the bug**
Over the past few weeks, we've been facing a random issue with our self-hosted ephemeral runners (currently running 2.319.1).

This is relatively recent and random. 
No changes were made to our ephemeral runners' infrastructure.

I'm going to update this ticket as we keep investigating, the point of creating it early is to check whether others are also facing something similar.

**To Reproduce**

We haven't been able to identify a clear reproduction scenario, but typically the runner (we're using https://philips-labs.github.io/terraform-aws-github-runner/) gets abruptly shut-down while a job is running.

In the GitHub Actions UI, the job still appears to be running (although it does not move to the next step) although the runner that was executing the job is terminated. 

The runners being ephemeral (and random) makes it difficult for us to collect additional logs/data after a failure.

## Runner Version and Platform
Version of your runner: 2.319.1
OS: Linux ip-10-0-2-32 5.15.0-1028-aws #32-Ubuntu SMP Mon Jan 9 12:28:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

## What's not working?
The runner appears to "crash" while executing a job.

## Job Log Output

I haven't been able to pinpoint actual errors in the logs.

```
The self-hosted runner: i-099b4df706b2777b0 lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```

At other times we would see an interrupted job in the UI:
<img width="1156" alt="Screenshot 2024-08-21 at 16 29 46" src="https://github.com/user-attachments/assets/4b2f05fa-d949-45d4-93b4-688552307bc9">

Or this error when running the "jahia/jahia-modules-action/integration-tests@v2" step (which is using docker-compose):
```
  Traceback (most recent call last):
    File "urllib3/connectionpool.py", line 677, in urlopen
    File "urllib3/connectionpool.py", line 426, in _make_request
    File "<string>", line 3, in raise_from
    File "urllib3/connectionpool.py", line 421, in _make_request
    File "http/client.py", line 1369, in getresponse
    File "http/client.py", line 310, in begin
    File "http/client.py", line 271, in _read_status
    File "socket.py", line 589, in readinto
  ConnectionResetError: [Errno 104] Connection reset by peer
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "requests/adapters.py", line 449, in send
    File "urllib3/connectionpool.py", line 727, in urlopen
    File "urllib3/util/retry.py", line 410, in increment
    File "urllib3/packages/six.py", line 734, in reraise
    File "urllib3/connectionpool.py", line 677, in urlopen
    File "urllib3/connectionpool.py", line 426, in _make_request
    File "<string>", line 3, in raise_from
    File "urllib3/connectionpool.py", line 421, in _make_request
    File "http/client.py", line 1369, in getresponse
    File "http/client.py", line 310, in begin
    File "http/client.py", line 271, in _read_status
    File "socket.py", line 589, in readinto
  urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

## Runner and Worker's Diagnostic Logs
Not available yet

**Comment by noamgreen** [comment]
i can tell you i have same issues , self-hosted in K8s  OOM all the time dont understand why
