### ISSUE TITLE
`BrokerMigration message received. Polling Broker for messages...` loop. No jobs picked up.

### ISSUE THREAD

**Issue by MarcusDunn** [actions/runner#3487]
This seems to have similar symptoms to https://github.com/actions/runner/issues/3371, but the fixes that appear there do not work. I am unsure if this issue may be better suited for the ARC repo.

**Describe the bug**
`[RUNNER xx-xx-xx xx:xx:xx INFO MessageListener] BrokerMigration message received. Polling Broker for messages...` is printed in a loop. No jobs are picked up. All runners are idle.

**Runners**
(I added the label to the topmost runner to see if it would fix it. It did not)
![image](https://github.com/user-attachments/assets/99ab4730-1294-4d47-b3fb-becfab9d69c6)

**Workflow**
![image](https://github.com/user-attachments/assets/5387b22d-c082-4691-9d99-8a80cfa6176c)

**Logs**
<details>
<summary>Full Runner Logs</summary>
<pre>
[2024-10-03 22:37:48Z INFO HostContext] No proxy settings were found based on environmental variables (http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY)
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Root': '/home/runner'
[2024-10-03 22:37:48Z INFO HostContext] Well known config file 'Credentials': '/home/runner/.credentials'
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Root': '/home/runner'
[2024-10-03 22:37:48Z INFO HostContext] Well known config file 'Runner': '/home/runner/.runner'
[2024-10-03 22:37:48Z INFO HostContext] Adding extra user agent 'actions-runner-controller/0.9.3' to all HTTP requests.
[2024-10-03 22:37:48Z INFO Listener] Runner is built for Linux (X64) - linux-x64.
[2024-10-03 22:37:48Z INFO Listener] RuntimeInformation: Linux 6.8.9-100.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu May  2 18:50:49 UTC 2024.
[2024-10-03 22:37:48Z INFO Listener] Version: 2.320.0
[2024-10-03 22:37:48Z INFO Listener] Commit: 78f21670b4a58aff19b5189207f54eb2bee324d1
[2024-10-03 22:37:48Z INFO Listener] Culture: 
[2024-10-03 22:37:48Z INFO Listener] UI Culture: 
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Root': '/home/runner'
[2024-10-03 22:37:48Z INFO Listener] Validating directory permissions for: '/home/runner'
[2024-10-03 22:37:48Z INFO CommandLineParser] Parse
[2024-10-03 22:37:48Z INFO CommandLineParser] Parsing 1 args
[2024-10-03 22:37:48Z INFO CommandLineParser] parsing argument
[2024-10-03 22:37:48Z INFO CommandLineParser] HasArgs: False
[2024-10-03 22:37:48Z INFO CommandLineParser] Adding Command: run
[2024-10-03 22:37:48Z INFO CommandSettings] Removing env var: 'ACTIONS_RUNNER_INPUT_JITCONFIG'
[2024-10-03 22:37:48Z INFO Listener] Arguments parsed
[2024-10-03 22:37:48Z INFO Runner] ExecuteCommand
[2024-10-03 22:37:48Z INFO ConfigurationStore] currentAssemblyLocation: /home/runner/bin/Runner.Listener.dll
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[2024-10-03 22:37:48Z INFO ConfigurationStore] binPath: /home/runner/bin
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Root': '/home/runner'
[2024-10-03 22:37:48Z INFO ConfigurationStore] RootFolder: /home/runner
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Root': '/home/runner'
[2024-10-03 22:37:48Z INFO HostContext] Well known config file 'Runner': '/home/runner/.runner'
[2024-10-03 22:37:48Z INFO ConfigurationStore] ConfigFilePath: /home/runner/.runner
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Root': '/home/runner'
[2024-10-03 22:37:48Z INFO HostContext] Well known config file 'Credentials': '/home/runner/.credentials'
[2024-10-03 22:37:48Z INFO ConfigurationStore] CredFilePath: /home/runner/.credentials
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Root': '/home/runner'
[2024-10-03 22:37:48Z INFO HostContext] Well known config file 'MigratedCredentials': '/home/runner/.credentials_migrated'
[2024-10-03 22:37:48Z INFO ConfigurationStore] MigratedCredFilePath: /home/runner/.credentials_migrated
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Root': '/home/runner'
[2024-10-03 22:37:48Z INFO HostContext] Well known config file 'Service': '/home/runner/.service'
[2024-10-03 22:37:48Z INFO ConfigurationStore] ServiceConfigFilePath: /home/runner/.service
[2024-10-03 22:37:48Z INFO CommandSettings] Flag 'help': 'False'
[2024-10-03 22:37:48Z INFO CommandSettings] Flag 'version': 'False'
[2024-10-03 22:37:48Z INFO CommandSettings] Flag 'commit': 'False'
[2024-10-03 22:37:48Z INFO CommandSettings] Flag 'check': 'False'
[2024-10-03 22:37:48Z INFO CommandSettings] Command 'configure': 'False'
[2024-10-03 22:37:48Z INFO CommandSettings] Command 'remove': 'False'
[2024-10-03 22:37:48Z INFO CommandSettings] Command 'warmup': 'False'
[2024-10-03 22:37:48Z INFO CommandSettings] Env arg 'jitconfig': '***'
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Root': '/home/runner'
[2024-10-03 22:37:48Z INFO Runner] Saved 353 bytes to '/home/runner/.runner'.
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Root': '/home/runner'
[2024-10-03 22:37:48Z INFO Runner] Saved 225 bytes to '/home/runner/.credentials'.
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Root': '/home/runner'
[2024-10-03 22:37:48Z INFO Runner] Saved 1631 bytes to '/home/runner/.credentials_rsaparams'.
[2024-10-03 22:37:48Z INFO HostContext] No proxy settings were found based on environmental variables (http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY)
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Root': '/home/runner'
[2024-10-03 22:37:48Z INFO HostContext] Well known config file 'Credentials': '/home/runner/.credentials'
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Root': '/home/runner'
[2024-10-03 22:37:48Z INFO HostContext] Well known config file 'Runner': '/home/runner/.runner'
[2024-10-03 22:37:48Z INFO HostContext] Adding extra user agent 'actions-runner-controller/0.9.3' to all HTTP requests.
[2024-10-03 22:37:48Z INFO ConfigurationManager] LoadSettings
[2024-10-03 22:37:48Z INFO ConfigurationStore] IsConfigured()
[2024-10-03 22:37:48Z INFO ConfigurationStore] IsConfigured: True
[2024-10-03 22:37:48Z INFO ConfigurationManager] Is configured: True
[2024-10-03 22:37:48Z INFO ConfigurationStore] Read setting file: 353 chars
[2024-10-03 22:37:48Z INFO ConfigurationManager] Settings Loaded
[2024-10-03 22:37:48Z INFO ConfigurationStore] IsServiceConfigured()
[2024-10-03 22:37:48Z INFO ConfigurationStore] IsServiceConfigured: False
[2024-10-03 22:37:48Z INFO CommandSettings] Command 'run': 'True'
[2024-10-03 22:37:48Z INFO ConfigurationStore] IsConfigured()
[2024-10-03 22:37:48Z INFO ConfigurationStore] IsConfigured: True
[2024-10-03 22:37:48Z INFO ConfigurationManager] Is configured: True
[2024-10-03 22:37:48Z INFO Runner] Could not parse the argument value '' for StartupType. Defaulting to Manual
[2024-10-03 22:37:48Z INFO Runner] Set runner startup type - Manual
[2024-10-03 22:37:48Z INFO CommandSettings] Flag 'once': 'False'
[2024-10-03 22:37:48Z INFO CommandSettings] Flag 'once': 'False'
[2024-10-03 22:37:48Z INFO Runner] RunAsync
[2024-10-03 22:37:48Z INFO ConfigurationManager] LoadSettings
[2024-10-03 22:37:48Z INFO ConfigurationStore] IsConfigured()
[2024-10-03 22:37:48Z INFO ConfigurationStore] IsConfigured: True
[2024-10-03 22:37:48Z INFO ConfigurationManager] Is configured: True
[2024-10-03 22:37:48Z INFO ConfigurationManager] Settings Loaded
[2024-10-03 22:37:48Z INFO MessageListener] {
  "AgentId": 503,
  "AgentName": "gha-runner-scale-set-kzpmc-runner-52m65",
  "PoolId": 7,
  "DisableUpdate": true,
  "Ephemeral": true,
  "ServerUrl": "https://pipelinesghubeus11.actions.githubusercontent.com/o1MxI6JFwQuueWtdkIhXQK0SKyNG1HbUEQh6sqzs6dAZETOp58/",
  "WorkFolder": "_work"
}
[2024-10-03 22:37:48Z INFO MessageListener] Loading Credentials
[2024-10-03 22:37:48Z INFO ConfigurationStore] HasCredentials()
[2024-10-03 22:37:48Z INFO ConfigurationStore] stored True
[2024-10-03 22:37:48Z INFO CredentialManager] GetCredentialProvider
[2024-10-03 22:37:48Z INFO CredentialManager] Creating type OAuth
[2024-10-03 22:37:48Z INFO CredentialManager] Creating credential type: OAuth
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Bin': '/home/runner/bin'
[2024-10-03 22:37:48Z INFO HostContext] Well known directory 'Root': '/home/runner'
[2024-10-03 22:37:48Z INFO HostContext] Well known config file 'RSACredentials': '/home/runner/.credentials_rsaparams'
[2024-10-03 22:37:48Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/runner/.credentials_rsaparams
[2024-10-03 22:37:48Z INFO MessageListener] Attempt to create session.
[2024-10-03 22:37:48Z INFO MessageListener] Connecting to the Runner Server...
[2024-10-03 22:37:48Z INFO RunnerServer] EstablishVssConnection
[2024-10-03 22:37:48Z INFO RunnerServer] Establish connection with 100 seconds timeout.
[2024-10-03 22:37:48Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2024-10-03 22:37:48Z INFO RunnerServer] EstablishVssConnection
[2024-10-03 22:37:48Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2024-10-03 22:37:48Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2024-10-03 22:37:48Z INFO RunnerServer] EstablishVssConnection
[2024-10-03 22:37:48Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2024-10-03 22:37:48Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2024-10-03 22:37:49Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2024-10-03 22:37:49Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2024-10-03 22:37:49Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2024-10-03 22:37:50Z INFO MessageListener] VssConnection created
[2024-10-03 22:37:50Z INFO Terminal] WRITE LINE: 
[2024-10-03 22:37:50Z INFO Terminal] WRITE LINE: 
[2024-10-03 22:37:50Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/runner/.credentials_rsaparams
[2024-10-03 22:37:50Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/runner/.credentials_rsaparams
[2024-10-03 22:37:51Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
[2024-10-03 22:37:51Z INFO MessageListener] Session created.
[2024-10-03 22:37:51Z INFO Terminal] WRITE LINE: Current runner version: '2.320.0'
[2024-10-03 22:37:51Z INFO Terminal] WRITE LINE: 2024-10-03 22:37:51Z: Listening for Jobs
[2024-10-03 22:37:51Z INFO JobDispatcher] Set runner/worker IPC timeout to 30 seconds.
[2024-10-03 22:37:51Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[2024-10-03 22:37:51Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/runner/.credentials_rsaparams
[2024-10-03 22:37:51Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
[2024-10-03 22:38:42Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[2024-10-03 22:39:32Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[2024-10-03 22:40:22Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[2024-10-03 22:41:12Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[2024-10-03 22:42:03Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[2024-10-03 22:42:53Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[2024-10-03 22:43:43Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[2024-10-03 22:44:33Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[2024-10-03 22:45:24Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[2024-10-03 22:46:14Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[2024-10-03 22:47:04Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
</pre>
</details>

**To Reproduce**
Setup ARC 0.9.3 with the following scale-set `values.yaml`
```yaml
        minRunners: 5
        maxRunners: 25
        githubConfigSecret: pre-defined-secret
        githubConfigUrl: https://github.com/utilityai
        runnerGroup: "Seymour"
        controllerServiceAccount:
          namespace: arc-systems
          name: actions-runner-controller-gha-rs-controller
```

**Expected behavior**
Jobs should be picked up.

## Runner Version and Platform
`ghcr.io/actions/actions-runner@sha256:8de989a63c2dad8aeb7c44b70f86189d148f887cbd917ecbe83879df54bf6590`

**Comment by luketomlinson** [comment]
Hey @MarcusDunn, can you verify that the `Seymour` runner group has the appropriate repos selected?

**Comment by MarcusDunn** [comment]
yes it does.

**Comment by luketomlinson** [comment]
Thanks @MarcusDunn. A couple more things. Can you show a snippet of what the `runs-on` yaml looks like for that job? I am wondering if there's some leading whitespace for the `gha-runner-scale-set` label. Also, can you remove the explicit label from the `-grpkv` runner? Scale Set runners are typically supposed to to not have labels.

**Comment by MarcusDunn** [comment]
It was the whitespace. Thank you so much, I cannot image how much time you saved me.

**Comment by rekha-prakash-maersk** [comment]
Hi @luketomlinson , we ran into the same issue today on **ARC 0.9.3** and runner version 2.320.0. The runners were continuously emitting below logs for **more than 6 hours**, but they were marked as idle on UI. No new jobs picked up. I had to remove the runners from the UI and then they got terminated in cluster. 

after termination, the new jobs to be picked up. 

```text
[RUNNER 2024-11-14 11:55:36Z INFO Terminal] WRITE LINE: Current runner version: '2.320.0'
Current runner version: '2.320.0'
[RUNNER 2024-11-14 11:55:36Z INFO Terminal] WRITE LINE: 2024-11-14 11:55:36Z: Listening for Jobs
2024-11-14 11:55:36Z: Listening for Jobs
[RUNNER 2024-11-14 11:55:36Z INFO JobDispatcher] Set runner/worker IPC timeout to 30 seconds.
[RUNNER 2024-11-14 11:55:36Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 11:55:36Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/runner/.credentials_rsaparams
[RUNNER 2024-11-14 11:55:36Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
[RUNNER 2024-11-14 11:56:27Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 11:57:17Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 11:58:07Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 11:58:57Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 11:59:47Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 12:00:37Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 12:01:28Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 12:02:18Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 12:03:08Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 12:03:58Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 12:04:48Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 12:05:38Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 12:06:29Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 12:07:19Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 12:08:09Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 12:08:59Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 12:09:49Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 12:10:40Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 12:11:30Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 12:12:20Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 12:13:10Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
[RUNNER 2024-11-14 12:14:00Z INFO MessageListener] BrokerMigration message received. Polling Broker for messages...
```


here is my scaleset values.yaml file,

```

maxRunners: 100

minRunners: 1

runnerGroup: "ubuntu-latest-prod"

runnerScaleSetName: "ubuntu-latest-self-host"
```

**Comment by emmanuelstroem** [comment]
@rekha-prakash-maersk 

I can confirm that manually terminating the runners from the UI got created new working ones. 

We had this other error stack trace though.

```
[RUNNER 2024-11-14 19:23:31Z INFO Terminal] WRITE LINE: Current runner version: '2.321.0'
Current runner version: '2.321.0'   
[RUNNER 2024-11-14 19:23:31Z INFO Terminal] WRITE LINE: 2024-11-14 19:23:31Z: Listening for Jobs
2024-11-14 19:23:31Z: Listening for Jobs
[RUNNER 2024-11-14 19:23:31Z INFO JobDispatcher] Set runner/worker IPC timeout to 30 seconds.
[RUNNER 2024-11-14 19:23:31Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/runner/.credentials_rsaparams
[RUNNER 2024-11-14 19:23:32Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
[RUNNER 2024-11-14 19:23:32Z ERR  GitHubActionsService] GET request to https://broker.actions.githubusercontent.com/message?sessionId=alpha-numeric-session-id-here&status=Online&runnerVersion=2.321.0&os=Linux&architecture=X64&disableUpdate=false failed. HTTP Status: NotFound
[RUNNER 2024-11-14 19:23:32Z ERR  BrokerServer] Catch exception during request
[RUNNER 2024-11-14 19:23:32Z ERR  BrokerServer] System.Exception: Failed to get job message. Request to https://broker.actions.githubusercontent.com/message failed with status: NotFound. Error message Error: Not Found
[RUNNER 2024-11-14 19:23:32Z ERR  BrokerServer]    at GitHub.Actions.RunService.WebApi.BrokerHttpClient.GetRunnerMessageAsync(Nullable`1 sessionId, String runnerVersion, Nullable`1 status, String os, String architecture, Nullable`1 disableUpdate, CancellationToken cancellationToken)
[RUNNER 2024-11-14 19:23:32Z ERR  BrokerServer]    at GitHub.Runner.Common.BrokerServer.<>c__DisplayClass7_0.<<GetRunnerMessageAsync>b__0>d.MoveNext()
[RUNNER 2024-11-14 19:23:32Z ERR  BrokerServer] --- End of stack trace from previous location ---
[RUNNER 2024-11-14 19:23:32Z ERR  BrokerServer]    at GitHub.Runner.Common.RunnerService.RetryRequest[T](Func`1 func, CancellationToken cancellationToken, Int32 maxRetryAttemptsCount, Func`2 shouldRetry)
[RUNNER 2024-11-14 19:23:32Z WARN BrokerServer] Back off 8.489 seconds before next retry. 4 attempt left.
[RUNNER 2024-11-14 19:23:41Z ERR  GitHubActionsService] GET request to https://broker.actions.githubusercontent.com/message?sessionId=alpha-numeric-session-id-here&status=Online&runnerVersion=2.321.0&os=Linux&architecture=X64&disableUpdate=false failed. HTTP Status: NotFound
[RUNNER 2024-11-14 19:23:41Z ERR  BrokerServer] Catch exception during request
[RUNNER 2024-11-14 19:23:41Z ERR  BrokerServer] System.Exception: Failed to get job message. Request to https://broker.actions.githubusercontent.com/message failed with status: NotFound. Error message Error: Not Found
[RUNNER 2024-11-14 19:23:41Z ERR  BrokerServer]    at GitHub.Actions.RunService.WebApi.BrokerHttpClient.GetRunnerMessageAsync(Nullable`1 sessionId, String runnerVersion, Nullable`1 status, String os, String architecture, Nullable`1 disableUpdate, CancellationToken cancellationToken)
[RUNNER 2024-11-14 19:23:41Z ERR  BrokerServer]    at GitHub.Runner.Common.BrokerServer.<>c__DisplayClass7_0.<<GetRunnerMessageAsync>b__0>d.MoveNext()
[RUNNER 2024-11-14 19:23:41Z ERR  BrokerServer] --- End of stack trace from previous location ---
[RUNNER 2024-11-14 19:23:41Z ERR  BrokerServer]    at GitHub.Runner.Common.RunnerService.RetryRequest[T](Func`1 func, CancellationToken cancellationToken, Int32 maxRetryAttemptsCount, Func`2 shouldRetry)
[RUNNER 2024-11-14 19:23:41Z WARN BrokerServer] Back off 5.695 seconds before next retry. 3 attempt left.
[RUNNER 2024-11-14 19:23:47Z ERR  GitHubActionsService] GET request to https://broker.actions.githubusercontent.com/message?sessionId=alpha-numeric-session-id-here&status=Online&runnerVersion=2.321.0&os=Linux&architecture=X64&disableUpdate=false failed. HTTP Status: NotFound
[RUNNER 2024-11-14 19:23:47Z ERR  BrokerServer] Catch exception during request
[RUNNER 2024-11-14 19:23:47Z ERR  BrokerServer] System.Exception: Failed to get job message. Request to https://broker.actions.githubusercontent.com/message failed with status: NotFound. Error message Error: Not Found
[RUNNER 2024-11-14 19:23:47Z ERR  BrokerServer]    at GitHub.Actions.RunService.WebApi.BrokerHttpClient.GetRunnerMessageAsync(Nullable`1 sessionId, String runnerVersion, Nullable`1 status, String os, String architecture, Nullable`1 disableUpdate, CancellationToken cancellationToken)
[RUNNER 2024-11-14 19:23:47Z ERR  BrokerServer]    at GitHub.Runner.Common.BrokerServer.<>c__DisplayClass7_0.<<GetRunnerMessageAsync>b__0>d.MoveNext()
[RUNNER 2024-11-14 19:23:47Z ERR  BrokerServer] --- End of stack trace from previous location ---
[RUNNER 2024-11-14 19:23:47Z ERR  BrokerServer]    at GitHub.Runner.Common.RunnerService.RetryRequest[T](Func`1 func, CancellationToken cancellationToken, Int32 maxRetryAttemptsCount, Func`2 shouldRetry)
[RUNNER 2024-11-14 19:23:47Z WARN BrokerServer] Back off 13.548 seconds before next retry. 2 attempt left.
[RUNNER 2024-11-14 19:24:00Z ERR  GitHubActionsService] GET request to https://broker.actions.githubusercontent.com/message?sessionId=alpha-numeric-session-id-here&status=Online&runnerVersion=2.321.0&os=Linux&architecture=X64&disableUpdate=false failed. HTTP Status: NotFound
[RUNNER 2024-11-14 19:24:00Z ERR  BrokerServer] Catch exception during request
[RUNNER 2024-11-14 19:24:00Z ERR  BrokerServer] System.Exception: Failed to get job message. Request to https://broker.actions.githubusercontent.com/message failed with status: NotFound. Error message Error: Not Found
[RUNNER 2024-11-14 19:24:00Z ERR  BrokerServer]    at GitHub.Actions.RunService.WebApi.BrokerHttpClient.GetRunnerMessageAsync(Nullable`1 sessionId, String runnerVersion, Nullable`1 status, String os, String architecture, Nullable`1 disableUpdate, CancellationToken cancellationToken)
[RUNNER 2024-11-14 19:24:00Z ERR  BrokerServer]    at GitHub.Runner.Common.BrokerServer.<>c__DisplayClass7_0.<<GetRunnerMessageAsync>b__0>d.MoveNext()
[RUNNER 2024-11-14 19:24:00Z ERR  BrokerServer] --- End of stack trace from previous location ---
[RUNNER 2024-11-14 19:24:00Z ERR  BrokerServer]    at GitHub.Runner.Common.RunnerService.RetryRequest[T](Func`1 func, CancellationToken cancellationToken, Int32 maxRetryAttemptsCount, Func`2 shouldRetry)
[RUNNER 2024-11-14 19:24:00Z WARN BrokerServer] Back off 12.328 seconds before next retry. 1 attempt
```
