### ISSUE TITLE
Self hosted runner are going offline suddenly and it is not connected.

### ISSUE THREAD

**Issue by akhilp6** [actions/runner#3501]
**Describe the bug**
We are using self hosted macos machines for our Github actions. It was working fine till yesterday but its suddenly getting disconnected and going to offline. And when I check the runner logs in `_diag`, I did find this 

## What's not working?
```
[2024-10-10 21:30:29Z INFO Terminal] WRITE LINE:
[2024-10-10 21:30:29Z INFO RSAFileKeyManager] Loading RSA key parameters from file /System/Volumes/Data/export/home/tester/actions-runner/.credentials_rsaparams
[2024-10-10 21:30:30Z ERR  GitHubActionsService] POST request to https://tokenghub.actions.githubusercontent.com/_apis/oauth2/token/****** failed. HTTP Status: BadRequest
[2024-10-10 21:30:30Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
[2024-10-10 21:30:30Z ERR  MessageListener] Catch exception during create session.
[2024-10-10 21:30:30Z ERR  MessageListener] GitHub.Services.OAuth.VssOAuthTokenRequestException: Registration was not found or is not medium trust. ClientType:
   at GitHub.Services.OAuth.VssOAuthTokenProvider.OnGetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
   at GitHub.Services.Common.IssuedTokenProvider.GetTokenOperation.GetTokenAsync(VssTraceActivity traceActivity)
   at GitHub.Services.Common.IssuedTokenProvider.GetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Listener.MessageListener.CreateSessionAsync(CancellationToken token)
[2024-10-10 21:30:30Z ERR  MessageListener] Test oauth app registration.
[2024-10-10 21:30:30Z INFO RSAFileKeyManager] Loading RSA key parameters from file /System/Volumes/Data/export/home/tester/actions-runner/.credentials_rsaparams
[2024-10-10 21:30:30Z ERR  GitHubActionsService] POST request to https://tokenghub.actions.githubusercontent.com/_apis/oauth2/token/***** failed. HTTP Status: BadRequest
[2024-10-10 21:30:30Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
[2024-10-10 21:30:30Z INFO MessageListener] Retriable exception: Registration was not found or is not medium trust. ClientType:
[2024-10-10 21:30:30Z INFO MessageListener] Sleeping for 30 seconds before retrying.
``` 

I have been seeing this issue from couple of days and its happening for all our hosts. 

I did see some online thread, some cases were clock of the server was off( which is not true in our case) 

## Runner Version and Platform
Runner version we are using is the latest `2.319.1`
OS of the machine running the runner? OSX

## Runner and Worker's Diagnostic Logs
Added the runner logs above.

**Comment by luketomlinson** [comment]
@akhilp6 do you have a session Id for that runner?

**Comment by ktaggart** [comment]
I am having the same issue with all of our hosts, and coincidentally it started at approximately the same time as the OP.
Runner version: 2.319.1
OS: Ubuntu 24.04 LTS

Any updates on this issue?

**Comment by ktaggart** [comment]
@luketomlinson, how do I find the session ID in order to get this issue moving forward? Our runners have been down for too long and I'd like to help resolve this issue ASAP.

**Comment by luketomlinson** [comment]
Hey @ktaggart, typically it would be from the runner logs as a queryParameter. 

We identified a bug on our side that was incorrectly deleting some runners. We've fixed this issue, but you'll need to re-register to get them back online. 

Let me know if this still appears to be happening.

**Comment by ktaggart** [comment]
> Hey @ktaggart, typically it would be from the runner logs as a queryParameter.
> 
> We identified a bug on our side that was incorrectly deleting some runners. We've fixed this issue, but you'll need to re-register to get them back online.
> 
> Let me know if this still appears to be happening.

Thanks for the response. I am pretty new to this and inherited our cluster. Can you point me to the registration docs?

**Comment by luketomlinson** [comment]
Sure thing @ktaggart. https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/adding-self-hosted-runners#adding-a-self-hosted-runner-to-a-repository.

**Comment by akhilp6** [comment]
@luketomlinson Is there a new runner version which we need to use to re-register them?

**Comment by ktaggart** [comment]
@luketomlinson 
> Sure thing @ktaggart. https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/adding-self-hosted-runners#adding-a-self-hosted-runner-to-a-repository.

I followed the instructions, created all the runners, added our labels, but they now sit idle and do not accept new jobs:
"Waiting for a runner to pick up this job..."

I compare the new .runner file to the old one and noted some rather stark differences:
old_runner
```
{
  "agentId": 642353,
  "agentName": "group.node_1",
  "poolId": 458,
  "poolName": "group",
  "serverUrl": "https://pipelines.actions.githubusercontent.com/<string>",
  "gitHubUrl": "https://github.com/enterprises/corp",
  "workFolder": "_work"
}
```
new_runner
```
﻿{
  "agentId": 1,
  "agentName": "group.node_1",
  "poolId": 1,
  "poolName": "Default",
  "serverUrl": "https://pipelinesghubeus10.actions.githubusercontent.com/<string>",
  "gitHubUrl": "https://github.com/corp-repos/repo",
  "workFolder": "_work"
}
```
When I attempted to use the poolName "group" I received an error indicating that the poolName "group" was not found, and I could only use "Default."

Also, the old_runner gitHubUrl is completely invalid - I have no idea how that could have worked previously, but it did. When I tried using that url, I received a "404 not found" error, which made sense.

I am wondering what the significance of the poolId and agentId are?

Any suggestions on how I can get my runner working/accepting jobs?

**Comment by ktaggart** [comment]
@luketomlinson, some more info.

After examining the runner log, I see the following:
Loading RSA key parameters from file /github_runner/runners/node_1/corp/001/.credentials_rsaparams
POST request to https://vstoken.actions.githubusercontent.com/_apis/oauth2/token/<token> failed. HTTP Status: BadRequest

I am not sure how the token that github provided is bad, but the token shown above is _not_ the same token shown in the .credentials file. Both the .credentials and .credentials_rsaparams files were created the same day and the same time, but are somehow out of sync.

Please comment.

**Comment by luketomlinson** [comment]
Hi @ktaggart, 

Where are you trying to register the runner? Runners can be registered at the repo, org, or enterprise level. That is determined by the `gitHubUrl` you provide to the `config` script. 

During that registration process, you choose a Runner Group (aka Pool) so PoolName == Runner Group Name. 

Once runners are registered, you'll need to make sure that runner group has access to the repository in question if the runner is registered at the org or enterprise level. 

Since you are re-registering runners, I would recommend deleting all of those `.credentials` files. They will be re-created when you re-register.

**Comment by ktaggart** [comment]
@luketomlinson, thanks for the response.

I followed the instructions you linked, and used the gitHubUrl that was provided via that process, e.g., 
`./config.sh --url https://github.com/corp/repo --token <TOKEN>`

In the above example the runner is being registered at the repo level, our internal corp github repo.

For poolName, I was only able to use 'Default' as when I tired using our previous group name, I received an error indicating that group name was not available, and I could only use 'Default'. I noted that in a previous message.

Q: Can I change that to our old group name manually by editing the .runner files, or will that cause an issue?

The runners do have access to the repo, as all the runners appear in the repo runners section and show as idle. and after the config was completed, I received a 'Connected to GitHub' message

As far as deleting the .credentials files, before running config.sh, I had to delete the existing .runner file in each runner directory in order to proceed, which resulted in a 'Removed .credentials' message while creating each new runner:

After that, a new .credentials file was in place, with _some_ old .credentials_rsaparams.

Q: Are you suggesting that I delete the .runner, .credentials and .credentials_rsaparams files and reinstall each runner?

Please clarify.

Thx.

**Comment by luketomlinson** [comment]
Hi @ktaggart,

From your previous comment, it appears the old runners were registered at the enterprise level with a different group. 

If you are still having issues, I'd recommend going through our support channels, rather than a public issue.

**Comment by cesarjorgemartinez** [comment]
+1 same problem with MacOS 14.7 version 2.319.1 and 2.320.0.
Time is ok, the runner is not touched in many time, and the use is frequently each day.

Suddenly broken:

```
[2024-10-25 09:50:05Z INFO Terminal] WRITE LINE: 
[2024-10-25 09:50:05Z INFO Terminal] WRITE LINE: 
[2024-10-25 09:50:05Z INFO RSAFileKeyManager] Loading RSA key parameters from file .../.credentials_rsaparams
[2024-10-25 09:50:05Z INFO RSAFileKeyManager] Loading RSA key parameters from file .../.credentials_rsaparams
[2024-10-25 09:50:06Z ERR  GitHubActionsService] POST request to https://vstoken.actions.githubusercontent.com/_apis/oauth2/token/xxxxxx failed. HTTP Status: BadRequest, AFD Ref: Ref A: xxxxx Ref B: xxxxxxx Ref C: 2024-10-25T09:50:05Z
[2024-10-25 09:50:06Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
[2024-10-25 09:50:06Z ERR  MessageListener] Catch exception during create session.
[2024-10-25 09:50:06Z ERR  MessageListener] GitHub.Services.OAuth.VssOAuthTokenRequestException: Registration was not found or is not medium trust. ClientType: 
   at GitHub.Services.OAuth.VssOAuthTokenProvider.OnGetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
   at GitHub.Services.Common.IssuedTokenProvider.GetTokenOperation.GetTokenAsync(VssTraceActivity traceActivity)
   at GitHub.Services.Common.IssuedTokenProvider.GetTokenAsync(IssuedToken failedToken, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Listener.MessageListener.CreateSessionAsync(CancellationToken token)
[2024-10-25 09:50:06Z ERR  MessageListener] Test oauth app registration.
[2024-10-25 09:50:06Z INFO RSAFileKeyManager] Loading RSA key parameters from file .../.credentials_rsaparams
[2024-10-25 09:50:07Z ERR  GitHubActionsService] POST request to https://vstoken.actions.githubusercontent.com/_apis/oauth2/token/xxx failed. HTTP Status: BadRequest, AFD Ref: Ref A: xxx Ref B: xxx Ref C: 2024-10-25T09:50:06Z
[2024-10-25 09:50:07Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
[2024-10-25 09:50:07Z INFO MessageListener] Retriable exception: Registration was not found or is not medium trust. ClientType: 
[2024-10-25 09:50:07Z ERR  Terminal] WRITE ERROR: 2024-10-25 09:50:07Z: Runner connect error: Registration was not found or is not medium trust. ClientType: . Retrying until reconnected.
[2024-10-25 09:50:07Z INFO MessageListener] Sleeping for 30 seconds before retrying.
```

**Comment by muharemd** [comment]
Syslog does not have anything useful in regards too this failure, I was  matching the time of the failure from runner logs matching the time in syslog and nothing really is logged as unusual. Only system startup sequence.
I will attach those few minutes of the logs around the failure to this ticket.

Error first started on time stamp below, and it was in system startup sequence:
`./Runner_20250107-070935-utc.log:[2025-01-07 07:09:40Z ERR  GitHubActionsService] POST request to https://vstoken.actions.githubusercontent.com/_apis/oauth2/token/df2c5fbf-896d-4391-bb8f-60d34754ee83 failed. HTTP Status: BadRequest, AFD Ref: Ref A: 420EEA3128E140DE9CE8E138E258CD88 Ref B: CPT30EDGE0219 Ref C: 2025-01-07T07:09:42Z`

**Comment by melloc01** [comment]
Has any of you had success in fixing the issue?

**Comment by michaelpporter** [comment]
FYI: We had the issue. Updating the image `ghcr.io/actions/actions-runner:2.329.0` fixed the issue.

```
Any updates released for the software, including major, minor, or patch releases, are considered as an available update. If you do not perform a software update within 30 days, the GitHub Actions service will not queue jobs to your runner. In addition, if a critical security update is required, the GitHub Actions service will not queue jobs to your runner until it has been updated.
```

**Comment by ganeshgk** [comment]
> FYI: We had the issue. Updating the image `ghcr.io/actions/actions-runner:2.329.0` fixed the issue.
> 
> ```
> Any updates released for the software, including major, minor, or patch releases, are considered as an available update. If you do not perform a software update within 30 days, the GitHub Actions service will not queue jobs to your runner. In addition, if a critical security update is required, the GitHub Actions service will not queue jobs to your runner until it has been updated.
> ```
@michaelpporter 
Had the same issue, thanks to you, else would have lost so much time.

**Comment by jmkava** [comment]
> > FYI: We had the issue. Updating the image `ghcr.io/actions/actions-runner:2.329.0` fixed the issue.
> > ```
> > Any updates released for the software, including major, minor, or patch releases, are considered as an available update. If you do not perform a software update within 30 days, the GitHub Actions service will not queue jobs to your runner. In addition, if a critical security update is required, the GitHub Actions service will not queue jobs to your runner until it has been updated.
> > ```
> 
> [@michaelpporter](https://github.com/michaelpporter) Had the same issue, thanks to you, else would have lost so much time.

Have the same issue with runner falling asleep on V2.329.0.
However it is not installed as a service at the moment.

**Comment by kleddiator** [comment]
Same symptom here on persistent (non-ephemeral) self-hosted Linux runners, v2.337.0, with a
precise log signature that may help narrow it down.

**Setup:** 5 persistent self-hosted runners, Ubuntu, runner 2.337.0, registered at repo level,
installed as systemd services via `svc.sh install`. Not ephemeral (`.runner` has no `ephemeral`
key). V2 broker flow (`useV2Flow: true`).

**Symptom:** Two machines independently went offline in the GitHub UI/API while the listener
process was still alive and `systemctl is-active` reported `active`. Load was zero. No crash, no
exit, no restart. They stayed in that state until the service was restarted manually — 59 and 27
minutes respectively. Queued jobs simply waited; nothing failed, so nothing alerted.

**Log signature.** On both machines the listener's last log line before the silence is identical:

```
[... 12:29:44Z INFO BrokerMessageListener] Acknowledging runner request '<id>'.
[... 12:29:45Z INFO ConfigurationStore] HasCredentials()
[... 12:29:45Z INFO CredentialManager] Creating credential type: OAuth
[... 12:29:45Z INFO RSAFileKeyManager] Loading RSA key parameters from file <path>/.credentials_rsaparams
[... 12:29:45Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
                                        <-- nothing at all for the next 59 minutes
```

The second machine is the same, 31 minutes later, with a 27-minute silence.

The healthy pattern is three steps and takes one to two seconds:

```
Acknowledging runner request '<id>'
AAD Correlation ID for this token request: Unknown
JobDispatcher] Job request 0 for plan <plan> job <id> received.
```

In both failures the **third step never arrives**, and the runner never acknowledges anything
again. It appears to hang between the OAuth token request and receiving the job message. Note
this is not a rare code path — `AAD Correlation ID for this token request` appears 2129 times in
one machine's logs; it is the normal per-job token acquisition.

Because a job had already been acknowledged, the run stays queued while the runner is gone.

**What does not explain it (measured, in case it saves someone else the detour):** we first
suspected the `TaskCanceledException` / `BrokerServer` errors that are plentiful in the logs, and
the `Runner listener exit with 0 return code, stop the service, no retry needed` line. Both are
red herrings for this failure mode:

- The `TaskCanceledException` occurred 12 times in one hour on a machine that was continuously
  online and running jobs. It is the normal cancellation of the in-flight long poll when the
  status changes from `Busy` to `Online`; the runner logs it itself as
  `Get messages has been cancelled using local token source. Continue to get messages with new status.`
- All 25 occurrences of `no retry needed` across 14 days and three machines are immediately
  preceded by `Sending SIGKILL to runner listener` / `Exiting...` — i.e. `runsvc.sh` having
  *received* SIGINT/SIGTERM. It is the consequence of a shutdown, never a spontaneous exit.
- Over seven days, every `Stopped` in the journal was followed by a `Started` within seconds. The
  service never stayed down. The process is alive throughout the outage — which is also why
  adding `Restart=` to the unit does not help this failure mode.

**Detection.** Since neither the process state nor the exit code reflects the failure, the only
reliable signal we found is polling `GET /repos/{owner}/{repo}/actions/runners` and comparing
`status` against the expected roster. Recovery: a service restart is enough; re-registration is
not required.

Happy to provide more of the `_diag/Runner_*.log` around either event if that helps.
