### ISSUE TITLE
Fails to configure on GHE w/ Private repo

### ISSUE THREAD

**Issue by brandonh-msft** [actions/runner#3574]
**Describe the bug**

**To Reproduce**
1. In a GitHub-hosted Enterprise instance
2. Create a private repo
3. Follow the steps to add a new runner by downloading the pkg (Linux) and running `config.sh`

**Expected behavior**
The runner should be created

## Runner Version and Platform
Version of your runner?
2.321.0

OS of the machine running the runner? Linux Ubuntu 20.04

## What's not working?
Please include error messages and screenshots.

```
--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication

What is the URL of your repository? https://github.com/myOrg/myRepo
What is your runner register token? ****************************************
Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration' (Request Id: 9E1E:11E088:5B0DF18:B07AC28:67366B45)
{"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
Response status code does not indicate success: 404 (Not Found).
```

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

```
[2024-11-14 21:27:26Z INFO Terminal] WRITE: What is your runner register token?
[2024-11-14 21:27:26Z INFO Terminal] READ SECRET
[2024-11-14 21:27:33Z INFO Terminal] Read value: '***'
[2024-11-14 21:27:33Z ERR  Terminal] WRITE ERROR: Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration' (Request Id: 9E1E:11E088:5B0DF18:B07AC28:67366B45)
[2024-11-14 21:27:33Z ERR  Terminal] WRITE ERROR: {"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
[2024-11-14 21:27:33Z ERR  Runner] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.GetTenantCredential(String githubUrl, String githubToken, String runnerEvent)
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at GitHub.Runner.Listener.Runner.ExecuteCommand(CommandSettings command)
[2024-11-14 21:27:33Z ERR  Terminal] WRITE ERROR: Response status code does not indicate success: 404 (Not Found).
[2024-11-14 21:27:33Z INFO Listener] Runner execution has finished with return code 1
```

**Comment by TingluoHuang** [comment]
make sure the token you use has the right permission for configure runners. (admin on the repo/org/enterprise)

**Comment by brandonh-msft** [comment]
why isn't this enough?
![image](https://github.com/user-attachments/assets/1f9ac2ac-e285-43e5-b63e-4ba92469cde6)

I shouldn't need to admin the whole repo/org/enterprise just to manage runners when there's a scope to... manage runners. right?

**Comment by brandonh-msft** [comment]
I've added `admin:org[*]` and `repo[*]` and get the same error.

**Comment by brandonh-msft** [comment]
The issue was that I was using a GH PAT token value as the Access Token when calling `config.sh`.

I had to, instead, make the call to the `runners/registration-token` endpoint which gives back a completely different token (even diff format). **THIS** is the token to use with `config.sh`

So, in order:

1. curl -sX POST -H "Authorization: Bearer $ACCESS_TOKEN" https://api.github.com/orgs/$ORGANIZATION/actions/runners/registration-token
2. ./config.sh --url https://github.com/BCP-TEST-MBBK --token (value of `token` property in JSON returned from Step 1 )
