### ISSUE TITLE
Support node22 in runs.using for JavaScript actions

### ISSUE THREAD

**Issue by sergei-startsev** [actions/runner#3600]
**Describe the bug**

Specifying `node22` as the runtime for JavaScript actions results in `System.ArgumentOutOfRangeException` error.

**To Reproduce**
```
runs:
  using: 'node22'
  main: 'main.js'
```

**Expected behavior**
- No errors.
- [Documentation](https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions) is updated.

## Runner Version and Platform

- Current runner version: 2.321.0
- Operating System: Ubuntu 24.04.1 LTS

## What's not working?
```
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node22' is not supported, use 'docker', 'node12', 'node16' or 'node20' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
```

**Comment by dipakparmar** [comment]
+1 for this.

**Comment by iamstarkov** [comment]
this would be lovely because node22 had been LTS for some time now

**Comment by albertodiazdorado** [comment]
+1

**Comment by runspired** [comment]
seems like no one can use any of the great new node features in any actions until this is fixed as repo code run using an action is constrained to <= node 20 😭

**Comment by MikeMcC399** [comment]
@nebuk89

In https://github.com/actions/runner/discussions/2704#discussioncomment-12016947 you wrote

> Sorry for the slowness on what comes next after node20! I was out for a few months but now I am back I will pick up with the team and start the annual wheel turn of moving up our node versions 🗡 

Do you (or anybody else) have any news for us about your concrete plans and timelines?

**Comment by garysassano** [comment]
In about 5 months, Node.js 24 will become the Active LTS version. Given the current pace, it seems unlikely this will be addressed before then. At that point, it might make more sense to update directly to Node.js 24 instead.

**Comment by MikeMcC399** [comment]
@garysassano 

> In about 5 months, Node.js 24 will become the Active LTS version. Given the current pace, it seems unlikely this will be addressed before then. At that point, it might make more sense to update directly to Node.js 24 instead.

We're really lacking any sort of response from the GitHub Actions organization at the moment. I'm unsure why this is.

It depends really on the strategy - whether each Node.js LTS is going to be supported, or whether there are going to be jumps, like from 20.x to 24.x. Preferably GitHub Actions should support each Node.js LTS version from when it is declared LTS until its End-of-Life transition.

Node.js | EOL
--- | ---
20.x | 2026-04-30
22.x | 2027-04-30
24.x | 2028-04-30

Milestones from https://github.com/nodejs/Release

**Comment by fern-sp** [comment]
In our company, we're assuming their internal strategy is that they do not want to maintain node-native runners (and are just ignoring it completely). So we moved from node20 runner and used a normal ubuntu or composite runner and ensure node is installed via actions/setup-node. Not as clean, but it seems to be the only option.

**Comment by andrewbrennanfr** [comment]
Do we have visibility on this? Or is looking for alternative ways what everyone else is doing?

**Comment by csvn** [comment]
> Do we have visibility on this? Or is looking for alternative ways what everyone else is doing?

@andrewbrennanfr See https://github.com/actions/runner/issues/3600#issuecomment-2930527651

Given that GitHub has used v12, v16 and v20 of NodeJS, it seems unlikely they will add anything except v24 when it becomes Active LTS. If you absolutely need to create an action that uses a newer version of NodeJS, you can do so by using [a Docker Container Action](https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-docker-container-action) instead.

**Comment by MikeMcC399** [comment]
There was a response from GitHub's @nebuk89 in https://github.com/orgs/community/discussions/160454#discussioncomment-13420519, which said:

> We plan to jump straight to node24 as it will be an LTS. We are still working on when we will start this upgrade :) but it will be some time in the next few months. Thanks for keeping engaged <3

**Comment by ChristopherHX** [comment]
I just saw a node24 draft PR that received comments from a known maintainer, so probably Actions Member.

> https://github.com/actions/runner/pull/3940

_We need to link this stuff ourself_

**Comment by salmanmkc** [comment]
> I just saw a node24 draft PR that received comments from a known maintainer, so probably Actions Member.
> 
> > [#3940](https://github.com/actions/runner/pull/3940)
> 
> _We need to link this stuff ourself_

Hi, yeah we have started work on this, but don't have an exact release date yet as we sort some internal bits out.

**Comment by MikeMcC399** [comment]
@salmanmkc 

Apparently `node24` has now gone live as https://github.com/actions/checkout/releases/tag/v5.0.0 is using it.

Is this supposed to be available for all actions now? It's not documented in https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax#runs-for-javascript-actions which still lists only `node20`

I might like to try this out, however I would not want to base a production action on `node24` until Node.js 24 transitions into LTS status later this year.

Can you share GitHub's plans for the use of `node24` please?

**Comment by salmanmkc** [comment]
> [@salmanmkc](https://github.com/salmanmkc)
> 
> Apparently `node24` has now gone live as https://github.com/actions/checkout/releases/tag/v5.0.0 is using it.
> 
> Is this supposed to be available for all actions now? It's not documented in https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax#runs-for-javascript-actions which still lists only `node20`
> 
> I might like to try this out, however I would not want to base a production action on `node24` until Node.js 24 transitions into LTS status later this year.
> 
> Can you share GitHub's plans for the use of `node24` please?

@MikeMcC399  Hi Mike, node24 is available technically on the runner. Each action should have a MAJOR version bump, so you will not be forced to do an upgrade in production. Take `actions/checkout` for example, I updated v4 to have the all the latest changes before doing a [v5.0.0](https://github.com/actions/checkout/releases/tag/v5.0.0) release, [v4.x.x](https://github.com/actions/checkout/releases/tag/v4.3.0) remains on node20.

See https://github.com/actions/runner/pull/3948 (Node 20 -> Node 24 migration feature flagging, opt-in and opt-out environment variables) for how the environment variables will work if you want to try force action versions. This change isn't released yet though.

I've opened PRs to upgrade the following actions, though it will take some time to get them all upgraded.
- https://github.com/actions/upload-artifact/pull/719
- https://github.com/actions/download-artifact/pull/415
- https://github.com/actions/cache/pull/1630
- https://github.com/actions/setup-node/pull/1325
- https://github.com/actions/checkout/pull/2226
- https://github.com/actions/add-to-project/pull/712
- https://github.com/actions/attest/pull/267
- https://github.com/actions/first-interaction/pull/327
- https://github.com/actions/attest-build-provenance/pull/675
- https://github.com/actions/attest-sbom/pull/192
- https://github.com/actions/configure-pages/pull/186
- https://github.com/actions/create-github-app-token/pull/267
- https://github.com/actions/delete-package-versions/pull/236
- https://github.com/actions/dependency-review-action/pull/952
- https://github.com/actions/deploy-pages/pull/404
- https://github.com/actions/github-script/pull/637
- https://github.com/actions/go-dependency-submission/pull/91
- https://github.com/actions/versions-package-tools/pull/87
- https://github.com/actions/gradle-build-tools-actions/pull/7
- https://github.com/actions/hello-world-javascript-action/pull/212
- https://github.com/actions/javascript-action/pull/529
- https://github.com/actions/labeler/pull/891
- https://github.com/actions/languageservices/pull/194
- https://github.com/actions/maven-dependency-submission-action/pull/16
- https://github.com/actions/publish-action/pull/92
- https://github.com/actions/publish-immutable-action/pull/227
- https://github.com/actions/reusable-workflows/pull/19
- https://github.com/actions/setup-dotnet/pull/654
- https://github.com/actions/setup-go/pull/624
- https://github.com/actions/setup-java/pull/888
- https://github.com/actions/setup-python/pull/1164
- https://github.com/actions/stale/pull/1279
- https://github.com/actions/starter-workflows/pull/2993
- https://github.com/actions/toolkit/pull/2110
- https://github.com/actions/typescript-action/pull/1093
- https://github.com/actions/ai-inference/pull/79

**Comment by MikeMcC399** [comment]
@salmanmkc 

Thanks for the "big picture" of all the work you're doing!

**Comment by jackylamhk** [comment]
@salmanmkc Thanks for the update! Are there plans to make Node 22 available or will it be skipped?

**Comment by salmanmkc** [comment]
> [@salmanmkc](https://github.com/salmanmkc) Thanks for the update! Are there plans to make Node 22 available or will it be skipped?

No worries! Will be skipped

**Comment by CatsMiaow** [comment]
https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/
> As a result we have started the deprecation process of Node20 for GitHub Actions. We plan to migrate all actions to run on Node24 in the fall of 2025.
> Beginning on March 4th, 2026, runners will begin using Node24 by default. 

Node.js v24 Active LTS Start `2025-10-28`

**Comment by salmanmkc** [comment]
Yeah that's the [blog post](https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/), node 24 is supported as of [v2.327.1](https://github.com/actions/runner/releases/tag/v2.327.1) however, using [v2.328.0](https://github.com/actions/runner/releases/tag/v2.328.0) will allow you to start testing with environment variables as outlined in the blog post.

**Comment by MikeMcC399** [comment]
- I guess this issue #3600 could be closed as "wont fix", since https://github.com/actions/runner/issues/3600#issuecomment-3183702089 already stated:

> Will be skipped

and https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax#runs-for-javascript-actions already documents 

> Use node20 for Node.js v20.
> Use node24 for Node.js v24.

with `node22` already officially skipped.

**Comment by iamstarkov** [comment]
@salmanmkc I've asked it somewhere else, but I'll repeat it here for exposure.

Do you plan to skip nodejs 26?

**Comment by MikeMcC399** [comment]
@salmanmkc 

Do you have any overview of which GitHub JavaScript actions still need to be migrated to `node24`?

The announcement [Deprecation of Node 20 on GitHub Actions runners](https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/) said

> We plan to migrate all actions to run on Node24 in the fall of 2025.

Going by that, I'd expect the migration to be complete or almost complete by now, however there are actions like https://github.com/actions/upload-artifact that are still on `node20`.

Could you share any new plans for the remainder of the migrations?

**Comment by ChristopherHX** [comment]
Trivia https://github.com/actions/upload-artifact/releases/tag/v5.0.0 claims to contain the node24 update as breaking change, but the PR to bump to node 24 was never merged and all CI checks from 3 month ago are all red 🤣.

Could really got marked internally as done.

**Comment by salmanmkc** [comment]
Download artifact, upload artifact and cache are all on node 24 now.
- https://github.com/actions/download-artifact/releases/tag/v7.0.0
- https://github.com/actions/upload-artifact/releases/tag/v6.0.0
- https://github.com/actions/cache/releases/tag/v5.0.1

There are a few actions that my PRs haven't all been reviewed or I need to chase/revisit, however the main actions that we provide are all upgraded to node 24 now.

**Comment by salmanmkc** [comment]
> Trivia https://github.com/actions/upload-artifact/releases/tag/v5.0.0 claims to contain the node24 update as breaking change, but the PR to bump to node 24 was never merged and all CI checks from 3 month ago are all red 🤣.
> 
> Could really got marked internally as done.

All the CI checks were red because I was referencing a a local package similar to how you do npm link, that's done for testing, once that is done I switched it over to published packages and it went green. 

As per v5, a release was done by the team as they were shipping some other changes and that included the toolkit changes which were done for node 24 support.

**Comment by salmanmkc** [comment]
Closing this as we have node 24 support now, see this post for more details https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/
