### ISSUE TITLE
2.321 on macOS 10.14 fails with "The SSL connection could not be established, see inner exception."

### ISSUE THREAD

**Issue by ilg-ul** [actions/runner#3612]
**Describe the bug**

The auto-update installed v2.321.0 and the runner no longer starts.

I removed everything and re-installed from scratch, and the config.sh failed.

**To Reproduce**

1. Follow the steps on https://github.com/organizations/xpack-dev-tools/settings/actions/runners/new?arch=x64&os=osx
2. The config.sh script fails with "WRITE ERROR: The SSL connection could not be established, see inner exception."

**Expected behavior**

The config.sh step to pass.

## Runner Version and Platform

Version of your runner: 2.321.0

OS of the machine: macOS 10.14

## What's not working?

```
[2024-12-06 10:09:22Z ERR  Runner] System.DllNotFoundException: Unable to load shared library 'libSystem.Security.Cryptography.Native.Apple' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/Users/ilg/actions-runners/xpack-dev-tools/bin/libSystem.Security.Cryptography.Native.Apple.dylib, 1): Library not loaded: /System/Library/Frameworks/CryptoKit.framework/Versions/A/CryptoKit
  Referenced from: /Users/ilg/actions-runners/xpack-dev-tools/bin/libSystem.Security.Cryptography.Native.Apple.dylib
  Reason: image not found
dlopen(libSystem.Security.Cryptography.Native.Apple.dylib, 1): image not found
dlopen(/Users/ilg/actions-runners/xpack-dev-tools/bin/liblibSystem.Security.Cryptography.Native.Apple.dylib, 1): image not found
dlopen(liblibSystem.Security.Cryptography.Native.Apple.dylib, 1): image not found
dlopen(/Users/ilg/actions-runners/xpack-dev-tools/bin/libSystem.Security.Cryptography.Native.Apple, 1): image not found
dlopen(libSystem.Security.Cryptography.Native.Apple, 1): image not found
dlopen(/Users/ilg/actions-runners/xpack-dev-tools/bin/liblibSystem.Security.Cryptography.Native.Apple, 1): image not found
dlopen(liblibSystem.Security.Cryptography.Native.Apple, 1): image not found

   at Interop.AppleCrypto.SslCreateContext(Int32 isServer)
   at System.Net.SafeDeleteSslContext.CreateSslContext(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.SafeDeleteSslContext..ctor(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
[2024-12-06 10:09:22Z ERR  Terminal] WRITE ERROR: The SSL connection could not be established, see inner exception.
[2024-12-06 10:09:22Z INFO Listener] Runner execution has finished with return code 1
xbbmi:xpack-dev-tools ilg$ 
```

## Job Log Output

- none

## Runner and Worker's Diagnostic Logs

[Runner_20241206-100917-utc.log](https://github.com/user-attachments/files/18036706/Runner_20241206-100917-utc.log)

---

v2.320.0 is fine, so one of the recent changes is no longer compatible with older macOSes.

As a workaround I configured the runner to disable auto-update, but this is not a long time solution. 

Support for older macOS system is a must, since most binary distributions target 10.13 or 10.14 as their base system, and these binaries are built on older macOSes.

**Comment by TingluoHuang** [comment]
We have to upgrade the dotnet SDK we use in the runner since the SDK was on dotnet 6 which ends its LTS. 😢 

It looks like the dotnet 8 [doesn't support macOS 10.14 anymore](https://github.com/dotnet/runtime/issues/93167).

Are you able to upgrade to macOS 10.15 so the new runner can work on your OS?

**Comment by ilg-ul** [comment]
> Are you able to upgrade to macOS 10.15 so the new runner can work on your OS?

Unfortunately not! :-(

**Comment by ilg-ul** [comment]
Any idea how long v2.320.0 will still be supported?

**Comment by ilg-ul** [comment]
> 30 days ,  so ca. 12-13. December

Hmmm.. that's pretty close. :-(

> I can build macOS 10.10 software on macOS 13.0 hosted runners (free contingent available) without problems

Yes, I know. I thought of using the macos-13 runner, but I have some very long builds (clang, riscv-none-elf-gcc, arm-none-eabi-gcc) that I'm afraid will not fit the 6 hours limit of the free runners. 

And I'm not very keen on buying an Intel Mac for this.. :-(
