### ISSUE TITLE
Unable to read data from the transport connection Exception 

### ISSUE THREAD

**Issue by axc450** [actions/runner#502]
I am attempting to set up a self-hosted agent on a server but cannot get past the first "Authentication" step. The error log is filled up with:
```
[2020-05-23 17:02:06Z ERR  RunnerServer] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at GitHub.Runner.Common.RunnerServer.EstablishVssConnection(Uri serverUrl, VssCredentials credentials, TimeSpan timeout)
```

I have tried turning the firewall off to no success. This server does sit behind a VPN, but I can communicate with GitHub just fine when RDP'd onto it. Find log attached:
[Runner_20200523-170124-utc.log](https://github.com/actions/runner/files/4672223/Runner_20200523-170124-utc.log)

**Comment by TingluoHuang** [comment]
@axc450 please check https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#communication-between-self-hosted-runners-and-github

base on log, you are able to hit `https://api.github.com/actions/runner-registration` but failed with `https://pipelines.actions.githubusercontent.com/H2p5hSE4GJRNE2bzDVixAXmQHFfaAZj0ziyMGUoGF9G3XP5SC1/_apis/connectionData `

**Comment by axc450** [comment]
I did some testing - I can access that page via a browse, but not from Powershell. I think this might be a TLS issue (I have had TLS 1.2 issues on the server before)

**Comment by axc450** [comment]
So it seems that `https://pipelines.actions.githubusercontent.com/` only support TLS 1.2 and the following cipher suites:
```
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x9f)
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x9e)
```

The server I am trying to host the runner on does not have any of these. The OS also hasnt been updated since 2018, so I will attempt to perform all windows patching and report back if the problem still occurs.

**Comment by dhiwakarK** [comment]
@axc450 My customer is facing same issue and was wondering how you managed to resolve this? Also, how you managed to know the list of supported Cipher suites for `https://pipelines.actions.githubusercontent.com`? Because the URL is not opening through browser

**Comment by axc450** [comment]
> @axc450 I am facing same issue and was wondering how you managed to resolve this? Also, how you managed to know the list of supported Cipher suites for `https://pipelines.actions.githubusercontent.com`? Because the URL is not opening through browser

We updated our Windows server to get the most up-to-date cypher suites.
I used https://www.ssllabs.com/ssltest/ to check the SSL status of the domain.

**Comment by dhiwakarK** [comment]
> We updated our Windows server to get the most up-to-date cypher suites.

Is there a command that they should run on Windows to get all the cypher suites @axc450 ?

>I used https://www.ssllabs.com/ssltest/ to check the SSL status of the domain.

This is super cool !!

**Comment by dhiwakarK** [comment]
Interestingly even after a complete Windows Server update (all patches), the ciphers are not up to date. The 4 suites were missing. This is on Windows Server 2019

**Comment by nikola-jokic** [comment]
Hi everyone,

This issue does not seem to be related to the runner itself, but rather to the host environment. If you are experiencing this issue on the GitHub hosted runners, please post your issue in the [Virtual Environments Repository](https://github.com/actions/virtual-environments/issues/new/choose) to ensure the correct team sees it.

Since we are trying to keep issues related to the runner itself, I am closing this issue now. But if you disagree, feel free to re-open this issue 😊
