### ISSUE TITLE
CreateProcess() failed when the CREATE_NEW_PROCESS_GROUP flag is set

### ISSUE THREAD

**Issue by al-cheb** [actions/runner#595]
**Describe the bug**
The original - https://github.community/t/createprocess-failed-for-executable-in-repo-on-windows/120616/2.
Unable to create process using WinApi function `CreateProcess` with flag `CREATE_NEW_PROCESS_GROUP` when the process is executed in GitHub Actions via `Runner.Worker.exe`.

![image](https://user-images.githubusercontent.com/47745270/87791257-a46d8f00-c84a-11ea-8b59-838f5e7265b4.png)

**To Reproduce**
Python script:
```
from subprocess import Popen, PIPE
script = "cmd.exe"
param = "/c echo Hello > C:\\test.txt"
CREATE_BREAKAWAY_FROM_JOB = 0x01000000
CREATE_NEW_PROCESS_GROUP = 0x00000200
CREATE_SUSPENDED = 0x00000004
pid = Popen([script, param], shell=True, stdin=PIPE, stdout=PIPE, stderr=PIPE,
            creationflags=CREATE_BREAKAWAY_FROM_JOB | CREATE_NEW_PROCESS_GROUP | CREATE_SUSPENDED)
print(pid)
```
Run:
`python CreateProcess.py`

**Expected behavior**
Run process as on the local machine or using task scheduler without error instead of the  `[WinError 5] Access is denied`.

```
jobs:
  build:
    runs-on: 'windows-latest'

    steps:
    - name: Install pssuspend
      run: Invoke-WebRequest https://live.sysinternals.com/pssuspend64.exe -OutFile C:\Windows\pssuspend.exe
    - name: Create Python script
      run: |
        @"
        from subprocess import Popen, PIPE
        script = "cmd.exe"
        param = "/c echo Hello > C:\\hello.txt"
        CREATE_BREAKAWAY_FROM_JOB = 0x01000000
        CREATE_NEW_PROCESS_GROUP = 0x00000200
        CREATE_SUSPENDED = 0x00000004
        pid = Popen([script, param], shell=True, stdin=PIPE, stdout=PIPE, stderr=PIPE,
                    creationflags=CREATE_BREAKAWAY_FROM_JOB | CREATE_NEW_PROCESS_GROUP | CREATE_SUSPENDED)
        print(pid)
        "@ | Out-File C:\CreateProcess.py
    - name: Run Python script and check C:\hello.txt does not exist
      run: |
        $taskName = "Run Process"
        schtasks /create /tn $taskName /sc DAILY /st 13:00 /ru SYSTEM /rl HIGHEST /tr "python C:\CreateProcess.py"
        Start-ScheduledTask -TaskName $taskName
        while ((Get-ScheduledTask -TaskName $taskName).State  -ne 'Ready') 
        {
            Start-Sleep -Seconds 5
        }
    - name: C:\hello.txt is missing
      run: -not (Test-Path C:\hello.txt)
    - name: Resume process and read content
      run: |
         $id = Get-CimInstance Win32_Process -Filter "Name='cmd.exe'" | Where CommandLine -match "hello.txt" | Foreach ProcessId
         $null = pssuspend -accepteula -nobanner -r $id
         Get-Content C:\hello.txt
```
![image](https://user-images.githubusercontent.com/47745270/87792247-4b065f80-c84c-11ea-90eb-f3e1de2a5015.png)

## Runner Version and Platform
Env: GitHub Actions
Version: 2.267.1
OS: Windows Server 2019

![image](https://user-images.githubusercontent.com/47745270/87790214-e3024a00-c848-11ea-915f-e89283673dbd.png)

## What's not working?
```
Traceback (most recent call last):
  File "C:\CreateProcess.py", line 8, in <module>
    creationflags=CREATE_BREAKAWAY_FROM_JOB | CREATE_NEW_PROCESS_GROUP | CREATE_SUSPENDED)
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Access is denied
```

![image](https://user-images.githubusercontent.com/47745270/87790342-19d86000-c849-11ea-8bb2-27a91ea06b91.png)

## Job Log Output
```
jobs:
  build:
    runs-on: 'windows-latest'

    steps:
    - name: Create Python script
      run: |
        @"
        from subprocess import Popen, PIPE
        script = "cmd.exe"
        param = "/c echo Hello > C:\\hello.txt"
        CREATE_BREAKAWAY_FROM_JOB = 0x01000000
        CREATE_NEW_PROCESS_GROUP = 0x00000200
        CREATE_SUSPENDED = 0x00000004
        pid = Popen([script, param], shell=True, stdin=PIPE, stdout=PIPE, stderr=PIPE,
                    creationflags=CREATE_BREAKAWAY_FROM_JOB | CREATE_NEW_PROCESS_GROUP | CREATE_SUSPENDED)
        print(pid)
        "@ | Out-File C:\CreateProcess.py
    - name: Run Python script and check C:\hello.txt does not exist
      run: |
        python C:\CreateProcess.py
```

**Comment by TingluoHuang** [comment]
I can't repro this in a self-hosted windows runner, might be related to how the hosted runner gets launched by MMS.

**Comment by Akhilvs007** [comment]
I am facing this issue currently @al-cheb , what was your solution for this issue.?
If no solution found , could you please reopen it ?

**Comment by ottointhesky** [comment]
I'm also facing this problem. In a local machine/docker image everthings works without any issue, but NOT in github runners. Has anyone found a solution/workaround to this issue?
