### ISSUE TITLE
Request throttling crashes the worker

### ISSUE THREAD

**Issue by yaananth** [actions/runner#709]
Internal tracking: https://github.com/github/c2c-actions-service/issues/1443

```
GitHub actions runner worker process crashed with error: GitHub.Services.Common.VssServiceException: Request was blocked due to exceeding usage of resource 'DBCPU' in namespace ''.
```

Logs:
```
[2020-09-15 08:34:25Z INFO HostContext] No proxy settings were found based on environmental variables (http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY)
[2020-09-15 08:34:25Z INFO HostContext] Well known directory 'Bin': '/home/runner/runners/2.273.2/bin'
[2020-09-15 08:34:25Z INFO HostContext] Well known directory 'Root': '/home/runner/runners/2.273.2'
[2020-09-15 08:34:25Z INFO HostContext] Well known config file 'Credentials': '/home/runner/runners/2.273.2/.credentials'
[2020-09-15 08:34:25Z INFO Worker] Version: 2.273.2
[2020-09-15 08:34:25Z INFO Worker] Commit: b75246e0fe35f83d6b586476b387822146b42fd6
[2020-09-15 08:34:25Z INFO Worker] Culture: 
[2020-09-15 08:34:25Z INFO Worker] UI Culture: 
[2020-09-15 08:34:25Z ERR  Worker] System.IO.IOException: Invalid pipe handle.
   at System.IO.Pipes.PipeStream.ValidateHandleIsPipe(SafePipeHandle safePipeHandle)
   at System.IO.Pipes.AnonymousPipeClientStream.Init(PipeDirection direction, SafePipeHandle safePipeHandle)
   at System.IO.Pipes.AnonymousPipeClientStream..ctor(PipeDirection direction, String pipeHandleAsString)
   at GitHub.Runner.Common.ProcessChannel.StartClient(String pipeNameInput, String pipeNameOutput)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
```

```
[2020-09-15 08:35:07Z INFO Worker] Waiting for the job to complete or for a cancel message from the channel.
[2020-09-15 08:35:07Z ERR  GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/ejUjMexhOj6SNJxt3h7rhmsOn6tc4t4CshKp9287OBpLeXcpQ5/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. HTTP Status: TooManyRequests, AFD Ref: Ref A: C1D899DBBA124C789E859679801E9B32 Ref B: BN3EDGE0516 Ref C: 2020-09-15T08:35:07Z
[2020-09-15 08:35:07Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2020-09-15 08:35:07Z INFO JobServer] Catch exception during connect. 4 attemp left.
[2020-09-15 08:35:07Z ERR  JobServer] GitHub.Services.Common.VssServiceException: Request was blocked due to exceeding usage of resource 'DBCPU' in namespace ''.
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at GitHub.Runner.Common.JobServer.ConnectAsync(VssConnection jobConnection)
[2020-09-15 08:35:07Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2020-09-15 08:35:07Z ERR  GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/ejUjMexhOj6SNJxt3h7rhmsOn6tc4t4CshKp9287OBpLeXcpQ5/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. HTTP Status: TooManyRequests, AFD Ref: Ref A: D6AC74E3C2BD42F18AD9F013E02C6E69 Ref B: BN3EDGE0516 Ref C: 2020-09-15T08:35:07Z
[2020-09-15 08:35:07Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2020-09-15 08:35:07Z INFO JobServer] Catch exception during connect. 3 attemp left.
[2020-09-15 08:35:07Z ERR  JobServer] GitHub.Services.Common.VssServiceException: Request was blocked due to exceeding usage of resource 'DBCPU' in namespace ''.
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at GitHub.Runner.Common.JobServer.ConnectAsync(VssConnection jobConnection)
[2020-09-15 08:35:07Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2020-09-15 08:35:07Z ERR  GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/ejUjMexhOj6SNJxt3h7rhmsOn6tc4t4CshKp9287OBpLeXcpQ5/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. HTTP Status: TooManyRequests, AFD Ref: Ref A: 9D4FD20F88EE4A0B983A80152E05505E Ref B: BN3EDGE0516 Ref C: 2020-09-15T08:35:07Z
[2020-09-15 08:35:07Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2020-09-15 08:35:07Z INFO JobServer] Catch exception during connect. 2 attemp left.
[2020-09-15 08:35:07Z ERR  JobServer] GitHub.Services.Common.VssServiceException: Request was blocked due to exceeding usage of resource 'DBCPU' in namespace ''.
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at GitHub.Runner.Common.JobServer.ConnectAsync(VssConnection jobConnection)
[2020-09-15 08:35:07Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2020-09-15 08:35:07Z ERR  GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/ejUjMexhOj6SNJxt3h7rhmsOn6tc4t4CshKp9287OBpLeXcpQ5/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. HTTP Status: TooManyRequests, AFD Ref: Ref A: CBD8D5EAC78D4D9795B4FF17B19BB63F Ref B: BN3EDGE0516 Ref C: 2020-09-15T08:35:07Z
[2020-09-15 08:35:07Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2020-09-15 08:35:07Z INFO JobServer] Catch exception during connect. 1 attemp left.
[2020-09-15 08:35:07Z ERR  JobServer] GitHub.Services.Common.VssServiceException: Request was blocked due to exceeding usage of resource 'DBCPU' in namespace ''.
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at GitHub.Runner.Common.JobServer.ConnectAsync(VssConnection jobConnection)
[2020-09-15 08:35:07Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2020-09-15 08:35:07Z ERR  GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/ejUjMexhOj6SNJxt3h7rhmsOn6tc4t4CshKp9287OBpLeXcpQ5/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. HTTP Status: TooManyRequests, AFD Ref: Ref A: B9FABBE6EA7C465F8E52829DA6168B0C Ref B: BN3EDGE0516 Ref C: 2020-09-15T08:35:07Z
[2020-09-15 08:35:07Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2020-09-15 08:35:07Z INFO Worker] Job completed.
[2020-09-15 08:35:08Z ERR  Worker] GitHub.Services.Common.VssServiceException: Request was blocked due to exceeding usage of resource 'DBCPU' in namespace ''.
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at GitHub.Runner.Common.JobServer.ConnectAsync(VssConnection jobConnection)
   at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
```

**Comment by TingluoHuang** [comment]
There is nothing the runner can do if the host is throttled.
