### ISSUE TITLE
Error: Sorry, there was a problem deleting your runner.

### ISSUE THREAD

**Issue by missedone** [actions/runner#710]
**Describe the bug**
I have the self-hosted runner 2.273.2 deployed in AWS EKS Kubernetes.
I notice one job never stops, so I delete the runner pod in the k8s cluster, and spin up a new runner pod to serve request.
however, the new runner logs shows listening for jobs, but the job not get started at all.
so i come the the github organization actions tab, try to delete the runner (which the runner pod is manually deleted), but got error below
![image](https://user-images.githubusercontent.com/555134/93298212-acdd3a00-f7a7-11ea-95a1-9cffc2d9f90a.png)

**To Reproduce**
2. Run '....'
3. See error

**Expected behavior**

## Runner Version and Platform
Version of your runner?
2.273.2

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
Please include error messages and screenshots.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.
> √ Settings Saved.
>
> .path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Starting Runner listener with startup type: service
Started listener process
Started running service
>
> √ Connected to GitHub
>
>2020-09-16 05:56:06Z: Listening for Jobs

pls let me know other log you need.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.
> [2020-09-16 05:56:04Z INFO UnixUtil] Running /usr/bin/chmod 755 "/runner/svc.sh"
[2020-09-16 05:56:04Z INFO ProcessInvokerWrapper] Starting process:
[2020-09-16 05:56:04Z INFO ProcessInvokerWrapper]   File name: '/usr/bin/chmod'
[2020-09-16 05:56:04Z INFO ProcessInvokerWrapper]   Arguments: '755 "/runner/svc.sh"'
[2020-09-16 05:56:04Z INFO ProcessInvokerWrapper]   Working directory: '/runner'
[2020-09-16 05:56:04Z INFO ProcessInvokerWrapper]   Require exit code zero: 'True'
[2020-09-16 05:56:04Z INFO ProcessInvokerWrapper]   Encoding web name:  ; code page: ''
[2020-09-16 05:56:04Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'False'
[2020-09-16 05:56:04Z INFO ProcessInvokerWrapper]   Redirected STDIN: 'False'
[2020-09-16 05:56:04Z INFO ProcessInvokerWrapper]   Persist current code page: 'False'
[2020-09-16 05:56:04Z INFO ProcessInvokerWrapper]   Keep redirected STDIN open: 'False'
[2020-09-16 05:56:04Z INFO ProcessInvokerWrapper]   High priority process: 'False'
[2020-09-16 05:56:04Z INFO ProcessInvokerWrapper] Failed to update oom_score_adj for PID: 77.
[2020-09-16 05:56:04Z INFO ProcessInvokerWrapper] System.UnauthorizedAccessException: Access to the path '/proc/77/oom_score_adj' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at System.IO.File.WriteAllText(String path, String contents)
   at GitHub.Runner.Sdk.ProcessInvoker.WriteProcessOomScoreAdj(Int32 processId, Int32 oomScoreAdj)
[2020-09-16 05:56:04Z INFO ProcessInvokerWrapper] Process started with process id 77, waiting for process exit.
[2020-09-16 05:56:04Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2020-09-16 05:56:04Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2020-09-16 05:56:04Z INFO ProcessInvokerWrapper] Finished process 77 with exit code 0, and elapsed time 00:00:00.0018426.
[2020-09-16 05:56:04Z INFO Listener] Runner execution has finished with return code 0

**Comment by missedone** [comment]
after stuck in such state for 5-10 min, now it recovers itself. 
the deleted runner can be removed. and the runner starts handling new builds

**Comment by t0rr3sp3dr0** [comment]
I've experienced the same issue as you. The message on GitHub's website is not clear, but if you try to remove the runner using the API you can see that it is complaining that the runner is still processing a job and cannot be removed at the time. It just allows you to remove the runner after a internal timeout on GitHub's servers that mark the job as failed.

In my case, I'm developing an operator that creates runners on-demand as K8s Job. So what I'm gonna do is to mimic the request that the runner would have sent to GitHub marking the job as failed, so that the runner is free to be deleted or to consume another job.

**Comment by davidkarlsen** [comment]
@t0rr3sp3dr0 Want to join forces on https://github.com/evryfs/github-actions-runner-operator/ ?

**Comment by ruvceskistefan** [comment]
Hi @missedone,
I think that the problem is that you're trying to remove the runner who is still processing the job. After the job is done, you managed to remove the runner (what you wrote after 5-10 minutes).
I'm going to close out this issue, please let us know if you are still seeing this issue or you have more questions!
