### ISSUE TITLE
Windows Runner Service don´t start with default configuration

### ISSUE THREAD

**Issue by MmAtBosch** [actions/runner#717]
**Describe the bug**
If you install a github self-hosted runner service on Windows 10 Pro via 
./config.cmd 
with the default given parameter, the service is not able to run.
The reason for that, is that the user NT AUTHORITY\NETWORK SERVICE does not have access to the working directory

**To Reproduce**
mkdir actions-runner; cd actions-runner
Invoke-WebRequest -Uri https://github.com/actions/runner/releases/download/v2.272.0/actions-runner-win-x64-2.272.0.zip -OutFile actions-runner-win-x64-2.272.0.zip

>> Add-Type -AssemblyName System.IO.Compression.FileSystem ; [System.IO.Compression.ZipFile]::ExtractToDirectory("$PWD/actions-runner-win-x64-2.272.0.zip", "$PWD")
PS C:\Users\bdcoperator\actions-runner>
>> ./config.cmd --url https://github.com/Demo --token xxx

This runner will have the following labels: 'self-hosted', 'Windows', 'X64'
Enter any additional labels (ex. label-1,label-2): [press Enter to skip] 
Enter name of work folder: [press Enter for _work]

Would you like to run the runner as service? (Y/N) [press Enter for N] Y
User account to use for the service [press Enter for NT AUTHORITY\NETWORK SERVICE]
Granting file permissions to 'NT AUTHORITY\NETWORK SERVICE'.

**Expected behavior**
get-service -name "actions.runner._services.runnername"
Status   Name               DisplayName
------   ----               -----------
Running actions.runner.... GitHub Actions Runner (_services.pr...

This might be done, when the ./config.cmd set the current user as service user.

## Runner Version and Platform
2.272.0
Windows 10 Pro

## What's not working?
Starting the runner service
start-service -name "actions.runner._services.runnername"

## Runner and Worker's Diagnostic Logs
cat ._diag\Runner_20200922-130530-utc.log
[2020-09-22 13:05:30Z INFO HostContext] No proxy settings were found based on environmental variables (http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY)
[2020-09-22 13:05:30Z INFO HostContext] Well known directory 'Bin': 'C:\Users\myuser\actions-runner\bin'
[2020-09-22 13:05:30Z INFO HostContext] Well known directory 'Root': 'C:\Users\myuser\actions-runner'
[2020-09-22 13:05:30Z INFO HostContext] Well known config file 'Credentials': 'C:\Users\myuser\actions-runner.credentials'
[2020-09-22 13:05:30Z INFO Listener] Runner is built for Windows (X64) - win-x64.
[2020-09-22 13:05:30Z INFO Listener] RuntimeInformation: Microsoft Windows 10.0.19041.
[2020-09-22 13:05:30Z INFO Listener] Version: 2.272.0
[2020-09-22 13:05:30Z INFO Listener] Commit: ae543d59756d8440d9b450f3ca74ada6a1b8aefc
[2020-09-22 13:05:30Z INFO Listener] Culture: en-US
[2020-09-22 13:05:30Z INFO Listener] UI Culture: en-US
[2020-09-22 13:05:30Z INFO HostContext] Well known directory 'Bin': 'C:\Users\myuser\actions-runner\bin'
[2020-09-22 13:05:30Z INFO HostContext] Well known directory 'Root': 'C:\Users\myuser\actions-runner'
[2020-09-22 13:05:30Z INFO Listener] Validating directory permissions for: 'C:\Users\myuser\actions-runner'
[2020-09-22 13:05:30Z ERR Terminal] WRITE ERROR: An error occurred: Permission to read the directory contents is required for 'C:\Users\myuser\actions-runner' and each directory up the hierarchy. Access to the path 'C:\Users\myuser' is denied.
[2020-09-22 13:05:30Z ERR Listener] System.UnauthorizedAccessException: Permission to read the directory contents is required for 'C:\Users\myuser\actions-runner' and each directory up the hierarchy. Access to the path 'C:\Users\myuser' is denied.
---> System.UnauthorizedAccessException: Access to the path 'C:\Users\myuser' is denied.
at System.IO.Enumeration.FileSystemEnumerator1.CreateDirectoryHandle(String path, Boolean ignoreNotFound) at System.IO.Enumeration.FileSystemEnumerator1.Init()
at System.IO.Enumeration.FileSystemEnumerator1..ctor(String directory, Boolean isNormalized, EnumerationOptions options) at System.IO.Enumeration.FileSystemEnumerable1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
at System.IO.Enumeration.FileSystemEnumerableFactory.UserEntries(String directory, String expression, EnumerationOptions options)
at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
at System.IO.Directory.EnumerateFileSystemEntries(String path)
at GitHub.Runner.Sdk.IOUtil.ValidateExecutePermission(String directory)
--- End of inner exception stack trace ---
at GitHub.Runner.Sdk.IOUtil.ValidateExecutePermission(String directory)
at GitHub.Runner.Listener.Program.MainAsync(IHostContext context, String[] args)
[2020-09-22 13:05:30Z ERR Listener] #####################################################
[2020-09-22 13:05:30Z ERR Listener] System.UnauthorizedAccessException: Access to the path 'C:\Users\myuser' is denied.
at System.IO.Enumeration.FileSystemEnumerator1.CreateDirectoryHandle(String path, Boolean ignoreNotFound) at System.IO.Enumeration.FileSystemEnumerator1.Init()
at System.IO.Enumeration.FileSystemEnumerator1..ctor(String directory, Boolean isNormalized, EnumerationOptions options) at System.IO.Enumeration.FileSystemEnumerable1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
at System.IO.Enumeration.FileSystemEnumerableFactory.UserEntries(String directory, String expression, EnumerationOptions options)
at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
at System.IO.Directory.EnumerateFileSystemEntries(String path)
at GitHub.Runner.Sdk.IOUtil.ValidateExecutePermission(String directory)

**Comment by yair-mantis** [comment]
>This might be done, when the ./config.cmd set the current user as service user.

**Comment by simonsabin** [comment]
The template code should really create the directory at c:\ to ensure that its got permissions if you are going to --runasservice
```
mkdir c:\actions-runner; cd c:\actions-runner
```

**Comment by ruvceskistefan** [comment]
Hi @MmAtBosch,

Are you still seeing this issue? If so, could you please install the runner on the path `C:\actions-runner` as recommended in the download instructions. As it says there, this will help avoid issues related to service identity folder permissions.

**Comment by MmAtBosch** [comment]
Hey @ruvceskistefan,
i just did a small test and the problem doesn´t exist anymore!
i tested i both ways, creating the right folder and installing it into another personal folder.
Both worked.

**Comment by ruvceskistefan** [comment]
Hi @MmAtBosch,
Thanks a lot for testing and reporting the results!

**Comment by murphman300** [comment]
bumping up for visibility, make sure to:

- install the actions-runner inside of "<your-drive>://" and nothing else deeper
- run the config.cmd command as admin if you want to run it as a service, otherwise it won't work

Note - the current guide in <your-repo>/settings/actions/runners/new does not specify any of this, please update the page with this information, or link to it.

**Comment by murphman300** [comment]
> The template code should really create the directory at c:\ to ensure that its got permissions if you are going to --runasservice
> 
> ```
> mkdir c:\actions-runner; cd c:\actions-runner
> ```

tagging re my previous reply in terms of lack of clear documentation
