### ISSUE TITLE
Auto upgrade to 2.275.1 keeps failing

### ISSUE THREAD

**Issue by lni** [actions/runner#869]
**Describe the bug**
The Linux/ARM64 runner failed to auto upgrade to 2.275.1 from 2.274.2.

**To Reproduce**
I have my Linux/ARM64 runner running as a systemd service, it worked fine for several days, then it stopped working since yesterday. Logs indicate that it probably got stuck when trying to auto upgrade to version 2.275.1. 

As the issue is caused by a background daemon, no manual step is required to reproduce it. 

**Expected behavior**
Auto upgrade should just complete and runner should keep accepting/processing jobs. 

## Runner Version and Platform
2.274.2

OS of the machine running the runner? OSX/Windows/Linux/...

Linux/ARM64 running on AWS EC2, OS is Ubuntu 18.04 for ARM64.  

## What's not working?

Runner stopped, no new jobs can be accepted/processed. 

```
Dec 18 02:58:40 ip-172-31-21-198 systemd[1]: actionsrunner.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Dec 18 02:58:40 ip-172-31-21-198 systemd[1]: actionsrunner.service: Failed with result 'exit-code'.
Dec 18 02:58:41 ip-172-31-21-198 systemd[1]: actionsrunner.service: Service hold-off time over, scheduling restart.
Dec 18 02:58:41 ip-172-31-21-198 systemd[1]: actionsrunner.service: Scheduled restart job, restart counter is at 3.
Dec 18 02:58:41 ip-172-31-21-198 systemd[1]: Stopped actions runner.
Dec 18 02:58:41 ip-172-31-21-198 systemd[1]: Started actions runner.
Dec 18 02:58:44 ip-172-31-21-198 run.sh[31674]: √ Connected to GitHub
Dec 18 02:58:44 ip-172-31-21-198 run.sh[31674]: 2020-12-18 02:58:44Z: Listening for Jobs
Dec 18 02:58:47 ip-172-31-21-198 run.sh[31674]: Runner update in progress, do not shutdown runner.
Dec 18 02:58:47 ip-172-31-21-198 run.sh[31674]: Downloading 2.275.1 runner
Dec 18 02:58:50 ip-172-31-21-198 run.sh[31674]: Waiting for current job finish running.
Dec 18 02:58:50 ip-172-31-21-198 run.sh[31674]: Generate and execute update script.
Dec 18 02:58:50 ip-172-31-21-198 run.sh[31674]: Runner will exit shortly for update, should back online within 10 seconds.
Dec 18 02:58:50 ip-172-31-21-198 systemd[1]: actionsrunner.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Dec 18 02:58:50 ip-172-31-21-198 systemd[1]: actionsrunner.service: Failed with result 'exit-code'.
Dec 18 02:58:51 ip-172-31-21-198 systemd[1]: actionsrunner.service: Service hold-off time over, scheduling restart.
Dec 18 02:58:51 ip-172-31-21-198 systemd[1]: actionsrunner.service: Scheduled restart job, restart counter is at 4.
Dec 18 02:58:51 ip-172-31-21-198 systemd[1]: Stopped actions runner.
Dec 18 02:58:51 ip-172-31-21-198 systemd[1]: Started actions runner.
Dec 18 02:58:55 ip-172-31-21-198 run.sh[31739]: √ Connected to GitHub
Dec 18 02:58:55 ip-172-31-21-198 run.sh[31739]: 2020-12-18 02:58:55Z: Listening for Jobs
Dec 18 02:58:57 ip-172-31-21-198 run.sh[31739]: Runner update in progress, do not shutdown runner.
Dec 18 02:58:58 ip-172-31-21-198 run.sh[31739]: Downloading 2.275.1 runner
Dec 18 02:59:00 ip-172-31-21-198 run.sh[31739]: Waiting for current job finish running.
Dec 18 02:59:00 ip-172-31-21-198 run.sh[31739]: Generate and execute update script.
Dec 18 02:59:00 ip-172-31-21-198 run.sh[31739]: Runner will exit shortly for update, should back online within 10 seconds.
Dec 18 02:59:00 ip-172-31-21-198 systemd[1]: actionsrunner.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Dec 18 02:59:00 ip-172-31-21-198 systemd[1]: actionsrunner.service: Failed with result 'exit-code'.
Dec 18 02:59:02 ip-172-31-21-198 systemd[1]: actionsrunner.service: Service hold-off time over, scheduling restart.
Dec 18 02:59:02 ip-172-31-21-198 systemd[1]: actionsrunner.service: Scheduled restart job, restart counter is at 5.
Dec 18 02:59:02 ip-172-31-21-198 systemd[1]: Stopped actions runner.
Dec 18 02:59:02 ip-172-31-21-198 systemd[1]: Started actions runner.
Dec 18 02:59:06 ip-172-31-21-198 run.sh[31803]: √ Connected to GitHub
Dec 18 02:59:06 ip-172-31-21-198 run.sh[31803]: 2020-12-18 02:59:06Z: Listening for Jobs
Dec 18 02:59:09 ip-172-31-21-198 run.sh[31803]: Runner update in progress, do not shutdown runner.
Dec 18 02:59:09 ip-172-31-21-198 run.sh[31803]: Downloading 2.275.1 runner
Dec 18 02:59:12 ip-172-31-21-198 run.sh[31803]: Waiting for current job finish running.
Dec 18 02:59:12 ip-172-31-21-198 run.sh[31803]: Generate and execute update script.
Dec 18 02:59:12 ip-172-31-21-198 run.sh[31803]: Runner will exit shortly for update, should back online within 10 seconds.
Dec 18 02:59:12 ip-172-31-21-198 systemd[1]: actionsrunner.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Dec 18 02:59:12 ip-172-31-21-198 systemd[1]: actionsrunner.service: Failed with result 'exit-code'.
Dec 18 02:59:13 ip-172-31-21-198 systemd[1]: actionsrunner.service: Service hold-off time over, scheduling restart.
Dec 18 02:59:13 ip-172-31-21-198 systemd[1]: actionsrunner.service: Scheduled restart job, restart counter is at 6.
Dec 18 02:59:13 ip-172-31-21-198 systemd[1]: Stopped actions runner.
Dec 18 02:59:13 ip-172-31-21-198 systemd[1]: Started actions runner.
Dec 18 02:59:17 ip-172-31-21-198 run.sh[31867]: √ Connected to GitHub
Dec 18 02:59:17 ip-172-31-21-198 run.sh[31867]: 2020-12-18 02:59:17Z: Listening for Jobs
Dec 18 02:59:20 ip-172-31-21-198 run.sh[31867]: Runner update in progress, do not shutdown runner.
Dec 18 02:59:20 ip-172-31-21-198 run.sh[31867]: Downloading 2.275.1 runner
Dec 18 02:59:23 ip-172-31-21-198 run.sh[31867]: Waiting for current job finish running.
Dec 18 02:59:23 ip-172-31-21-198 run.sh[31867]: Generate and execute update script.
Dec 18 02:59:23 ip-172-31-21-198 run.sh[31867]: Runner will exit shortly for update, should back online within 10 seconds.
Dec 18 02:59:23 ip-172-31-21-198 systemd[1]: actionsrunner.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Dec 18 02:59:23 ip-172-31-21-198 systemd[1]: actionsrunner.service: Failed with result 'exit-code'.
Dec 18 02:59:24 ip-172-31-21-198 systemd[1]: actionsrunner.service: Service hold-off time over, scheduling restart.
Dec 18 02:59:24 ip-172-31-21-198 systemd[1]: actionsrunner.service: Scheduled restart job, restart counter is at 7.
Dec 18 02:59:24 ip-172-31-21-198 systemd[1]: Stopped actions runner.
Dec 18 02:59:24 ip-172-31-21-198 systemd[1]: Started actions runner.
Dec 18 02:59:28 ip-172-31-21-198 run.sh[31930]: √ Connected to GitHub
Dec 18 02:59:28 ip-172-31-21-198 run.sh[31930]: 2020-12-18 02:59:28Z: Listening for Jobs
Dec 18 02:59:31 ip-172-31-21-198 run.sh[31930]: Runner update in progress, do not shutdown runner.
Dec 18 02:59:31 ip-172-31-21-198 run.sh[31930]: Downloading 2.275.1 runner
Dec 18 02:59:38 ip-172-31-21-198 run.sh[31930]: Waiting for current job finish running.
Dec 18 02:59:38 ip-172-31-21-198 run.sh[31930]: Generate and execute update script.
Dec 18 02:59:38 ip-172-31-21-198 run.sh[31930]: Runner will exit shortly for update, should back online within 10 seconds.
Dec 18 02:59:39 ip-172-31-21-198 systemd[1]: actionsrunner.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Dec 18 02:59:39 ip-172-31-21-198 systemd[1]: actionsrunner.service: Failed with result 'exit-code'.
```

## Job Log Output

See above. 

## Runner and Worker's Diagnostic Logs

SelfUpdate-20201218-034910.log from the _diag folder. There are many such SelfUpdate-*.log files, all telling the similar "process xxxxxx still running" story. 

```
[2020-12-18 03:49:10-2074] --------whoami--------
ubuntu
[2020-12-18 03:49:10-2089] --------whoami--------
[2020-12-18 03:49:10-2096] Waiting for Runner.Listener (17349) to complete
[2020-12-18 03:49:10-2103] Process 17349 still running
```

Runner_20201218-034101-utc.log from the _diag folder.

```
[2020-12-18 03:41:05Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/ubuntu/runner/.credentials_rsaparams
[2020-12-18 03:41:05Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/ubuntu/runner/.credentials_rsaparams
[2020-12-18 03:41:05Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
[2020-12-18 03:41:05Z INFO MessageListener] Session created.
[2020-12-18 03:41:05Z INFO Terminal] WRITE LINE: 2020-12-18 03:41:05Z: Listening for Jobs
[2020-12-18 03:41:05Z INFO JobDispatcher] Set runner/worker IPC timeout to 30 seconds.
[2020-12-18 03:41:08Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/ubuntu/runner/.credentials_rsaparams
[2020-12-18 03:41:08Z INFO MessageListener] Message '250' received from session '6baabc98-bcc9-489e-a1e0-53105964e43f'.
[2020-12-18 03:41:08Z INFO Runner] Refresh message received, kick-off selfupdate background process.
[2020-12-18 03:41:08Z INFO SelfUpdater] Version '2.275.1' of 'agent' package available in server.
[2020-12-18 03:41:08Z INFO SelfUpdater] Current running runner version is 2.274.2
[2020-12-18 03:41:08Z INFO SelfUpdater] An update is available.
[2020-12-18 03:41:08Z INFO Terminal] WRITE LINE: Runner update in progress, do not shutdown runner.
[2020-12-18 03:41:08Z INFO Terminal] WRITE LINE: Downloading 2.275.1 runner
[2020-12-18 03:41:08Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/runner/bin'
[2020-12-18 03:41:08Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/runner'
[2020-12-18 03:41:08Z INFO HostContext] Well known directory 'Work': '/home/ubuntu/runner/_work'
[2020-12-18 03:41:08Z INFO SelfUpdater] Attempt 1: save latest runner into /home/ubuntu/runner/_work/_update/runner1.tar.gz.
[2020-12-18 03:41:08Z INFO SelfUpdater] Download runner: begin download
[2020-12-18 03:41:09Z INFO SelfUpdater] Download runner: finished download
[2020-12-18 03:41:09Z INFO SelfUpdater] Which: 'tar'
[2020-12-18 03:41:09Z INFO SelfUpdater] Location: '/bin/tar'
[2020-12-18 03:41:09Z INFO ProcessInvokerWrapper] Starting process:
[2020-12-18 03:41:09Z INFO ProcessInvokerWrapper]   File name: '/bin/tar'
[2020-12-18 03:41:09Z INFO ProcessInvokerWrapper]   Arguments: '-xzf "/home/ubuntu/runner/_work/_update/runner1.tar.gz"'
[2020-12-18 03:41:09Z INFO ProcessInvokerWrapper]   Working directory: '/home/ubuntu/runner/_work/_update'
[2020-12-18 03:41:09Z INFO ProcessInvokerWrapper]   Require exit code zero: 'False'
[2020-12-18 03:41:09Z INFO ProcessInvokerWrapper]   Encoding web name:  ; code page: ''
[2020-12-18 03:41:09Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'False'
[2020-12-18 03:41:09Z INFO ProcessInvokerWrapper]   Redirected STDIN: 'False'
[2020-12-18 03:41:09Z INFO ProcessInvokerWrapper]   Persist current code page: 'False'
[2020-12-18 03:41:09Z INFO ProcessInvokerWrapper]   Keep redirected STDIN open: 'False'
[2020-12-18 03:41:09Z INFO ProcessInvokerWrapper]   High priority process: 'False'
[2020-12-18 03:41:09Z INFO ProcessInvokerWrapper] Updated oom_score_adj to 500 for PID: 14431.
[2020-12-18 03:41:09Z INFO ProcessInvokerWrapper] Process started with process id 14431, waiting for process exit.
[2020-12-18 03:41:11Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2020-12-18 03:41:11Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2020-12-18 03:41:11Z INFO ProcessInvokerWrapper] Finished process 14431 with exit code 0, and elapsed time 00:00:01.4753408.
[2020-12-18 03:41:11Z INFO SelfUpdater] Finished getting latest runner package at: /home/ubuntu/runner/_work/_update.
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/runner/bin'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/runner'
[2020-12-18 03:41:11Z INFO SelfUpdater] Copy /home/ubuntu/runner/_work/_update/bin to /home/ubuntu/runner/bin.2.275.1.
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/runner/bin'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/runner'
[2020-12-18 03:41:11Z INFO SelfUpdater] Copy /home/ubuntu/runner/_work/_update/externals to /home/ubuntu/runner/externals.2.275.1.
[2020-12-18 03:41:11Z INFO SelfUpdater] Copy any remaining .sh/.cmd files into runner root.
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/runner/bin'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/runner'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/runner/bin'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/runner'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/runner/bin'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/runner'
[2020-12-18 03:41:11Z INFO SelfUpdater] Download latest runner and unzip into runner root.
[2020-12-18 03:41:11Z INFO Terminal] WRITE LINE: Waiting for current job finish running.
[2020-12-18 03:41:11Z INFO SelfUpdater] All running job has exited.
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/runner/bin'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/runner'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/runner/bin'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/runner'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/runner/bin'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/runner'
[2020-12-18 03:41:11Z INFO SelfUpdater] Delete old version runner backup.
[2020-12-18 03:41:11Z INFO Terminal] WRITE LINE: Generate and execute update script.
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/runner/bin'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/runner'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Diag': '/home/ubuntu/runner/_diag'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/runner/bin'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/runner'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Bin': '/home/ubuntu/runner/bin'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Root': '/home/ubuntu/runner'
[2020-12-18 03:41:11Z INFO HostContext] Well known directory 'Work': '/home/ubuntu/runner/_work'
[2020-12-18 03:41:11Z INFO SelfUpdater] Generate update script into: /home/ubuntu/runner/_work/_update.sh
[2020-12-18 03:41:11Z INFO SelfUpdater] Which: 'bash'
[2020-12-18 03:41:11Z INFO SelfUpdater] Location: '/bin/bash'
[2020-12-18 03:41:11Z INFO SelfUpdater] Update script start running
[2020-12-18 03:41:11Z INFO Terminal] WRITE LINE: Runner will exit shortly for update, should back online within 10 seconds.
[2020-12-18 03:41:11Z INFO Runner] Auto update task finished at backend, an runner update is ready to apply exit the current runner instance.
[2020-12-18 03:41:11Z INFO Runner] Stop message queue looping.
[2020-12-18 03:41:11Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/edZHcFyE5aqXZ5q8KzWmg7MN3wW1feWSQSerN9H3THVNDc0ufb/_apis/distributedtask/pools/1/messages?sessionId=6baabc98-bcc9-489e-a1e0-53105964e43f&lastMessageId=250 has been cancelled.
[2020-12-18 03:41:11Z INFO MessageListener] Get next message has been cancelled.
[2020-12-18 03:41:11Z INFO Runner] Ignore any exception after cancel message loop. System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Listener.MessageListener.GetNextMessageAsync(CancellationToken token)
   at GitHub.Runner.Listener.Runner.RunAsync(RunnerSettings settings, Boolean runOnce)
[2020-12-18 03:41:11Z INFO JobDispatcher] Shutting down JobDispatcher. Make sure all WorkerDispatcher has finished.
[2020-12-18 03:41:11Z INFO Listener] Runner execution has finished with return code 3
```

**Comment by TingluoHuang** [comment]
@lni how did you configure the runner as systemd service? did you use the `./svc.sh install` script under runner root to install? or you write your own systemd file for the runner?

**Comment by lni** [comment]
I didn't realize that there is this runsvc.sh script for running as a service. Thanks for the info!
