### ISSUE TITLE
Runner 2.276.0 crashes on macOS 10.12: System.DllNotFoundException: Unable to load shared library 'libSystem.Native'

### ISSUE THREAD

**Issue by Saviq** [actions/runner#930]
**Describe the bug**
Runner version 2.276.0 crashes on macOS 10.12.

We know macOS 10.12 is EOL, but to keep supporting as big a set of hardware as possible, we wanted to keep building on self-hosted 10.12. Or at least not be forced to transition in a scramble…

**To Reproduce**
1. `./run.sh`

**Expected behavior**
Runner works.

## Runner Version and Platform
macOS 10.12
actions-runner-osx-x64-2.276.0.tar.gz

## What's not working?
```
$ ./run.sh 
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libSystem.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibSystem.Native, 1): image not found
   at System.IO.FileSystem.FileExists(ReadOnlySpan`1 fullPath, Int32 fileType, ErrorInfo& errorInfo)
   at System.IO.File.Exists(String path)
   at GitHub.Runner.Listener.Program.LoadAndSetEnv()
   at GitHub.Runner.Listener.Program.Main(String[] args)
./run.sh: line 51: 74469 Abort trap: 6           "$DIR"/bin/Runner.Listener run $*
```

**Comment by Saviq** [comment]
I can confirm macOS 10.13 is fine, fully updated 10.12 fails with the above error.

**Comment by Saviq** [comment]
2.276.1, with reverted .NET, works fine again.
